### ISSUE TITLE
SDNS prevents YouTube from saving history

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#10]
> Заметил в последнее время что приложение YouTube для iOS перестало записывать историю просмотра. Посмотрев логи, заметил что адрес s.youtube.com занесен в черный список. Именно он отвечает за сохранение истории сервиса YT.

<details> <summary> Screenshot </summary>

![image](https://user-images.githubusercontent.com/15856304/47253447-7ed80980-d45b-11e8-877c-a6e2121f0d35.png)

</details>

**Comment by ameshkov** [comment]
Resolved
