### ISSUE TITLE
False blocking : fortuneo.fr

### ISSUE THREAD

**Issue by Umor976** [AdguardTeam/AdGuardSDNSFilter#100]
### Steps to reproduce

1. https://www.fortuneo.fr/
2.
3.
4.

### Expected behavior

It's a banking site, genuine site. 
I wish to get access back to this domain and all subdomains.

### Actual behavior

It's blocked by dns filter. 
If i change DNS servers, it works perfectly however from a computer or phone.

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:|  176.103.130.130 176.103.130.131 2a00:5a60::ad1:ff 2a00:5a60::ad2:ff
| How did you setup DNS configuration:| System
| Device model:| (e.g. Google Pixel)
| Operating system and version:| Windows 10 , android 9.0

**Comment by Alex-302** [comment]
It is not blocked by AdGuard
![image](https://user-images.githubusercontent.com/8361299/61210413-17f33280-a705-11e9-8620-9a4514d602d0.png)

@Umor976 please enter in CMD `nslookup fortuneo.fr` and make screenshot.

**Comment by Umor976** [comment]
Hello,thanks for your reply.Here you can find the screenshot ... and no reply for the fortuneo.fr site


I'm using adguard DNS ,  i think i did maybe a mistake while reporting an issue with adguarddnsfilter?Regards

    Le lundi 15 juillet 2019 à 13:33:51 UTC+3, Alex <notifications@github.com> a écrit :  
 
 
It is not blocked by AdGuard


@Umor976 please enter in CMD nslookup fortuneo.fr and make screenshot.

**Comment by Alex-302** [comment]
Please reply on GitHub, your screenshot is not attached.

**Comment by Umor976** [comment]
Hello,thanks for your reply. Here you can find the screenshot ... and no reply for the fortuneo.fr site
![1563187971698blob](https://user-images.githubusercontent.com/52877538/61229406-cb255100-a730-11e9-8480-13528be83aa8.png)



I'm using adguard DNS ,  i think i did maybe a mistake while reporting an issue with adguarddnsfilter instead of AdguardDNS

**Comment by Alex-302** [comment]
Strange. Can't find the blocking rule...

**Comment by ameshkov** [comment]
```
Andreys-MacBook-Pro:browser-extension ameshkov$ nslookup fortuneo.fr 176.103.130.130
Server:		176.103.130.130
Address:	176.103.130.130#53

** server can't find fortuneo.fr: SERVFAIL
```

Interesting! This looks like a bug of AdGuard DNS, and not a filters issue.

**Comment by ameshkov** [comment]
Well, it appears that this is some kind of a geo-block, this domain cannot be resolved from one of our servers because their nameserver drops our requests.
