### ISSUE TITLE
mobile-data.onetrust.io 

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#1004]
The [mobile-data.onetrust.io](http://mobile-data.onetrust.io/) domain is still permitted on your standard public Ad-block DNS resolver, please can you review this and block this? It is a tracker and data collection agency and therefore should be reviewed and blocked.

Helpdesk ID: 620601

**Comment by hagezi** [comment]
If you block the domain, some apps will no longer start. For example Servus TV App on iOS.

**Comment by Eow2022yia** [comment]
> If you block the domain, some apps will no longer start. For example Servus TV App on iOS.

It works perfectly fine on my iPhone with the domain blocked, it must be an issue with your network or other factors.

**Comment by Eow2022yia** [comment]
Hi, I am experiencing the same issue while this domain is currently allowed, pop-ups are constantly appearing with intrusive privacy notices, please review and strongly consider blocking this domain.

**Comment by Eow2022yia** [comment]
Hi, I am experiencing the same issue while this domain is currently allowed, pop-ups are constantly appearing with intrusive privacy notices, please review and strongly consider blocking this domain.

This domain is blocked as well by the following pi-holes:

mobile-data.onetrust.io is being blocked by
Goodbye Ads, Energized Ultimate, 1Hosts (Lite), Energized Basic, 1Hosts (Pro), 1Hosts (mini) and 1Hosts (Xtra).

Pi-hole GitHub(s):
https://github.com/jerryn70/GoodbyeAds

https://github.com/EnergizedProtection/block

https://o0.pages.dev

Thank you.

**Comment by Alex-302** [comment]
> constantly appearing with intrusive privacy notices

I need examples. Btw we do not block annoyances in DNS filter.

**Comment by Eow2022yia** [comment]
> > constantly appearing with intrusive privacy notices
> 
> I need examples. Btw we do not block annoyances in DNS filter.

Hi, thank you for following up.

![71646E1E-C09B-4510-B4E8-898F488F4FED](https://user-images.githubusercontent.com/109627209/180427017-4eb24080-f652-4dcb-9567-57857c4099cf.jpeg)

Please note and also consider that this domain is also blocked on the following lists: Goodbye Ads, Energized Ultimate, 1Hosts (Lite), Energized Basic, 1Hosts (Pro), 1Hosts (mini) and 1Hosts (Xtra).

Kind Regards

**Comment by Alex-302** [comment]
I mean examples of apps.

**Comment by Eow2022yia** [comment]
> I mean examples of apps.

![DC3C5813-3A99-4A13-B7A6-857165AD6CBD](https://user-images.githubusercontent.com/109627209/180615585-6681746a-3f76-4129-8885-e093d4c0f9f5.jpeg)
Met Office weather as one example, it is more of a tracker rather than an annoyance.

**Comment by Alex-302** [comment]
links to apps)

**Comment by Eow2022yia** [comment]
> links to apps)
> I cannot just block a domain on first request.

Hi,

Unfortunately I don’t have this precise technical information you are seeking.

As the developer this thread is requesting you to review this domain, you have all the relevant details related to this.

Thank you.

**Comment by Alex-302** [comment]
You provided the screenshot. Is it random from intener, or a real screenshot?

**Comment by Eow2022yia** [comment]
> You provided the screenshot. Is it random from intener, or a real screenshot?

Hi,

The screenshot I taken was live, I captured it on the Met Office application.

Thank you.

**Comment by Eow2022yia** [comment]
> You provided the screenshot. Is it random from intener, or a real screenshot?

Hi,

The screenshot I taken was live, I captured it on the Met Office application.

Thank you.

**Comment by Alex-302** [comment]
This?
https://play.google.com/store/apps/details?id=com.ionicframework.metapp415486&hl=uk&gl=US

**Comment by Eow2022yia** [comment]
> This?
> 
> https://play.google.com/store/apps/details?id=com.ionicframework.metapp415486&hl=uk&gl=US

This one,

https://apps.apple.com/us/app/met-office-weather-forecast/id1068146838

Please also note this is just one example of the many applications that use this domain.

**Comment by Alex-302** [comment]
Blocking on this domain does not prevent cookie consent.

**Comment by FsAguard62** [comment]
I have it running on my iphones it seems to be part of the Dictionary.com app as you can see in the screenshot and reading what was said on here I debating if I should block it. 
![541C2846-7A39-4207-A938-60B78DB67558](https://user-images.githubusercontent.com/78290214/209445079-b5ee06d7-e130-4258-9511-a62bd12a4042.png)

**Comment by Eow2022yia** [comment]
> I have it running on my iphones it seems to be part of the Dictionary.com app as you can see in the screenshot and reading what was said on here I debating if I should block it. 
> 
> ![541C2846-7A39-4207-A938-60B78DB67558](https://user-images.githubusercontent.com/78290214/209445079-b5ee06d7-e130-4258-9511-a62bd12a4042.png)
> 
> 

Hi, thanks for providing this information @FsAguard62 

@Alex-302 can this please be reviewed and blocked on the AdGuard DNS?

Thank you.

**Comment by FsAguard62** [comment]
I am always looking for new domains that look suspicious, and I don't want to drive you crazy with tons of questions about them 🙂! I could show you more about that domain from the DNS details before I clear the activity log if you need it. It has only shown up a few times so far. Happy Holidays to you, mate.
