### ISSUE TITLE
Please add the below trackers in Adguard DNS

### ISSUE THREAD

**Issue by jakecharlie** [AdguardTeam/AdGuardSDNSFilter#1007]
Please add the below trackers in Adguard DNS:

From Amazon:
device-metrics-us.amazon.com
device-metrics-us-2.amazon.com
aax-us-east-retail-direct.amazon.com
fls-na.amazon.com

From Amazon Video:
api.us-east-1.aiv-delivery.net

From Google:
crashlyticsreports-pa.googleapis.com
analytics.google.com
dl.google.com
firebase-settings.crashlytics.com
1a1c5454-dnsotls-ds.metric.gstatic.com
5aijiw-dnsotls-ds.metric.gstatic.com
hzn4xq-dnsotls-ds.metric.gstatic.com
kfjyir-dnsotls-ds.metric.gstatic.com
f1oy5e-dnsotls-ds.metric.gstatic.com
e7aq1q-dnsotls-ds.metric.gstatic.com
ixk9cc-dnsotls-ds.metric.gstatic.com
7ecj87-dnsotls-ds.metric.gstatic.com
xnfmj4-dnsotls-ds.metric.gstatic.com
paop5b-dnsotls-ds.metric.gstatic.com
ftu5ar-dnsotls-ds.metric.gstatic.com
rfyrdd-dnsotls-ds.metric.gstatic.com
8uwrh0-dnsotls-ds.metric.gstatic.com
9c8d2f7c-dnsotls-ds.metric.gstatic.com
hlcac4-dnsotls-ds.metric.gstatic.com
9d9rps-dnsotls-ds.metric.gstatic.com
c181f1ac-dnsotls-ds.metric.gstatic.com
mjezcj-dnsotls-ds.metric.gstatic.com
jkm3k6-dnsotls-ds.metric.gstatic.com
u6qyq0-dnsotls-ds.metric.gstatic.com
n8newr-dnsotls-ds.metric.gstatic.com
cf5d3b0f-dnsotls-ds.metric.gstatic.com
e533db2e-dnsotls-ds.metric.gstatic.com
dezodh-dnsotls-ds.metric.gstatic.com
wuxnvc-dnsotls-ds.metric.gstatic.com
ukv1rv-dnsotls-ds.metric.gstatic.com
monwhp-dnsotls-ds.metric.gstatic.com
kbepbi-dnsotls-ds.metric.gstatic.com
odu27y-dnsotls-ds.metric.gstatic.com

From LG:
aic.cdpbeacon.lgtvcommon.com
aic-ngfts.lge.com

From ipify:
api.ipify.org

From ScoreCard Research Beacon:
sb.scorecardresearch.com

From Bugsnag:
sessions.bugsnag.com

From chinese company Taobao:
adashbc.ut.taobao.com

From whatsapp:
static.whatsapp.net

From Avast:
analytics.ff.avast.com

From Xiaomi:
data.sec.intl.miui.com
cdn.awsusor1.fds.api.mi-img.com
resolver.msg.global.xiaomi.net

Many others trackers:
h.online-metrix.net
sdk.iad-01.braze.com
sdk.iad-05.braze.com
log-collector.shopee.com.br
https://dttijy4dc6foz.cloudfront.net/
https://d2idu5mmj5r5g3.cloudfront.net/
3t5fmdir75gmnl3elswfs4zj4eq27crvpipbgs6z837e82faa1c700c0sac.d.aa.online-metrix.net
d2idu5mmj5r5g3.cloudfront.net

**Comment by Alex-302** [comment]
The first device-metrics-us.amazon.com is already blocked. Did not check another, but is seems they are also blocked.

**Comment by Alex-302** [comment]
api.ipify.org not a tracker
