### ISSUE TITLE
Why does this project influenced by political incident?

### ISSUE THREAD

**Issue by qingchuwudi** [AdguardTeam/AdGuardSDNSFilter#1008]
Last night my network almost down after the `AdGuard DNS filter` rule updated at 21:20.

![](https://s3.bmp.ovh/imgs/2022/08/03/a89e5210623ec1fe.jpg)

Most of the domain name CANNOT be resolved!

Does this project influenced by political incident? Why? 

![](https://s3.bmp.ovh/imgs/2022/08/03/c80920ab509f74db.jpg)

![](https://s3.bmp.ovh/imgs/2022/08/03/be57986332869924.jpg)

**Comment by Alex-302** [comment]
Cannot reproduce. The shortestrule in this filter is `|piwik.`
