### ISSUE TITLE
https://eksiup.com

### ISSUE THREAD

**Issue by erdorado** [AdguardTeam/AdGuardSDNSFilter#1010]
This website is an image upload website for a commonly used webportal eksisozluk.com. This website is in blocked condition and is not getting openned when the dns is active on iphone. It is clearly mis-blocked content. 
Tested with dns profile deletion and works perfectly. I have checked the filter and saw that the webpage is in adguard blocked dns list.

**Comment by Alex-302** [comment]
Hi
It is loaded from Easylist.

I don't see requsts to eksiup.com on eksisozluk.com

**Comment by erdorado** [comment]
Hi Alex,
eksiup is not belong to the eksisozluk or doesn't create direct requests to the eksisozluk. It is just widely used website to image uploads especially from the eksisozluk users.

**Comment by Alex-302** [comment]
Fixed.
