### ISSUE TITLE
||bc0a.com^ blocks images on www.beretta.com

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#1012]
```
nslookup marvel-b1-cnd.bc0a.com 
Server:		192.168.0.1
Address:	192.168.0.1#53

Non-authoritative answer:
Name:	marvel-b1-cnd.bc0a.com
Address: 0.0.0.0
```

Please see screenshots below:

<details> 

![image](https://user-images.githubusercontent.com/15856304/183854685-57596a86-42de-4524-a8b6-ed6df9536736.png)

![image](https://user-images.githubusercontent.com/15856304/183854851-93abf9b5-c207-42ac-82a3-04a1b3693938.png)

![image](https://user-images.githubusercontent.com/15856304/183854988-59ba4e11-c14c-4d3c-a331-73fd9ffb3c9e.png)

</details>

**Comment by Alex-302** [comment]
@Eugene-Savenko I can't reproduce. Even do not see requests to bc0a.com

**Comment by Eugene-Savenko** [comment]
Me neither, but could it be that they use different domains in different locations? The customer seems to be from the US. Can we try with a VPN? Not sure if that's helpful, but you can find more info in the 627366 ticket.

**Comment by Alex-302** [comment]
We always need a direct link to the broken page.

**Comment by Eugene-Savenko** [comment]
You can see on the screenshot.

**Comment by hagezi** [comment]
@Alex-302 https://www.beretta.com/en-us/gifts/
Blocking `marvel-b1-cdn.bc0a.com` will result in the products' images not being displayed.

Cheers,
Gerd

**Comment by Alex-302** [comment]
@hagezi Does the problem still recur?

**Comment by hagezi** [comment]
@Alex-302 sorry, no, had tested with an old version of the list.
