### ISSUE TITLE
stats.norton.com

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdGuardSDNSFilter#1016]
### Steps to reproduce

1. stats.norton.com is used by Norton Antivirus products to send information related to threat monitoring and detection. Blocking it hampers the product's ability to protect users.

### Expected behavior

Should be whitelisted
### Actual behavior

Blocks it. 

<details><summary>Screenshot:</summary>

![a](https://user-images.githubusercontent.com/29574622/184317680-344b0665-d948-447e-a20e-80a036050ceb.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (e.g. Default, 94.140.14.14 as well as NextDNS with Adguard DNS filter enabled)
| How did you setup DNS configuration:| (System/Router)
| Operating system and version:| (Windows 11)

**Comment by Alex-302** [comment]
@jellizaveta Here are some info
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Worm%3AWin32%2FVirauto.A
Viruses block this domain, so it seems it is legal.

**Comment by SeriousHoax** [comment]
To add some more info on it, 
I don't know if there's any official Norton/Symantec documentation saying what I added in the issue, but a Norton support staff said it.
Also, after installing Norton, they want you to install their browser extension to protect users from malicious & phishing websites because Norton AV don't block malicious sites system-wide like some other products eg: Avast, Bitdefender, etc. 
After clicking the certain button in the Norton UI, it redirects to their extension page via the mentioned host, it seems. Because when it's blocked, it can not land on that extension page showcasing all the extensions Norton offers. Browser attempts to load the page fails. It just closes automatically. Non-tech savvy users might not be able to manually look for the extension in the respective browser extension store. 
So, I think if this `stats.norton.com` host is something that Norton uses for functionality and threat intelligence telemetry, then it should be whitelisted.

**Comment by jellizaveta** [comment]
closed via https://github.com/AdguardTeam/AdguardFilters/commit/a29a3248d847efc04aae9662a80a2d5d054e7dac
