### ISSUE TITLE
Please add the trackers below in Adguard DNS

### ISSUE THREAD

**Issue by jakecharlie** [AdguardTeam/AdGuardSDNSFilter#1017]
Please add the trackers below in Adguard DNS. Many of them are from Chinese companies and are already being blocked by NextDNS, EasyList and AdAway. Thank you.

api-a.op-mobile.opera.com
ipm-provider.ff.avast.com
track.titanpush.com
cdn-settings.appsflyersdk.com
log-collector.shopee.com.br
data-rep.livetech.shopee.com.br
idfp.tongdun.net
widget.fitanalytics.com
abtest.alibaba.com
adashx4ae.ut.taobao.com
audid-api.taobao.com
onesignal.com
zc.adswizz.com
sb.scorecardresearch.com
sdk.iad-01.braze.com
mobileconfig.sascdn.com
pro.ip-api.com
api.iterable.com
zn41r1dpknmdeypvr-evernote.siteintercept.qualtrics.com
startup.mobile.yandex.net
metadata.provider.plex.tv
launches.appsflyer.com
catchdata.didiglobal.com
sessions.bugsnag.com

**Comment by Alex-302** [comment]
I see non-traking domains, and the first random is blocked - `log-collector.shopee.com.br`
