### ISSUE TITLE
Not able to use share to earn extension with Samsung Internet with Adgaurd DNS

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#1021]
@Batman2814 commented on [Mon Aug 15 2022](https://github.com/AdguardTeam/AdGuardDNS/issues/337)

![Screenshot_20220815-100602_Samsung Internet](https://user-images.githubusercontent.com/96619913/184662402-2e695e38-81f1-472d-af29-ae81fcd7788e.jpg)

I'm not able to use the extension share to earn that is a add-on to Samsung Internet to get cashback when Adguard DNS is on. I switched to Google DNS in Adguard and it was able to connect and work.

**Comment by Alex-302** [comment]
We do not block it.
![image](https://user-images.githubusercontent.com/8361299/185192742-0bb4f3d6-6480-4731-aa8b-499cbe828921.png)
