### ISSUE TITLE
AdGuard DNS breaks Coda

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#1030]
@tyteen4a03 commented on [Sat Aug 20 2022](https://github.com/AdguardTeam/AdGuardDNS/issues/351)

Steps to reproduce:

1. Turn off AdGuard DNS
2. Sign up for Coda on coda.io
3. Download the Coda app (https://play.google.com/store/apps/details?id=io.coda.codaapp&hl=en&gl=US)
4. Log into the app and ensure dashboard is loading
5. Turn on AdGuard DNS
6. Close the Coda app and reopen it

You will see only a turquoise background.

**Comment by Alex-302** [comment]
@tyteen4a03 Hi. Cannot reprodcue with default AdGuard DNS(with ad blocking) or with Default DNS + DNS filtering using filters.
Using https://adguard-dns.io/ you can find what breaks the app(if it is caused by DNS requests blocking).

**Comment by tyteen4a03** [comment]
Hi, are you trying on Android with Private DNS option?

**Comment by Alex-302** [comment]
Please describe
- where used AdGaurd DNS(a router or a device)
- screenshot of the broken app, or a video

**Comment by tyteen4a03** [comment]
Hi, sorry I forgot about the issue. Issue seems to be gone now!
