### ISSUE TITLE
Unblock Samsung TV Event logs

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#1031]
@Batman2814 commented on [Tue Aug 23 2022](https://github.com/AdguardTeam/AdGuardDNS/issues/358)

I noticed when having Adguard personal DNS setup on my Eero router that event logs are not working on my Samsung 2021 Smart tv. The reason I'm asking is smarthings support needs access to event logs to see what the problem is so does anyone know how to unblock it in filtering so my Samsung TV can record event logs to diagnosed problems. If someone could help me figure this out I'd much appreciate it.

**Comment by Alex-302** [comment]
@Batman2814 Please describe how to reproduce an issue with the logs.

Also you can try https://adguard-dns.io/ and check what exactly is blocked.

**Comment by Batman2814** [comment]
The thing is I can't see the Samsung tv event logs that are stored on my Samsung TV. I been looking through filtering and unblocking and disabling Blocklist even all my Blocklist which only leaves Adguard personal DNS active and it still doesn't show event logs for Samsung tv.

**Comment by Batman2814** [comment]
what do u mean how to reproduce an issue with the logs?

**Comment by Alex-302** [comment]
We can't fix an issue if we do not know how to check it.

**Comment by Batman2814** [comment]
![20220824_071839](https://user-images.githubusercontent.com/96619913/186416520-f903caf0-60a8-46f1-b42c-d4372d0298d3.jpg)

All I know is that Under about tv event logs my tv should record logs whenever my tv is in use even when I turn it on and off. The photo attached is showing records logs when I turned off Adguard DNS but as soon as I turn Adguard DNS back on is stops recording logs.

**Comment by Alex-302** [comment]
@Batman2814 Please test with 94.140.14.140
What do you mean by `personal DNS`in the fist message?

**Comment by Batman2814** [comment]
Adgaurd Personal DNS

**Comment by Batman2814** [comment]
do i put that dns in my samsung tv settings or eero router?

**Comment by Alex-302** [comment]
> do i put that dns in my samsung tv settings or eero router?

Try both:) One my Samsung TV ignores own DNS settings and uses router's.

> Adgaurd Personal DNS

So you can check what is blocked by DNS in the Query Log.

**Comment by Batman2814** [comment]
i did try both in samsung tv and eero router nothing changes still won't show logs. when put it in eero router dns my samsung automatically connects to dns server that is eero not Adgaurd DNS.

**Comment by Alex-302** [comment]
Ok. If it does not work with 94.140.14.140(non-filtered DNS), we cannot fix it.

**Comment by Batman2814** [comment]
the reason probably why logs wern't showing anything on non-filtered DNS was I didn't have it set to my router long enough for my tv to generate event logs. so I will change it back and leave it on to non- filtered adgaurd dns longer to see if my samsung tv will geneerate event logs and I will get back to you on the issue.

**Comment by Batman2814** [comment]
I tried something different where I plugged Ethernet Cable from Samsung TV to eero router with non-filtering Adguard DNS there was event Log created which said Power-on Reason, WoL
so logs where able to be generated with Non filtering so would it be possible to fix that in Adgaurd Personal private DNS.

**Comment by Batman2814** [comment]
Update 2: I switched back to Adguard Personal Private DNS with ethernet cable directly plugged in router event logs for generated. but somehow when its not connected through ethernet and just wifi event logs are not generated.

**Comment by Batman2814** [comment]
yes

**Comment by Alex-302** [comment]
Weird. It seems this probled is related to the TV.
