### ISSUE TITLE
Template for a new DNS filter issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#1039]
Just like what we have in the filters repo, we need to have a template (a couple of templates?) in the DNS filter repo.

I suggest adding these:
- [x] Bug report(incl. nsfw)
- [x] Feature request
- [x] A link to the documentation: https://adguard-dns.io/kb/general/dns-filtering-syntax/
- [x] Pull-request

In the bug report section we'll need to provide a list of products to choose from.

I suggest these:

* AdGuard DNS
* AdGuard Home
* AdGuard app (specify which one in the field below)
* Other blocker (specify which one in the field below)

**Comment by Alex-302** [comment]
Started https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/1040

After finalizing the structure, we can create separate templates for ads, tracking and incorrect blocking.

**Comment by Alex-302** [comment]
Added:
- config.yml - links to the doc and KB article about reporting;
- bug_report.yml
- bug_report_NSFW.yml (dummy)
- feature_request.yml
- pull_request_template.md
