### ISSUE TITLE
[Whitelist] c.msn.com

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdGuardSDNSFilter#1047]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://forms.office.com/Pages/ResponsePage.aspx?id=DQSIkWdsW0yxEjajBLZtrQAAAAAAAAAAAAO__SYWlsFUMFZERjEzMTRNS0JCRjVaWVExRkZTMEtGWi4u

### Add your comment and screenshots

Can't start after pressing "Click here to start"

Domain `c.office.com` blocked by CNAME `c.msn.com`

```
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 48602
;; flags: qr rd ra ; qd: 1 an: 3 au: 0 ad: 1 

;; OPT PSEUDOSECTION: 
; EDNS: version: 0; flags: ; udp: 1280
;; QUESTIONS:
;;	c.office.com., type = A, class = IN

;; ANSWERS:
c.office.com.		5	IN	CNAME	c.msn.com.
c.msn.com.		5	IN	CNAME	c-msn-com-nsatc.trafficmanager.net.
c-msn-com-nsatc.trafficmanager.net.	5	IN	A	20.110.81.91

;; AUTHORITY RECORDS:

;; ADDITIONAL RECORDS:


;; Message size: 183 bytes
```

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Answered in PR.
