### ISSUE TITLE
www.blizzard.com

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardSDNSFilter#1049]
@adguard-bot commented on [Tue Sep 20 2022](https://github.com/AdguardTeam/AdguardFilters/issues/130233)

### Issue URL (Incorrect Blocking)
 [https://www.blizzard.com/en-us/apps/battle.net/desktop](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.blizzard.com%2Fen-us%2Fapps%2Fbattle.net%2Fdesktop)
### Comment
> With AdGuard DNS filters enabled, the Battle.net app is unable to update games (like World of Warcraft) for the last few weeks. The updates get stuck on Initializing and eventually error out.
> 
> The issue seems to be due to the following DNS entry being blocked:
> 
> telemetry-in.battle.net
> 
> Adding a custom override fixes the issue:
> 
> @@||telemetry-in.battle.net^$important
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Uvbpj6e.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/uUefCtt.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | AdGuard Home
Browser: | Battle.net Desktop App
Filters: | <b>Other:</b><br/>AdGuard DNS
Other extensions used: | none

**Comment by jellizaveta** [comment]
Unfortunately, I have not been able to reproduce this problem. Updates are successful, games are downloaded. 
Please clear the filtering log, reproduce the problem and send a screenshot of the log with blocked requests.

**Comment by jellizaveta** [comment]
Unfortunately, I have not been able to reproduce this problem. Updates are successful, games are downloaded.
Please clear the filtering log, reproduce the problem and send a screenshot of the log with blocked requests.
