### ISSUE TITLE
Phising/Malware websites

### ISSUE THREAD

**Issue by blackstone250** [AdguardTeam/AdGuardSDNSFilter#1051]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

Nextdns 

### What DNS filters do you have enabled?

AdGuard DNS filter: A filter composed of several other filters (AdGuard Base filter, Social media filter, Tracking Protection filter, Mobile Ads filter, EasyList and EasyPrivacy) and simplified specifically to be better compatible with DNS-level ad blocking.

### What browser or app do you use?

Firefox, Chrome, Safari, Microsoft Edge, Opera, Yandex Browser, Other app

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed ads, Missed analytics or tracker

### Add your comment and screenshots

https://mega-flirtbooks.life/?u=adgk605&o=nq7p8gy
https://dqqna.delicatedate.net/c/da57dc555e50572d?s1=47029&s2=930749&s3=&s5=backuser&click_id=&iexpp=1&j1=1&j3=1&j5=1
https://ahun-creuse-tourisme.com/double-fisting/bdsm-slave-help-guides.php
https://cumception.com/photos/humiliation-slave-boyfriend/
https://oneamour.com
https://besthookupwebsites.org/ 
http://chatnog.ml/?y=pscd&s=687474703a2f2f646174696e6773722e636f6d2f6e65772f3f733d383926263534313735393633303833373437382664693d37672d313432322665643d676d6126693d61646d696e38392c32343133342c666361726c73736f6e32333040676d61696c2e636f6d2c466361726c73736f6e3233302674733d31363631343637313332263738393435383832373831343038&
https://biguz.net

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Wrong place. We block phishing in another internal list. Better report to support@adguard.com next time.
