### ISSUE TITLE
Disney Plus app won't work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#1052]
@Batman2814 commented on [Mon Sep 26 2022](https://github.com/AdguardTeam/AdGuardDNS/issues/388)

![20220926_072402](https://user-images.githubusercontent.com/96619913/192277474-b26774d4-2252-41f5-9ab5-ea430bde073f.jpg)

I'm not able to use the Disney plus app on my Samsung TV or Amazon fire TV stick 4k max.

**Comment by Alex-302** [comment]
We do not block cd-dmgz.bamgrid.com

**Comment by ameshkov** [comment]
@Batman2814 check the query log too see which blocklist is doing that. You can unblock that domain from there too.
