### ISSUE TITLE
leadfamly.com

### ISSUE THREAD

**Issue by Oniqqqq** [AdguardTeam/AdGuardSDNSFilter#1055]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://leadfamly.com/

### Add your comment and screenshots

![image](https://user-images.githubusercontent.com/38912221/192952603-d4cf4819-ecf4-40f0-a70e-5c9d361bb210.png)
![image](https://user-images.githubusercontent.com/38912221/192952875-ce439233-563b-4fbf-bdb6-f24031847578.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not blocked at the moment
![image](https://user-images.githubusercontent.com/8361299/193030543-1b964f5c-264f-457b-9495-5025a544698e.png)
