### ISSUE TITLE
blutv.com live TV stream video player either takes too long to start or doesn't work at all with AdGuardDNS

### ISSUE THREAD

**Issue by Sanseviearia** [AdguardTeam/AdGuardSDNSFilter#1058]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

DNS-over-HTTPS - Default server - https://dns.adguard-dns.com/dns-query

### What DNS filters do you have enabled?

Public AdGuard DNS server  
DNS-over-HTTPS
Default server
https://dns.adguard-dns.com/dns-query

### What browser or app do you use?

Opera

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.blutv.com/int/canli-yayin/bloomberg-turkiye-izle

### Add your comment and screenshots

When AdGuard DoH is set under Opera Settings > System > DNS-over-HTTPS provider: `https://dns.adguard.com/dns-query` video player on blutv takes either too long to start or doesn't start at all. Turning off DoH or setting up any other DNS provider such as NextDNS, Quad9 etc. live stream starts instantly! To reproduce the issue make sure to set up AdGuardDNS DoH exactly described above. Don't activate AdGuardDNS filter inside AdGuard browser extension, doing so won't reproduce it. It must be set up as DoH in the browser settings. It also doesn't work (live stream either takes too long to start or doesn't start at all) on any device like Android TV, phone or tablet as well as Firefox browser with AdGuardDNS DoH and DoT.

This issue is created before with the title [blutv.com VOD video player doesn't work with AdGuardDNS #934](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/934) but assigned dev couldn't reproduce it and asked too many things, I did but he kept asking and finally he asked a HAR file which has lots of identifiable data and private info. I explained it and spent lots of time to test it with different variation and provided screenshots but the dev simple didn't care and claimed "it is 100% is not cause by domain blocking" for an issue he couldn't even reproduced. It has been 6 months since then, and I wanted to give AdGuardDNS another shot but the issue is still exist and the issue is closed without any fix. 

I first encountered this issue with EasyList and created an issue there, their devs fixed it within 3 days without even asking anything. [This](https://github.com/easylist/easylist/issues/11456) is how they fixed the issue. This and all other details with screenshots and all is on the other issue [#934 ](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/934).

Hope this time a dev, preferably a different one provides a fix once an for all.

Thanks!

@ameshkov 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Sometimes it does not play with Cloudflare DNS. If plays - delay is 15-25 seconds.
Not sure, if this is AdGuard's issue.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/193238378-e9513501-3740-403c-8ee3-c91faa890749.png)


</details>

**Comment by trackerct** [comment]
some ads and trackers.  please block this. i use adguard family filter dns. 
log-va.tiktokv.com
mon.isnssdk.com
mon.tiktokv.com
mon-va.byteoversea.com
mon-va.tiktokv.com
www.adxserve.com
adsgard.aprod.scopely.io
489a19fa-d831-4954-858d-46436d5cdb20.register.collector.scopely.io
c.amazon-adsystem.com
fenrir-resolver.aprod.scopely.io
config.sdk.scopely.io
iot-eu-logser.realme.com
applog.matrix.easebar.com
sigma-statistics-push.proxima.nie.easebar.com
mcount.easebar.com
who.nie.easebar.com
appdump.nie.easebar.com
cdn.orangeclickmedia.com
iot-logser.realme.com
iriscoremetadataprod.blob.core.windows.net
apitm.toolmatrix.plus
sigma-statistics-push.proxima.nie.easebar.com
applog.matrix.easebar.com
api.segment.io
o861134.ingest.sentry.io
sentry.justwatch.com
wzrkt.com
mdp-appconf-sg.heytapdl.com
client-uc.heytapmobi.com
amnyescsmgcagjj.com
teleport.soom.la
aax.amazon-adsystem.com
regionconfig.amplitude.com
api2.amplitude.com
6b73d00a-d4a1-4350-825a-cd3f49afa460.register.collector.scopely.io
sessions.bugsnag.com
guce.oath.com
m.yap.yahoo.com
data.flurry.com
log.tapatalk.com
appsrv.display.io
display.ad.daum.net
ad.cauly.co.kr
xconf.cauly.co.kr
image.cauly.co.kr
csi.gstatic.com
in.appcenter.ms
a.adtng.com
www.obashwmzrfofi.com
platform.bidgear.com
www.visariomedia.com
pl15402247.highperformancecpm.com
st.bebi.com
ja2n2u30a6rgyd.com
uop.umeng.com
mcf4wh-jdfmxrzzzttwqcrf-d3b4.device.marketingcloudapis.com
logs.psm.wmcdp.io
identity.api.wmcdp.io
identity.mparticle.com
config2.mparticle.com
dpm.demdex.net
sanalytics.tbs.com
config.claspws.tv
metrics.claspws.tv
api.ipify.org
ws-na.amazon-adsystem.com
pro.ip-api.com
api6.ipify.org
track.wattpad.com
cdn-settings.segment.com
aax-us.amazon-adsystem.com
api2.branch.io
remote-data.urbanairship.com
device-api.urbanairship.com
self.events.data.microsoft.com
mobile.pipe.aria.microsoft.com
log.rewardpumpkin.com
public.shtranssion.com
creative.eagllwin.com
api.eagllwin.com
api.hisavana.com
firebaselogging-pa.googleapis.com
tags.tiqcdn.com
config.rcs.mnc002.mcc286.pub.3gppnetwork.org
netperform-is.vodafone.com.tr
vodafonetr.sc.omtrdc.net
mplusps.ims.vodafone.com
mpluswf.ims.vodafone.com
tr-vcode-od.vivoglobal.com
tr-vcode-api.vivoglobal.com
tr-st-sl.vivoglobal.com
tr-domaincfg.vivoglobal.com
tr-timesync.vivoglobal.com
tr-romsp-unifyconfig.vivoglobal.com
advertise.ldplayer.net
storeen.ldmnq.com
adabdapi.ldmnq.com
storeus.ldmnq.com
startup.mobile.yandex.net
data.media-lab.ai
sf16-static.i18n-pglstatp.com
asia-ex-adlog.vivoglobal.com
asia-analyzer-appstore.vivoglobal.com
asia-exstsdk.vivoglobal.com
asia-comort-stsdk.vivoglobal.com
asia-comonrt-stsdk.vivoglobal.com
asia-analyzer-appstore.vivoglobal.com
grs.dbankcloud.eu
grs.platform.dbankcloud.ru
sctclick2.com
cdn.orangeclickmedia.com
amnyescsmgcagjj.com
infinitedata-pa.googleapis.com

**Comment by Sanseviearia** [comment]
> Sometimes it does not play with Cloudflare DNS. If plays - delay is 15-25 seconds. Not sure, if this is AdGuard's issue.
> Details
> 
> ![image](https://user-images.githubusercontent.com/8361299/193238378-e9513501-3740-403c-8ee3-c91faa890749.png)
> 
> Look at timerat the bottom of screenshot.

Hi Alex, not sure if we can fix it with you as you said you can't reproduce it but let's give it another shot. I'd like to remind you [this](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/934#issuecomment-1101931709) test I did months ago.

The delay you mentioned is new but there is a significant difference between AdGuardDNS and others. What you see it player completely loaded and waiting for stream vs page, image, player load takes too much time.

When AdGuardDNS is set in the browser Settings / System / Use DNS-over-HTTPS instead of the system’s DNS settings: (sometimes setting doesn't stick, to make sure it is, close Settings tab, reopen it and check DNS section if it is set AdGuard and also check with dnscheck.tools as well)

1. Page load takes too long to complete, spinning wheel on the browser tap keeps spinning over and over and over...
2. Loading images takes time too
3. While page load takes time, player isn't loaded at all, just a black box
4. Then player is partially loaded, player time is -0:00 with no red dot and CANLI text
5. After awhile player loading is complete and it waits the stream, you can see that red dot with CANLI text
6. Then stream starts

When any other DNS is set

1. Page load is instant
2. Image load is instant
3. Player load is instant (Red dot with CANLI text)
4. A few seconds wait time for stream to start

You either could not reproduce it (maybe not setting AdGuardDNS from Settings of the browser DoH) or don't want to fix it for some reason. Either way, please pass this issue to another dev, @ameshkov?.

In the mean time, since EasyList fixed this issue, why don't you apply the same fix and let's see if it'll fix the issue for AdGuardDNS too?

EasyList Fix link: https://github.com/easylist/easylist/commit/734ec0dcae07d65f60b39abad9367fe5a35fa454

`@@||yottaa.net^*/analytics/gtm-analytics-events.min.js$domain=hannaandersson.com
@@||yottaa.net^*/scripts/eventtracking/$script,domain=containerstore.com
@@||youbora.com/*/js/adapters/jwplayer$script
@@||youbora.com/*/js/adapters/theoplayer$script
@@||youtube.com/api/analytics/$~third-party
@@||zappos.com/js/trackingPixel/mercentTracker.js
@@||zoominfo.com/c/amplitude-js$script,~third-party`

**Comment by Sanseviearia** [comment]
> some ads and trackers. please block this. i use adguard family filter dns. 

Is this anyhow related to bluTV?

**Comment by Alex-302** [comment]
> When CloudFlare / CF No Malware DNS is set
> 
> 1. Page load is instant
> 2. Image load is instant
> 3. Player load is instant (Red dot with CANLI text)
> 4. A few seconds wait time for stream to start

No. I checked with СА and plater did not load fast, and sometimes failed to load.

> In the mean time, since EasyList fixed this issue, why don't you apply the same fix and let's see if it'll fix the issue for AdGuardDNS too?

Please read how DNS filtering works.

**Comment by Sanseviearia** [comment]
> No. I checked with СА and plater did not load fast, and sometimes failed to load.
See? It works without any issues on my end, always instant. That's why I asked another dev to step in. You can't reproduce it. Also, it's better to mention that setting and switching different DNS providers in browser settings don't always work. For instance you make the change but it keeps using the previous one. To make sure it does make the switch I did closed settings, reopened it and saw it still uses the previous one, then I changed it again and checked with dnscheck tools to make sure it made the change. So it took a lot of time for me to try different DNS providers back and forth. Maybe you faced the same issue as well, thought DNS has changed but it didn't and that's why CloudFlare didn't work for you sometimes...

And again, setting AG DNS from AG extension is not enough to reproduce this issue, DNS must be set from browser settings.
> Please read how DNS filtering works.
Oh, I do know how it works, thanks. The issue is related to that domain EL whitelisted, so they fixed the issue but I didn't see the same whitelisting on AG yet.

**Comment by Alex-302** [comment]
> The issue is related to that domain EL whitelisted, so they fixed the issue but I didn't see the same whitelisting on AG yet.

`youbora.com` was removed from DNS filter 10 month ago
https://github.com/AdguardTeam/AdGuardSDNSFilter/commit/b168c1e10f65b207d203e906757ebf484de55386

Could you please check with the same DNS, but in another browser?
