### ISSUE TITLE
NaverCafe(com.nhn.android.navercafe) app loading slow

### ISSUE THREAD

**Issue by jiyongwoo** [AdguardTeam/AdGuardSDNSFilter#1064]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [x] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Add your comment and screenshots

ipada.**_cafe.naver_**.com blocking makes **_NaverCafe_**(com.nhn.android.navercafe) app loading slow
(this server(ipada.cafe.naver.com) ~ NaverCafe service; no visible ad)
Please remove '||ipada.cafe.naver.com^' from adguard dns filter
Maybe this has removed from ad(not dns) filter
![KakaoTalk_20221008_004054409](https://user-images.githubusercontent.com/41583431/194609111-b6c51afc-4351-4829-a9d5-e43c2fdb4c68.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
I cannot login.
@piquark6046 Could you please check?

**Comment by piquark6046** [comment]
The initial loading speed that is a loading delay when a user opens the application is the same.
I tested with AdGuard for Android 3.6.10 + DNS filtering filter + Quad9 configuration.

@jiyongwoo Did you register any cafe group?
@Alex-302 Do you need more data about it?

**Comment by Alex-302** [comment]
@piquark6046 Just wondering if blocking of thad domain can affect an app's performance.

**Comment by jiyongwoo** [comment]
When you test, kill app process and then restart app.

**Comment by jiyongwoo** [comment]
With blocking, after green screen, it takes 6~7 seconds blank.
Without blocking, after green screen, it takes 1~2 seconds blank.

**Comment by piquark6046** [comment]
@jiyongwoo Ok. I confirmed that blocking `ipada.naver.com` domain can delay initial loading.
