### ISSUE TITLE
zebrack app

### ISSUE THREAD

**Issue by yellow-x-black** [AdguardTeam/AdGuardSDNSFilter#1068]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard DNSフィルター
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed ads

### Where did you encounter the problem?

https://play.google.com/store/apps/details?id=com.zebrack

### Add your comment and screenshots

1.The ads displayed after finishing reading the manga on the Zebrack app have not been completely removed.  I think there will be about 3.

2.I couldn't take a screenshot.

*I can't speak English. I can speak Japanese.

### Privacy

- [x] I agree to follow this condition

**Comment by Alex-302** [comment]
I don't see ads, only blank pages. Ads are blocked.
