### ISSUE TITLE
False positives on ipinfo.io

### ISSUE THREAD

**Issue by ZeroAnarchy** [AdguardTeam/AdGuardSDNSFilter#1071]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

[AdGuard DNS Filter](https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt)

### What browser or app do you use?

Other app

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://ipinfo.io

### Add your comment and screenshots

On October 20, the site [ipinfo.io](https://ipinfo.io) stopped opening via AdGuard DNS. After https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/1070 pull request ipinfo.io is both on the [filter list](https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt) and the [exclusion list](https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/Filters/exclusions.txt). Something went wrong.

> dig A ipinfo.io @94.140.14.14
> 
> ; <<>> DiG 9.18.7 <<>> A ipinfo.io @94.140.14.14
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 23461
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 1232
> ;; QUESTION SECTION:
> ;ipinfo.io.                     IN      A
> 
> ;; ANSWER SECTION:
> ipinfo.io.              3600    IN      A       0.0.0.0
> 
> ;; Query time: 66 msec
> ;; SERVER: 94.140.14.14#53(94.140.14.14) (UDP)
> ;; WHEN: Thu Oct 20 19:56:39 +03 2022
> ;; MSG SIZE  rcvd: 54

### Privacy

- [X] I agree to follow this condition

**Comment by flavorgold1** [comment]
This site should not be on this list at all.

It just provides run of the mill info on IP addresses.

**Comment by wrt54g** [comment]
pixel.ipinfo.io is a tracking website, but ipinfo.io itself is not.

**Comment by ILLKX** [comment]
I think https://raw.githubusercontent.com/lassekongo83/Frellwits-filter-lists/master/Frellwits-Swedish-Hosts-File.txt which is contained in the default Adguard Filter list is too aggressive.

> ||api.ipify.org^
> ||ipinfo.io^

**Comment by Alex-302** [comment]
@ph00lt0 

> The website is used directly (also without subdomain) in API' to snitch IP addresses of visitors of third party websites.

That info, related to IP, is public.

**Comment by ZeroAnarchy** [comment]
Thanks!

**Comment by ZeroAnarchy** [comment]
@ph00lt0 

> Highly disagree. It shares data with a third party. Often illegally informing this company that this IP visited a certain website/app. Nothing about this is public data. Only the return of data is public.

You may be right, but your words are not supported by evidence. 

I looked at the documentation on the site and they don't have the functionality you describe on any of the paid plans. They use a regular token for the API request, which is not linked to any specific sites. How do you think IPInfo should know that a certain IP visited a certain site?

Also, as far as I remember, this site has never been on any tracker blocking lists. If it is in "Frellwits-Swedish-Hosts-File" then why it is not in "Frellwits-Swedish-Filter".

https://ipinfo.io/faq/article/130-ip-data-privacy

**Comment by ZeroAnarchy** [comment]
@ph00lt0

By blocking ipinfo.io on client devices you will not prevent the web server from accessing the IPInfo API on its side. The client won't even know about it.

Maybe you mean that the request to the API comes from JavaScript in the user's browser, but 1) I haven't seen any site that does that with ipinfo, 2) the webmaster can disable sending Referer header in JavaScript.

**Comment by jellizaveta** [comment]
Hi all! The domain `ipinfo.io` was already unblocked in our filters, due to errors in the config an exception was not working. We fixed that.
The exception does not involve the domain used for tracking.

**Comment by jellizaveta** [comment]
Hi all! The domain [ipinfo.io](http://ipinfo.io/) was already unblocked in our filters, but an exception was not working. We fixed that.
The exception does not involve the domain used for tracking.
