### ISSUE TITLE
Off parental control

### ISSUE THREAD

**Issue by zaizaai** [AdguardTeam/AdGuardSDNSFilter#1082]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS, AdGuard private DNS, AdGuard Home, Other

### Version

ahaha

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

Jans

### What DNS filters do you have enabled?

I want to off parental control

### What browser or app do you use?

Firefox, Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

chrome and firefox

### Add your comment and screenshots

I'm already at legal age

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
You can use https://adguard-dns.io/
