### ISSUE TITLE
api.ipify.org false positive?

### ISSUE THREAD

**Issue by BornToBeRoot** [AdguardTeam/AdGuardSDNSFilter#1086]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### Version

-

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

-

### What DNS filters do you have enabled?

https://v.firebog.net/hosts/AdguardDNS.txt

### What browser or app do you use?

Other app

### Which device type do you use?

Other device

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

-

### Add your comment and screenshots

api.ipify.org is a false positive... it's used to get the public IP 

TLD: https://www.ipify.org/

Also api64.ipify.org is not blocked...

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
api.ipify.org not a tracker

**Comment by BornToBeRoot** [comment]
Thanks!
