### ISSUE TITLE
Adding i.tct-rom.com to Public DNS

### ISSUE THREAD

**Issue by jacktoreno** [AdguardTeam/AdGuardSDNSFilter#1087]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

I am using the public DNS service.

### What browser or app do you use?

Firefox

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed analytics or tracker

### Where did you encounter the problem?

i.tct-rom.com

### Add your comment and screenshots

Hello. Can you please add "i.tct-rom.com" to the public DNS. This is a tracker used by many of my system apps on my device. I have disabled all possible apps but there are system apps I cannot disable. The apps continuously send information regarding my device over and over. 

Thanks for your time.

![1](https://user-images.githubusercontent.com/71465509/198833991-6536cf45-b17f-4449-a90b-b1021adde7a7.png)
![2](https://user-images.githubusercontent.com/71465509/198833994-add254ed-f778-4f3d-b5aa-1ec380f65774.png)
![3](https://user-images.githubusercontent.com/71465509/198833996-a27df384-c61d-462e-9f7f-6429379b45ba.png)
![4](https://user-images.githubusercontent.com/71465509/198834107-7c7f5751-177d-480a-a0ff-31fba9a6ddcd.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@jacktoreno Hi. Can't find any info about this subdomain. Are these requests made by this app?
https://apk.support/app-ru/com.tct.soundrecorder

**Comment by jacktoreno** [comment]
@Alex-302 Hello and thanks for the reply. Here is the app I am talking about which is one of many system apps that send information to that subdomain above.

https://www.mediafire.com/file/5kiu0mlzt4v9g1i/Sound_Recorder-com.tcl.tct.soundrecorder.apk/file

I have used HTTPToolkit here for HTTPS analysis:

https://httptoolkit.com/

On both my PC and Android device. HTTPToolkit pushes its own cert into the Android device. Let me know if you require further information. Note that this app is part of TCL phone devices.

**Comment by Alex-302** [comment]
Ok, checked also APK
https://beta.pithus.org/report/e5c5823b379dee110f50dee85905ea5107294d51e442c1954afa62809b7632ca
Will block i.tct-rom.com

**Comment by jacktoreno** [comment]
Thank you.

**Comment by Alex-302** [comment]
DNS filter is compiled from few sources. AdguardFilters is on of the sources.
