### ISSUE TITLE
Blockade

### ISSUE THREAD

**Issue by nettw** [AdguardTeam/AdGuardSDNSFilter#109]
@Alex-302 

### Steps to reproduce

Hi,

I hope that you put these lists into the filter and block them in the file, thank you!
||global.adserver.yahoo.com^
||tw.adserver.yahoo.com^
||ailiyou1999.com^
||snyowx29.com^
||tuigang1999.com^
||victory1999.com^

### Expected behavior

They are the ad server that must be blocked.

### Actual behavior

Has not been added yet.

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default
| How did you setup DNS configuration:| System
| Device model:| Samsung Galaxy A7 2018
| Operating system and version:| Android 9

**Comment by Alex-302** [comment]
Hi. I need more details. Where are they used?

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #38124](https://github.com/AdguardTeam/AdguardFilters/issues/38124) via [**ZenHub**](https://www.zenhub.com/)
