### ISSUE TITLE
joinsg.net is being blocked

### ISSUE THREAD

**Issue by weirdal3333** [AdguardTeam/AdGuardSDNSFilter#1091]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

regular dns ip entry in router

### What DNS filters do you have enabled?

just the public dns

### What browser or app do you use?

Firefox

### Which device type do you use?

Other device

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://joinsg.net

### Add your comment and screenshots

It says it's malware. It's not malware.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Cannot reproduce. Probably already fixed.
