### ISSUE TITLE
Miss ettoday.net ad

### ISSUE THREAD

**Issue by a77841s** [AdguardTeam/AdGuardSDNSFilter#1092]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### What DNS filters do you have enabled?

AdGuard DNS filter
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed ads, Missed analytics or tracker

### Where did you encounter the problem?

https://health.ettoday.net/amp/amp_news.php7?news_id=1391907&from=google.com

### Add your comment and screenshots

![IMG_20221104_035623](https://user-images.githubusercontent.com/53136211/199821536-51c28080-855c-4ee1-aa05-42a1f995d353.jpg)
![IMG_20221104_035540](https://user-images.githubusercontent.com/53136211/199821547-5dbfd234-5007-4a8e-8a19-6a0a866bbd55.jpg)

ad.ettoday.net、ad1.ettoday.net、ad2.ettoday.net

I only know of these three items, and others, such as the notice below.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
DNS can't block elements of pages.
