### ISSUE TITLE
Cannot reach to last.fm

### ISSUE THREAD

**Issue by abx-dx** [AdguardTeam/AdGuardSDNSFilter#1093]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://family.adguard-dns.com/dns-query

### What DNS filters do you have enabled?

Nothing.

### What browser or app do you use?

Other app

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.last.fm

### Add your comment and screenshots

Recently last.fm has been blocked via AdGuard DNS Family Protection.

### Privacy

- [X] I agree to follow this condition

**Comment by ameshkov** [comment]
Fixed it, thank you!
