### ISSUE TITLE
enertres.com

### ISSUE THREAD

**Issue by rayman18** [AdguardTeam/AdGuardSDNSFilter#1099]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Dns default filters

### What browser or app do you use?

Safari

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://enertres.com/

### Add your comment and screenshots

1- website not loading. Adguard message blocking

### Privacy

- [X] I agree to follow this condition

**Comment by VladisLoveZh** [comment]
Seems safe. Removed from blocklist
