### ISSUE TITLE
Invalid rule

### ISSUE THREAD

**Issue by rEnr3n** [AdguardTeam/AdGuardSDNSFilter#110]
### Steps to reproduce

1. Find `-logging.nextmedia.com` at the filter list.

### Expected behavior

Domain names cannot start with a dash.

**Comment by Alex-302** [comment]
AdGuard DNS and AdGuard Home can block domains by mask.
![image](https://user-images.githubusercontent.com/8361299/62609624-cd7f6300-b90a-11e9-890a-5e426c8b1c20.png)
