### ISSUE TITLE
need to block browser.events.data.msn.cn

### ISSUE THREAD

**Issue by TomKing062** [AdguardTeam/AdGuardSDNSFilter#1100]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

https://easylist-downloads.adblockplus.org/easylistchina+easylist.txt
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed analytics or tracker

### Add your comment and screenshots

on my windows 10, Edge Dev 109 requests browser.events.data.msn.cn instead of browser.events.data.msn.com when new edge browser is open, so browser.events.data.msn.cn should be blocked like browser.events.data.msn.com
no need to screenshot i think

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Wrong reprository. Added to filters.
