### ISSUE TITLE
Blocked secure site

### ISSUE THREAD

**Issue by bg777** [AdguardTeam/AdGuardSDNSFilter#1102]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.dtg1873.de

### Add your comment and screenshots

Secure website of sports club DTG 1873  in Dortmund, Germany

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
will be checked.
