### ISSUE TITLE
cmsbetconstruct.com

### ISSUE THREAD

**Issue by Miteirao** [AdguardTeam/AdGuardSDNSFilter#1103]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### Version

Adguard Android 3.6.10 (51)

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

Cloudflare default DoH

### What DNS filters do you have enabled?

Adguard DNS filter
https://filters.adtidy.org/android/filters/15_optimized.txt

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://m.vbet.lat/pb/ https://m.fogobet.com/pb/ and others

### Add your comment and screenshots

Betconstruct is an essential part of Vbet and others same-system betting sites. Promotions page, home page banners and other features doesn't work with Adguard DNS filter enabled.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Removed from our filter.
