### ISSUE TITLE
False positives on dbankcloud.cn

### ISSUE THREAD

**Issue by fyihang** [AdguardTeam/AdGuardSDNSFilter#1110]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### What DNS filters do you have enabled?

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Other app

### Which device type do you use?

Other device

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

dbankcloud.cn

### Add your comment and screenshots

Adguard DNS Filter blocks all the sub -domain names of dbankcloud.cn, but this domain name is used for Hilink smart devices. If this domain name is blocked, Hilink smart devices cannot be connected to the server and cannot be used normally. After adding this domain name to the allowable list, the Hilink smart device at home can work normally.

At 04:14 today (UTC), Adguard Home automatically updated the filter, and my Huawei Smart Lock could not be used. This brought me a lot of trouble and reduced the safety of the family.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Changed rules. Please check again.
