### ISSUE TITLE
Thanx.com blocked

### ISSUE THREAD

**Issue by slothdog** [AdguardTeam/AdGuardSDNSFilter#1111]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

v0.107.18

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://doh.opendns.com/dns-query

### What DNS filters do you have enabled?

Parental filter

### What browser or app do you use?

Safari

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

Thanx.com

### Add your comment and screenshots

![72E7C4B2-8162-4624-B8FA-E2F75DCEE79F](https://user-images.githubusercontent.com/1995595/203583642-82fcf56d-72eb-4b97-9493-1388d43cf9df.png)

### Privacy

- [X] I agree to follow this condition

**Comment by VladisLoveZh** [comment]
Reviewed as safe, so it's unlocked now.
