### ISSUE TITLE
e.customeriomail.com

### ISSUE THREAD

**Issue by PavelParkhomenko** [AdguardTeam/AdGuardSDNSFilter#1114]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Safari

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

e.customeriomail.com

### Add your comment and screenshots

One of our users contacted technical support and requested unblocking the following site:
e.customeriomail.com
Currently this request can not be resolved when using AdGuard DNS server.

Please check if unblocking is possible.

### Privacy

- [X] I agree to follow this condition

**Comment by hagezi** [comment]
`e.customeriomail.com` is blocked by CNAME `track.customer.io`. Marked as referral domain. So it is only called when you click on a corresponding link.

**Comment by jellizaveta** [comment]
@hagezi Hello, could you please send a link for checking?

**Comment by hagezi** [comment]
@jellizaveta see https://customer.io/docs/link-tracking/ for for more details.
