### ISSUE TITLE
Site block 

### ISSUE THREAD

**Issue by Niken42** [AdguardTeam/AdGuardSDNSFilter#1119]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Add your comment and screenshots

![Screenshot_20221127-205907_Chrome](https://user-images.githubusercontent.com/119207438/204143513-d4f4b5cb-4358-4fa8-adf2-8475c1c97384.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Already fixed.
