### ISSUE TITLE
False positive on https://bit.ly/TwitchDrops-Darktide

### ISSUE THREAD

**Issue by Doc-4** [AdguardTeam/AdGuardSDNSFilter#1121]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

No filters outside of what's filtered by the standard server config on 94.140.14.14

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://bit.ly/TwitchDrops-Darktide

### Add your comment and screenshots

I use adguard DNS configured via IP on a router with DOT enabled as opportunistic. Using ISP DNS and flushing the cache lets the site work again.
![image](https://user-images.githubusercontent.com/60247583/204144321-75ef84cd-92fc-4479-ad08-cd1b21d52d14.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Already fixed.
