### ISSUE TITLE
Bit.ly is not bad!! 

### ISSUE THREAD

**Issue by fiifa** [AdguardTeam/AdGuardSDNSFilter#1122]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### What DNS filters do you have enabled?

AdGuart filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://bit.ly/

### Add your comment and screenshots

Hello, i have a problem... AD guartd blocking a bit.ly site. Can you fix it, please? Thanks. 

### Privacy

- [X] I agree to follow this condition

**Comment by fiifa** [comment]
So much people wrote this here.

**Comment by Alex-302** [comment]
Not blocked at the moment
![image](https://user-images.githubusercontent.com/8361299/204759501-511b7631-10c7-4105-a875-936130007e5e.png)

**Comment by fiifa** [comment]
Hello, tysm!
