### ISSUE TITLE
bit.ly shortcuts should not be blocked

### ISSUE THREAD

**Issue by Franzie** [AdguardTeam/AdGuardSDNSFilter#1123]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

latest

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

dc267413.d.adguard-dns.com

### What DNS filters do you have enabled?

AdGuard DNS

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://bit.ly

### Add your comment and screenshots

https://bit.ly get's blocked, but only in Firefox

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not blocked at the moment. 
![image](https://user-images.githubusercontent.com/8361299/204759592-adb209a0-e05f-48bf-a109-df03d72e6bec.png)
