### ISSUE TITLE
Essential Missing Sites/Domains From AdGuard DNS

### ISSUE THREAD

**Issue by Eow2022yia** [AdguardTeam/AdGuardSDNSFilter#1127]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

I am only using AdGuard’s public DNS resolver.

### What browser or app do you use?

Firefox, Safari, Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed ads, Missed analytics or tracker

### Add your comment and screenshots

Hello there,

Please may I request a review for the following domains to be blacklisted as they are adware and/or trackers:

	1.	fengkongcloud.com
	2.	urbanairship.com
	3.	scorecardresearch.com
	4.	telemetry.bluedot.io
	5.	stocks-analytics-events.news.apple-dns.net
	6.	device-metrics-us-2.amazon.com
	7.	device-metrics-us.amazon.com
	8.	firebaseinstallations.googleapis.com
	9.	firebasedynamiclinks.googleapis.com
	10.	firebaseremoteconfig.googleapis.com
	11.	firebaseinappmessaging.googleapis.com
	12.	fcmtoken.googleapis.com
	13.	k.isprog.com 
	14.	deviceid.tantanapp.com
	15.	sc-report.tantanapp.com
	16.	devices.tantanapp.com
	17.	client-monitor.tantanapp.com
	18.	report.tantanapp.com
	19.	client-tracking.tantanapp.com
	20.	paas-push-api-log.immomo.com
	21.	referee.immomo.com
	22.	counter.tantanapp.com
	23.	connperf.immomo.com
	24.	app-log-lab.tantanapp.com
	25.	geolocation.onetrust.com
	26.	cdn.cookielaw.org
	27.	row-advil.waze.com
	28.	advil.waze.com
	29.	scontent-iad3-1.cdninstagram.com
	30.	scontent-iad3-2.cdninstagram.com
	31.	app-site-association.cdn-apple.com
	32.	paas-push-api.immomo.com
	33.	autoupdate.tantanapp.com
	34.	keepconn.tantanapp.com
	35.	keepconn.gcp.vip.tantanapp.com
	36.	app-site-association.cdn-apple.com
	37.	notice.sp-prod.net
	38.	campaign.adobe.com
	39.	datadoghq.eu
	40.	datadoghq.com
	41.	geolocation.onetrust.com
	42.	redirector.gvt1.com
	43.	analytics.google.com
	44.	redirector.googlevideo.com
	45.	reports.radiotime.com
	46.	protostats.bigo.sg
	47.	bugsnag.com
	48.	usabilla.com
	49.	analytics.sky.com
	50.	metrics.sky.com
	51.	smetrics.sky.com
	52.	madmetrics.com
	53.	dzc-metrics.mzstatic.com
	54.	braze.com
	55.	braze.eu
	56.	smetrics.mcdonalds.com
	57.	onetag.com
	58.	webproxy-advp.iad-apple.com.akadns.net
	59.	tracedock.com
	60.	ingenioustechnologies.com
	61.	a8.net
	62.	actionlink.jp
	63.	365you.com
	64.	securemvt.apple.com
	65.	userreport.com
	66.	sf16-muse-va.ibytedtos.com
	67.	startup.mobile.yandex.net
	68.	mc.yandex.ru
	69.	graph.digiseller.ru
	70.	postaffiliatepro.com
	71.	eulerian.net
	72.	bat.bing.com
	73.	quantummetric.com
	74.	lightboxcdn.com
	75.	quantummetric.com
	76.	ads.54646.co
	77.	adfarm.adition.com
	78.	benabid.me
	79.	cryft.com
	80.	adfarm1.adition.com
	81.	mobile-data.onetrust.io

     * Some may already be blocked.

Thank you.

### Privacy

- [X] I agree to follow this condition

**Comment by Eow2022yia** [comment]
Hi,

You may try the sites,

It is your DNS so could you please verify this regarding which are blocked currently or not?

Thanks.

**Comment by Eow2022yia** [comment]
> > Some may already be blocked
> 
> 
> 
> We need the list with domains, which are not blocked only.
> 
> 
> 
> > firebase
> 
> 
> 
> It is not an analytics service. It is a bug tracker.

Hi,

You may try the sites,

It is your DNS so could you please verify this regarding which are blocked currently or not?

Thanks.

**Comment by Alex-302** [comment]
I need the sites, where you find that domains.

**Comment by Eow2022yia** [comment]
> I need the sites, where you find that domains.

Hi,

This is from my own personal list of domains that are not released,

However many of these may also be found on 1HostsPro and Energized Protection Block Lists.

Thank you.

**Comment by Alex-302** [comment]
I can't add these domains. The most of them are already blocked or not ads/tracking, or may break sites.

**Comment by Eow2022yia** [comment]
> I can't add these domains. The most of them are already blocked or not ads/tracking, or may break sites.

May I ask?
Which ones may break sites?

There is many domains there that should be blocked by default as they are on most AdBlockers and DNS.
