### ISSUE TITLE
Fitbit domain is not working with AdGuard DNS

### ISSUE THREAD

**Issue by vox-danger** [AdguardTeam/AdGuardSDNSFilter#1128]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard DNS

### AdGuard version

2.0

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

the problem is with app, not a site

### Which device do you use?

Mobile

### Where is the problem encountered?

Fitbit domain

### What filters do you have enabled?

AdGuard Mobile Ads filter, AdGuard DNS filter, EasyList

### Add your comment and screenshots

In fitbit app it shows oops! looks like there is no internet connection retry but disabling adguard dns it worked so please whitelist all fitbit app domains

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@vox-danger Hello! Unfortunately, I cannot reproduce this issue. Could you please clear the filtering log in AdGuard, then go to the Fitbit application and repeat the issue, then send a screenshot of the filtering log with all blocked requests.

**Comment by Alex-302** [comment]
Filtering log is available only in AdGuard `private` DNS

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/205307780-b0669a35-8762-4650-bd13-4a64117759fb.png)


</details>

**Comment by vox-danger** [comment]
Hello thank you for your reply so i successfully set my my device and the adguard private dns dashboard 
now i can see the fitbit domain 
![image](https://user-images.githubusercontent.com/111675278/205476128-6a26b292-398e-4f8f-8c8b-17540ec4954f.png)
now how to unblock it?

**Comment by hagezi** [comment]
@vox-danger The domains are processed, so not blocked, there is nothing to unblock.

**Comment by vox-danger** [comment]
thanks for the reply but when i added the dns still the fitbit app is showing the same error 
i have attached the screenshot 
if you are trying to recreate the issue i will include what have i don for more info:
1. make sure your private dns is set to adguard's private dns
2. download the fitbit app from google play store 
3. sign in or sign up
4. set up a fitbit smartwatch and link to the app
5. go to account, then click your device 
6. open face gallery
7. then it shows this error in this screenshot
![Screenshot_20221205_153826](https://user-images.githubusercontent.com/111675278/205591977-5ed62268-236d-43d9-9243-d84633f08ae9.jpg)
Thanks for your quick response again.
:)

**Comment by hagezi** [comment]
@vox-danger Post the domains from the Querlyog that are blocked during the app usage.

**Comment by hagezi** [comment]
@vox-danger Whitelist google-analytics.com in AdGuardDNS, add the following to the user rules:
`@@|google-analytics.com^`

Wait 2 minutes and then try if it works.

**Comment by vox-danger** [comment]
@hagezi i saw the link already but the thing is in don't want to remove the private dns (the adblocker) just for fitbit app 
domains:
gallery-webview.fitbit.com
static0.fitbit.com
corporate-webapps.fitbit.com
android-cdn-api.fitbit.com
android-api.fitbit.com

**Comment by hagezi** [comment]
@vox-danger 
As described above, the domians you have posted are not blocked by AdGuardDNS, so they cannot be the cause. Only the blocked ones are of interest.
Try whitelisting from `google-analytics.com`.

**Comment by vox-danger** [comment]
well i whitlisted all fitbit domains and google anylatics let me check

**Comment by Alex-302** [comment]
@vox-danger Please check with non-filtered AdGuard DNS
94.140.14.140
https://unfiltered.adguard-dns.com/dns-query

**Comment by vox-danger** [comment]
@Alex-302 how?

**Comment by Alex-302** [comment]
> 94.140.14.140

**Comment by vox-danger** [comment]
@Alex-302  i still couldn't get it can you explain me how to do it on android?

**Comment by Alex-302** [comment]
@vox-danger https://developers.google.com/speed/public-dns/docs/using#android but enter `94.140.14.140` instead of Google server. Or choose it in AdGuard app.

**Comment by vox-danger** [comment]
bro why did you close it?

**Comment by Alex-302** [comment]
@vox-danger We have no ability to check this problem. If there are no answers to questions for a long time, we close.
Users can always reply, even in closed issues.
