### ISSUE TITLE
||deapi.afreecatv.com^ seems to be blocking ads at afreecatv.com

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#1129]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

The above-mentioned rule seems to be blocking ads at afreecatv.com on the DNS level (via NextDNS and Private AdGuard DNS).

### Proposed solution

Consider adding the rule to the public DNS blocklist

### Additional information

Reported by 689496 (helpdesk ID)

**Comment by Alex-302** [comment]
Will be handled in regular filters.
