### ISSUE TITLE
tag.search.sensefuel.live

### ISSUE THREAD

**Issue by nbivan** [AdguardTeam/AdGuardSDNSFilter#1132]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

www.bricomart.es

### Add your comment and screenshots

The filter blocks tag.search.sensefuel.live, causing the search engine to not work on the web https://www.bricomart.es/

### Privacy

- [X] I agree to follow this condition

**Comment by hagezi** [comment]
I can confirm, the rule `||tag.search.sensefuel.live^` breaks the search.

**Comment by Alex-302** [comment]
One site only. It's not worth it to remove the rule. You can use adguard-dns.io and disable the rule by `||tag.search.sensefuel.live^$badfilter`
Fixed same issue for ad blockers.
