### ISSUE TITLE
Uber Eats Tracking (UK)

### ISSUE THREAD

**Issue by welshname** [AdguardTeam/AdGuardSDNSFilter#1133]
Haven't managed to figure out what the URLs are yet but the live tracking of your delivery doesn't work.

If you close the tracking and reopen then it updates, but with the tracking page open you get no updates.

Not sure if this is the same for normal Uber tracking too.

Thanks

**Comment by jellizaveta** [comment]
@welshname Hello! Please provide more details. Where did you encounter the problem, what filters do you have enabled, what browser or app are you using, what type of device are you using?
