### ISSUE TITLE
Add EasyList Dutch third-party ad servers to sources

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#1134]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

There's a list of dutch ad servers that we currently don't block on the DNS level.

It makes sense to add them.

### Proposed solution

See the details here:
https://github.com/AdguardTeam/HostlistsRegistry/issues/62#issuecomment-1339474139

**Comment by jellizaveta** [comment]
EasyList Dutch added to the AdGuard DNS filter.

**Comment by deeeds** [comment]
Can the EasyList Dutch also be added to adguard-dns.io as well?
