### ISSUE TITLE
netcoresmartech.com

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdGuardSDNSFilter#1135]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

Adguard DNS

### What DNS filters do you have enabled?

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.cgv.vn/

### Add your comment and screenshots

Website is break because Adguard DNS is affected by EasyPrivacy filter

Can't choose seats when booking

Allow domain name `netcoresmartech.com` will work

Steps:
1. Login account
2. Choose to book movie tickets
3. Select date and time
4. Can't choose a seat at the seat selection page

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
I am not sure if we can remove the rule, because one site only is broken. You can use our private DNS and unblock this domain.

**Comment by bigdargon** [comment]
@Alex-302 Thank you! I reported to EasyList but no response yet! https://github.com/easylist/easylist/issues/14338

**Comment by Alex-302** [comment]
For DNS filterig broken sites is not a high priority issue. For example, google ads/analytics blocking greaks many sites, but we cannot remove blocking rules, because DNS filtering will be useless.
