### ISSUE TITLE
Cloudways website blocked by AdGuard DNS

### ISSUE THREAD

**Issue by limjimmy25** [AdguardTeam/AdGuardSDNSFilter#1140]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Default.

### What browser or app do you use?

Firefox, Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.cloudways.com/

### Add your comment and screenshots

![Screenshot Cloudways](https://user-images.githubusercontent.com/120151583/206613712-85634079-fa7d-4c35-9440-adb5194d6594.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
www.cloudways.com marked as safe and removed from the block list.
