### ISSUE TITLE
These Domains need to be unblocked for my Shaw app to work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#1142]
@Batman2814 commented on [Mon Dec 12 2022](https://github.com/AdguardTeam/AdGuardDNS/issues/470)

1.) www.google-analytics.com
2.) rum-collector-2.pingdom.net
3.) siteintercept.qualtrics.com
4.) rum-static.pingdom.net
5.) strack.shaw.ca
6.) cdn.appdynamics.com
7.) shaw.demdex.net
8.) cm.everesttech.net

As far as I know this is on Android.

**Comment by ameshkov** [comment]
Google Analytics and Qualtrics definitely won't be unblocked.
Pingdom - maybe.
Others need to be checked.

@Batman2814 you can unblock them in your own User rules.

**Comment by jellizaveta** [comment]
@Batman2814 Hello, we do not block these domains:
```
rum-collector-2.pingdom.net
siteintercept.qualtrics.com
rum-static.pingdom.net
strack.shaw.ca

```
Unfortunately, I can't register in this app. Could you please send the logs to filters@adguard.com?

**Comment by Batman2814** [comment]
can u tell me how to do that?

**Comment by jellizaveta** [comment]
1. Prepare to collect AdGuard log
https://kb.adguard.com/en/android/solving-problems/log

2. Setup default system default DNS, enable DNS filtering in AdGuard DNS settings and reproduce this issue;

3. Sent the logs with issue link, time stamp and actual behavior(reproduced/not reproduced) to [support@adguard.com](mailto:support@adguard.com)

4. Enable AdGuard DNS in DNS settings and disable DNS filtering

Repeat step 3.

**Comment by Batman2814** [comment]
when u say default system default dns do u mean system default in the app where it use internet service provider because I'm using Adgaurd Personal DNS on my router.

**Comment by Batman2814** [comment]
do u want me to collect adgaurd log when adguard personal dns is on or off in the Adguard Android App

**Comment by jellizaveta** [comment]
@Batman2814 If you unblock the domains you mentioned in your issue - does the app work correctly?

**Comment by Batman2814** [comment]
it does work correctly if i do unblock them.
you want me to collect logs twice one with  default Adgaurd DNS in the app on and one with Adgaurd Personal DNS on

**Comment by jellizaveta** [comment]
Okay, if your exceptions work, please leave them in your user filter. Of the domains you sent in the AdGuard DNS blocks only: 
```
google-analytics.com
cm.everesttech.net
shaw.demdex.net.
```
But we can't exclude them because they are used for tracking and advertising.

**Comment by Batman2814** [comment]
In order for the app to work I have to allow tracking in order to use the app. is there a way to make the app work without it having to track me.

**Comment by jellizaveta** [comment]
You can try contacting the app support
