### ISSUE TITLE
These Domains need to be unblocked for Paybbight app to work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#1143]
@Batman2814 commented on [Mon Dec 12 2022](https://github.com/AdguardTeam/AdGuardDNS/issues/471)

1.) Inside paybright app to open apple website in the app this domain needs to be unblocked
apple.sjv.io 

2.) This domain also must be unblocked to open Samsung website in the app 
i.w55c.net

**Comment by jellizaveta** [comment]
@Batman2814 Hi!
We do not block `apple.sjv.io. Check the filtering log to see which blocklist blocked this request and unblock it. 
`i.w55c.net` is used to show ads on other sites, we can't unblock it.
