### ISSUE TITLE
Family protection servers: Blocks free software download site Vector

### ISSUE THREAD

**Issue by KSR-Yasuda** [AdguardTeam/AdGuardSDNSFilter#1145]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

Family protection servers (`94.140.14.{15,16}`)

### What DNS filters do you have enabled?

Family protection servers (`94.140.14.{15,16}`)

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://ftp.vector.co.jp/42/07/3179/PwOffTimer.zip

### Add your comment and screenshots

It is the download page of [a free software](https://www.vector.co.jp/soft/winnt/util/se311657.html?ds) in free software site [Vector](https://www.vector.co.jp/?ds).

It is quite not NSFW site, but is blocked by parental control DNS.

Default server (ad block only) works for it.
Just parental control filter is wrong.

### Privacy

- [X] I agree to follow this condition

**Comment by VladisLoveZh** [comment]
ftp.vector.co.jp marked as safe and removed from the block list.
