### ISSUE TITLE
An inquiry 

### ISSUE THREAD

**Issue by FsAguard62** [AdguardTeam/AdGuardSDNSFilter#1150]
Hello AdGuard Team, Is this another spying, tracking site of Microsoft's associated domain’s > bingviz.azurefd.net < This is something new that I am seeing on the dns activity log query list ?!? I am sorry that I deleted the activity log so I could provide you with more information about this domain. I don't know if this is tied to an application or just running randomly on the iPhone ISO system. Note, I wasn't sure how to ask this question. I also want to ask this question on the AG filters issues part too. But there is no place for asking questions there.

**Comment by Alex-302** [comment]
Hi. In general Azure is not a tracking. MS services may be broken.
