### ISSUE TITLE
IPFS Share Blocked

### ISSUE THREAD

**Issue by bubblesthebear** [AdguardTeam/AdGuardSDNSFilter#1151]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

No software, just set to AdGuard public DNS

### What DNS filters do you have enabled?

The default public server with general filtering

### What browser or app do you use?

Safari

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

ipfs.dweb.link

### Add your comment and screenshots

[Webpage](ipfs.dweb.link) was blocked by AdGuard but the context for visiting the link was to receive a file I shared to myself via [](share.ipfs.io) 
<details>![9B4A9035-6422-46C4-B46F-3B70B2CCED7D](https://user-images.githubusercontent.com/42428543/207730824-fc715947-4c90-4a3d-a1c4-6afeaa574d31.png)`
![30E2196C-16F7-4247-BC5C-4472B71A8E54](https://user-images.githubusercontent.com/42428543/207730828-faeb7dde-c781-4c73-ba91-621db6922b76.png)</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
This domain is marked as malware. @Oniqqqq could you please take a look?

**Comment by Oniqqqq** [comment]
Hello! Thank you for reporting this. ipfs.dweb.link itself is a legitimate service, but someone could use it to create phishing links. We have whitelisted the ipfs.dweb.link domain itself, but some of the previously reported subdomains should still be blocked. Please, check if it works in your case.
