### ISSUE TITLE
acko insurance website wrong marked as adult website

### ISSUE THREAD

**Issue by Govind-Rajulu** [AdguardTeam/AdGuardSDNSFilter#1155]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### What DNS filters do you have enabled?

All Adguard Filters,
All Easylist filters,
All Fanboy's filters.

### What browser or app do you use?

Firefox

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.acko.com/

### Add your comment and screenshots

Have turned on Parental filter in Adguard Private DNS

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
will be checked
