### ISSUE TITLE
delivery.kotak-amc.com is incorrectly blocked

### ISSUE THREAD

**Issue by rnavaneethan** [AdguardTeam/AdGuardSDNSFilter#1157]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

AdGuard Home v0.107.21

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

tls://1dot1dot1dot1.cloudflare-dns.com

### What DNS filters do you have enabled?

https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_23.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_8.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_24.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_6.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_3.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_32.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

http://delivery.kotak-amc.com/MFCOJWI?id=166421=JkQBUgQBUANUGQ8CUgwOU1IOUlxTAQFUAlMHBFRSAAFXWwBVBgNUVQMDDwkFAAgFVgFIFl5QQgVcBARADlBYdwJVUApeGQdeCBkIBgYICgkNCQJRBQcFVABRUEgORUJHXxceB1dbDUcAF0AeWlZNUF8VVQlTH1cLX04sciV+fGAsB1gHTkFX&fl=DUxFE0ENSx4SEk4eWlZNUF9VUkpTXllLew8HWxRcV0MMV19MUFsLVhZKXEFEUE1Ia1dBEFxeWw9tBQRXOQMGBVdn&ext=dXRtX3NvdXJjZT1pbnYmdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249ZXF1aXR5X291dF9kZWMyMiZ1dG1fdGVybT1lcXVpdHlfb3V0X2RlYzIyJnA1Y29udGFjdGlkPTE2NDQyMTImcDVTb3VyY2U9bWFpbA==

### Add your comment and screenshots

Looks like delivery.kotak-amc.com is CNAME for `lnk.pepipost.net`. For some reason, AdGuard Home is blocking this site. Kindly check. 

I would like to point out that I disabled all blocked and have only `use AdGuard browsing security web service` enabled for this client. 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Will be fixed.
