### ISSUE TITLE
cdn.userreport.com is incorrectly blocked

### ISSUE THREAD

**Issue by SukkaW** [AdguardTeam/AdGuardSDNSFilter#1158]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### What DNS filters do you have enabled?

* AdGuardDNSFilter

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://feedback.userreport.com/54df04ba-e0bb-448a-8b33-0767e02a3942

### Add your comment and screenshots

The domain `cdn.userreport.com` is blocked by AdGuardDNSFilter, causing the page fails to load.

<details>
  <img width="1327" alt="image" src="https://user-images.githubusercontent.com/40715044/208808714-f4a6726d-59ef-49a9-9791-9de1cd40d7e9.png">
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
We cannot unblock this domain. If you are using this site, you can setup own private AdGuard DNS https://adguard-dns.io/ and unblock this domain for all or specific your devices.
