### ISSUE TITLE
Android devices can't get update, because the update provide server domain block by ADH

### ISSUE THREAD

**Issue by Lawlietr** [AdguardTeam/AdGuardSDNSFilter#116]
I have 3 Android phone ( pixel2, pixel3, oneplus one ), same android version 9.0
All devices using my own dns server, the dns services based on ADH

I found the Google play app update just show "waiting for download" very long time
I checkout and found the problem because that domain "gvt1.com" are block by AdGuard Simplified Domain Names filter.

**Comment by BlazDT** [comment]
Opened pull request:

@ryanbr can you please remove the rule from EasyList again, thank you.

**Comment by ameshkov** [comment]
@BlazDT we should remove it from AdGuard Base filter instead. 

`redirector.gvt1.com` domains have nothing to do with ads or tracking and having it on the list might cause different compatibility issues.

**Comment by BlazDT** [comment]
OK, opened pull request for EasyList source. Our base filter should normally exclude it then too.
