### ISSUE TITLE
https://www.mariehaynes.com/

### ISSUE THREAD

**Issue by vubipo** [AdguardTeam/AdGuardSDNSFilter#1160]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

94.140.14.49
94.140.14.59

### What DNS filters do you have enabled?

We blocked this page because of parental filter restrictions.
**You're trying to reach a website listed by AdGuard as inappropriate for kids. If you’re an adult, you can switch off Parental control in the settings or add this website to the allowlist.**
[More information](https://link.adtidy.org/forward.html?action=site_report_page&app=adguard_dnsparental&domain=www.mariehaynes.com)

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Add your comment and screenshots

blocked due to parental filter, this is a seo news website.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Marked as safe and removed from the block list. Update should be available today or at least tomorrow.
