### ISSUE TITLE
Domain should be added to the block list

### ISSUE THREAD

**Issue by FsAguard62** [AdguardTeam/AdGuardSDNSFilter#1161]
This is shown on my iphone like this > mcfv5k1xv60g8mpw-0wnbxsghw31.device.marketingcloudapis.com < it has to with the delivery of advertising stuff. Please look into this? 
![A2282CAA-A53E-4649-B44A-5C42EFB9E36D](https://user-images.githubusercontent.com/78290214/209478336-c1a235ae-79f9-4267-8197-cb377844350f.png)

**Comment by Alex-302** [comment]
Cannot be blocked without details.

**Comment by FsAguard62** [comment]
Greetings, Alex, I found a bit more information about it, and it happens when I had, “every time” opened the Grammarly.com iPhone application and the website there could be other apps, and I did some investigating on the web/internet so, I also made a few screenshots to show you, it seems to be a salesforce domain that gathers up information on the device maybe more, this was also, had been once or maybe several times mentioned before on your GitHub site, and I been blocking it for quite some time ago now, on all of my iPhone devices. 🙂

May I ask you what kind of details are you looking for, exactly, other than reproducing the issue? 🙂

Sincerely, 🙂Frank S.








Original screenshot: 

End.

On Monday, December 26, 2022, 4:24 AM, Alex ***@***.***> wrote:




Closed #1161 as completed.

**Comment by Alex-302** [comment]
I can't reproduce, so I cannot check what the purpose of this domain. It may be used not for analytics only(salesforce.com).
