### ISSUE TITLE
My DeviantArt Site got blocked without knowing the reason

### ISSUE THREAD

**Issue by HedgePrism** [AdguardTeam/AdGuardSDNSFilter#1163]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS, AdGuard private DNS, AdGuard Home, Other

### Version

2,0

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

Website or app doesn't work properly

### What DNS filters do you have enabled?

the problem is with app, not a site

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed analytics or tracker, Website or app doesn't work properly

### Where did you encounter the problem?

DeviantArt Domain and got blocked for no reason

### Add your comment and screenshots

![image](https://user-images.githubusercontent.com/121504602/209685129-974e78a5-fe81-40bf-b820-53973ca1881b.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It is blocked by the parental control module because the site contains erotic content. You may disable it.
