### ISSUE TITLE
Block sb.scorecardresearch.com

### ISSUE THREAD

**Issue by hj-collab** [AdguardTeam/AdGuardSDNSFilter#1164]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

I am using Adguard public DNS DoH. So no controls for me.

### What browser or app do you use?

Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed analytics or tracker

### Add your comment and screenshots

Following up on a previous request. https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/492

This is being blocked by default in uBlock Origin and none of the site breaks. It's just a tracker and not a functionality of any site where it's being used.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Many sites was broken by blocking of this domain.
The most recent case: https://github.com/AdguardTeam/AdguardFilters/issues/139431
