### ISSUE TITLE
the site is blocked my.calltouch.ru

### ISSUE THREAD

**Issue by Oniqqqq** [AdguardTeam/AdGuardSDNSFilter#1165]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard DNS Filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

my.calltouch.ru

### Add your comment and screenshots

![image](https://user-images.githubusercontent.com/38912221/209935249-adf281a9-5494-4793-9d9a-3079176fd697.png)
one of our customers reported that the website is being blocked, but it's not in our dns lists: https://reports.adguard.com/en/my.calltouch.ru/report.html 

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Blocked by EasyPrivacy tracking servers. It's a tracking service, I don't think we should unblock it
