### ISSUE TITLE
edition.cnn.com

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardSDNSFilter#1167]
@adguard-bot commented on [Fri Dec 30 2022](https://github.com/AdguardTeam/AdguardFilters/issues/138729)

### Issue URL (Incorrect Blocking)
 [https://edition.cnn.com/2022/12/28/china/china-zhengzhou-car-pile-up-intl-hnk/index.html](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fedition.cnn.com%2F2022%2F12%2F28%2Fchina%2Fchina-zhengzhou-car-pile-up-intl-hnk%2Findex.html)
### Comment
Username: @jslawler
> Reported here: https://www.reddit.com/r/Adguard/comments/zy5fzq/cant_watch_videos_on_stove_sites_when_adguard_is/?utm_source=share&utm_medium=ios_app&utm_name=iossmf
> 
> 
> Reproduced by me, using only AdGuard DNS filter. Safari protection was disabled.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/OhRZTiI.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/H3WKlNp.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard/AdGuard Pro for iOS v4.4.5
Browser: | Safari
DNS filtering: | server: `Personal AdGuard DNS`<br>filters: `AdGuard DNS Filter`
Filters: | <b>Other:</b><br/>AdGuard DNS

---

@jslawler commented on [Fri Dec 30 2022](https://github.com/AdguardTeam/AdguardFilters/issues/138729#issuecomment-1367667115)

When AdGuard DNS Filter is enabled (and likely some other filters which are part of AdGuard DNS Filter) the video on this page fails to load.

When it's turned off, it immediately loads for me.

---

@BlazDT commented on [Fri Dec 30 2022](https://github.com/AdguardTeam/AdguardFilters/issues/138729#issuecomment-1367873734)

Even when DNS protection is enabled I cannot reproduce. Please check @zloyden 

---

@zloyden commented on [Fri Dec 30 2022](https://github.com/AdguardTeam/AdguardFilters/issues/138729#issuecomment-1367944471)

I can confirm that. @jslawler please report about it here next time https://github.com/AdguardTeam/AdGuardSDNSFilter.

**Comment by jslawler** [comment]
@zloyden I reported the issue via the reporting tool, not via GitHub.

Possibly the reporting tool should be expanded to use this repo as well.

**Comment by zloyden** [comment]
Fixed by the scriptlet rule. Update the filters in 2-3 hours.
If you using only the AdGuard DNS, I suggest you either switch to AdGuard non-filtered DNS or Private DNS. We won't unblock the request.
