### ISSUE TITLE
Url Shortener lihi2.cc seems blocked

### ISSUE THREAD

**Issue by ztdu** [AdguardTeam/AdGuardSDNSFilter#1169]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

AdGuard for iOS v. 4.4.5 (990)

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

AdGuard DNS-over-HTTPS

### What DNS filters do you have enabled?

No

### What browser or app do you use?

Safari

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://lihi2.cc/R4kUu?fbclid=PAAaa_-Zk8NjSwtS_nc5EmRDnYc2_63DVtElfpxqqKeFi7lRtKTqJondqr-AU_aem_AaGzMoKVAKGYroyR8i7OEXWt8juphBNSDDF-Yxtr8thNZK3sxupqyXsGRIfsQwt93xbRZjxtx8RrVYawqBCUuUbkOZBq3Q4KrscZavHK2RVH-2R2yRuJX9txv2Ft6ngfPEE

### Add your comment and screenshots

1. lihi2.cc is just a url shortener, with utm and some tracking functionality. You can block those tracking tricks but please don’t block the whole domain including so many people’s webpage redirected from lihi2.cc
2. 
![3FF98BC1-C9FE-45EB-B66C-5992BAB73634](https://user-images.githubusercontent.com/80333016/210209221-1988d521-c2e8-4316-abc9-180e17ee2c41.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reproduced.
