### ISSUE TITLE
Remove a wrong rule on My VNPT app

### ISSUE THREAD

**Issue by trmdi** [AdguardTeam/AdGuardSDNSFilter#1172]
### What DNS server do you use?

AdGuard private DNS

### What DNS filters do you have enabled?

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

My VNPT

### Which device type do you use?

Mobile

### What type of problem have you encountered?

App doesn't work properly

### Add your comment and screenshots

This was removed in another repo but still need be removed here.
Please see comments here:
https://github.com/AdguardTeam/AdguardFilters/issues/122941#issuecomment-1365874468

@zloyden

**Comment by Alex-302** [comment]
@bigdargon Hi. Could you please take a look? (also https://github.com/AdguardTeam/AdguardFilters/issues/122941#issuecomment-1365874468)
Maybe `||ipcc-vnp1.vnptmedia.vn^` blocks too much.

**Comment by bigdargon** [comment]
@Alex-302 Thank you! I have checked and will remove it!

**Comment by Alex-302** [comment]
@bigdargon Thanks.
