### ISSUE TITLE
es-plus.videoplaza.tv to add to DNS blocklist 

### ISSUE THREAD

**Issue by VladisLoveZh** [AdguardTeam/AdGuardSDNSFilter#1176]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

User request: 

> It would be great that your servers 94.140.14.14 and 94.140.15.15 could block the address "es-plus.videoplaza.tv". This address generates adds and (maybe tracking) in Spain. So, my question is for asking if you could add it to your blocklists.
> 
> I only mentioned StevenBlackList to justify that some subdomains of "videoplaza.tv" are already being blocked in other stable lists, but Adguard list only blocks "videoplaza.com" which is not enough to block this ads.
> 
> https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt - Line 21788 (only videoplaza.com)
> https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts - Lines 1528 - 1534 (subdomains of videoplaza.tv, but not yet "es-plus.videoplaza.tv", I will write them too 🙂 )_

### Proposed solution

add es-plus.videoplaza.tv to DNS blocklist

**Comment by Alex-302** [comment]
@VladisLoveZh Hi. Where we can check it?
