### ISSUE TITLE
jbhivi.store

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/AdGuardSDNSFilter#1177]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### What DNS filters do you have enabled?

AdGuard DNS Filter

### What browser or app do you use?

Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed ads

### Where did you encounter the problem?

https://jbhivi.store/

### Add your comment and screenshots

Can you kindly please block `https://jbhivi.store/`

It is a phishing website and targets https://jbhifi.com.au, they have [put up a post on Facebook warning the public and in the screenshot is the URL](https://m.facebook.com/JBHiFi/photos/a.214773761888730/6299810073385038/?type=3&mibextid=Nif5oz)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It is dead.

**Comment by gyCfjSnO** [comment]
> It is dead.

I got the domain taken down quicker than getting it added onto a Blocklist 😂
