### ISSUE TITLE
opten.hu

### ISSUE THREAD

**Issue by kovacsr89** [AdguardTeam/AdGuardSDNSFilter#1178]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard DNS filter
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.opten.hu/

### Add your comment and screenshots

The opten.hu is completely safe, but it blocked by AdGuard DNS filter.
https://reports.adguard.com/en/opten.hu/report.html

![adguard_opten](https://user-images.githubusercontent.com/5217311/211171828-7dd2b845-05cd-45bd-b884-6fdc2babdf63.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Please check tomorrow.
