### ISSUE TITLE
crm-cdn.peek-cloppenburg.com

### ISSUE THREAD

**Issue by CowMowTV** [AdguardTeam/AdGuardSDNSFilter#1181]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard DNS without NSFW

### What browser or app do you use?

Chrome, Safari, Microsoft Edge

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

crm-cdn.peek-cloppenburg.com

### Add your comment and screenshots

Clicking on ads in mails from Peek&Cloppenburg Düsseldorf leads into DNS_PROBE_FINISHED_NXDOMAIN (Edge) or Cannot resolve hostname (CMD/Terminal, Safari) error. Should be pretty self explanatory.

Is it intentional that AdGuard generally blocks CRM tools, even if they are only used in consented newsletters, or is it a false positive? The issue only has existed for roughly 3 weeks.

### Privacy

- [X] I agree to follow this condition

**Comment by hagezi** [comment]
@Alex-302 
Blocked by CNAME: `puc-cdn.exponea.com`
Rule: `||exponea.com^`
