### ISSUE TITLE
linkt-help.top

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/AdGuardSDNSFilter#1184]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### What DNS filters do you have enabled?

AdGuard DNS Filter

### What browser or app do you use?

Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed ads

### Where did you encounter the problem?

linkt-help.top

### Add your comment and screenshots

Can you kindly please block this site engaging in phishing activities?

The website in question is `linkt-help.top`, and it is targeting a legitimate website/business `linkt.com.au`.

Website was reported to the web host & domain registrar, the site may be offline by the time you see this so I have [archived the webpage](https://web.archive.org/web/20230111140114/http://www.linkt-help.top/linkt1.php) for your convenience.

I've also [flagged with a number of security vendors](https://www.virustotal.com/gui/url/8f89f1d423845780f1edd5031e0b44ead1e3914802172a499b2bda22bbdfa9d7?nocache=1)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/212064911-98598837-9aa1-4c0f-a903-8ff089d33af3.png)
