### ISSUE TITLE
alert-bendigobank.com

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/AdGuardSDNSFilter#1186]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### What DNS filters do you have enabled?

AdGuard DNS Filter

### What browser or app do you use?

Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed ads

### Where did you encounter the problem?

alert-bendigobank.com

### Add your comment and screenshots

This website should be added on the block list, the website in question is `alert-bendigobank.com`, and it is targeting a legitimate website/business https://www.bendigobank.com.au/.

A copy of the archived phishing website can be found here https://web.archive.org/web/20230112065834/https://alert-bendigobank.com/ and attached is a screenshot of the website accessed today.

16 security vendors flagged this URL as malicious on VirusTotal https://www.virustotal.com/gui/url/08bc9ad10c0cf23f827c9554cb680239949861773df6ff6ece65dc2f2b7e6688?nocache=1

![image](https://user-images.githubusercontent.com/49738152/212000286-2688cf33-f82e-4d19-baa1-8462a093b2ce.png)

### Privacy

- [X] I agree to follow this condition

**Comment by VladisLoveZh** [comment]
Reviewed as scam\phishing – Closed.
