### ISSUE TITLE
anz-shield-secure.com

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/AdGuardSDNSFilter#1187]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### What DNS filters do you have enabled?

AdGuard DNS Filter

### What browser or app do you use?

Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed ads

### Where did you encounter the problem?

anz-shield-secure.com

### Add your comment and screenshots

This website should be added on the block list, the website in question is `anz-shield-secure.com`, and it is targeting a legitimate website/business https://www.anz.com.au/.

I was unable to create an archived copy of the phishing website using the Wayback Machine as it has reCAPTCHA enabled, I have however attached a screenshot for your convenience.

7 security vendors flagged this URL as malicious on VirusTotal https://www.virustotal.com/gui/url/6d796f85b757fd04a1cb6a03a613fb0dd543a003551f146e4ccef529f7c6fb8f?nocache=1

![image](https://user-images.githubusercontent.com/49738152/212010091-cd682c04-2641-4690-a318-e99dd25751eb.png)

### Privacy

- [X] I agree to follow this condition

**Comment by VladisLoveZh** [comment]
Reviewed as phishing\scam – closed.
