### ISSUE TITLE
 false lock website

### ISSUE THREAD

**Issue by A9FM** [AdguardTeam/AdGuardSDNSFilter#1188]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

*

### What DNS filters do you have enabled?

*

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://tgstat.com

### Add your comment and screenshots

![image](https://user-images.githubusercontent.com/68541852/212103767-cfdd95fd-cfbc-48ca-91cf-7cb9afe900b4.png)
false lock web-site

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Will be checked. Not related to DNS ditectly.
