### ISSUE TITLE
reviewmygov.tuquy.com

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/AdGuardSDNSFilter#1190]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

I believe the website `http://reviewmygov.tuquy.com/MyGov/index.html` to be a phishing website and targets https://my.gov.au/, can this be added on to the blocklist please?

I have reported to both the web host and domain registrar.

[VirusTotal](https://www.virustotal.com/gui/url/120d77be52cfd73768ba8cecd7cf9762cb2e13a8d66dec80f145b4856aa224bd?nocache=1)
[Wayback Machine](https://web.archive.org/web/20230113052519/http://reviewmygov.tuquy.com/MyGov/index.html)

![reviewmygov tuquy com](https://user-images.githubusercontent.com/49738152/212255124-e8149647-2e34-4426-b18b-c3ad089d11e2.png)

### Proposed solution

Block the domain

**Comment by Alex-302** [comment]
Dead.

**Comment by Alex-302** [comment]
About phishing better write to support@adguard.com
