### ISSUE TITLE
www.thechillresort.com

### ISSUE THREAD

**Issue by NSR-007** [AdguardTeam/AdGuardSDNSFilter#1193]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Adguard DNS set in Asus router

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.thechillresort.com/

### Add your comment and screenshots

Blocked... However its a hotel resort in Koh Chang
![Screenshot_2023-01-17-09-54-27-121_com android chrome](https://user-images.githubusercontent.com/101789250/212799652-e87de3b8-cc5f-4895-ab3a-d0589c5169ff.jpg)
![Screenshot_2023-01-17-09-54-15-004_com android chrome](https://user-images.githubusercontent.com/101789250/212799664-ae4cea26-6010-4565-aaf1-3bbc662fa600.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Will be fixed.
About dangerous sites(incl. false alarms) please write to support@adguard.com
