### ISSUE TITLE
lihi2.cc in adguard-malware-shavar

### ISSUE THREAD

**Issue by yoyo930021** [AdguardTeam/AdGuardSDNSFilter#1194]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

v0.107.21

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

h3://dns.cloudflare.com/dns-query
https://dns.cloudflare.com/dns-query
https://101.101.101.101/dns-query
[/www.feib.com.tw/]https://101.101.101.101/dns-query

### What DNS filters do you have enabled?

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Firefox, Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://lihi2.cc/ew1vM

### Add your comment and screenshots

The lihi2.cc is a URL shortener in Taiwan. https://lihi.io/
It is mainly used for marketing.

It should not appear in the security ruleset.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Cannot reproduce.
About dangerous sites(incl. false alarms) please write to support@adguard.com
