### ISSUE TITLE
www.ghmc.gov.in not opening using public DNS

### ISSUE THREAD

**Issue by mohitanchalia** [AdguardTeam/AdGuardSDNSFilter#1195]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Public DNS 94.140.14.14, 94.140.15.15

### What browser or app do you use?

Chrome, Safari

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.ghmc.gov.in

### Add your comment and screenshots

Trying to access a government website ([www.ghmc.gov.in](http://www.ghmc.gov.in/)) in India, but it does not load with AdGuard Public DNS turned on as seen in below screenshot (with and without Adguard DNS):
![Without and with Adguard DNS ghmc gov in](https://user-images.githubusercontent.com/122956584/213086868-1d6931cb-caac-4239-800c-dbe40cf70091.png)

Request you to please allow this website to load via your Public DNS.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
I guess this is site's DNS configuration issue. Maybe this site works in India only.

Same with Google DNS 

![image](https://user-images.githubusercontent.com/8361299/213162200-68798839-fe31-409e-ae36-3fdd98e636ac.png)

**Comment by mohitanchalia** [comment]
But it's opening correctly here using Google's DNS server 8.8.8.8, 8.8.8.4. 
Only when I change to Adguard Public DNS, it stops working.

**Comment by Alex-302** [comment]
Are you in India or outside?

**Comment by mohitanchalia** [comment]
India

**Comment by Alex-302** [comment]
Please check if you can visit this site with VPN.

**Comment by mohitanchalia** [comment]
Yes, it's working with a USA VPN

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdGuardDNS #512](https://github.com/AdguardTeam/AdGuardDNS/issues/512) via [**Zenhub**](https://www.zenhub.com/)
