### ISSUE TITLE
lifeandstylemag.com Block by Parental Control (False Positive)

### ISSUE THREAD

**Issue by archon-valec** [AdguardTeam/AdGuardSDNSFilter#1197]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

AdGuard Home v0.107.21

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://dns10.quad9.net/dns-query
https://dns.adguard-dns.com/dns-query
tls://dns.adguard-dns.com
quic://dns.adguard-dns.com
tls://security-filter-dns.cleanbrowsing.org
https://doh.opendns.com/dns-query
tls://security.cloudflare-dns.com
https://security.cloudflare-dns.com/dns-query
https://dns.quad9.net/dns-query
tls://dns.quad9.net
https://dns11.quad9.net/dns-query
tls://dns11.quad9.net
https://protected.canadianshield.cira.ca/dns-query
tls://protected.canadianshield.cira.ca
https://doh.applied-privacy.net/query
tls://dot1.applied-privacy.net
https://dnsforge.de/dns-query
tls://dnsforge.de
https://freedns.controld.com/p2
tls://p2.freedns.controld.com
https://adblock.doh.mullvad.net/dns-query
tls://adblock.doh.mullvad.net

### What DNS filters do you have enabled?

The NoTracking blocklist
https://adguardteam.github.io/HostlistsRegistry/assets/filter_32.txt
379,737
January 19, 2023 at 15:52

Perflyst and Dandelion Sprout's Smart-TV Blocklist
https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt
152
January 19, 2023 at 15:52

OISD Blocklist Full
https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt
338,103
January 19, 2023 at 15:52

Steven Black's List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt
168,818
January 19, 2023 at 15:52

Dandelion Sprout's Game Console Adblock List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_6.txt
10
January 19, 2023 at 15:52

WindowsSpyBlocker - Hosts spy rules
https://adguardteam.github.io/HostlistsRegistry/assets/filter_23.txt
347
January 19, 2023 at 15:52

Phishing URL Blocklist (PhishTank and OpenPhish)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt
10,071
January 19, 2023 at 15:52

Dandelion Sprout's Anti-Malware List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt
13,807
January 19, 2023 at 15:52

NoCoin Filter List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_8.txt
720
January 19, 2023 at 15:52

Scam Blocklist by DurableNapkin
https://adguardteam.github.io/HostlistsRegistry/assets/filter_10.txt
372
January 19, 2023 at 15:52

Stalkerware Indicators List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_31.txt
837
January 19, 2023 at 15:52

The Big List of Hacked Malware Web Sites
https://adguardteam.github.io/HostlistsRegistry/assets/filter_9.txt
13,468
January 19, 2023 at 15:52

Malicious URL Blocklist (URLHaus)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt
24,035
January 19, 2023 at 15:52

Peter Lowe's Blocklist
https://adguardteam.github.io/HostlistsRegistry/assets/filter_3.txt
3,664
January 19, 2023 at 15:52

AdGuard DNS filter
https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
48,552
January 19, 2023 at 15:52

HaGeZi Personal Black & White
https://adguardteam.github.io/HostlistsRegistry/assets/filter_34.txt
26,835
January 19, 2023 at 15:52

Dan Pollock's List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_4.txt
11,398
January 19, 2023 at 15:52

AdAway Default Blocklist
https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
7,355
January 19, 2023 at 15:52

1Hosts (Lite)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_24.txt
58,205
January 19, 2023 at 15:52

### What browser or app do you use?

Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

www.lifeandstylemag.com

### Add your comment and screenshots

Website is safe, yet blocked by parental control. Even when clicking on "more information" on the block page, it says it's safe. 

![image](https://user-images.githubusercontent.com/83673957/213558816-ccc3c7f2-2d4d-435c-84f3-efabcc30b0b6.png)

![image](https://user-images.githubusercontent.com/83673957/213558953-52644114-8bf5-4d09-8272-7ed52a9632fe.png)

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
The website is on parental control lists because it contains adult content, such as nudity
