### ISSUE TITLE
newrelic.com

### ISSUE THREAD

**Issue by dzadonskii** [AdguardTeam/AdGuardSDNSFilter#1200]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS, AdGuard Home

### Version

AdGuard Home v0.107.19

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://dns.quad9.net/dns-query
quic://dns.adguard-dns.com
https://doh.opendns.com/dns-query
https://dns.adguard-dns.com/dns-query

### What DNS filters do you have enabled?

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
https://adaway.org/hosts.txt
https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
https://someonewhocares.org/hosts/zero/hosts
https://raw.githubusercontent.com/DandelionSprout/adfilt/master/GameConsoleAdblockList.txt
https://abp.oisd.nl/
https://abp.oisd.nl/nsfwbig/

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://newrelic.com

### Add your comment and screenshots

1. Blocked AdGuard filter. This was not the case until today. It completely breaks NewRelic website (website / client login / dashboard)
![blocked2](https://user-images.githubusercontent.com/41732202/214309755-3a5321d7-f0b8-4dab-8733-60420f7ac21d.png)

2. Even if I add a custom exception it is still blocked by upstream AdGuard DNS servers
![blocked](https://user-images.githubusercontent.com/41732202/214310493-af233732-617f-4878-b6b4-04d3ed4e1a0b.png)

3. With custom exception and using non-AdGuard upstream DNS it resolves correctly
![allowed](https://user-images.githubusercontent.com/41732202/214310407-dc11d321-6177-49a3-ae33-c8e29be81afa.png)

### Privacy

- [X] I agree to follow this condition

**Comment by lex-obrien** [comment]
+1 as this bit me this evening as well!  Thank you for reporting!
