### ISSUE TITLE
||kampyle.com^

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#1201]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

http://kampyle.com/

### Add your comment and screenshots

I just wanted to report that AdGuard DNS list is blocking Norton Power Eraser's Feedback form (when you click feedback from the program itself and it opens a web page to a feedback form) from loading or submitting.

### Privacy

- [X] I agree to follow this condition

**Comment by goodjohnjr** [comment]
> 

Here is the link to the Norton Power Eraser (https://support.norton.com/sp/static/external/tools/npe.html) Feedback form that opens in a web browser when you click on it in NPE:

https://nebula-cdn.kampyle.com/direct/form.html?region=prodUsOregon&websiteId=458056&formId=28866&product=nmr&language=en&version=6.0.x&oslocale=enu

Several AdGuard DNS filters block various domains that form uses, including the default AdGuard DNS list. 

I use Microsoft Edge in Windows 11 Home desktop, AdGuard VPN with AdGuard DNS (Custom with the filters: AdGuard DNS, No Coin, URL Haus, Phishing URL Block List), AdGuard For Windows (AdGuard English, AdGuard Mobile, AdGuard Tracking, AdGuard Annoyances, No Coin, URL Haus).

**Comment by goodjohnjr** [comment]
> @goodjohnjr We do not block this domain after my commit. ![image](https://user-images.githubusercontent.com/8361299/215084033-1b46e991-a755-409e-9d01-ae59a1783f8f.png) If third-party DNS filter blocks it(StevenBlack's list, AdAway) - please write to authors.

I posted that before I knew about the fix, I had seen that questions were asked and details were missing, so I responded.

It seems to be working now, I have removed all non AdGuard lists except for security lists in AdGuard & AdGuard DNS, to make it easier when reporting issues.
