### ISSUE TITLE
https://app.adriel.com/

### ISSUE THREAD

**Issue by vubipo** [AdguardTeam/AdGuardSDNSFilter#1208]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

94.140.14.49
94.140.14.59

### What DNS filters do you have enabled?

We blocked this page because of parental filter restrictions.

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://app.adriel.com/

### Add your comment and screenshots

![image](https://user-images.githubusercontent.com/10122879/215232685-33dcf081-2466-4cd2-8ede-c5d0a33f4024.png)

### Privacy

- [X] I agree to follow this condition

**Comment by VladisLoveZh** [comment]
Should be unlocked from now on.
