### ISSUE TITLE
Imposible to use some websites

### ISSUE THREAD

**Issue by trimechee** [AdguardTeam/AdGuardSDNSFilter#1209]
Hello, I don't u se adblock extension, juste AdGuard dns , i  have message to disable my adblocker so  I can't use these websites : 

https://www.rjno1.com/

https://www.buzznewstunisia.tn

https://www.universitedz.com/

https: //coflix.tv/

It will be great to add these websites to white liste  please, thank you very much  !

**Comment by Alex-302** [comment]
The most of anti-adblock scripts cannot be bypassed when used only DNS filtering.

**Comment by trimechee** [comment]
That's sad :(
