### ISSUE TITLE
http(s)://ru.vivo.com/

### ISSUE THREAD

**Issue by Quake4** [AdguardTeam/AdGuardSDNSFilter#1211]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [x] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://family.adguard-dns.com/dns-query

### What DNS filters do you have enabled?

https://family.adguard-dns.com/dns-query

### What browser or app do you use?

Microsoft Edge, Yandex Browser

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

http://ru.vivo.com/

### Add your comment and screenshots

1. This is smartphone producer site of Vivo.
<details>![image](https://user-images.githubusercontent.com/29517243/216566456-7874241b-0f4c-4409-90e6-2ef32c51efa9.png)</details>
2. Remove vivo.com from block in family list.

### Privacy

- [X] I agree to follow this condition

**Comment by VladisLoveZh** [comment]
Removed from block lists.
