### ISSUE TITLE
Site with book blocked wrong

### ISSUE THREAD

**Issue by istudyatuni** [AdguardTeam/AdGuardSDNSFilter#1212]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Not filter, just dns.adguard.com in the phone settings

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

http://belpaese2000.narod.ru/Trad/Komissar/komissarind.htm

### Add your comment and screenshots

URL blocked "because can contain malicious programs", but there is only book (as I understand)

### Privacy

- [X] I agree to follow this condition

**Comment by VladisLoveZh** [comment]
Removed from phishing list.
