### ISSUE TITLE
KI-Berlin.de blocked

### ISSUE THREAD

**Issue by lsc64** [AdguardTeam/AdGuardSDNSFilter#1219]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

AdGuard Home v0.107.22

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://dns.quad9.net/dns-query
tls://dns.quad9.net
https://dns.adguard.com/dns-query
tls://dns.adguard.com
quic://dns.adguard.com
tls://dns.google
https://dns.google/dns-query
https://security.cloudflare-dns.com/dns-query
tls://security.cloudflare-dns.com
https://dns.digitale-gesellschaft.ch/dns-query
tls://dns.digitale-gesellschaft.ch

### What DNS filters do you have enabled?

Online Malicious URL Blocklist
https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh-online.txt
3.024
14 February 2023 at 00:43
AdGuard DNS filter
https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
49.084
14 February 2023 at 00:43
OISD Blocklist Full
https://adguardteam.github.io/HostlistsRegistry/assets/filter_27.txt
277.842
14 February 2023 at 00:43
Malicious URL Blocklist (URLHaus)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt
21.273
14 February 2023 at 00:43
The Big List of Hacked Malware Web Sites
https://adguardteam.github.io/HostlistsRegistry/assets/filter_9.txt
13.478
14 February 2023 at 00:43
Stalkerware Indicators List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_31.txt
851
14 February 2023 at 00:43
Scam Blocklist by DurableNapkin
https://adguardteam.github.io/HostlistsRegistry/assets/filter_10.txt
426
14 February 2023 at 00:43
NoCoin Filter List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_8.txt
730
14 February 2023 at 00:43
Dandelion Sprout's Anti-Malware List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt
10.298
14 February 2023 at 00:43
Phishing URL Blocklist (PhishTank and OpenPhish)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt
17.735
14 February 2023 at 00:43
The NoTracking blocklist
https://adguardteam.github.io/HostlistsRegistry/assets/filter_32.txt
394.116
14 February 2023 at 00:43
OISD Blocklist Basic
https://adguardteam.github.io/HostlistsRegistry/assets/filter_5.txt
74.947
14 February 2023 at 00:43
Peter Lowe's Blocklist
https://adguardteam.github.io/HostlistsRegistry/assets/filter_3.txt
3.702
14 February 2023 at 00:43
Steven Black's List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt
177.897
14 February 2023 at 00:43
AdAway Default Blocklist
https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
7.365
14 February 2023 at 00:43
1Hosts (Lite)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_24.txt
57.430
14 February 2023 at 00:43
1Hosts (mini)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_38.txt
57.566
14 February 2023 at 00:43
Dandelion Sprout's Game Console Adblock List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_6.txt
72
14 February 2023 at 00:43
Perflyst and Dandelion Sprout's Smart-TV Blocklist
https://adguardteam.github.io/HostlistsRegistry/assets/filter_7.txt
264
14 February 2023 at 00:43
WindowsSpyBlocker - Hosts spy rules
https://adguardteam.github.io/HostlistsRegistry/assets/filter_23.txt
357
14 February 2023 at 00:43SmartTV
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt
225
14 February 2023 at 00:43
FireTV
https://perflyst.github.io/PiHoleBlocklist/AmazonFireTV.txt
17
14 February 2023 at 00:43

### What browser or app do you use?

Firefox, Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

http://ki-berlin.de/

### Add your comment and screenshots

The website is not harmful.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Seems legit. Unblocked.
