### ISSUE TITLE
New tracker domains to block

### ISSUE THREAD

**Issue by jakecharlie** [AdguardTeam/AdGuardSDNSFilter#1220]
Please add these domains to be blocked in AdguardDNS filter. It is already being blocked in NextDNS list:

From Xiaomi:
api.sec.intl.miui.com
authbe.sec.intl.miui.com
flash.sec.intl.miui.com
api.sec.intl.miui.com
api.setting.intl.miui.com
data.sec.intl.miui.com

From Shopee:
log-collector.shopee.com.br

**Comment by jellizaveta** [comment]
`log-collector.shopee.com.br` blocked by AdGuard DNS. Where can I check the tracking for Xiaomi ?

**Comment by AdamWr** [comment]
I don't have a Xiaomi device so I cannot check it out, but if these domains are related to tracking/analytics and nothing is broken when are blocked, then I think that we can add them.

**Comment by jellizaveta** [comment]
Domains for Xiaomi added

**Comment by jakecharlie** [comment]
Hello,

I just took the test and I can confirm to you that the domain **log-collector.shopee.com.br** is still not being blocked.

Today Adguard list https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt is blocking the domain:

||log-collector.shopee.
||log-collector.shopee.vn^

I think that you should block too:

||log-collector.shopee.com.br^

I can confirm as a user who uses NextDNS with multiple lists and who monitors each domain that travels through the network, that Adguard DNS is still not blocking the above domain. I recommend my suggestion with all due respect.
