### ISSUE TITLE
Amazon, LG, Google, Avast and others new tracker domains to be blocked

### ISSUE THREAD

**Issue by jakecharlie** [AdguardTeam/AdGuardSDNSFilter#1226]
Hello everyone, I have the habit of monitoring all my devices connected to the internet through NextDNS, which allows me to add several lists manually, in addition to NextDNS itself, so I added AdguardDNS, EasyPrivacy, AdAway, StevenBlack and notracking.

I noticed that the domains below, which are being blocked in the other lists, are not being blocked by AdguardDNS list.

I did the monitoring through devices such as:
- Amazon Echo Show
- Amazon Fire Tv Stick
- LG webOS SmartTV
- Motorola android smartphone
- Xiaomi smartphone

Therefore, please add these domains to be blocked in AdguardDNS filter so that more users can stop being tracked by these companies below. I wish you all a great week.

**Amazon:**
api.us-east-1.aiv-delivery.net
device-metrics-us-2.amazon.com
device-metrics-us.amazon.com
aax-us-east-retail-direct.amazon.com

**LG WebOS SmartTV:**
aic.cdpbeacon.lgtvcommon.com
aic-ngfts.lge.com

**Google:** 
www.googletagmanager.com
firebase-settings.crashlytics.com
adservice.google.com

**Avast**
analytics.ff.avast.com
shepherd.ff.avast.com
ipm-provider.ff.avast.com

**From chinese companies:**
audid-api.taobao.com
adashx4ae.ut.taobao.com
abtest.alibaba.com
woodpecker.uc.cn
httpdns-sc.aliyuncs.com
beacon-api.aliyuncs.com
adash.man.aliyuncs.com

**Imagination Unwired Ads company:**
sdkv2.imaginationunwired.com

**Mixpanel Ads company:**
api-js.mixpanel.com

 **FreeWheel, A Comcast ads Company:**
7ceaf.v.fwmrm.net
fwmrm.net

**Functional Software tracking company:**
sentry.io
o612897.ingest.sentry.io

**Scorecard Research tracking company:** 
sb.scorecardresearch.com

**AppsFlyer tracking company:** 
launches.appsflyer.com

**Piano Software tracking domain:**
experience.tinypass.com

**SmartBear Software tracking company:**
sessions.bugsnag.com
notify.bugsnag.com

**Branch Ads company:**
vulcan2.branch.io
vulcan5.branch.io

**Brazilian R7.com news website Ads domain:**
adv.r7.com

**Comment by Alex-302** [comment]
Can't be blocked because blocking will brear the sites, also we do not block bug-tracking services:

<details>

```
Mixpanel Ads company:
api-js.mixpanel.com

FreeWheel, A Comcast ads Company:
7ceaf.v.fwmrm.net
fwmrm.net

Functional Software tracking company:
sentry.io
o612897.ingest.sentry.io

Scorecard Research tracking company:
sb.scorecardresearch.com

AppsFlyer tracking company:
launches.appsflyer.com

Piano Software tracking domain:
experience.tinypass.com

SmartBear Software tracking company:
sessions.bugsnag.com
notify.bugsnag.com

firebase-settings.crashlytics.com

Google:
[www.googletagmanager.com](http://www.googletagmanager.com/)
```


</details>








Amazon:
> api.us-east-1.aiv-delivery.net

related to amazon video. Why it should be blocked?

> device-metrics-us-2.amazon.com
device-metrics-us.amazon.com
aax-us-east-retail-direct.amazon.com

where used these domains? Espesially the last.

LG WebOS SmartTV:
aic.cdpbeacon.lgtvcommon.com

> aic-ngfts.lge.com

What the purpose of this domain? Can't block without a HAR file with content.



> adservice.google.com

not used for loading ads.



Avast
> analytics.ff.avast.com

https://github.com/AdguardTeam/AdguardFilters/issues/99154

Added again, will wait for feedback.

shepherd.ff.avast.com
> ipm-provider.ff.avast.com

not used to host ads


----


> From chinese companies:
audid-api.taobao.com
adashx4ae.ut.taobao.com
woodpecker.uc.cn
beacon-api.aliyuncs.com
adash.man.aliyuncs.com

added.

> abtest.alibaba.com

not tracking

> httpdns-sc.aliyuncs.com

why should be blocked?

> Imagination Unwired Ads company:
sdkv2.imaginationunwired.com

added.

Branch Ads company:
vulcan2.branch.io
vulcan5.branch.io

> Brazilian R7.com news website Ads domain:
adv.r7.com

added.



Next time please do self-review of each of reported domains or at least provide sources, because the most of these domains cannot be blocked, and check takes a lot of time.

**Comment by jakecharlie** [comment]
> 

Hello Alex,

Thank you for reply.

I will try to explain one by one which lists are blocking them.

**Amazon:**
api.us-east-1.aiv-delivery.net
NextDNS  ads & trackers and AdAway lists: https://i.imgur.com/szdxcKM.png

device-metrics-us-2.amazon.com
device-metrics-us.amazon.com
NextDNS ads & trackers list: https://i.imgur.com/OLm3AvG.png https://i.imgur.com/7UKZZa5.png

aax-us-east-retail-direct.amazon.com
NextDNS  ads & trackers and AdAway lists: https://i.imgur.com/RQAsxl4.png

These are Amazon Advertising's tracking and ad domains.
"device-metrics-us", for example, polls every minute, sending telemetry data from the Echo Show device and Fire TV to Amazon's servers.  There are also topics saying about it: https://www.reddit.com/r/firewalla/comments/qd3k1j/about_devicemetricsusamazoncom/
https://discourse.pi-hole.net/t/device-metrics-us-amazon-com-requests-like-crazy/5731

[1Hosts (Xtra](https://github.com/badmojr/1Hosts) are also blocking them: https://o0.pages.dev/Xtra/adblock.txt

**Comment by jakecharlie** [comment]
**LG WebOS SmartTV:**
aic.cdpbeacon.lgtvcommon.com
NextDNS ads & trackers and AdAway [github.com/AdAway/adaway.github.io](https://github.com/AdAway/adaway.github.io) lists

aic-ngfts.lge.com
Blocked by notracking: [github.com/notracking/hosts-blocklists](https://github.com/notracking/hosts-blocklists)

**Avast**
I use Avast antivirus on android smartphone. I can assure you that it keeps updating and sending virus data to the avast cloud even with these tracking domains blocked.

**Comment by jakecharlie** [comment]
I, for example, keep all collaboration data to help developers or for marketing and trackers disabled on all devices and software settings and even then there are these telemetry submissions.

It's like whatsapp itself that sends data without user authorization through dit.whatsapp.net and without the possibility of deactivation by the user in the settings, that Adguard already blocks correctly.

**Comment by Alex-302** [comment]
> device-metrics-us-2.amazon.com
device-metrics-us.amazon.com

added.

> api.us-east-1.aiv-delivery.net
> fls-na.amazon.com
> aax-us-east-retail-direct.amazon.com

not sure about them.

> aic.cdpbeacon.lgtvcommon.com

https://gist.github.com/wassname/78eeaaad299dc4cddd04e372f20a9aa7?permalink_comment_id=4371356#gistcomment-4371356

**Comment by jakecharlie** [comment]
@Alex-302 

Hello,

I just took the test and I can confirm to you that the domains device-metrics-us-2.amazon.com / device-metrics-us.amazon.com are still not being blocked.

Today Adguard list https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt is blocking the domain:

||device-metrics-*.amazon.com^

I think that you should block:

||device-metrics-us.amazon.com^
||device-metrics-us-2.amazon.com^

I can confirm as a user who uses NextDNS with multiple lists and who monitors each domain that travels through the network, that Adguard DNS is still not blocking the above domains. I recommend my suggestion  with all due respect.

**Comment by Alex-302** [comment]
Adguard DNS blocks them

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/221479839-344c4ad2-026e-4595-bfe2-b32d08d47c2b.png)


</details>
