### ISSUE TITLE
Adguard DNS Filter blocks the ad rewards of World of Warships Blitz

### ISSUE THREAD

**Issue by umitseyhan75** [AdguardTeam/AdGuardSDNSFilter#1231]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

Adguard for Windows 7.12

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

Adguard DNS Non-filtering - DNS-over-Quic

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Other app

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://play.google.com/store/apps/details?id=net.wargaming.wows.blitz

### Add your comment and screenshots

.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
This is expected behavior and we cannot fix it - unblocking of ads is required.
