### ISSUE TITLE
wirelessautoswitch.com Blocked in Public DNS

### ISSUE THREAD

**Issue by nbetcher** [AdguardTeam/AdGuardSDNSFilter#1234]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

 94.140.14.14, 94.140.15.15

### What DNS filters do you have enabled?

N/A using public DNS

### What browser or app do you use?

Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.wirelessautoswitch.com/

### Add your comment and screenshots

https://www.wirelessautoswitch.com/ is blocked stating it is malware. It is not; it is also used by my company whom has vetted its validity and software's integrity beyond reproach.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Will be fixed.

**Comment by enakr** [comment]
Added to allowlist. Thank you!
