### ISSUE TITLE
app.adjust.com redirector incorrect blocking

### ISSUE THREAD

**Issue by kitadai31** [AdguardTeam/AdGuardSDNSFilter#1235]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard DNS DoH

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.mozilla.org/en-US/firefox/browsers/mobile/android/

### Screenshots

<details>
<summary>Screenshot 1</summary>

![page](https://user-images.githubusercontent.com/90122968/221421029-0d16c8b1-bf24-4cbe-bcd0-15f6d60de56a.png)
</details>

<details>
<summary>Screenshot 2</summary>

![incorrectblock](https://user-images.githubusercontent.com/90122968/221421040-3aa6bc1a-01de-4452-a14d-51dc192fe521.png)
</details>

### Comment

`app.adjust.com` is excepted in exceptions.txt.

https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/db0a2f7507c073477979cf9d16c719d63d529cea/Filters/exceptions.txt#L214-L215

However, this @@ rule is being excluded incorrectly by exclusions.txt.

https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/db0a2f7507c073477979cf9d16c719d63d529cea/Filters/exclusions.txt#L665-L666

As a result, app.adjust.com is blocked by `||adjust.com^`.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It cannot be unblocked. 
Also all popular DNS lists block it.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/8361299/221680846-56179d9b-66fe-45b6-b683-e0f6fd9de030.png)


</details>

But you can try https://adguard-dns.io/ and control filtering process.

**Comment by kitadai31** [comment]
In the past, there have been decisions like #185 #493 .
I think the situation has not changed since then, what do you think?

FYI https://twitter.com/search?q=app.adjust.com&f=live

If your thinking has changed, I'm sorry.

**Comment by hagezi** [comment]
@Alex-302 

All "just" referral doamins:
```
app.adjust.com
app.adjust.net.in
app.adjust.io
app.adjust.world
```

Cheers,
Gerd

**Comment by Alex-302** [comment]
@hagezi I saw requests to Adjust domains when using mobile apps, without opening any links.

**Comment by hagezi** [comment]
@Alex-302 https://help.adjust.com/en/article/tracker-urls#adjust-endpoint

**Comment by Alex-302** [comment]
We get a lot of feedback, but there are almost no complaints about these domains being blocked.

**Comment by hagezi** [comment]
I believe you, it was just a hint that it is "actually" a click tracker, which you can read about in the doc. There are also the parameters documented, of course there is also the possibility to send hardcoded data as parameters. One would have to analyze such calls "without clicks" more closely what exactly is transmitted there and why. I think that it can also be used for in app navigation.

A click tracker can always be "misused" for other things, e.g. tracking app launches.

**Comment by Alex-302** [comment]
> used for in app navigation

Maybe.
