### ISSUE TITLE
incorrect blocking

### ISSUE THREAD

**Issue by syazwanshark** [AdguardTeam/AdGuardSDNSFilter#1250]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS, AdGuard private DNS, AdGuard Home, Other

### What DNS filters do you have enabled?

Ads guard filter

### What browser or app do you use?

Safari

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://istudent.uitm.edu.my/index_isp.htm

### Add your comment and screenshots

![8619BA25-3703-4005-BD5C-05880FF2309A](https://user-images.githubusercontent.com/107603546/224219128-d237408d-1acc-4aed-a40f-577749db68fd.png)
![03771888-2B8D-4B37-BC26-3D0F8CF73457](https://user-images.githubusercontent.com/107603546/224219135-6d2ea907-c462-435d-b1ad-72ded3320d98.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Fixed.
