### ISSUE TITLE
https://t.co/WTAagzKq5U link is safe

### ISSUE THREAD

**Issue by hasantahsinakin** [AdguardTeam/AdGuardSDNSFilter#1251]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

I don't know

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed analytics or tracker

### Where did you encounter the problem?

https://t.co/WTAagzKq5U

### Add your comment and screenshots

Adguard dns block the link: https://t.co/WTAagzKq5U

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Should be fixed. bit.ly was blockd by a mistake.
