### ISSUE TITLE
bit.ly is blocked

### ISSUE THREAD

**Issue by KSR-Yasuda** [AdguardTeam/AdGuardSDNSFilter#1252]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

Family protection servers (`94.140.{14.15,15.16}`) and Default Server '`94.140.{14.14,15.15}`)

### What DNS filters do you have enabled?

AdGuard DNS Filter
Both of Family protection servers (`94.140.{14.15,15.16}`) and Default Server '`94.140.{14.14,15.15}`) behaves the same to block the bit.ly domain.

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://bit.ly/*

### Add your comment and screenshots

It shows AdGuards' access block page for pages in bit.ly domain.

However, bit.ly is just URL shortening services.
The service itself is not malicious.

### Privacy

- [X] I agree to follow this condition

**Comment by KSR-Yasuda** [comment]
Umm, it sometimes go through.

Checking it by `nslookup` command,
some blocks bit.ly (to return `94.140.14.33`), and
the other accepts (to return correct bit.ly IP).

### Google DNS (for Reference)

```
% nslookup bit.ly 8.8.8.8
Non-authoritative answer:
Server:  dns.google
Address:  8.8.8.8

Name:    bit.ly
Addresses:  67.199.248.10
          67.199.248.11
```

Above is real bit.ly IP.

### AdGuard Default Server

```
% nslookup bit.ly 94.140.14.14
Non-authoritative answer:
Server:  dns.adguard.com
Address:  94.140.14.14

Name:    bit.ly
Address:  94.140.14.33
```

```
% nslookup bit.ly 94.140.15.15
Non-authoritative answer:
Server:  dns.adguard.com
Address:  94.140.15.15

Name:    bit.ly
Addresses:  67.199.248.11
          67.199.248.10
```

### AdGuard Family Protection Server

```
% nslookup bit.ly 94.140.14.15
Non-authoritative answer:
Server:  dns-family.adguard.com
Address:  94.140.14.15

Name:    bit.ly
Address:  94.140.14.33
```

```
% nslookup bit.ly 94.140.15.16
Non-authoritative answer:
Server:  dns-family.adguard.com
Address:  94.140.15.16

Name:    bit.ly
Addresses:  67.199.248.11
          67.199.248.10
```

**Comment by ameshkov** [comment]
Thank you for reporting it!

This is a mistake on our side, will be fixed in about 2-3 hours.
