### ISSUE TITLE
Ad guard

### ISSUE THREAD

**Issue by Avijitsarda** [AdguardTeam/AdGuardSDNSFilter#1253]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

![Screenshot_20230310-151603_Chrome](https://user-images.githubusercontent.com/125152956/224283371-a6971c5f-fa21-4ea1-af09-1bc4215c7836.jpg)

### Proposed solution

Please check this problems and bugs 

### Additional information

Any link  not access in my device 😬😔 sir please help

**Comment by Alex-302** [comment]
Please copy text link.

**Comment by Avijitsarda** [comment]
Thank you for your response

**Comment by Avijitsarda** [comment]
Thank you!
