### ISSUE TITLE
counter.dev

### ISSUE THREAD

**Issue by ihucos** [AdguardTeam/AdGuardSDNSFilter#1260]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### What DNS filters do you have enabled?

I don't know

### What browser or app do you use?

Other app

### Which device type do you use?

Other device

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://counter.dev

### Add your comment and screenshots

Hello,

counter.dev is an open source project that can also be found here: https://github.com/ihucos/counter.dev
That it is blocked was found unexpected by different users in hacker news here: https://news.ycombinator.com/item?id=35144256

Can we remove it from the list?

I am the maintainer of counter.dev and happy to help if needed.

Thanks!
![blank](https://user-images.githubusercontent.com/2066372/224865967-da15b7e1-318c-41f8-92d4-d435ae5a0cc5.jpeg)

### Privacy

- [X] I agree to follow this condition

**Comment by physx2494** [comment]
While the work you are doing is excellent, and by no means do I want to demotivate, the website is still, in one way or another, an analytics provider.

**Comment by ihucos** [comment]
Correct, the website is a privacy friendly analytics provider. I thought the expected behaviour of a blocker would be to block activities like tracking - like done by "my" analytics provider. This bug would be about the entire website not displaying on the browser. Is that expected behaviour?

**Comment by physx2494** [comment]
I see. Certainly an unexpected behavior.
________________________________

**Comment by ihucos** [comment]
Yes, absolutely! I will change the tracking script to to request `t.counter.dev` (That subdomain naming makes sense). There are some legacy integrations that used the inline script but they will fade out with time.

I'll let you know when its done.

**Comment by Alex-302** [comment]
Great, thanks)

**Comment by ihucos** [comment]
I had to be careful to not disturb the service. It is done. The tracking script now calls `t.counter.dev` which can be added to the blocklist. `counter.dev` - the website itself - can then be allow-listed.

To verify check:
https://cdn.counter.dev/script.js
https://github.com/ihucos/counter.dev/blob/master/docs/script.js

Thank you very much and let me know if there are any questions.

**Comment by ameshkov** [comment]
@ihucos 

Quick question: the privacy conscious users will be triggered by a third-party script loading on websites so we'll need to block `cdn.counter.dev` as well. Will it be an issue for the website functions?

**Comment by ihucos** [comment]
Hello ameshkov,

thank you very much for asking.

> Will it be an issue for the website functions?

No, that is only used to serve the tracking script, feel free to block it.

**Comment by ihucos** [comment]
Yes, confirm.

**Comment by Alex-302** [comment]
@ihucos Thanks! Fixed in the regular filter and created the pull-request in this repo.
