### ISSUE TITLE
Missing block: f11-ads.com

### ISSUE THREAD

**Issue by Thomas-Schubert** [AdguardTeam/AdGuardSDNSFilter#1261]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Safari

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed ads

### Where did you encounter the problem?

f11-ads.com

### Add your comment and screenshots

I'm manually blocking this domain currently.

### Privacy

- [X] I agree to follow this condition

**Comment by Thomas-Schubert** [comment]
Try https://cdn-de.f11-ads.com/ ...

**Comment by Alex-302** [comment]
@Thomas-Schubert Where is it used?
I found only their descryption https://de.f11-ads.com/privacy.php?lang=0
and tracking request  `https://de.f11-ads.com/adtrack.php?id=` on one site.

**Comment by Thomas-Schubert** [comment]
I don’t know, presumably both.

**Comment by Alex-302** [comment]
Added
