### ISSUE TITLE
AdGuard DNS blocks Xbox Beta App

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#127]
@Chinaski1 commented on [Wed Sep 11 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/3066)

### Issue Details

- **AdGuard version:**
  -  3.2.150
- **Filtering mode:**
  -  Local VPN
- **Device:**
  -  Samsung SM-G955U
- **Operating system and version:**
  -  Android 9
- **Root access:**
  -  No

### Actual Behavior

1) Open Xbox Beta settings
2) Configure dns.adguard.com as Private DNS sever
3) AdGuard DNS seems to block friends functionality in the Xbox Beta
Android App

### Screenshots

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/64707813-43538d00-d4bc-11e9-8c0d-0713a1d86d15.png)

</details>

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/64707836-4b133180-d4bc-11e9-84b1-1d67ad89ed6c.png)

</details>

### Logs in NCloud

---

@scoobygottheboot commented on [Thu Sep 12 2019](https://github.com/AdguardTeam/AdguardForAndroid/issues/3066#issuecomment-530994611)

I'm the submitter for the issue. 

My main filtering method is through private DNS and not via the app. I installed the app specifically for the logs.

**Comment by ameshkov** [comment]
@Alex-302 can you reproduce the issue?

**Comment by ameshkov** [comment]
@scoobygottheboot could you please send the logs to `filters@adguard.com`?

**Comment by scoobygottheboot** [comment]
@ameshkov sent it over just now.

**Comment by ameshkov** [comment]
@scoobygottheboot please try adding `@@||vortex.data.microsoft.com^` to the DNS user filter: DNS filtering -> DNS requests blocking -> DNS user filter

**Comment by Alex-302** [comment]
Cannot reproduce with AdGuard and Cloudflare DNS with/without DNS filtering in AG settings.

**Comment by scoobygottheboot** [comment]
Issue still persists with private dns. I'm going to do further testing to
ensure the issue is not my wifi network

**Comment by Alex-302** [comment]
@scoobygottheboot could you please check with [AdGuard for Android](https://adguard.com/en/adguard-android/overview.html)?
1. Prepare to collect AdGuard log
https://kb.adguard.com/ru/android/solving-problems/log
2. Setup default system default DNS, enable `DNS filtering` in `AdGuard DNS` settings and reproduce this issue;
3. Sent the logs with issue link, time stamp and actual behavior(reproduced/not reproduced) to support@adguard.com 

4. Enable `AdGuard DNS` in DNS settings and disable `DNS filtering`
5. Repeat step 3.
