### ISSUE TITLE
Mistakenly blocked website

### ISSUE THREAD

**Issue by JustTunerYT** [AdguardTeam/AdGuardSDNSFilter#1271]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

dns.adguard.com

### What browser or app do you use?

Opera

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

nnt.ugrasu.ru

### Add your comment and screenshots

Website is being blocked by mistake. This website is supposed to be an official website for organization of a university. All the information me or anyone else, which is a personal information, is being put and is not being used in any criminal action.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Seems legit. @VladisLoveZh could you please take a look?

**Comment by JustTunerYT** [comment]
![Screenshot_2023-03-20-19-05-46-804_com opera gx](https://user-images.githubusercontent.com/63610557/226364585-083023a6-4552-4749-8eb7-92bffccded04.jpg)
This is the current state of the website. I recall problem not solved.

**Comment by JustTunerYT** [comment]
@jellizaveta Can you look again please?

**Comment by VladisLoveZh** [comment]
> > This website was unblocked.
> 
> How do I know if changes were applied and I can visit the website? Because its still blocked for me

It may take up to ~48 hours for the changes to take effect

**Comment by JustTunerYT** [comment]
> > > This website was unblocked.
> 
> @JustTunerYT
> 
> > How do I know if changes were applied and I can visit the website? Because its still blocked for me
> 
> It may take up to ~48 hours for the changes to take effect

OK, thanks
