### ISSUE TITLE
1337x.to

### ISSUE THREAD

**Issue by usermyname12** [AdguardTeam/AdGuardSDNSFilter#1273]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

DOH

### What DNS filters do you have enabled?

dns regular

### What browser or app do you use?

Firefox, Chrome, Safari, Microsoft Edge, Opera, Yandex Browser, Other app

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://1337x.to/

### Add your comment and screenshots

It had weird behavior from yesterday, now it is blocked and shows the adguard message.

### Privacy

- [X] I agree to follow this condition

**Comment by hagezi** [comment]
https://reddit.com/r/Piracy/comments/117fq8t/just_a_quick_heads_up_for_anyone_who_uses_1337xto/
