### ISSUE TITLE
ib.absa.co.za/absa-online/login.jsp

### ISSUE THREAD

**Issue by PavelParkhomenko** [AdguardTeam/AdGuardSDNSFilter#1275]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://ib.absa.co.za/absa-online/login.jsp

### Add your comment and screenshots

There is a problem accessing the banking website when using AdGuard DNS (94.140.14.14 94.140.15.15). It only happens once you login. There is a blocked request to https://dpm.demdex.net/ 
Please check if unblocking is possible.

![Screenshot_1]
![IMG_20230316_082351_2](https://user-images.githubusercontent.com/104919935/226272558-07f6a147-96f2-4513-b2d1-002b09659e88.jpg)

![Screenshot_2](https://user-images.githubusercontent.com/104919935/226272616-24856aaa-2085-4ee4-8a26-7afb7d1d4466.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
We cannot unblock this tracking domain.
Please use adguard-dns.io - it allows to block/unblock anything. In AdGuard for Windows you can also unblock this domain.
