### ISSUE TITLE
New trackers to be blocked

### ISSUE THREAD

**Issue by jakecharlie** [AdguardTeam/AdGuardSDNSFilter#1278]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

-

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

-

### What DNS filters do you have enabled?

Adguard DNS filter

### What browser or app do you use?

Other app

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed analytics or tracker

### Add your comment and screenshots

Hello, please block the trackers below in the Adguard public DNS list: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

**Xiaomi:**
tracking.intl.miui.com
api.ad.xiaomi.com
api.ad.intl.xiaomi.com
diagnosis.ad.xiaomi.com

**OnePlus, Oppo and Realme (BBK Electronics brands)**
sms.ads.heytapmobi.com
data.sms.heytapmobi.com
dragate.dc.oppomobile.com
moa-upload-online.coloros.com
allawnos.com
allawntech.com
heytapdl.com
heytapmobile.com
omes-sec.heytapmobile.com
stat-in.dc.oppomobile.com
httpdns-push.heytapmobile.com
conf-in.dc.heytapmobi.com
conff.dc.oppomobile.com
dragate-in-dc.heytapmobile.com
mdp-appconf-sg.heytapdl.com
adx-in.ads.heytapmobile.com
apsrgeo.amap.com
confe.dc.oppomobile.com
esa-reg-eup.myoppo.com
i6.weather.oppomobile.com

The tracker "i6.weather.oppomobile.com" I do not know what procedure you adopt, because according to the article below, Oppo / Realme sends GPS location data frequently to this server and it is activated by default, there is no way for the user to deactivate it

Some of Xiaomi and Oppo/Realme trackers have been proven by scientific tests: https://arxiv.org/pdf/2302.01890.pdf
There are also brand users alert about these trackers:
https://www.reddit.com/r/ControlD/comments/p8lcmf/please_block_these_oppo_telemetry/
https://forum.xda-developers.com/t/which-app-is-constantly-sending-data-to-allawnos-com-coloros-com-heytapmobile-com.4463103/

**Taobao (chinese):**
accscdn.m.taobao.com
acs.m.taobao.com
adashbc.ut.taobao.com

**Domain tracker from smartadserver.com ads company**
mobileconfig.sascdn.com

**I recomend to block every tracker from "qualtrics.com"**
zn41r1dpknmdeypvr-evernote.siteintercept.qualtrics.com

**Aliexpress tracker:**
us.ynuf.aliapp.org

**I recomend to block every tracker from "online-metrix.net"**
859g1sils525cvjo2vxjyeyhlhu4uqfq5dyskns726e50ef2a7c3fe28sac.d.aa.online-metrix.net

**Didi Global (chinese) tracker:**
cnt.didiglobal.com

**Yahoo ads tracker tracker**
service.cmp.oath.com

Remembering that my intention is just to help. Thank you, Adguard team.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Xiaomi trackers ar already blocked.

**Comment by Alex-302** [comment]
Blocked some trackers.

**Comment by jakecharlie** [comment]
Hey @tomac4t  I think in that case could you do a favor? Create a free nextdns account and add DoT on your Oneplus smartphone. There by nextdns you can do the real monitoring of all the requests and with that find out which domains with the end heytapmobi.com are important and what are trackers. Because I saw many reports on the internet of users sayinf about trackers with this domain on Realme and Oppo phones (which is from the same manufacturer as yours).

I did this with my Xiaomi, so I can accurately report the Xiaomi tracking domains. So it would be great if you could do it with BBK electronics cell phones as well.

**Comment by jakecharlie** [comment]
Please also access the scientific article I cited above and compare domain by domain. Because they confirm the trackers, but they do not mention which domain are essential and which are not, so only with a BBK smartphone in hands to test it.

https://arxiv.org/pdf/2302.01890.pdf

**Comment by jakecharlie** [comment]
The article says about sms.ads.heytapmobi.com, 
data.sms.heytapmobi.com, i6.weather.oppomobile.com, dragate.dc.oppomobile.com and moa-upload-online.coloros.com

Apparently the problem is in the total blocking of the domain heytapmobi.com e you found usage problems if the domain sms.ads.heytapmobi.com were blocked.

Please only block data.sms.heytapmobi.com, i6.weather.oppomobile.com, dragate.dc.oppomobile.com and moa-upload-online.coloros.com to know if something will break in your smartphone. 

Today the block is in:
heytapmobi.com^
apsrgeo.amap.com^
||confe.dc.oppomobile.com^
||conff.dc.oppomobile.com^
||dragate.dc.oppomobile.com^
||esa-reg-eup.myoppo.com^
||heytapmobile.com^
||moa-upload-online.coloros.com^
||stat-in.dc.oppomobile.com^

Now the goal is to separate the essentials from the non-essential and probably tracker
