### ISSUE TITLE
Do not block heytapmobi.com entire domain directly

### ISSUE THREAD

**Issue by Hill-98** [AdguardTeam/AdGuardSDNSFilter#1281]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

v0.107.26

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

127.0.0.1:8853
[/in-addr.arpa/ip6.arpa/lan/]127.0.0.1:5353

### What DNS filters do you have enabled?

AdGuard DNS filter
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

StevenBlack
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts

CHN: AdRules DNS List
https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt
 
 

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

OPPO App Strore

### Add your comment and screenshots

Do not directly block the whole domain of heytapmobi.com, this will cause severe damage to OPPO's services.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1278#issuecomment-1484776438
