### ISSUE TITLE
www.multitran.com

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardSDNSFilter#1282]
@adguard-bot commented on [Tue Mar 28 2023](https://github.com/AdguardTeam/AdguardFilters/issues/146767)

### Issue URL (Ads)
 [https://www.multitran.com/m.exe?ll1=1&ll2=2&s=deflection&l2=2](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.multitran.com%2Fm.exe%3Fll1%3D1%26ll2%3D2%26s%3Ddeflection%26l2%3D2)
### Comment
> Проблема касается всего сайта multitran.ru

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/a1Gd8JA.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.12
Browser: | Yandex
AdGuard driver: | TDI
Stealth mode: | disabled
DNS filtering: | server: `https://dns.adguard-dns.com/dns-query`<br>filters: `https://filters.adtidy.org/windows/filters/15.txt, User+rules`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/assistant/4.3/assistant.user.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js
Referrer: | [https://www.multitran.com/m.exe?a=3&l1=1&l2=2&s=fault+check](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.multitran.com%2Fm.exe%3Fa%3D3%26l1%3D1%26l2%3D2%26s%3Dfault%2Bcheck)

---

@sattera1 commented on [Tue Mar 28 2023](https://github.com/AdguardTeam/AdguardFilters/issues/146767#issuecomment-1486984013)

![image](https://user-images.githubusercontent.com/77280614/228268798-32da7ba1-fea4-46f8-b197-0e247d3d7e45.png)
![image](https://user-images.githubusercontent.com/77280614/228272776-7e9d5b8a-3ba5-4182-adb5-5cd0a3199d35.png)

I don't know what has been corrected but the website isn't working properly anymore (I'm not sure how to explain it correctly - the grey background disappears which is a bit hard for eyes as well as other minor changes such as grey lines separating nouns from verbs, verbs from phrases, etc.). After switching off Adguard the site returns to a normal operation but with ads.

---

@zloyden commented on [Tue Mar 28 2023](https://github.com/AdguardTeam/AdguardFilters/issues/146767#issuecomment-1487021227)

The site displays correctly on my end. Could you only leave protection, but disable DNS, stealth mode and filters? Then restart the browser and open the site.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33488229/228273833-5e53eb53-e89c-46b9-a8e2-dfbcd4785792.png)

</details><br/>

---

@sattera1 commented on [Tue Mar 28 2023](https://github.com/AdguardTeam/AdguardFilters/issues/146767#issuecomment-1487057804)

After disabling only DNS (stealth mode had already been inactive) and leaving filters as is the website displays normal again.
![image](https://user-images.githubusercontent.com/77280614/228281254-388cf254-f346-4125-b2e3-f1afdb9e6005.png)

---

@zloyden commented on [Wed Mar 29 2023](https://github.com/AdguardTeam/AdguardFilters/issues/146767#issuecomment-1488009584)

Strange. I have [the same](https://github.com/AdguardTeam/AdguardFilters/issues/146767#issuecomment-1487021227) with our DNS - I mean there is no incorrect blocking on my end.

**Comment by jellizaveta** [comment]
@sattera hello! Сan't reproduce the issue with AdGuard DNS enabled. Do you have user rules in DNS filter?

**Comment by sattera1** [comment]
So, I tried many options and this is what I've found out:

1. Before creating the issue ticket I had ads on www.multitran.ru with Adguard running. I tried to block them pointing at certain areas of a web page containing the ads and using a right mouse button menu -> Adguard Browser Helper -> Block ads on this website, thus creating User's rules. However, it didn't help. The ads were still there. Today I deleted these user's rules and the problem with an incorrect display of the the website has gone. DNS is enabled. Solved!

2. The only way to remove the ads on www.multitran.ru is Settings - Network - Enable traffic filtering. But after that I start experiencing a new problem: a delay of 7-10 seconds between clicking on Enter button and the sites (any website) starting loading. During this gap the loading circle on the browser tab is rolling counter-clockwise and nothing is happening. So, web browsing is not a comfortable thing anymore. You have to wait for 7-10 seconds before any website start opening. 

Tested on 2 PCs with the same Adguard settings
Win7 x64 / Win11 x64

**Comment by jellizaveta** [comment]
@sattera1 Do you have antivirus installed?

**Comment by sattera1** [comment]
No, I do not

**Comment by jellizaveta** [comment]
What do you mean by: `Enable traffic filtering`

**Comment by jellizaveta** [comment]
Could be a compatibility issue. 
@Aydinv13 Could you please take a look: https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1282#issuecomment-1488344156 ?

**Comment by sattera1** [comment]
> What do you mean by: `Enable traffic filtering`

I mean this option in Settings
![image](https://user-images.githubusercontent.com/77280614/228526460-0b5d4170-3221-4103-8781-11180a05dd8c.png)

**Comment by sattera1** [comment]
Without this option enabled the ads on multitran.ru stay unblocked.

**Comment by Aydinv13** [comment]
@sattera1 Hi there!

Without the _Enable Traffic filtering_ option the ads will be everywhere. It should be turned on permanently.
>But after that I start experiencing a new problem: a delay of 7-10 seconds between clicking on the Enter button and the sites (any website) starting loading.

I wasn't able to reproduce the problem. Could you please try to reset your settings and check again? `Settings - General Settings -> Reset settings to defaults`

**Comment by sattera1** [comment]
Thanks for this promt! Reset to defaults really helped. I didn't go through a 4-step setting procedure after the reset. Now the websites response is faster (response is about 1-2 seconds longer than with Adguard disabled) and there are no ads. A delay of 7-10 seconds re-occurs if in Settings the DNS is switched from my provider's DNS **to Adguard DNS**. This is where the problem turned out to be with big delays in response. I'll keep watching. Thanks for your assistance.
