### ISSUE TITLE
Parental controls block a lot of incorrect domains

### ISSUE THREAD

**Issue by Hill-98** [AdguardTeam/AdGuardSDNSFilter#1285]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

v0.107.26

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

127.0.0.1:8853
[/in-addr.arpa/ip6.arpa/lan/]127.0.0.1:5353

### What DNS filters do you have enabled?

AdGuard DNS filter
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

StevenBlack
https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn/hosts

CHN: AdRules DNS List
https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt
 
 
 

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

BiliBili App

### Add your comment and screenshots

I enabled parental controls in AdGuard Home, but I found that many domains were incorrectly blocked.

Including a lot of qq.com gdtimg.com sogou.com qlogo.cn bilibili.com subdomains, these domains are required domains for QQ and bilibili, since they are Chinese apps, it is impossible for them to contain any inappropriate content.

So these domains can't be blocked by parental controls, they will of course have some tracking domains, but that's not part of parental controls.

### Privacy

- [X] I agree to follow this condition

**Comment by Hill-98** [comment]
The domains I have pointed out are just some of the ones that were wrongly blocked, there may be other domains that are wrongly blocked.

I don't understand what makes AdGuard block these domains?

**Comment by vinafisyahla** [comment]
Saya sudah dewasa
