### ISSUE TITLE
錯誤封鎖 Oa.tr.line.me

### ISSUE THREAD

**Issue by chiuyangcheng** [AdguardTeam/AdGuardSDNSFilter#1286]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

家庭防護过濾器。

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

Oa.tr.line.me

### Add your comment and screenshots

网站 Oa.tr.line.me 被錯誤的標記为色情网址，其实只是通訊应用LINE的頁面，封鎖後会導致部分LINE頁面无法開启。

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It was fixed.
