### ISSUE TITLE
incorrect blocking http://jjloheac.online.fr/consoEDF.html

### ISSUE THREAD

**Issue by jjloheac** [AdguardTeam/AdGuardSDNSFilter#1289]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### Version

router dns

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

dns into the router

### What DNS filters do you have enabled?

dns into the router adress

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

http://jjloheac.online.fr/consoEDF.html

### Add your comment and screenshots

sdfqsdf

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Works on my end.

**Comment by jjloheac** [comment]
Thank's
JJacques Loheac
06.08.87.01.76
