### ISSUE TITLE
Please block mqtt-mini.facebook.com track domain

### ISSUE THREAD

**Issue by jakecharlie** [AdguardTeam/AdGuardSDNSFilter#1294]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

-

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

-

### What DNS filters do you have enabled?

Adguard public DNS

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed analytics or tracker

### Add your comment and screenshots

Hello, I found that the MIUI of Xiaomi smartphones make constant requests to the Facebook domain "**mqtt-mini.facebook.com**" for tracking.

In the last 30 days, after monitoring with NextDNS, I noticed that more than 3000 requests were made for that specific domain.

More than 100 requests are made daily.

I tested it on three smartphones to see if it was from a Meta app (like Facebook, Facebook Lite, Instagram, Instagram Lite, Facebook Messenger, Facebook Messenger Lite and Whatsapp) or if it would even crash some of Meta applications.

Two smartphones were Xiaomi. One of them I reset to just factory apps. The third was from Motorola.

"A" is Xiaomi with all Meta apps installed and logged in.

"B" is Xiaomi only with the factory applications, that is, there is no factory installed Meta application, only from Google and Xiaomi.

"C" is Motorola with all Meta apps installed and logged in.

All three smartphones had different DNS from NextDNS to block the domain "**mqtt-mini.facebook.com**"

Only smartphones A and B were blocked from these domains, which did not change the use of any of Meta's applications. That is, the Motorola smartphone never connected to this domain, despite having all the above applications installed and logged in.

After searching the internet, I verified that it is indeed a Facebook tracker: https://confection.io/trackers/mqtt-mini-facebook-com/

There are reports about this domain:
https://twitter.com/Noztox/status/1558069694023622656

https://twitter.com/thefossguy/status/1476090554010468352

https://www.reddit.com/r/blokada/comments/oi0xmi/comment/h4tgvrm/?utm_source=share&utm_medium=web2x&context=3

In the latest link, the user also has Xiaomi's MIUI and has verified that the tracking is theirs.

There is probably an information sharing agreement between Xiaomi and Meta for this tracking to happen.

Therefore, please block this domain **mqtt-mini.facebook.com**, as it is tracking and monitoring and does not affect Meta applications and Xiaomi smartphones.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
This is not [only] a tracking domain. FB app will be broken.

**Comment by ameshkov** [comment]
@jakecharlie this domain is used for Facebook Messenger functionality.

It does indeed uses the [MQ Telemetry Transport](https://en.wikipedia.org/wiki/MQTT) hence the confusion.

However, it uses it not for telemetry, but for passing messages. More information [here](https://www.facebook.com/notes/10158791547142200/).

> One  of the problems we experienced was long latency when sending a message.  The method we were using to send was reliable but slow, and there were  limitations on how much we could improve it. With just a few weeks until  launch, we ended up building a new mechanism that maintains a  persistent connection to our servers. To do this without killing  battery life, we used a protocol called MQTT  that we had experimented with in Beluga. MQTT is specifically designed  for applications like sending telemetry data to and from space probes,  so it is designed to use bandwidth and batteries sparingly. By maintaining  an MQTT connection and routing messages through our chat pipeline, we  were able to often achieve phone-to-phone delivery in the hundreds of  milliseconds, rather than multiple seconds.

**Comment by ameshkov** [comment]
@jakecharlie this is an interesting question.

The problem is that what you're seeing is a DNS query, not an actual connection, and it's hard to say why it's there without inspecting what's inside (which requires rooting the device).

The domain might be used by the Facebook SDK which is used by tons of different apps. If you had AdGuard for Android or a similar app installed, we could at least figure out what app connects to that domain.

**Comment by ameshkov** [comment]
@jakecharlie hmm, to be honest, this is a difficult question. Most of firewall apps will only show you IP addresses, most of content blockers apps just filter DNS traffic so they can't be used to figure out which app is doing that.

I think [NetGuard](https://play.google.com/store/apps/details?id=eu.faircode.netguard) should be capable of doing it properly, but part of its functionality is paid so not sure if the free one will be enough.

**Comment by ameshkov** [comment]
It still bothers me a bit that Facebook itself states that the domain is not a tracking domain.

@Alex-302 we'll probably need to check what actual payload is sent over the connection (rooted device + fiddler or https filtering) just to make sure that we're not blocking something functional.

**Comment by Alex-302** [comment]
In my large logs I see only one DNS record - `edge-mqtt.facebook.com` Searched for `mqtt`.
Since this request is very rare, I will assume that it is not related to tracking or analytics.
