### ISSUE TITLE
Incorrect block derzaj.biz

### ISSUE THREAD

**Issue by iNovenkij** [AdguardTeam/AdGuardSDNSFilter#1296]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS, AdGuard Home

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

http://derzaj.biz

### What DNS filters do you have enabled?

public-dns, https://adguard-dns.io/en/public-dns.html

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

http://derzaj.biz

### Add your comment and screenshots

1. This is my site. There isn't viruses! It doesn't even have ads!
1.5. Only adguard is blocking my site.
2. ![Screenshot_2](https://user-images.githubusercontent.com/42391424/231816446-f29c883a-2d1e-4b1e-b499-c737e2be99fb.png)
3. ![Screenshot_3](https://user-images.githubusercontent.com/42391424/231816986-7eeaab4f-58af-4931-895a-f5c8393f4752.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Will be fixed asap.
