### ISSUE TITLE
Do not block sp1.baidu.com

### ISSUE THREAD

**Issue by Franinc** [AdguardTeam/AdGuardSDNSFilter#1300]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### What DNS filters do you have enabled?

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.baidu.com/s?wd=hello

### Add your comment and screenshots

`sp1.baidu.com` is currently used to provide TTS in Baidu's translation service.

And I saw `sp2.baidu.com` and `sp3.baidu.com` also on the filtered list.
Maybe we should stop blocking these three URLs just in case?

![Snipaste_2023-04-19_06-30-15](https://user-images.githubusercontent.com/26399054/232919225-ea4b7969-f6e7-43c6-a722-dae531c93df9.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Fixed for ad blockers, but we can't remove the rule, which blocks tracking. 
But you can use our free private DNS https://adguard-dns.io/ and unblock this or another domain (or block).
