### ISSUE TITLE
auto refresh on statistics page

### ISSUE THREAD

**Issue by stephentalla** [AdguardTeam/AdGuardSDNSFilter#1309]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Perhaps, it is more appealing to have the statistics page refresh automatically.

### Proposed solution

Auto refresh

**Comment by Alex-302** [comment]
Hi.
Which statistics page exactly?
