### ISSUE TITLE
tracker.files.fm

### ISSUE THREAD

**Issue by szyha** [AdguardTeam/AdGuardSDNSFilter#1310]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [x] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### Version

NextDNS

### What DNS filters do you have enabled?

HaGeZi - Multi NORMAL
AdGuard DNS filter

### What browser or app do you use?

Other app

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

BitTorrent clients

### Add your comment and screenshots

It is a well-known BitTorrent tracker. According to https://newtrackon.com/ it has been running for almost 4 years.

### Privacy

- [X] I agree to follow this condition

**Comment by hagezi** [comment]
@Alex-302 Thanks, not on my lists. The domain is on my allowlist for torrent tracker,
