### ISSUE TITLE
Give option to visit untrusted site

### ISSUE THREAD

**Issue by j-refs** [AdguardTeam/AdGuardSDNSFilter#1311]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

It is unacceptable to prevent access totally from untrusted sites. Even Google, freaking Google, allows an option to visit untrusted sites. I have to disable Adguard DNS to visit I site I know I trust. If this happens again somewhere else, I'm gonna have to move away from Adguard. 

### Proposed solution

Provide option to visit untrusted site. 

### Additional information

Even Google does this. No excuses

**Comment by Alex-302** [comment]
This is impossible when using DNS.
