### ISSUE TITLE
Zararsız sitelere zararlı diyir

### ISSUE THREAD

**Issue by omurll57** [AdguardTeam/AdGuardSDNSFilter#1312]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home, Other

### What DNS filters do you have enabled?

Eski

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

csduragi.com

### Add your comment and screenshots

Çok kötü bir uygulama adguard hiç beğenmedim

https://user-images.githubusercontent.com/118687072/234522428-8dbbc53b-173f-4a3c-b869-c1ec8ecc2680.mp4

![20230426_102832](https://user-images.githubusercontent.com/118687072/234522506-d641b4ce-e35a-4000-b2a7-9fa93eb3809d.jpg)
``
/

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reproduced at the moment.
Better write to support@adguard.com next time.
