### ISSUE TITLE
BBW.com (Bath and Body Works) incorrectly blocked by parental filter

### ISSUE THREAD

**Issue by spetryjohnson** [AdguardTeam/AdGuardSDNSFilter#1314]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

AdGuard Home Version:  v0.107.29

### What DNS filters do you have enabled?

Parental controls

### What browser or app do you use?

Chrome, Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

www.bbw.com

### Add your comment and screenshots

BBW.com is the website for Bath and Body Works. It is incorrectly blocked by the parental filter.

(It redirects to bathandbodyworks.com)

![image](https://user-images.githubusercontent.com/275393/234986374-102e10b2-d98f-4d9d-b795-5e4c84afb07e.png)
![image](https://user-images.githubusercontent.com/275393/234986301-5a88ddff-c151-45ea-b2b9-5bb02d8b1d3d.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Eugene-Savenko** [comment]
Hi there! The website has been removed from the blocklist. Thanks for letting us know!
