### ISSUE TITLE
Incorrect blocking for my website

### ISSUE THREAD

**Issue by hotdogun** [AdguardTeam/AdGuardSDNSFilter#1315]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

94.140.15.15

### What DNS filters do you have enabled?

94.140.15.15

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

http://re-do.ddns.net/

### Add your comment and screenshots

this is my private wiki website for my friend

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It should be working properly now.
