### ISSUE TITLE
AdGuard blocked my private server

### ISSUE THREAD

**Issue by Andrei-Iosifescu123** [AdguardTeam/AdGuardSDNSFilter#1316]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

dns.adguard.com

### What DNS filters do you have enabled?

dns.adguard.com

### What browser or app do you use?

Firefox, Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://magura.ddns.net

### Add your comment and screenshots

1. This is my private server, which is set up using noip DDNS. It leads to the router admin page when accessed on port 443. When accesing the ip directly, AdGuard does not block it.
2. 
![Screenshot_20230429_135151_org mozilla firefox](https://user-images.githubusercontent.com/35394195/235298936-8d039020-e125-4007-9818-42281dbae2fc.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by Valera5560** [comment]
https://arielsystem.pro/ru/sign-in no block the web saite

**Comment by Alex-302** [comment]
It should be working properly now.
