### ISSUE TITLE
Private Nextcloud server blocked

### ISSUE THREAD

**Issue by vikmaks1** [AdguardTeam/AdGuardSDNSFilter#1317]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

94.140.14.14

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

chesters.ddns.net

### Add your comment and screenshots

I`m using AdGuard DNS on my router and it blocks accessing a private Nextcloud server via browsers or app.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It should be working properly now.
