### ISSUE TITLE
Adguard blocked my private Adguard home server

### ISSUE THREAD

**Issue by wanam** [AdguardTeam/AdGuardSDNSFilter#1318]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

Adguard Home v0.107.29

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

1.1.1.1

### What DNS filters do you have enabled?

- https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
- https://adaway.org/hosts.txt

### What browser or app do you use?

Firefox, Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

wanam.ddns.net

### Add your comment and screenshots

Adguard filters (Security and Parental control) block my private server "wanam.ddns.net".
Disabling both filters fixes the issue.
![adguard-blocking](https://user-images.githubusercontent.com/739291/235304425-5b8ee242-e098-45d1-981c-ab9045f64e2d.png)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It should be working properly now.
