### ISSUE TITLE
Add Roku Logging Domains (logs.roku.com)

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardSDNSFilter#132]
Roku devices phone home way too frequently for logging. Blocking these domains do not affect functionality and are already in various popular blocklists.

Could they be added to the default SDNS filter so everyone can enjoy their privacy for both AdGuard Home and AdGuard DNS users?

`||logs.roku.com^`

or if specific domains are required:

```
logs.roku.com
mobile.logs.roku.com
austin.logs.roku.com
giga.logs.roku.com
liberty.logs.roku.com
tyler.logs.roku.com
cooper.logs.roku.com
scribe.logs.roku.com
```

**Comment by Alex-302** [comment]
@planet0 Hi. Do you have this device? Are ads loaded on not/blocked?

**Comment by planet0** [comment]
Hi @Alex-302, yes, we have three on the network.
At the moment the Roku ads are blocked via your rules for Google Ads, however none of the logging domains are blocked and the devices send analytics/tracking logs back to Roku every 30 seconds. This is more for privacy than visual ads. Does the SDNS filter account for privacy rules?

**Comment by Alex-302** [comment]
Ok, I will add `||logs.roku.com^`

**Comment by planet0** [comment]
Thanks @Alex-302 👍

**Comment by Alex-302** [comment]
Done.

**Comment by Alex-302** [comment]
Better report to https://github.com/AdguardTeam/AdguardFilters/ Ad and tracking servers rules are added to SDNSFilter from AdguardFilters files.

**Comment by planet0** [comment]
That's actually good to know, wasn't sure if SDNSFilter request would be accepted there. Will do from now on.

**Comment by Alex-302** [comment]
If the rule loaded from EasyPrivacy, and break something, we fixing it in this repository.
