### ISSUE TITLE
Missed ad/analytics domains for Oppo and Realme

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardSDNSFilter#1320]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### Version

NA

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

DoH

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Safari

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed analytics or tracker

### Where did you encounter the problem?

AdGuard DNS query logs

### Add your comment and screenshots

A few of my devices were producing some known ad/trackers from mobile devices Realme and Oppo.

- bdapi-ads.realmemobile.com
- adsfs.oppomobile.com
- ck.ads.oppomobile.com
- data.ads.oppomobile.com

Blocking these did not seem to have a negative effect on my devices, but as they appear in many other mainstream DNS filter lists, I figured there's a higher possibility they don't break things.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
https://d3ward.github.io/toolz/adblock.html is not a reason to block domains. Without content, loaded/send to that domain, I can't block them.

**Comment by jslawler** [comment]
I agree with what you said, but I'm not sure of the relation of these domains on that website to this issue?

**Comment by Alex-302** [comment]
Do you have an Oppo device?

**Comment by jslawler** [comment]
Yes, an Oppo A53, running ColorOS 13.

**Comment by Alex-302** [comment]
rooted?

**Comment by jslawler** [comment]
No, from what I've read in the past the A53 model has issues with unlocking the bootloader.

If needed, I can look into unlocking it again.

**Comment by Alex-302** [comment]
Ok, added 
```
||bdapi-ads.realmemobile.com^
||adsfs.oppomobile.com^
||ads.oppomobile.com^
```
