### ISSUE TITLE
cf-ipfs.com is blocked

### ISSUE THREAD

**Issue by inflation** [AdguardTeam/AdGuardSDNSFilter#1321]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

AdGuard non-filtered DNS using QUIC

### What DNS filters do you have enabled?

AdGuard DNS Filter

### What browser or app do you use?

Chrome, Safari

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

cf-ipfs.com

### Add your comment and screenshots

cf-ipfs.com is a public gateway to the IPFS network. Its self is not responsible for any phishing or malware. Blocking the whole domain prevents legitimate usage.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Will be unblocked.
