### ISSUE TITLE
adblock is blocking almost everything with stupid Parental control even though Parental control is disabled.

### ISSUE THREAD

**Issue by cybernetics** [AdguardTeam/AdGuardSDNSFilter#1322]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

AdGuard 2.10.0.1272 for macOS Ventura 13.3.1

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

AdGuard DNS Family Protection (DNS-over-QUIC)

### What DNS filters do you have enabled?

AdGuard DNS Filter

### What browser or app do you use?

Firefox, Chrome, Safari, Microsoft Edge, Opera, Yandex Browser, Other app

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

links getting blocked frequently. for ex, telegram short links and other link redirectors.

### Add your comment and screenshots

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/79887/235405276-4e0ff4c8-0b1e-40d2-b536-666c60315d09.png">

### Privacy

- [X] I agree to follow this condition

**Comment by Eugene-Savenko** [comment]
That has been fixed. Please allow up to 2 hours for the DNS servers to update the lists. Sorry for the inconvenience.
