### ISSUE TITLE
Lots of safe sites getting blocked erroneously by AdGuard parental control web service

### ISSUE THREAD

**Issue by stewartsoda** [AdguardTeam/AdGuardSDNSFilter#1323]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

AdGuard Home v0.107.29

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://dns10.quad9.net/dns-query
tls://dns.quad9.net

### What DNS filters do you have enabled?

AdGuard DNS filter
https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt

AdAway Default Blocklist
https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt

### What browser or app do you use?

Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

http://www.adp.com/

### Add your comment and screenshots

I'm getting a lot of websites erroneously blocked by parental controls even though the sites are innocuous and contain no adult content.
For example:

- www.adp.com
- intuit.com
- venus.com
- many others - my log is full of "Blocked adult websites"

If I disable the parental control service (either on a per-client or a global basis) then the websites aren't blocked.

![image](https://user-images.githubusercontent.com/944568/235462839-35b0cd55-1126-44eb-b7a8-01180ed0525b.png)

![image](https://user-images.githubusercontent.com/944568/235463320-a01cf844-1103-42bf-9333-994417d7c439.png)

### Privacy

- [X] I agree to follow this condition

**Comment by stewartsoda** [comment]
It appears to happen when using https://family.adguard-dns.com/dns-query as the DNS resolver, too, regardless of AdGuard Home parental filter settings.

**Comment by Eugene-Savenko** [comment]
It looks like some of the websites have already been removed from the list:

`adp.com` - not blocked
`intuit.com `- not blocked

`venus.com` - removed this one from the blocklist.

We're looking into the issue and will revert the changes (remove the batch of sites containing such a high rate of false positives) as soon as we can.
