### ISSUE TITLE
ADP / QuickBooks Online Blocked

### ISSUE THREAD

**Issue by abdalians** [AdguardTeam/AdGuardSDNSFilter#1324]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

Adguard Home v0.107.29

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

                1.1.1.1;
                8.8.8.8;

### What DNS filters do you have enabled?

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/9934227/235502810-140d21c2-3f10-4854-8587-ea3f1e21e7c9.png">

### What browser or app do you use?

Firefox, Chrome, Safari

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://teampay.adp.com https://quickbook.intuit.com

### Add your comment and screenshots

Both of these websites were working before the weekend and are now being blocked by AdGuard Home. 
Had to put in whitelist rules to allow these websites to work. 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. Can't reproduce. In the query log you can see which filter blocks them.

**Comment by hagezi** [comment]
`quickbook.intuit.com` does not exist (NXDOMAIN)

`quickbooks.intuit.com` or CNAME 'mktg.intuit.com.edgekey.net'  is not blocked in any known block list
`teampay.adp.com` is not blocked in any known block list
