### ISSUE TITLE
Improper blocking of veterinary university sites (started today)

### ISSUE THREAD

**Issue by Githubhorseshorseshorsess** [AdguardTeam/AdGuardSDNSFilter#1325]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

94.140.14.15

### What DNS filters do you have enabled?

94.140.14.15 Adguard DNS - Family server

### What browser or app do you use?

Firefox, Chrome, Safari

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Add your comment and screenshots

Two veterinary university websites stopped working recently (sometime between last week and today). Both are professional school websites with no inappropriate content. The must have been added to AdGuard's DNS block list by bug or error. it is also strange because when the AdBlock page comes up warning about the sites, and I click "More Information," AdGuard's website says "This website is safe." So perhaps there is some disconnect between AdGuard's true blacklist and the DNS blacklist?
<img width="979" alt="Screenshot 2023-05-01 at 10 04 42 PM" src="https://user-images.githubusercontent.com/132318132/235564267-9a0ca602-8bca-4708-a612-5e77f0725e21.png">
<img width="836" alt="Screenshot 2023-05-01 at 10 04 50 PM" src="https://user-images.githubusercontent.com/132318132/235564271-c69ab3f7-88b2-4ba1-b3f4-b9b64f70dd5d.png">

(The same issue occurred for both vet.cornell.edu and cvm.msu.edu, the websites for Cornell University's veterinary school and Michigan State University's veterinary school, respectively. I am submitting help requests for both. Thank you so much for your help!!!)

### Privacy

- [X] I agree to follow this condition

**Comment by Githubhorseshorseshorsess** [comment]
I should add that when accessing these sites from another network (which does not use the AdGuard DNS service, the websites work perfectly fine). Thanks!

**Comment by Eugene-Savenko** [comment]
@Githubhorseshorseshorsess I was unable to replicate the issue - the website is not blocked by our Parental Control filters and Family Protection DNS. Could you please check again in ~2 hours?
