### ISSUE TITLE
Improper blocking of Michigan State University veterinary school website

### ISSUE THREAD

**Issue by Githubhorseshorseshorsess** [AdguardTeam/AdGuardSDNSFilter#1326]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

94.140.14.15 Family DNS Server

### What DNS filters do you have enabled?

94.140.14.15 Family DNS Server

### What browser or app do you use?

Firefox, Chrome, Safari

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://cvm.msu.edu/

### Add your comment and screenshots

As described in companion entry for the same problem with Cornell University's veterinary school website being blocked, the Michigan State University College of Veterinary Medicine is currently blocked by the AdGuard public family DNS filter. This started very recently, in the last week. It is also strange because when I click "more information" from the AdGuard block screen, it says that the cvm.msu.edu website is safe. So maybe it is just a new bug in the public DNS server blacklist, since it appears inconsistent with AdGuard's reporting on the site? 

Screenshots attached. 

<img width="850" alt="Screenshot 2023-05-01 at 10 04 28 PM" src="https://user-images.githubusercontent.com/132318132/235564707-149aee3d-66e2-4d00-81d6-2e369caa91d2.png">
<img width="983" alt="Screenshot 2023-05-01 at 10 04 36 PM" src="https://user-images.githubusercontent.com/132318132/235564709-670b8292-909a-4bb2-830c-c67e1d9b1f55.png">

### Privacy

- [X] I agree to follow this condition

**Comment by Githubhorseshorseshorsess** [comment]
I should add that when accessing these sites from another network (which does not use the AdGuard DNS service, the websites work perfectly fine). Thanks!

**Comment by Eugene-Savenko** [comment]
This one is not blocked either... It could be that it's been added to the allowlist some time ago, but servers have not received the update yet, which usually takes around 2 hours. Please, check again in a couple of hours.
