### ISSUE TITLE
Zoho analytics 

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardSDNSFilter#1327]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

v0.107.29

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://security.cloudflare-dns.com/dns-query
https://dns.quad9.net/dns-query

### What DNS filters do you have enabled?

https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
https://big.oisd.nl/

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed analytics or tracker

### Where did you encounter the problem?

https://www.zoho.com/accounts/oneauth.html

### Add your comment and screenshots

Zoho One auth app calls to `apptics.zoho.com` which appears to be a mobile analytics service

Some of the URL's logged in Lulu when running the app on macOS.

```
https://apptics.zoho.com/api/janalytic/v3/remoteconfig/getapi?mode=1&identifier=com.zoho.iamlogin&os=macos
https://apptics.zoho.com/api/janalytic/v3/regdevice?mode=1&identifier=com.zoho.iamlogin
https://apptics.zoho.com/api/janalytic/v3/addscreens?mode=1&identifier=com.zoho.iamlogin&
https://apptics.zoho.com/api/janalytic/v3/addsessions?mode=1&identifier=com.zoho.iamlogin&
https://apptics.zoho.com/api/janalytic/v3/addevents?mode=1&identifier=com.zoho.iamlogin&
```

More info on the service

```
https://www.zoho.com/apptics/
```

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@emlimap Hi. Need steps to reproduce.

**Comment by Alex-302** [comment]
@emlimap Where can I download it?

**Comment by emlimap** [comment]
@Alex-302 
Android: https://play.google.com/store/apps/details?id=com.zoho.accounts.oneauth
mac/ios: https://apps.apple.com/app/apple-store/id1142928979
windows: https://apps.microsoft.com/store/detail/authenticator-app-oneauth/9NPG98QLH8JN?hl=en-gb
