### ISSUE TITLE
New trackers to be blocked

### ISSUE THREAD

**Issue by jakecharlie** [AdguardTeam/AdGuardSDNSFilter#1328]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

-

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

-

### What DNS filters do you have enabled?

Adguard dns public filter

### What browser or app do you use?

Opera

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed analytics or tracker

### Add your comment and screenshots

Please block these trackers:

From brazil:
tracker.bt.uol.com.br
 matt.mercadolivre.com.br

consent.cookiefirst.com
 choices.consentframework.com
logsene-receiver.eu.sematext.com
 widgets.outbrain.com
dorangesource.alicdn.com
abtest.alibaba.com

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
> consent.cookiefirst.com
> abtest.alibaba.com
> choices.consentframework.com
> logsene-receiver.eu.sematext.com

not trackers.

> widgets.outbrain.com
> matt.mercadolivre.com.br

questionable.

> tracker.bt.uol.com.br

exists. Moved to a correct file.

> dorangesource.alicdn.com

added
