### ISSUE TITLE
Incorrect blocking for my website

### ISSUE THREAD

**Issue by BiazPrasastha** [AdguardTeam/AdGuardSDNSFilter#1333]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [x] You're using an up-to-date version of AdGuard DNS filter;
- [x] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS, AdGuard private DNS

### What DNS filters do you have enabled?

Adguard DNS filter

### What browser or app do you use?

Firefox, Chrome, Microsoft Edge

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://bsy-go.suryayudha-wsb.id/

### Add your comment and screenshots

1. This is my website that i maintenance
2. 
![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/49233008/50946d4e-fd5b-4f04-9b02-b9cbb1d75762)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
https://www.virustotal.com/gui/url/d995f244828382bc8c675eb2745cc496944368f89eeebf3f6971a0f36efdc7cb
