### ISSUE TITLE
rutor.org.in need remove from blacklist

### ISSUE THREAD

**Issue by gurulo123** [AdguardTeam/AdGuardSDNSFilter#1346]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### What DNS filters do you have enabled?

Adguard DNS

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

rutor.org.in

### Add your comment and screenshots

Hello, this is my site, site was hacked, we fixed all virus, we removed all virus, site is clean, please Recheck, thanks

### Privacy

- [X] I agree to follow this condition

**Comment by gurulo123** [comment]
<img width="1074" alt="Снимок экрана 2023-05-16 в 01 25 19" src="https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/133713887/ddf4a23a-048a-47ae-811e-711cce9d139c">

**Comment by Alex-302** [comment]
Will be unblocked.
