### ISSUE TITLE
www.newsweekjapan.jp

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardSDNSFilter#1348]
@adguard-bot commented on [Tue May 16 2023](https://github.com/AdguardTeam/AdguardFilters/issues/151005)

### Issue URL (Incorrect Blocking)
 [https://www.newsweekjapan.jp/stories/woman/2023/05/5-2_3.php](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.newsweekjapan.jp%2Fstories%2Fwoman%2F2023%2F05%2F5-2_3.php)
### Comment
> This occurs when DNS filtering is used.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/EP36orv.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/jhiTgXU.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 11
AdGuard product: | AdGuard for Android v3.6.11+(54)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
Stealth mode: | disabled
DNS filtering: | server: `System`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Language-specific:</b><br/>AdGuard Japanese
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js

---

@Yuki2718 commented on [Tue May 16 2023](https://github.com/AdguardTeam/AdguardFilters/issues/151005#issuecomment-1549746178)

Not sure how much it matters. User can still click on the link.

**Comment by Alex-302** [comment]
Amazon Ads used here.
