### ISSUE TITLE
||non.li^ blocks l.francebleu.fr  and a bunch of other domains

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#1349]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AG DNS filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

l.francebleu.fr 

### Add your comment and screenshots

```
nslookup l.francebleu.fr 1.1.1.1
Server:		1.1.1.1
Address:	1.1.1.1#53

Non-authoritative answer:
l.francebleu.fr	canonical name = non.li.
Name:	non.li
Address: 35.227.233.185
```

> Our clients delegate a subdomain to us via CNAME to our domain [non.li](http://non.li/) (35.227.233.185). These subdomains are employed to measure clicks on social media posts, and we assure you that they are not utilized for displaying ads or retargeting users. Our solution has obtained an exemption from consent requirements provided by [CNIL](https://www.cnil.fr/fr/cookies-et-autres-traceurs/regles/cookies-solutions-pour-les-outils-de-mesure-daudience).

CRM ID: 758682

### Privacy

- [X] I agree to follow this condition

**Comment by Eugene-Savenko** [comment]
l.franceinter.fr
l.franceculture.fr
l.francetvinfo.fr
l.francemusique.fr
l.francebleu.fr
l.mouv.fr
l.fip.fr
l.radiofrance.fr
go.letelegramme.fr

**Comment by moisemorard** [comment]
Hello,

I'm the CEO of Nonli. 
User privacy is a top priority for us. We do measure user clicks, but all of our data is anonymized and we can't trace it back to a specific user. For example, we do not allow our clients to have accurate click-throughs per minute and we round them up to the nearest 10 to protect users.
We have followed the strict rules of the RGPD and are listed on the [CNIL website](https://www.cnil.fr/fr/cookies-et-autres-traceurs/regles/cookies-solutions-pour-les-outils-de-mesure-daudience) among the solutions exempted from consent, each user can disable tracking by clicking on the corresponding link. 
For example: 
https://l.francebleu.fr/cookie/consent
https://l.leparisien.fr/cookie/consent

Thanks for your help

**Comment by Yuki2718** [comment]
https://github.com/easylist/easylist/issues/15960

**Comment by Alex-302** [comment]
@Eugene-Savenko What exactly is broken and how to reproduce?

**Comment by moisemorard** [comment]
Hello @Alex-302, Nonli is used like Bitly. When our customers publish a content on social media a link is created and this link doesn't work if you have adguard installed.
For example, you can reproduce it by clicking on [this Facebook post](https://www.facebook.com/113434835339857_7274972905852645)
