### ISSUE TITLE
http://www.quicken.com/ incorrectly blocked

### ISSUE THREAD

**Issue by jamie1911** [AdguardTeam/AdGuardSDNSFilter#1355]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS
`94.140.14.15`
`94.140.15.16`

### What DNS filters do you have enabled?

AdGuard Family protection servers

### What browser or app do you use?

Chrome, Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

http://www.quicken.com/

### Add your comment and screenshots

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/6832363/55f748d6-e63e-455a-9cc4-860c67515f48)

### Privacy

- [X] I agree to follow this condition

**Comment by stewartsoda** [comment]
I encountered this, too. Again. Looks like https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1323 again.

**Comment by Alex-302** [comment]
Will be checked.
