### ISSUE TITLE
email.seznam.cz is falsely blocked when running AdGuard parental control web service in AdGuard Home

### ISSUE THREAD

**Issue by krystofkrticka** [AdguardTeam/AdGuardSDNSFilter#1357]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

AdGuard Home v0.107.29

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

```
# Google DNS
https://dns.google/dns-query
tls://dns.google
#
# Cloudflare DNS
https://dns.cloudflare.com/dns-query
tls://1dot1dot1dot1.cloudflare-dns.com
#
# AdGuard DNS
https://unfiltered.adguard-dns.com/dns-query
tls://unfiltered.adguard-dns.com
```
### What DNS filters do you have enabled?

```
AdGuard DNS filter
AdAway Default Blocklist
NoCoin Filter List
EasyList Czech and Slovak (Domains)
Pi-hole Parser - Czech Republic
```

### What browser or app do you use?

Firefox, Chrome, Safari, Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

email.seznam.cz

### Add your comment and screenshots

Czech email provider seznam.cz is blocked by parental control but with this stance we could take every email provider as NSFW. This causes for legitimate users to be unable to access their email inbox. For now I fixed this by unblocking the site using custom rules.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@krystofkrticka Can't reproduce. Does it still happen?

**Comment by krystofkrticka** [comment]
I fixed it by unblocking it using custom rule. But in the end I completely disabled parental control service module because it had way too many false positives. And used Unified Hosts block list instead.
