### ISSUE TITLE
Invalid domains in list (10.10.34.)(4adtf.com.)(ejghgjhhgadcdchjaada.ru.)

### ISSUE THREAD

**Issue by Ad-Blokker** [AdguardTeam/AdGuardSDNSFilter#1358]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### What DNS filters do you have enabled?

AdGuard DNS filter

Description: Filter composed of several other filters (AdGuard Base filter, Social Media filter, Tracking Protection filter, Mobile Ads filter, EasyList and EasyPrivacy) and simplified specifically to be better compatible with DNS-level ad blocking.

Version: 2.0.50.57

### What browser or app do you use?

Other app

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Add your comment and screenshots

Parsing error for:

```
10.10.34.
4adtf.com.
ejghgjhhgadcdchjaada.ru.
```

Using combination filter from:
https://filters.adtidy.org/extension/chromium/filters/15.txt
Which uses AdGuard as upstream

---

```ejghgjhhgadcdchjaada.ru.```
correction is requested in EasyList:
https://github.com/easylist/easylist/issues/15988

### Privacy

- [X] I agree to follow this condition

**Comment by krystian3w** [comment]
Correction is not required in EasyList a in the AdBlock/ABP engine so that you can omit the period for cosmetic filters, in regex and the `domain=` modifier.

**Comment by Alex-302** [comment]
Rules with `TLD.` are not invalid.

**Comment by krystian3w** [comment]
Valid in Adblock Plus and AdBlock.
