### ISSUE TITLE
`linux-usb.vger.kernel.narkive.com` is said NSFW

### ISSUE THREAD

**Issue by KSR-Yasuda** [AdguardTeam/AdGuardSDNSFilter#1359]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

AdGuard Family Safe Server (`94.140.14.15`)

### What DNS filters do you have enabled?

AdGuard Family Safe Server (`94.140.14.15`)

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://linux-usb.vger.kernel.narkive.com

### Add your comment and screenshots

The server `linux-usb.vger.kernel.narkive.com` is blocked by the family safe servers (`94.140.{14.15, 15.16}`).

It's a mailing list archive site.
At least, I think it is not an NSFW site.

```text
# AdGuard Default Server (OK)
% nslookup linux-usb.vger.kernel.narkive.com 94.140.14.14
Non-authoritative answer:
Server:  dns.adguard.com
Address:  94.140.14.14

DNS request timed out.
    timeout was 2 seconds.
Name:    linux-usb.vger.kernel.narkive.com
Address:  149.248.211.108
```

```text
# AdGuard Family Safe Server (NG)
% nslookup linux-usb.vger.kernel.narkive.com 94.140.14.15
Non-authoritative answer:
Server:  dns-family.adguard.com
Address:  94.140.14.15

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
Name:    linux-usb.vger.kernel.narkive.com
Address:  94.140.14.35
```

```text
# Google Public DNS (OK; for comparison)
% nslookup linux-usb.vger.kernel.narkive.com 8.8.8.8
Non-authoritative answer:
Server:  dns.google
Address:  8.8.8.8

Name:    linux-usb.vger.kernel.narkive.com
Address:  149.248.211.108
```

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reprodcuced at the moment.

**Comment by KSR-Yasuda** [comment]
@Alex-302

> Not reprodcuced at the moment.

In my env, still the server is blocked.
What is wrong...?

<details>

```bash
% date -R
Wed, 24 May 2023 09:32:51 +0900

# Family Safe Server #1 (NG)
% nslookup linux-usb.vger.kernel.narkive.com 94.140.14.15
Non-authoritative answer:
Server:  dns-family.adguard.com
Address:  94.140.14.15

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
Name:    linux-usb.vger.kernel.narkive.com
Address:  94.140.14.35

# Family Safe Server #2 (NG)
% nslookup linux-usb.vger.kernel.narkive.com 94.140.15.16
Non-authoritative answer:
Server:  dns-family.adguard.com
Address:  94.140.15.16

DNS request timed out.
    timeout was 2 seconds.
Name:    linux-usb.vger.kernel.narkive.com
Address:  94.140.14.35

# Default Server #1 (OK)
% nslookup linux-usb.vger.kernel.narkive.com 94.140.14.14
Non-authoritative answer:
Server:  dns.adguard.com
Address:  94.140.14.14

Name:    linux-usb.vger.kernel.narkive.com
Address:  149.248.211.108

# Default Server #2 (OK)
% nslookup linux-usb.vger.kernel.narkive.com 94.140.15.15
Non-authoritative answer:
Server:  dns.adguard.com
Address:  94.140.15.15

Name:    linux-usb.vger.kernel.narkive.com
Address:  149.248.211.108
```
</details>

**Comment by KSR-Yasuda** [comment]
I'm not using VPN...
Anyway, I'll use the default DNS for now.

**Comment by Alex-302** [comment]
@KSR-Yasuda 

> I'm not using VPN...

**I** use VPN:) It has own VPN settings, and and DNS requests go through it.

**Comment by KSR-Yasuda** [comment]
Now it is working. Thank you!

**Comment by Alex-302** [comment]
Great
