### ISSUE TITLE
Crypto

### ISSUE THREAD

**Issue by trimechee** [AdguardTeam/AdGuardSDNSFilter#1361]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Hello, does our beloved AdGuardSDNSFilter block also crypto currency mining malware scripts ?

### Proposed solution

block mining natively

**Comment by Alex-302** [comment]
Yes, but we do not block public mining pools.

**Comment by trimechee** [comment]
Interesting ! Thank you so much :)
