### ISSUE TITLE
incorrect blocking

### ISSUE THREAD

**Issue by jobbb2** [AdguardTeam/AdGuardSDNSFilter#1363]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### Version

https://family.adguard-dns.com/dns-query

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://family.adguard-dns.com/dns-query

### What DNS filters do you have enabled?

https://family.adguard-dns.com/dns-query

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

filmpalast.to

### Add your comment and screenshots

Please remove it from you family blocklist.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Will be checked. But I am not sure if it will be unblocked.
