### ISSUE TITLE
https://kirkepartner.dk

### ISSUE THREAD

**Issue by anders-m** [AdguardTeam/AdGuardSDNSFilter#1364]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

94.140.14.15

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Add your comment and screenshots

It's a website for tecknical church stuff...

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Will be checked.
