### ISSUE TITLE
signalfx.com false positive blocking

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#1366]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

It has been reported that signalfx.com is server-side metrics and not a web analytics system, it makes no sense to block it.

### Proposed solution

Please check it and remove it from the blocklist if confirmed.

**Comment by Alex-302** [comment]
Already fixed.
