### ISSUE TITLE
Consider adding domains responsible for advertising on Samsung TV

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#137]
||config.samsungads.com^
||ads.samsungads.com^
||samsungtvads.com^
||samsungads.com^

> _Machine translation from German:_ The links above are responsible for ads on Samsung SmartTV devices. I have blocked the above-mentioned links for months and could find no impairment of the tv's, advertisements have no more surfaced.

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1046
