### ISSUE TITLE
catchuphls.hosting.thisisdax.com false blocking

### ISSUE THREAD

**Issue by arobsco** [AdguardTeam/AdGuardSDNSFilter#1371]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS, Other

### Version

NextDNS

### What DNS filters do you have enabled?

AdGuard DNS filter
AdGuard Base filter

### What browser or app do you use?

Chrome, Microsoft Edge, Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.globalplayer.com/

### Add your comment and screenshots

All catchup services on Global Player are non functional due to this domain being blocked by 
<details>![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/18175536/5a2f15fe-8793-4168-adbc-df34501844ee)</details>

App and website return an error stating that catchup services are unavailable as a result. When the domain is filtered either through NextDNS allow list or by removing the adguard filter the services are functional again.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. I don't see such requests. Need more details, inc. your region or used VPN location.
