### ISSUE TITLE
https://www.supervielle.com.ar/ is blocked by AdGuard DNS

### ISSUE THREAD

**Issue by OlgaPetukhova** [AdguardTeam/AdGuardSDNSFilter#1372]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

AdGuard DNS filter 2.0.50.92

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

www.supervielle.com.ar

### Add your comment and screenshots

1. Checked with several AdGuard DNS servers, the website isn't opening.
2. Changing the server to non-AdGuard one and disabling the filter resolved the issue.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@OlgaPetukhova Can't reproduce. It is not blocked by filters, safe browsring or by a family protection.
