### ISSUE TITLE
Add trojan trackers domain to Adguard public dns list

### ISSUE THREAD

**Issue by ihurin** [AdguardTeam/AdGuardSDNSFilter#1373]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

The kaspersky antivirus team has detected that these domains are being connected automatically by Apple Imessage on the iPhone and with that a trojan file is downloaded that starts to track everything that is done on the user's smartphone and sends it to a remote server: microphone recordings, photos from instant messengers, geolocation, and data about a number of other activities of the owner of the infected device: https://usa.kaspersky.com/blog/triangulation-attack-on-ios/28444/

Russia's Federal Security Service (FSB) said this trojan is from NSA. They said the plot showed "close cooperation" between Apple and the National Security Agency (NSA), the U.S. agency responsible for cryptographic and communications intelligence and security. 
https://www.reuters.com/technology/russias-fsb-says-us-nsa-penetrated-thousands-apple-phones-spy-plot-2023-06-01/

### Proposed solution

add and block these domains in the list:

addatamarket.net
backuprabbit.com
businessvideonews.com
cloudsponcer.com
datamarketplace.net
mobilegamerstats.com
snoweeanalytics.com
tagclick-cdn.com
topographyupdates.com
unlimitedteacup.com
virtuallaughing.com
web-trackers.com
growthtransport.com
anstv.net
ans7tv.net

**Comment by Alex-302** [comment]
They are not working
![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/8361299/96987a8e-e3b9-4474-abf7-385e97402686)
