### ISSUE TITLE
incorrect blocking

### ISSUE THREAD

**Issue by panwarIITG** [AdguardTeam/AdGuardSDNSFilter#1376]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

94.140.14.15 and 94.140.15.16

### What DNS filters do you have enabled?

Adguard DNS filter family protection

### What browser or app do you use?

Chrome, Other app

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.truecaller.com/

### Add your comment and screenshots

This site is used to reverse search names by phone numbers . it is not a porn site, still it is getting blocked by family protection server and I am getting this image
<img width="771" alt="image" src="https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/45776864/bae52201-8464-4395-b3d8-071635a0d353">
Please unban this site.
thank you

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Already fixed.
