### ISSUE TITLE
Block some french domains on Adguard list.

### ISSUE THREAD

**Issue by ihurin** [AdguardTeam/AdGuardSDNSFilter#1377]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Ads on some French TV services

### Proposed solution

Here are the domains that would be great to be blocked for everybody :

MyTF1 : "7b9de.v.fwmrm.net" and "adv.tf1.fr" and "adproxy.tf1.fr"
6play : "7cbf2.v.fwmrm.net"
FranceTV : "7cd77.v.fwmrm.net"
RMC BFM Play : "7dcde.v.fwmrm.net"
MyCanal : "proxy.ads.canalplus-bo.net" and "7bd92.v.fwmrm.net"

### Additional information

ZD ticket 764102

**Comment by Alex-302** [comment]
Blocking of v.fwmrm.net causes many issues, which cannot be resolver using only DNS.

**Comment by Alex-302** [comment]
> MyTF1 : "7b9de.v.fwmrm.net" and "adv.tf1.fr" and "adproxy.tf1.fr"

Done.
