### ISSUE TITLE
Bloqueio incorreto 

### ISSUE THREAD

**Issue by TonSantos1991** [AdguardTeam/AdGuardSDNSFilter#1380]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [x] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Filtro DNS público com controle Parental 

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

Globo.com

### Add your comment and screenshots

![Screenshot_20230611_023920_Chrome](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/136218459/35095822-3830-4172-8659-0c66325086d3)

Site adicionado ao controle Parental com se fosse pornografia

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Fixed.
