### ISSUE TITLE
Incorrect blockinf

### ISSUE THREAD

**Issue by Zyadshaban1** [AdguardTeam/AdGuardSDNSFilter#1381]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### What DNS filters do you have enabled?

Ad guard children filtring

### What browser or app do you use?

Chrome, Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

www.truecaller.com

### Add your comment and screenshots

Truecaller is a popular and famous app

It only identify unknown number that calls you 

It was blocked by mistake so please unblock it 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Fixed.
