### ISSUE TITLE
AdGuard DNS filter blocks survicate.com

### ISSUE THREAD

**Issue by j-brzozowski** [AdguardTeam/AdGuardSDNSFilter#1383]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### What DNS filters do you have enabled?

AdGuard DNS Filter

### What browser or app do you use?

Other app

### Which device type do you use?

Other device

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

survicate.com, panel.survicate.com

### Add your comment and screenshots

06/14/2023 3:30:42 PM
Blocked by: AdGuard DNS filter
||survicate.com^

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@j-brzozowski Hi
How/where can I check how the survicate script works?
I see it on https://www.probikeshop.fr/vtt-electrique-nukeproof-megawatt-297-comp-intl-gris/338413.html But it seems it does nothing.

**Comment by j-brzozowski** [comment]
@Alex-302 This page will show a survey after you scrolled 50% https://survicate.com/software/email-survey/

**Comment by Alex-302** [comment]
This domain is also blocked by EasyPrivacy. So I'd prefer to check third-party site, which uses survicate.com (it was added to tracking protection filter more than 7 years ago)

**Comment by j-brzozowski** [comment]
EasyPrivacy is a blacklist that completely removes all forms of tracking from the internet.

When it comes to Survicate, there are more types of surveys:
- Targeted Website Surveys - that require tracking code installed on a website, e.g., https://b2bservices.xyz/tws-sample/
- Link Surveys - standalone, full-page surveys available on dedicated links, e.g., https://survey.survicate.com/69646e5c1d7f37d8/?p=anonymous

**Comment by Alex-302** [comment]
> EasyPrivacy is a blacklist that completely removes all forms of tracking from the internet.

Our DNS blocks ads and tracking.



> * Targeted Website Surveys - that **require tracking code** installed on a website, e.g.,

If a separate domain will be used for tracking, we could change our DNS filtering rule.

**Comment by j-brzozowski** [comment]
This is not tracking but rather the standard functionality of surveys. Many SaaS products must store data in order to function properly - this includes chats, surveys, and any interactions with users/visitors. These aren't blocked by your list. I observe numerous similar services on the EasyPrivacy list that aren't present on the AdGuard DNS list.

Survicate stores data in LocalStorage and SessionStorage, not in cookies or other tracking technologies. This data is strictly essential for the functioning of surveys.

Contrary to EasyPrivacy, which limits the display of pages to essentially text and graphics (without any additional technologies), AdGuard is intended to be a list that safeguards against advertising, tracking, and malicious or phishing sites. Survicate does not belong to any such category of sites.

Additionally, blocking Survicate may inadvertently hinder the user experience on websites that use its survey services for feedback collection and improvement. The lack of transparency and detailed reasoning for the blacklisting can lead to misunderstandings and cause harm to the reputation of legitimate businesses such as Survicate.

Survicate's data collection is strictly for the purpose of their product functionality, not for any sort of unauthorized personal data mining, which makes them different from malicious tracking services. Survicate's practices are in line with general data protection and privacy standards, ensuring user information is handled responsibly and securely. As an entity located in the EU, we strictly comply with the requirements of the GDPR.

Given this, could you consider removing the domain entirely?
