### ISSUE TITLE
Blocked Human Social Services Site

### ISSUE THREAD

**Issue by Crystalfirebaby** [AdguardTeam/AdGuardSDNSFilter#1384]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Idk

### What browser or app do you use?

Chrome, Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

Liberty-resources.org

### Add your comment and screenshots

![SmartSelect_20230614_160215_Brave](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/136644804/4b27ec18-baab-42d4-9e1d-07d5ddb68693)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Fixed.
