### ISSUE TITLE
Nxmxmlx

### ISSUE THREAD

**Issue by Duransoylu** [AdguardTeam/AdGuardSDNSFilter#1387]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Kclclcllxlx

### Proposed solution

Nxmxkxlxll

### Additional information

Nxmxmxmxm

**Comment by Duransoylu** [comment]
Kgkfllf

**Comment by Duransoylu** [comment]
Nsnzkz

**Comment by Duransoylu** [comment]
Leve a kommet

**Comment by Duransoylu** [comment]
@Duransoylu 
Nsksmkslzkskkkzkzsl
Kdkkdkslsl

**Comment by Jarbascoutinhoribeiro** [comment]
Sim

**Comment by jellizaveta** [comment]
Please don't just open the issue. Describe the problem according to the template, if it exists.
