### ISSUE TITLE
Block Antizapret proxy.

### ISSUE THREAD

**Issue by notstnx** [AdguardTeam/AdGuardSDNSFilter#1389]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

94.140.14.14
94.140.15.15

### What DNS filters do you have enabled?

https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://cloudflare-ipfs.com/ipfs/QmZsD5NF3edtmiK1jhV3de1swqBtXTfXrCZLnc4GimQgaW/proxy-ssl.js

### Add your comment and screenshots

This link is used for the Antizapret proxy. Before that, everything worked fine.
You can make sure that the links do not cause any harm.
https://antizapret.prostovpn.org:8443/proxy.pac
https://antizapret.prostovpn.org:18443/proxy.pac

### Privacy

- [x] I agree to follow this condition

**Comment by jellizaveta** [comment]
`AdGuard DNS` does not block `cloudflare-ipfs.com` and `antizapret.prostovpn.org` . Do you have any user rules?

**Comment by jellizaveta** [comment]
@notstnx hello. Any news?

**Comment by notstnx** [comment]
@jellizaveta Not anymore. I use the public DNS from AdGuard. There are no other filters anymore. A day later, Public AdGuard DNS stopped complaining about the malicious link.

**Comment by jellizaveta** [comment]
Thanks for the reply! I'm closing the task.
