### ISSUE TITLE
||mybluemix.net^ blocks the Weather Line app

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#139]
Reported by helpdesk ID 2335224

 I have DNS privacy turned on and pointed to the AdGuard DNS-over-HTTPS DNS server (regular, not family). Today I purchased a weather application on IOS named Weather Line. As part of its functionality, it retrieves weather information from The Weather Channel servers. It fails to retrieve data when I use the AdGuard DNS server, but works fine, still with privacy mode mode on, if I use another DNS server, such as Cloudflare’s server. Looking at the DNS requests log, it appears the AdGuard DNS server is black-holing the IP address of the API server for The Weather Channel used by the weather application. A screen shot is attached below of the log entry. The blocked DNS entry is for:

twcservice.mybluemix.net <http://twcservice.mybluemix.net/>

If you go to that address via a browser, you will land on a page describing itself as weather company data via IBM API’s (IBM now owns the The Weather Channel). I believe the site is legitimate. Should it be blocked by your DNS server? 

<details>

![image](https://user-images.githubusercontent.com/15856304/66301786-6c6f0e00-e900-11e9-8b43-9706efd42ea6.png)

</details>

**Comment by zloyden** [comment]
Fixed in this [pull request](https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/125).
