### ISSUE TITLE
bit.ly is incorrectly reported as dangerous website

### ISSUE THREAD

**Issue by Galang23** [AdguardTeam/AdGuardSDNSFilter#1391]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X ] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

AdGuard Home v0.107.32

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://dns10.quad9.net/dns-query
94.140.14.140
1.1.1.1
1.0.0.1

### What DNS filters do you have enabled?

AdGuard DNS filter
AdAway Default Blocklist
Dan Pollock's List
Peter Lowe's Blocklist
IDN: ABPindo
Perflyst and Dandelion Sprout's Smart-TV Blocklist
The Big List of Hacked Malware Web Sites
WindowsSpyBlocker - Hosts spy rules
OISD Blocklist Basic
Scam Blocklist by DurableNapkin
Malicious URL Blocklist (URLHaus)

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://bit.ly/

### Add your comment and screenshots

AdGuard misidentify bit.ly, the URL shortener, as a dangerous website. This is false positive, as bit.ly only provides shortened URL of user's url. This may interrupt workflow and browsing experience to many users. This occurs when bit.ly is accessed from either HTTPS and HTTP. The attached screenshots demonstrate the report.

![firefox_PAkyJgvug1](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/13700948/c8f2d1f6-c523-48e2-aa3b-e7500e7ce58e) accessed via HTTPS (previously showing SSL certificate mismatch before I click "accept risk and continue" on firefox).

![firefox_bnRTyRwQts](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/13700948/0e3a4274-e9b4-42ea-861e-7bf31c233b8c) accessed via HTTP.

### Privacy

- [X] I agree to follow this condition

**Comment by XChrispy** [comment]
Came here to say the same. When you select more information, Adguard's own page says it's safe: https://reports.adguard.com/en/bit.ly/report.html?aid=16593

**Comment by Galang23** [comment]
When I created this issue, the page was blocked. I think it has been fixed when you replied. Now it's fixed.
