### ISSUE TITLE
Ошибка с блокировкой

### ISSUE THREAD

**Issue by vinbintan** [AdguardTeam/AdGuardSDNSFilter#1396]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

<details> ![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/137514470/64ce0d6b-ea49-4c5d-b88a-91859ae19bdc) </details>

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://taplink.cc/che.rny.shev

### Add your comment and screenshots

<details> ![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/137514470/7d8e65e7-305a-4fe8-beda-0ff7ef93a124) </details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
На данный момент домен не находится в блокируемых списках. Доступ к сайту сейчас есть.
