### ISSUE TITLE
[custom filter] placing comment next to rule not working

### ISSUE THREAD

**Issue by dnmTX** [AdguardTeam/AdGuardSDNSFilter#1398]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [ ] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [ ] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Cloudflare DNS DoT

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

1.1.1.1
1.0.0.1

### What DNS filters do you have enabled?

Personal Custom Filter

### What browser or app do you use?

Slimjet Version 39.0.2.0 (based on Chromium 111.0.5563.41) (Official Build) (64-bit)

### Which device type do you use?

Laptop

### Add your comment and screenshots

I hope that i'm posting in the correct repo.
@AdguardTeam i just noticed that if i try to add a comment(either `!` or `#`) next to some rule(blocked domain),that rule is not active and the domain is not blocked. For example:
`|d3lqotgbn3npr.cloudfront.net^ ! Ebay !`
Found it helpfull,on my end,especially with the `cloudfront.net` domains,to add a comment as i 've noticed that the same domain might deliver different content to other website(s) and this way i can just use the `$denyallow` rule to mitigate.
If such a option was not implemented,i would like to make a FEATURE REQUEST.
Thank you as allways 👍 

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
In Adblock-Style Syntax only line that **starts** with an exclamation mark or a hash sign is a comment. Unfortunately, it's hard enough to implement a comment in a line without losing compatibility with other rule types. The comment can be written at the top, it will also be clear visually
