### ISSUE TITLE
tiscali.it blocked 

### ISSUE THREAD

**Issue by burstina** [AdguardTeam/AdGuardSDNSFilter#1399]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

adguard public dns for family

### What browser or app do you use?

Firefox

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

tiscali.it

### Add your comment and screenshots

tiscali.it is a trusted italian website, but DNS blocks tjis website 

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
The domain itself is not blocked by AdGuard DNS. Unfortunately, I also cannot reproduce the access problem. Please repeat the problem and attach a screenshot of the filter log.
