### ISSUE TITLE
Laposte.fr : Login doesn't work - shows a blank page

### ISSUE THREAD

**Issue by ycngmn** [AdguardTeam/AdGuardSDNSFilter#1400]
### Platform

Android

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Issue Details

1. Go to laposte.fr
2.  Create an account / Login 
3.  ( Doesn't load. Shows a blank page ) 

### Expected Behavior

My dashboard is shown after a succesful login.

### Actual Behavior

Shows a blank / white page. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by jellizaveta** [comment]
The issue is happens due to `||tagcommander.com` being blocked
Unfortunately we are unable to unblock this domain, because this tracker is popular.
You can exclude this domain from DNS filtering by adding `@@||cdn.tagcommander.com` to the User filter.
