### ISSUE TITLE
Incorrect blocking for leechers-paradise.org, eapteka.ru (cdn.eapteka.ru),  BBC Android application (a1.api.bbc.co.uk)

### ISSUE THREAD

**Issue by IRainman** [AdguardTeam/AdGuardSDNSFilter#1401]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

Version: v0.107.32

### What DNS filters do you have enabled?

https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

leechers-paradise.org, eapteka.ru (cdn.eapteka.ru),  BBC Android aplication (a1.api.bbc.co.uk),

### Add your comment and screenshots

Additional information can be founded [here](https://github.com/AdguardTeam/AdGuardHome/issues/5819)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
We do not block eapteka.ru / cdn.eapteka.ru

> leechers-paradise.org

fixed, bit-torrent related.

> a1.api.bbc.co.uk

used for tracking. Where blocking causes problems?

**Comment by IRainman** [comment]
@Alex-302 At least the [BBC learning English](https://play.google.com/store/apps/details?id=uk.co.bbc.learningenglish) application isn't working properly.

**Comment by Alex-302** [comment]
@IRainman What exactly?

**Comment by IRainman** [comment]
Now I probably don't reproduce the Issue with BBC, I will open a new issue if bug reproduced again.
