### ISSUE TITLE
logs.datadog.com works, but logs.datadog.eu is currently blocked

### ISSUE THREAD

**Issue by pedrolamas** [AdguardTeam/AdGuardSDNSFilter#1404]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

v0.107.32

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

1.1.1.1

### What DNS filters do you have enabled?

* https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

(internal app)

### Add your comment and screenshots

This is a follow up on #621, which fixed the blocking issue for apps using logs.datadoghq.com, but should also include the logs.datadoghq.eu as they have that domain for EU apps.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
We do not remove blocking rule without good reason.
If an app fails when analytics are blocked/unavalable - better ask devs to fix it. It is a bad behavior, when an app can't work without ability to sent analytics/telemetry.

**Comment by Alex-302** [comment]
But using adguard-dns.io you can unblock or block any domain (supported separated settings for different devices).
