### ISSUE TITLE
Failed to unsubscribe with email.gitpod.io 

### ISSUE THREAD

**Issue by IRainman** [AdguardTeam/AdGuardSDNSFilter#1409]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

Version: v0.107.32

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

1.1.1.1

### What DNS filters do you have enabled?

https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://email.gitpod.io 

### Add your comment and screenshots

...

### Privacy

- [X] I agree to follow this condition

**Comment by IRainman** [comment]
@Alex-302 simplify `email.gitpod.io` is blocked by DNS.

**Comment by jellizaveta** [comment]
Should not be blocked under the `@@|||e.customeriomail.com^|` exception. Could you provide a bit more information or steps for reproduction?

**Comment by IRainman** [comment]
I simplify add the `@@||email.gitpod.io^` exception, and it works for me. I can't provide more information, because I'm already unsubscribe and now site shown me only empty page.

**Comment by Alex-302** [comment]
This domain is not blocked at the moment
![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/8361299/ec246e88-eb9f-437b-bf8c-0a956a27fd5a)

**Comment by IRainman** [comment]
@Alex-302 nice, thank you!
