### ISSUE TITLE
Redirecting from gate.first-id.fr is not working

### ISSUE THREAD

**Issue by DafRami** [AdguardTeam/AdGuardSDNSFilter#1411]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

94.140.14.14
94.140.15.15

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://gate.first-id.fr/?redirectHost=https://www.marianne.net

### Add your comment and screenshots

For instance: 

marianne.net => https://gate.first-id.fr/?redirectHost=https://www.marianne.net => gate.first-id.fr: no DNS record
![Capture-1](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/96936777/f38fdb4a-1f7c-42fd-977e-2c2d43de0162)

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Added an exception for this domain. Will be available today or at the latest tomorrow.
