### ISSUE TITLE
ezodn.com IS tracking cancer, but also required to get past a common GDPR dark pattern

### ISSUE THREAD

**Issue by elandorr** [AdguardTeam/AdGuardSDNSFilter#1412]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

my own, and it doesn't matter

### What DNS filters do you have enabled?

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Firefox, Chrome, Safari, Microsoft Edge, Opera, Yandex Browser, Other app

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Add your comment and screenshots

A particularly annoying GDPR dark pattern does not work when ezodn.com is blacklisted.

For privacy reasons I obviously can't show where I encountered it last, but it's a generic problem. Some of you probably saw this before. Maybe, if you find it again on some generic mainstream site, you can post.

Without your blacklist, it looks like:
![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/56206745/c049117c-6f60-46e0-af29-e72f994c66a1)

Where you are expected to go through a gigantic list one by one to achieve basic dignity. (or use an add-on to do it for you)

With it blacklisted, you cannot get past it:
![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/56206745/a86f2903-9258-4392-8163-01527627d9a5)

It doesn't react to clicks at all.

Not sure how this should be handled. Yes, this domain, and their entire company are obviously cancer, but that hits a philosophical question: Do you submit to the death-grip of capitalism, or die? If you are forced to use such a site, you are forced to whitelist it anyway. It's common, and might be on a supermarket's site, which you are forced to use, or some other store you need to survive physically.

It's surprising that a majority of capitalists are still dumb enough to not simply use such a model on everything. It's extremely simple to defeat AGH and similar blacklists: Just put the crap behind a host that must be whitelisted.

This thing has a CSS id of 'ez-cookie-dialog-wrapper'.

For the techy people, here's a minimal userscript you can share:
https://greasyfork.org/en/scripts/462127-ez-cookie-remover/code

Now I can be stubborn enough to find this, make or find a script, but that's niche-in-a-niche territory.

For regular people, having a basic standard list break a basic cookie abuse prompt is a problem. Especially, if you set up a minimal AGH installation for them, and they have no clue why stuff suddenly breaks.

Another fun fact about how retarded the EU is: None of these even work. No matter, if you accept or not, or remove the thing altogether, cookies have already been set. The whole 'consent' shenanigans don't do anything.

Suggestions?

I think I might even want to keep it blacklisted to point out the idiocy wherever possible. Maybe this thread can serve that. However, that means fewer people will be willing to put up with AGH/etc at all. An emerging problem!

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
DNS blocking is not the most flexible method of blocking. If blocking a particular domain causes a lot of trouble, we can unblock it. But with popular tracking and advertising services it is preferable not to do this, as it defeats the purpose of filtering. Could you please attach a link to the site where this issue occurs?

**Comment by zloyden** [comment]
Yeah, that's an example where we found the issue. Accepting the cookie notices should work fine.
Note the update will be availabe today or at least tomorrow.
