### ISSUE TITLE
Outbrain Ads (not trackers)

### ISSUE THREAD

**Issue by userjohnmichael** [AdguardTeam/AdGuardSDNSFilter#1415]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Public AdGuard DNS servers

### What browser or app do you use?

Firefox, Chrome, Microsoft Edge, Opera

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed ads

### Where did you encounter the problem?

https://www.lemonde.fr/international/article/2023/07/03/un-bureau-pour-enqueter-sur-l-agression-russe-en-ukraine-ouvre-a-la-haye_6180385_3210.html

### Add your comment and screenshots

I am using the Default servers from Adguard DNS which should block Ads, but I am still seeing Outbrain ads on every page I visit. See I'm not talking about trackers, I'm talking about ads.

I did an experiment to try to block Outbrain ads via domain.

**1)** Go to the link: https://www.lemonde.fr/international/article/2023/07/03/un-bureau-pour-enqueter-sur-l-agression-russe-en-ukraine-ouvre-a-la-haye_6180385_3210.html
Using NextDNS, I only enabled the Adguard DNS blocklist, which showed exactly the same result as using Adguard DNS (obviously). You will see Outbrain Ads, like this: https://i.imgur.com/3Tt3LyX.jpeg

**2)** So in NextDNS I blacklisted only one domain (images.outbrainimg.com), keeping the AdGuard DNS filter blacklist enabled. The result was this: https://i.imgur.com/0DNDVfB.jpeg

**3)** So in NextDNS I blacklisted one more domain (in addition to images.outbrainimg.com, I added widgets.outbrain.com), keeping the AdGuard DNS filter blacklist enabled. The result was this: https://i.imgur.com/72qESYA.jpeg
https://i.imgur.com/pJY02S3.jpeg

As can be seen, if Adguard DNS adds to the blacklist the domains **widgets.outbrain.com** and **images.outbrainimg.com**, then Outbrain ads will be finally blocked in desktop and mobile pages.

As I said, the Adguard DNS Default Servers list blocks not only trackers, but ads as well. Please block Outbrain ads in the AdGuard DNS filter.

### Privacy

- [X] I agree to follow this condition

**Comment by userjohnmichael** [comment]
At least on the official website (https://adguard-dns.io/en/public-dns.html) says that this block list should block ads too, not only trackers. Correct? If you block ads, then surely Outbrain's ads should be blocked.

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/128099029/379bff6f-8122-468f-a783-25b084c9af68)

**Comment by userjohnmichael** [comment]
Another example: https://veja.abril.com.br/coluna/maquiavel/parana-aviao-com-tres-pessoas-desaparece-na-serra-do-mar/

Only AdGuard DNS filter: https://i.imgur.com/wNrf9d9.jpg

AdGuard DNS filter + **widgets.outbrain.com** and **images.outbrainimg.com** blocked: https://i.imgur.com/k4UA0HS.jpg

**Comment by userjohnmichael** [comment]
More examples:
**1)** https://www.theverge.com/2023/7/3/23783092/twitter-tweetdeck-new-preview-force-legacy-apis
Only AdGuard DNS filter: https://i.imgur.com/XaSyaim.jpg
AdGuard DNS filter + widgets.outbrain.com and images.outbrainimg.com blocked: https://i.imgur.com/VIktB7s.jpg

**2)** https://news.sky.com/story/fire-that-killed-three-probably-caused-by-e-bike-charging-officials-say-12914139
Only AdGuard DNS filter: https://i.imgur.com/Y4Ut0KM.jpg
AdGuard DNS filter + widgets.outbrain.com and images.outbrainimg.com blocked: 
 https://i.imgur.com/ifULocI.jpg

**3)** https://www.euronews.com/2023/07/03/ukraine-war-advances-near-bakhmut-700000-ukrainian-children-in-russia-moscow-drones-rain-o
Only AdGuard DNS filter: https://i.imgur.com/YH8oDoV.jpg
AdGuard DNS filter + widgets.outbrain.com and images.outbrainimg.com blocked: https://i.imgur.com/qXWQUri.jpg

**Comment by Alex-302** [comment]
Redirects are blocked, so I guess it is not a problem to block this widget. But without blocking `widgets.outbrain.com` / `widgets.outbrain.com/outbrain.js` to avoid some anti-adblock decections.
