### ISSUE TITLE
weird thingy on what should be a pretty safe site. but... 

### ISSUE THREAD

**Issue by Hyperpolymath** [AdguardTeam/AdGuardSDNSFilter#1416]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

no fallback or bootstrap (I think)

### What DNS filters do you have enabled?

all of them except duplicates and language ones

### What browser or app do you use?

Other app

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://univc.alumnialliances.com

### Add your comment and screenshots

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/6759885/78f982b9-1d3f-428b-9b4a-23bd04bdb69d)

well, I hope this is not a trick by Cornell as a laugh, as it is supposedly the Cornell Security and Investigations Special Interest Group for their Alumni Association. However, it goes through to this, and then doesn't let you go further.

Oh, I'm using Brave, and a bunch of flags are set but no idea why this might affect the site, as it doesn't seem to affect other sites and, well, it's odd it cannot even go through when I use that thing.

Be interested in knowing why it is such a bad site. also, here's that email, which seems to be okay, with DKIM, DMARC and SPF all strict mode all okay

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/6759885/c13c2eeb-c6a5-424b-95f4-82cb52d0b52b)

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/6759885/e87ed8e5-4dc3-4af2-ae84-62f9d15d7413)

(certain key authorisation bits excluded, but never actually get to a screen that lets me enter them anyway.

### Privacy

- [X] I agree to follow this condition

**Comment by Hyperpolymath** [comment]
I have contacted them too, and I'm very sure that they will get back to me eventually.

**Comment by zloyden** [comment]
It was removed from our base. The update should be available today or at least tomorrow.
