### ISSUE TITLE
||powerinboxedge.com^

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#142]
### Steps to reproduce
1. Subscribe to any email mailing list that uses PowerInbox, i.e. https://www.komando.com/
2. Ads served from powerinboxedge.com won't be filtered

<details><summary>Screenshot:</summary>

![PIE](https://user-images.githubusercontent.com/33634917/66587832-e66af580-eb93-11e9-9e78-1009b43d8485.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default
| How did you setup DNS configuration:| AdGuard for iOS 3.1
| Device model:| unspecified iPhone
| Operating system and version:| iOS 13.1
| Filters used:| Base, Mobile Ads, EasyList, Peter Lowe's, Tracking Protection, Fanboy's Enhanced Tracking List, Fanboy Anti-Facebook, Social media, Annoyances, Fanboy's Annoyances, Web Annoyances Ultralist, Adblock Warning Removal List, I don't care about cookies, Fanboy's Cookiemonster List, Spam404, NoCoin Filter List, Safari filter, SDN filter, Experimental filter, BarbBlock

**Comment by KaleoK** [comment]
I had reported this. Clarification:

If I add a filter to Weblock, any other email newsletter using powerinboxedge to serve ads, the ads get blocked. It is only in Kim Koamndo’s newsletters that these still get through.

Adding the filter, in AdGuard, does not block those ads in any email newsletter. Can’t figure this out.

**Comment by Alex-302** [comment]
I don't see ads in my mail box:
![image](https://user-images.githubusercontent.com/8361299/66675525-27373d00-ec6e-11e9-8d1a-1011e0c00edf.png)

@KaleoK could you, please forward this email to agshitmail@yandex.ua?

**Comment by KaleoK** [comment]
Update: The ads are blocked in Safari but not in the iPad Mail app or in Spark.

**Comment by KaleoK** [comment]
Alex, she has more than one newsletter. You may have picked the only one that does not have ads.

**Comment by Alex-302** [comment]
please check: `||stripe.rs-1028-a.com^`

**Comment by KaleoK** [comment]
Alex, added that rule. Made no difference. 
On both my iPad and iPhone, Futuremind’s Adblock and their Weblock block those ads in emails. So, don’t know why AdGuard does not.

**Comment by Alex-302** [comment]
Hmm. Could you, please, make screenshot of blocked ads by Futuremind’s Adblock? Does this app has filtering log?

**Comment by KaleoK** [comment]
With Adblock, blank boxes are displayed. With AdGuard, the ads are displayed; this includes animated ads. This is with and without using the AdGuard DNS.

Liveintent/Powerinbox ads are the absolute ugliest and most intrusive on the planet. This is what makes AdGuard’s failure really frustrating. Hope that you can crack this one.

Leon

**Comment by Alex-302** [comment]
> blank boxes are displayed

Got it. Added `||stripe.rs-1028-a.com^`
Please check tomorrow.

**Comment by KaleoK** [comment]
I had forgotten to add the DNS log. I had already added the stripe filter. It did not help, as you can see it was not blocked. I just added the images-prod.powerinboxedge.com filter. It block some, but not all, of the ads!

Leon

**Comment by KaleoK** [comment]
With the images-prod filter, again some of the powerinbox ads are being blocked. The DNS log is not showing that domain as blocked. ?

**Comment by Alex-302** [comment]
Please check tomorrow) (after 12 hours)

**Comment by KaleoK** [comment]
Thanks. The powerinboxedge ads are being blocked. However, in emails, this is only if the DNS Privacy is on. Makes no difference if I select CloudFlare or AdGuard. Either way, no ads.

Just wondering why that is.

Leon

**Comment by Alex-302** [comment]
> in emails

using web site or client app?

**Comment by KaleoK** [comment]
Client app

**Comment by Alex-302** [comment]
That rule was moved to base filter, so it will be applied on sites(which does not use theit proxy for thirв-party resources) and clietnt apps(with our DNS)

**Comment by KaleoK** [comment]
Thanks for cracking this one. Just wondering why, when this filter and the two powerinboxedge filters were in my User Filters, the ads were still getting through.

|| stripe.rs-1028-a.com^

Is there a difference in how Basic Filters or other lists work and how the User Filter works?

Leon

**Comment by Alex-302** [comment]
User filter is not applied to DNS requests, and ads can be blocked on the site only.

**Comment by KaleoK** [comment]
OK. Thanks.

I had added these to my User Filter list. The second and third one are said to block ads in apps. Before you added Powerinboxedge to the Basic filter, i was seeing absolutely no ads (in apps, websites, emails, etc) except for those ugly LIveIntent/PowerInBox ads. Now, I have bliss!

It would help if you search function actually showed individual filters that matched the search criteria. That way, a user can know if a given domain is included in one of the lists.

One other thing, I whitelisted HGTV.com <http://hgtv.com/> but the pages on that site do not completely load.

Leon

**Comment by Alex-302** [comment]
> One other thing, I whitelisted HGTV.com <http://hgtv.com/> but the pages on that site do not completely load.

how you did it?

**Comment by KaleoK** [comment]
I have tried 

hgtv.com
http://hgtv.com/ <http://hgtv.com/>
https:www.hgtv.com/ <http://www.hgtv.com/>

and none of them work.

**Comment by Alex-302** [comment]
where you enter this?
Please make screenshot.
