### ISSUE TITLE
BugByte Website Being Incorrectly Flagged and Blocked as Adult

### ISSUE THREAD

**Issue by nsarakas** [AdguardTeam/AdGuardSDNSFilter#1423]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

AdGuard Home  v0.107.33

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://cloudflare-dns.com/dns-query

### What DNS filters do you have enabled?

AdGuard Parental Control

### What browser or app do you use?

Chrome, Safari

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://bugbyte.fi

### Add your comment and screenshots

Website is for an indie gaming developer. The website is being blocked as an adult website.
<img width="603" alt="image" src="https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/2875949/a89204c7-a051-45ff-a2f1-2992fe797e75">

If I use a VPN or swap to my mobile off WiFi, the website correctly pops up.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
The domain is unlocked, the update will appear today or tomorrow at the latest.
