### ISSUE TITLE
Hoooyi.com is fine?

### ISSUE THREAD

**Issue by alexlyee** [AdguardTeam/AdGuardSDNSFilter#1426]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### What DNS filters do you have enabled?

basic adguard dns filter

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.hoooyi.com/collections/shirts

### Add your comment and screenshots

I don't think this site is bad... is it? Can I remove it from my DNS' blacklist?

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
The domain is unlocked, the update will appear today or tomorrow at the latest.
