### ISSUE TITLE
Deva

### ISSUE THREAD

**Issue by Deva0257** [AdguardTeam/AdGuardSDNSFilter#1427]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [x] You're using an up-to-date version of AdGuard DNS filter;
- [x] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### What DNS filters do you have enabled?

Adguard dna
Guvkfrucjbkgktjcn mc

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

Www.crime.com

### Add your comment and screenshots

No comment 

### Privacy

- [X] I agree to follow this condition

**Comment by Deva0257** [comment]
Vedio play

**Comment by Deva0257** [comment]
No comment

**Comment by Deva0257** [comment]
Vedio no warks

**Comment by jellizaveta** [comment]
The task is closed due to a suspicion of spam.
