### ISSUE TITLE
Some Google's domains used for ads/tracking to be blocked

### ISSUE THREAD

**Issue by hollownights** [AdguardTeam/AdGuardSDNSFilter#1429]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard Public Plain DNS (Default servers)

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed ads, Missed analytics or tracker

### Add your comment and screenshots

Here are some Google's domains used for serving ads or for tracking that aren't currently blocked by AdGuard Public DNS: Some of them seem to only be contacted by mobile apps.

```
analytics-api-samples.googlecode.com
video-stats.video.google.com
www.googleadservices.com
domains.googlesyndication.com
www.googletagservices.com
ads.google.com
afs.googlesyndication.com
mobileads.google.com
video-ad-stats.googlesyndication.com
adservice.google.com
googletagmanager.com
www.googletagmanager.com
mail-ads.google.com
pagead.l.doubleclick.net
```

P.S.: The required prerequisite "If a website or an app is broken, disabling AdGuard DNS filter resolves the issue. " for a bug report is out of place, as not all bug reports are about websites/apps breakage.

### Privacy

- [X] I agree to follow this condition

**Comment by hollownights** [comment]
> Not all these domains used for tracking.

Yes, some are used for serving ads, like `mail-ads.google.com`

> We do not block few of these domains because many sited will be unusable.

How so? Out of those 15 domains, only `googletagmanager.com` can be seen in AdGuard's "[exclusions](https://raw.githubusercontent.com/AdguardTeam/AdGuardSDNSFilter/master/Filters/exclusions.txt)" list, and only 
`www.googleadservices.com` and `pagead.l.doubleclick.net` can be seen in the "[exceptions](https://raw.githubusercontent.com/AdguardTeam/AdGuardSDNSFilter/master/Filters/exceptions.txt)" list. All the others should be good to be blocked (in fact, they already all figure in any good blocking list).

**Comment by Alex-302** [comment]
@hollownights 

> How so? Out of those 15 domains

I visit very many sites every day - normal and literally trash, but don't see in my dns log these domains

analytics-api-samples.googlecode.com
video-stats.video.google.com
ads.google.com
afs.googlesyndication.com
mobileads.google.com
video-ad-stats.googlesyndication.com
adservice.google.com
mobileads.google.com
mail-ads.google.com
pagead.l.doubleclick.net

**Comment by hollownights** [comment]
@Alex-302 

> I visit very many sites every day - normal and literally trash, but don't see in my dns log these domains

Well, that's funny, cause you can easily find references to them on Google's searches results or on VirusTotal (though on VT some of them seem to be hidden, as there are cross references to them from other other domains, but no direct hits, like [video-stats.video.google.com](https://www.virustotal.com/gui/domain/video-stats.video.google.com/relations) that doesn't appears by itself anymore, but appears as a subdomain related to [video.google.com](https://www.virustotal.com/gui/domain/video.google.com/relations)).

Anyway, links to Google Searches and VirusTotal info on some those domains:

```
https://www.google.com/search?q="analytics-api-samples.googlecode.com"
https://www.google.com/search?q="video-stats.video.google.com"
https://www.google.com/search?q="www.googleadservices.com"
https://www.google.com/search?q="domains.googlesyndication.com"
https://www.google.com/search?q="www.googletagservices.com"
https://www.google.com/search?q="ads.google.com"
https://www.google.com/search?q="afs.googlesyndication.com"
https://www.google.com/search?q="mobileads.google.com"
https://www.google.com/search?q="video-ad-stats.googlesyndication.com"
https://www.google.com/search?q="adservice.google.com"
https://www.google.com/search?q="googletagmanager.com"
https://www.google.com/search?q="www.googletagmanager.com"
https://www.google.com/search?q="mobileads.google.com"
https://www.google.com/search?q="mail-ads.google.com"
https://www.google.com/search?q="pagead.l.doubleclick.net"
```

```
https://www.virustotal.com/gui/domain/analytics-api-samples.googlecode.com/relations
https://www.virustotal.com/gui/domain/video-stats.video.google.com/relations
https://www.virustotal.com/gui/domain/www.googleadservices.com/relations
https://www.virustotal.com/gui/domain/domains.googlesyndication.com/relations
https://www.virustotal.com/gui/domain/www.googletagservices.com/relations
https://www.virustotal.com/gui/domain/ads.google.com/relations
https://www.virustotal.com/gui/domain/afs.googlesyndication.com/relations
https://www.virustotal.com/gui/domain/mobileads.google.com/relations
https://www.virustotal.com/gui/domain/video-ad-stats.googlesyndication.com/relations
https://www.virustotal.com/gui/domain/adservice.google.com/relations
https://www.virustotal.com/gui/domain/googletagmanager.com/relations
https://www.virustotal.com/gui/domain/www.googletagmanager.com/relations
https://www.virustotal.com/gui/domain/mobileads.google.com/relations
https://www.virustotal.com/gui/domain/mail-ads.google.com/relations
https://www.virustotal.com/gui/domain/pagead.l.doubleclick.net/relations
```

**Comment by Alex-302** [comment]
![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/8361299/127f6272-b8b0-4bf2-95b0-8fe217478c22)

**Comment by hollownights** [comment]
> results only about blocking, not about details. They look old. Do you suggest to block a domain, which is not used?

It's hard to know to what extent they are or aren't used anymore, as once in a while all of them popup when analyzing .apk files. Even www.googletagmanager.com doesn't get direct hits on VT (which belongs to Google) anymore, despite the fact that it is a very much active domain, so things aren't that simple.

**Comment by hollownights** [comment]
Well, it turns out all those domains do have hits on VirusTotal, and the reason I couldn't see them I was because uBlock was blocking the pages from loading all of their elements. @Alex-302 I would appreciate if you could take a look at the VT links.

**Comment by Alex-302** [comment]
Just provide real actual examples where that domains used.

**Comment by hollownights** [comment]
www.googleadservices.com / googletagmanager.com / www.googletagmanager.com

```
https://www.ionos.com/
https://www.washingtonpost.com/
```


googletagmanager.com / www.googletagmanager.com

```
https://www.avast.com
https://www.anker.com/
https://www.nytimes.com/
https://www.ikea.com/
```


adservice.google.com

```
https://www.howtogeek.com/
https://www.bestbuy.com
```


www.googletagservices.com

```
https://www.howtogeek.com/
https://www.ikea.com/
```


mail-ads.google.com

`Just log in to GMail. Really. That's it.`


domains.googlesyndication.com/relations

`Years and years of being contacted only by malicious files: https://www.virustotal.com/gui/domain/domains.googlesyndication.com/relations`


afs.googlesyndication.com

`Also years and years of being contacted only by malicious files: https://www.virustotal.com/gui/domain/afs.googlesyndication.com/relations`


@Alex-302
