### ISSUE TITLE
gplinks.in is blocked by AdGuard DNS filter

### ISSUE THREAD

**Issue by alexx7311** [AdguardTeam/AdGuardSDNSFilter#1430]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://gplinks.in/

### Add your comment and screenshots

The AdGuard DNS filter contains a rule that blocks access to the website. 

<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/114913601/624a8a8a-9c96-4a22-acca-4af4ed58b1a6)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not sure about it. Need examples of using.
