### ISSUE TITLE
https://freecash.com/r/df1e644dd5

### ISSUE THREAD

**Issue by AliyiAhmed** [AdguardTeam/AdGuardSDNSFilter#1432]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS, AdGuard Home

### Version

meet.google.com/vnv-xzgy-njd

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

bc1q982q5xlrkp0ttevh49q9yeazs7plx8rxcq3durhttps://freecash.com/r/df1e644dd5meet.google.com/vnv-xzgy-njd

### What DNS filters do you have enabled?

https://freecash.com/r/df1e644dd5meet.google.com/vnv-xzgy-njdhttps://www.tiktok.com/studio/download?download_source=email

### What browser or app do you use?

Chrome, Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed ads, Website or app doesn't work properly

### Where did you encounter the problem?

Aliyi93

### Add your comment and screenshots

Good 👍 WiFi: FAMILY 
:  

Share this WiFi with your friends. 
https://bnc.lt/a/key_live_kpUBktOLTXkC97YOxubRSidcDqby7f7y?channel=Social&feature=Share&campaign=Share+Instabridge&type=0&duration=0&source=android&data=eyIkcHVibGljbHlfaW5kZXhhYmxlIjoidHJ1ZSIsImhvdHNwb3RfaWQiOiIxMjA4MjcxOSJ9### 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
What is wrong?
