### ISSUE TITLE
Hostigram.xyz is blocked as malware site

### ISSUE THREAD

**Issue by josemsanchezb** [AdguardTeam/AdGuardSDNSFilter#1438]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

[AdGuard DNS filter](https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-agh.txt)

### What browser or app do you use?

Safari

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://hostigram.xyz

### Add your comment and screenshots

I use hostigram.xyz for several reasons and today I figured out that the site is blocked as malware site, but it isn't a malware site

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
The domain has been removed from the malware list. The update will be available within a day
