### ISSUE TITLE
Blocking uts-front.line-apps.com will affect normal functionality.

### ISSUE THREAD

**Issue by tasi788** [AdguardTeam/AdGuardSDNSFilter#1439]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### Version

v0.107.35

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

tls://dns.google

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://itunes.apple.com/app/line/id443904275

### Add your comment and screenshots

Line has launched a large chat community called Line OpenChat, the biggest difference of which is that Line OpenChat can accommodate up to 5000 people simultaneously. Therefore, more and more people are using Line OpenChat. Blocking uts-front.line-apps.com would cause Line OpenChat to fail to load correctly.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Is the problem already occurring when using the app? Could you please send a screenshot of the error?

**Comment by tasi788** [comment]
Yes, everything has returned to normal since I manually whitelisted the domain.
![IMG_20230801_175943_828.jpg](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/11913223/fe9d4539-3950-4c42-91b7-a6589e97458c)

**Comment by jellizaveta** [comment]
Fixed, will be available with the new update within 24 hours
