### ISSUE TITLE
Adguard DNS issue

### ISSUE THREAD

**Issue by chiragsutariyagithub** [AdguardTeam/AdGuardSDNSFilter#1441]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### What DNS filters do you have enabled?

Adguard DNS ip

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Add your comment and screenshots

1

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
What is wrong?
