### ISSUE TITLE
worldremit app

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardSDNSFilter#1443]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

AdGuard Home v0.107.36

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://8.8.8.8/dns-query
https://dns.nextdns.io/

### What DNS filters do you have enabled?

https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
https://big.oisd.nl/

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed analytics or tracker

### Where did you encounter the problem?

https://www.worldremit.com/en

### Add your comment and screenshots

Steps to reproduce:

1. Install world remit app https://apps.apple.com/gb/app/worldremit-money-transfer/id875855935
2. Open world remit app for first time
3. You should see DNS requests for `sdk.fra-01.braze.eu` in AdGuard Home logs

Note: It doesn't connect to Braze after you tap on reject all in GDPR prompt.

You already have `||iad-*.braze.com^` filter in DNS filter list. So just need to add their EU endpoint, something like ```||fra-*.braze.eu^```

Their US & EU endpoints: https://www.braze.com/docs/user_guide/administrative/access_braze/sdk_endpoints
 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/3c0cf1befaa5f82496b6eb9c480230445c3f5b90
