### ISSUE TITLE
Adguard incorrectly blocks link.sbstck.com, substack's official link redirect site

### ISSUE THREAD

**Issue by FaviFake** [AdguardTeam/AdGuardSDNSFilter#1444]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### What DNS filters do you have enabled?

dns.adgurd.com add my phone's private DNS setting

### What browser or app do you use?

Chrome, Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://link.sbstck.com

### Add your comment and screenshots

1. Adguard incorrectly blocks link.sbstck.com, substack's official link redirect site
2. Screenshots
![Screenshot_20230809_065434_Chrome Canary](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/86537048/6d8829d8-29f2-4ba0-b820-2e9378b0804b)
![Screenshot_20230809_065430_Chrome Canary](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/86537048/aadb90d6-4e49-46c5-afc8-b15e949468ee)
![Screenshot_20230809_065332_Samsung Internet](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/86537048/8b139d06-2531-4d55-a6d0-137b7ceccee9)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Probably fixed

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/8361299/a4dad380-90e9-49af-a142-6354164cea1d)


</details>
