### ISSUE TITLE
webengage.com

### ISSUE THREAD

**Issue by alexx7311** [AdguardTeam/AdGuardSDNSFilter#1446]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

webengage.com

### Add your comment and screenshots

<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/114913601/e96b1192-8c8c-465f-a844-69f63fad08aa)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by SarthakWebEngage** [comment]
Hi @alexx7311, any updates on this issue?

**Comment by hagezi** [comment]
https://slayterdev.github.io/tracker-radar-wiki/domains/webengage.com.html

**Comment by SarthakWebEngage** [comment]
++ @Rahul Bareja ***@***.***> @Aditya Sawant
***@***.***> @Sanjay Mishra
***@***.***> @Shahrukh
Imam ***@***.***>

**Comment by SarthakWebEngage** [comment]
Hey Adguard team,
Can you help me with the details of the link you've shared?
Also, any updates on the unblocking?
