### ISSUE TITLE
iOS Updates Blocked

### ISSUE THREAD

**Issue by MinimalMule** [AdguardTeam/AdGuardSDNSFilter#1447]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

AdGuard Home v0.107.36

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://dns.cloudflare.com/dns-query
tls://1dot1dot1dot1.cloudflare-dns.com
https://dns.quad9.net/dns-query

### What DNS filters do you have enabled?

AdGuard DNS filter
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
0
11 August 2023 at 06:36

AdAway Default Blocklist
https://adaway.org/hosts.txt
6,542
11 August 2023 at 06:37

Perflyst and Dandelion Sprout's Smart-TV Blocklist
https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt
164
11 August 2023 at 06:37

Peter Lowe's List
https://pgl.yoyo.org/adservers/serverlist.php?hostformat=adblockplus&showintro=1&mimetype=plaintext
3,716
11 August 2023 at 06:37

Dan Pollock's List

### What browser or app do you use?

Safari, Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

iOS Settings App, check for updates returns errors with this blocklist enabled

### Add your comment and screenshots

1. Attempt to search for update produces error on iPhone with blocklist enabled
2. disabling blocklist allowed updates to be found 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Can't reproduce with AdGuard DNS and AdGuard DNS filter.
If it is blocked by one of custom filters - please write to author of corresponding filter.
What is blocked you can check in the query log for a period, when you tried to update system.
