### ISSUE TITLE
||turntonetworks.com^

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#145]
Incorrectly blocked.

As stated by user,

> I’m not sure who this would be addressed. We’re a user generated content company. This is our website: https://www.turntonetworks.com/ <https://www.turntonetworks.com/>. Basically, we supply ratings and reviews, and community questions and answers to our clients. We’re not an advertising company. However our scripts are being blocked by your ad blocker. Is there a process to get whitelisted on your plugin.

The ||turntonetworks.com^ rule is present in SDNS filter.

**Comment by Alex-302** [comment]
I don't see `turntonetworks.com` in any filter.

**Comment by ameshkov** [comment]
Yep, it's not there anymore it seems
