### ISSUE TITLE
fmhy.net

### ISSUE THREAD

**Issue by MIOGMIOG** [AdguardTeam/AdGuardSDNSFilter#1452]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### Version

uBlock Origin 1.51.0

### What DNS filters do you have enabled?

Adguard DNS Filter (uBlock origin reports only adguard dns filter to block the site and disabling this filter fixes the issue)
default uBlock Origin filters
Hagezi pro DNS blocklist

### What browser or app do you use?

Firefox

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://fmhy.net/

### Add your comment and screenshots

1. It's an official Free Media Heck Yeah (FMHY) page with no malware or malicious content.
It should not be blocked because this blocklist is not made to block piracy. Also site itself isnt NSFW, but there are some links to NSFW sites.
2. ![image](https://media.discordapp.net/attachments/1041315363184463946/1141726759071535205/IMG_20230817_152232.jpg)

### Privacy

- [X] I agree to follow this condition

**Comment by sabaasa** [comment]
can confirm: site is safe
