### ISSUE TITLE
http://farfalla.noads.biz/latinas.html

### ISSUE THREAD

**Issue by robacorazones** [AdguardTeam/AdGuardSDNSFilter#1458]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### Version

Android

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

http://farfalla.noads.biz/latinas.html I want to download some midi but the side is blocked can you help me please those midi of Pablo milanes

### What DNS filters do you have enabled?

http://farfalla.noads.biz/latinas.html I want to download some midi but the side is blocked can you help me please those midi of Pablo milanes

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

http://farfalla.noads.biz/latinas.html I want to download some midi but the side is blocked can you help me please those midi of Pablo milanes

### Add your comment and screenshots

http://farfalla.noads.biz/latinas.html I want to download some midi but the side is blocked can you help me please those midi of Pablo milanes

### Privacy

- [X] I agree to follow this condition

**Comment by robacorazones** [comment]
Can you get those midi for me

**Comment by Alex-302** [comment]
@robacorazones No. It's dead.

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/8361299/c8ae5123-851b-42a6-92d6-8ff7ac39ff76)
