### ISSUE TITLE
Open block website 

### ISSUE THREAD

**Issue by Pujoart** [AdguardTeam/AdGuardSDNSFilter#1459]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS, AdGuard private DNS, AdGuard Home

### What DNS filters do you have enabled?

dns.adguard.com

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://customercare.abhimata.co.id

### Add your comment and screenshots

website customercare.abhimata.co.id for our customer ticketing application, please unblock it
![Screenshot_2023-09-01-15-26-06-494_com android chrome](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/143791261/6f01dc3b-28de-423a-ad05-a6750cc989d6)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
https://www.virustotal.com/gui/url/0298f30e20991965b0b4a2b14b39ef244d5a7daf1f4537f03a2ffd4e78dc7db7

It seems it is not incorrect blocking.
