### ISSUE TITLE
Webaite ticketing & file sharing 

### ISSUE THREAD

**Issue by Pujoart** [AdguardTeam/AdGuardSDNSFilter#1463]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

dns.adguard.com

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed analytics or tracker

### Where did you encounter the problem?

https://customercare.abhimata.co.id

### Add your comment and screenshots

This website is for file sharing and ticketing only for our customers, please unblock it, thank you
[Screenshot_2023-09-04-19-48-12-318_com goyal website2apk](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/143791261/bb23d0c5-128a-4929-9a44-44953833875e)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
https://reports.adguard.com/en/customercare.abhimata.co.id/report.html
not blocked
