### ISSUE TITLE
Please bring chatwork back quickly! It's a big nuisance!

### ISSUE THREAD

**Issue by yonasawa** [AdguardTeam/AdGuardSDNSFilter#1466]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### What DNS filters do you have enabled?

Please bring chatwork back quickly! It's a big nuisance!

### What browser or app do you use?

Safari

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

chatwork

### Add your comment and screenshots

Please bring chatwork back quickly! It's a big nuisance!

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Unblocked. Next time please copy an address.
