### ISSUE TITLE
Incorrect blocking

### ISSUE THREAD

**Issue by HDFLucky** [AdguardTeam/AdGuardSDNSFilter#1468]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

AdGuard v4.1

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

-

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

facebook.com link to you mail.com

### Add your comment and screenshots

I am a long time Youmail customer; they are NOT malware.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
What is broken? We do not block these sites.
