### ISSUE TITLE
t.co

### ISSUE THREAD

**Issue by tyteen4a03** [AdguardTeam/AdGuardSDNSFilter#1470]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard default DNS filter

### What browser or app do you use?

Firefox

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://t.co

### Add your comment and screenshots

t.co is Twitter's URL shortener. The entire domain is being blocked by AsGuard.

### Privacy

- [X] I agree to follow this condition

**Comment by libnumafly** [comment]
AdGuard Home makes blocking too.

**Comment by centunesima** [comment]
Ive got the same problem. 
Twitter links via mobile are blocked and in general t.co domain id detected as not secure.

**Comment by gingerbeardman** [comment]
Seems resolved?

**Comment by libnumafly** [comment]
> Seems resolved?

looks yes.

**Comment by centunesima** [comment]
Yes

Il lun 11 set 2023, 10:59 Kensei Sakai ***@***.***> ha
scritto:
