### ISSUE TITLE
Twitter/X's t.co shortener is blocked

### ISSUE THREAD

**Issue by StarryFinita** [AdguardTeam/AdGuardSDNSFilter#1471]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

t.co

### Add your comment and screenshots

This website is the domain used by Twitter/X to shorten all outbound links for analytics tracking.

This block is not only a false positive, it also breaks pretty much every single outbound link leading out of Twitter/X.

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/69710618/634a293e-6eb5-4f49-a8e2-a7b4ed453d02)

### Privacy

- [X] I agree to follow this condition

**Comment by libnumafly** [comment]
dup #1470 .

**Comment by gingerbeardman** [comment]
Seems resolved?

**Comment by StarryFinita** [comment]
> Seems resolved?

Can confirm.

**Comment by StarryFinita** [comment]
> Seems resolved?

Can confirm.
