### ISSUE TITLE
incorrect blocking https://discuss.ardupilot.org/

### ISSUE THREAD

**Issue by khancyr** [AdguardTeam/AdGuardSDNSFilter#1472]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

Adguard Home v0.107.36

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://dns.adguard-dns.com/dns-query
tls://dns.adguard-dns.com
1.1.1.1
https://dns.cloudflare.com/dns-query
tls://1dot1dot1dot1.cloudflare-dns.com
https://dns10.quad9.net/dns-query

### What DNS filters do you have enabled?

https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_32.txt

https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_16_French/filter.txt

https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_4_Social/filter.txt
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_11_Mobile/filter.txt
https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_3_Spyware/filter.txt
https://easylist.to/easylist/easylist.txt
https://easylist.to/easylist/easyprivacy.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_23.txt
https://github.com/AdguardTeam/AdguardFilters/blob/master/FrenchFilter/sections/specific.txt
https://github.com/AdguardTeam/AdguardFilters/blob/master/FrenchFilter/sections/general_extensions.txt

### What browser or app do you use?

Firefox

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://discuss.ardupilot.org/

### Add your comment and screenshots

Cannot access https://discuss.ardupilot.org/ since today12/09/2023 anymore

![Screenshot_2023-09-12-00-58-37-02_3aea4af51f236e4932235fdada7d1643](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/705341/1455af92-0302-41b3-ab9d-895cd942e276)
![Screenshot_2023-09-12-00-58-48-49_3aea4af51f236e4932235fdada7d1643](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/705341/0da56bf3-c923-4320-934a-2d908466b154)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reproduced. Maybe false positive
