### ISSUE TITLE
Request to unblock localhost.run

### ISSUE THREAD

**Issue by zYxDevs** [AdguardTeam/AdGuardSDNSFilter#1476]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard DNS Filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed analytics or tracker

### Where did you encounter the problem?

https://localhost.run

### Add your comment and screenshots

1. Localhost.run is only tunneling service that Online apps on vps with their subdomain.
2. Localhost.run doesnt contain any ads or pornographic content.

<details>

![Screenshot_20230918-095302_Chrome](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/45356875/daed3e92-ad4e-4b96-a9be-8df802f88759)

</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Unblocked. This change will be applied to anti-phishing during few hours.
