### ISSUE TITLE
https://m.netflixmirror.com/home

### ISSUE THREAD

**Issue by iminamoto** [AdguardTeam/AdGuardSDNSFilter#1479]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Adguard dns

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Add your comment and screenshots

![Screenshot_20230922-060614](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/85867378/eb6cafef-57e1-4084-bf78-641e9057020c)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It is dead
![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/8361299/b481ec91-04a1-4374-87ec-1be7df72e76f)
