### ISSUE TITLE
monstertv.se

### ISSUE THREAD

**Issue by JkJ076** [AdguardTeam/AdGuardSDNSFilter#1486]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

DNS on my phone - dns.adguard.com 

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

Your DNS.. dns.adguard.com

### What DNS filters do you have enabled?

None

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.monstertv.se/

### Add your comment and screenshots

![Screenshot_20230927_051435_Chrome](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/49118118/d58d9272-0888-4449-a4ab-3963c3b4fc08)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi
Not sure
https://www.virustotal.com/gui/url/a371da66df6d8ca27f67247dad9a316dc877806e698158fc11d92720e8c16081
https://urlhaus.abuse.ch/url/2714087/
Let's wait for removing from another blacklists.

**Comment by hagezi** [comment]
```
Secure DNS:
 - CleanBrowsing   BLOCKED
 - Cloudflare      BLOCKED
 - CONTROLD.TIF    BLOCKED
 - DNS0.eu         BLOCKED
 - DNS0.eu.ZERO    BLOCKED
 - NextDNS.TIF_AI  BLOCKED
 - NRD.DGA.IDN     OK
 - OpenDNS         OK
 - Quad9           BLOCKED
 - SafeDNS         OK
 - UltraDNS        BLOCKED
```

**Comment by Alex-302** [comment]
@hagezi 
> - AdGuardDNS      OK

Our DNS block it.
