### ISSUE TITLE
bsc-dataseed1.binance.org

### ISSUE THREAD

**Issue by Stardusstt** [AdguardTeam/AdGuardSDNSFilter#1488]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

 v0.107.38

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

1.1.1.1

### What DNS filters do you have enabled?

AdGuard DNS filter
[https://adguardteam.github.io/Ho](https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt)

### What browser or app do you use?

Chrome, Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

bsc-dataseed1.binance.org

### Add your comment and screenshots

<img width="611" alt="image" src="https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/40061990/1e41e639-3530-4731-9985-afea117ed85c">

cause MetaMask failed to load balance of tokens.(e.g. usdt on bnb)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
What is broken and how to reproduce?

**Comment by Stardusstt** [comment]
problem
---
![1](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/40061990/856de03b-dff3-4e53-a050-25b1f12f8217)
![2](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/40061990/81c6caf4-f18f-4997-bc20-47508c097434)

reproduce
---
add AdGuard DNS filter in DNS blocklists

fix
---
use Custom filtering rules
> @@||bsc-dataseed1.binance.org^$important

**Comment by Stardusstt** [comment]
MetaMask

**Comment by Alex-302** [comment]
Fixed in Easylist (one of the sources of our DNS filter).
