### ISSUE TITLE
Site blocked and shouldn't

### ISSUE THREAD

**Issue by Ohlyver** [AdguardTeam/AdGuardSDNSFilter#1492]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Just the DNS address added to the network custom DNS in my phone settings

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://bafybeifllzsk35d5skjxjh3wm24cu3ngevtcxc3xstxudcncm6wer6q3y4.ipfs.w3s.link/

### Add your comment and screenshots

Website is safe and only a repo for some firmwares. Adguard is blocking it as a malicious or unsafe website.

### Privacy

- [X] I agree to follow this condition

**Comment by Aniketsin607** [comment]
H

**Comment by Alex-302** [comment]
Fixed.

**Comment by Ohlyver** [comment]
Still blocked on my end ...

________________________________

**Comment by Alex-302** [comment]
Tried again. Please check after few hours.
