### ISSUE TITLE
gs.statcounter.com website is broken when AdGuard DNS is used

### ISSUE THREAD

**Issue by dftf-stu** [AdguardTeam/AdGuardSDNSFilter#1499]
### Platform

Windows

### Protocol

DNS-over-HTTPS

### Do you use AdGuard app?

No I don't

### Your configuration

**Laptop**
OS: Windows 10 Home 22H2 (64-bit) Build 19045.3448
Microsoft Edge: 117.0.2045.60 (Official build) (64-bit)
Firefox: 118.0.1 (64-bit)

**Phone**
OS: Android 12 (kernel: 4.9.292)
Brave: 1.58.137
Chrome: 117.0.5938.153
Firefox: 118.1.1
Opera: 77.4.4095.74896
Vivaldi: 6.2.3110.143

### Traceroute to AdGuard DNS

Not sure if I'd want to provide this publicly, sorry!

If a developer requires it, happy to e-mail it privately -- though I'm pretty-sure you could replicate this internally easily!

### Issue Details

Steps to reproduce:

**In Microsoft Edge (on Windows)**
1. Click the "..." to bring-up the menu, then go to ⚙Settings
2. In the "Search settings" box, type **DNS**
3. Under "Use secure DNS to specify how to lookup the network address for websites", click "Choose a service provider"
4. Type **https://dns.adguard-dns.com/dns-query** into the box below
5. Fully-close Microsoft Edge

**In Firefox (on Windows)**
1. Go to the hamburger-menu (the three-lines) then Settings
2. Type **DNS** into the "Find in settings" search-box
3. Choose "Max Protection"
4. Under "Choose provider", change the dropdown to "Custom"
5. Type **https://dns.adguard-dns.com/dns-query** into the box below
6. Fully-close Firefox

**In Google Chrome (on Android)**
1. Tap the three-dots (top-right) then tap ⚙Settings at the bottom of the menu
2. Tap "Privacy and Security"
3. Tap "Use secure DNS"
4. Make sure "Use secure DNS" is ON
5. Then tap "Choose another provider"
6. Tap the down-arrow, then choose "Customised"
7. Above the line that appears, type **https://dns.adguard-dns.com/dns-query**
8. Tap the back-arrow ⬅ in the top-left three times to return to the webpage you were last on

**Then, in any browser:**

Now visit [https://gs.statcounter.com/os-market-share](https://gs.statcounter.com/os-market-share) and you should notice that the site renders in a text-only format

(NOTE: if you don't, you may need to clear your cookies or cache if you've visited that site in the past)

Then change your DNS back and you should notice the site now loads correctly again
(again, you may need to clear your cookies and cache if it is still broken)

### Expected Behavior

The site should load correctly when AdGuard DNS is used, as it does with other DNS providers

### Actual Behavior

The site loads in a text-only style format, with no working charts or graphs (see screenshot)

### Screenshots

**Microsoft Edge** (on Windows 10):

In this image, the top two screens show AdGuard DNS being used; the bottom two show Google DNS being used:

![AdGuard-DNS-MicrosoftEdge-ON](https://github.com/AdguardTeam/AdGuardDNS/assets/83965343/b7331442-c3b6-4edc-b481-7889d46a86dd)

**Firefox** (on Windows 10):

Again, the top two screens are when AdGuard DNS is being used; the bottom two are when NextDNS is being used:

![AdGuard-DNS-Firefox](https://github.com/AdguardTeam/AdGuardDNS/assets/83965343/d55b2032-9391-4a1c-8636-514d84589bf7)

**Google Chrome** (on Android):

![AdGuard-DNS-ChromeAndroid](https://github.com/AdguardTeam/AdGuardDNS/assets/83965343/2c729779-ce89-4019-ae42-dfc7a8afd838)

### Additional Information

This issue occurs in browsers on both my Windows PC, and my Android phone

Setting the DNS service in any-browser to use AdGuard DNS causes the gs.statcounter.com site to break

**Comment by dftf-stu** [comment]
Hi @ameshkov: I logged this ticket originally on the "Issues" page of the "[AdGuardDNS](https://github.com/AdguardTeam/AdGuardDNS/issues)" GitHub, as I asked one of your team (on the "AdguardBrowserExtension" GitHub) for advice on where to log issues with the Public DNS service, and they said there.

(The original URL of my ticket there was: https://github.com/AdguardTeam/AdGuardDNS/issues/676 )

As you moved it without providing any update, I assumed the ticket had been deleted!  May I suggest in future after moving a ticket to a different GitHub repository to leave a comment so that an e-mail gets sent and the person can then find their ticket again easily?

Thank you

**Comment by Alex-302** [comment]
@dftf-stu Will be fixed in the PR.
