### ISSUE TITLE
Please unblock da.gd

### ISSUE THREAD

**Issue by relrod** [AdguardTeam/AdGuardSDNSFilter#1510]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

I'm honestly unsure how to answer this - I am on public hotel wifi and they seem to have some kind of AdGuard setup that is blocking the site.

### What browser or app do you use?

Firefox, Safari

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://da.gd/ and http://i.da.gd/

### Add your comment and screenshots

<details>
<img width="780" alt="image" src="https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/43930/ffd1165b-d797-40f0-9352-33aa57100713">
</details>

I am unable to access (i.)da.gd from hotel wifi due to adguard blocking it.

da.gd is an [open source](https://github.com/dagd/dagd) URL shortener and simple information tool.

While it does occasionally get used by scammers, we (the da.gd team) have a very active volunteer team who handles reports of such abuse very quickly. We also have automation and blacklists in place to try to catch these issues early on. We take abuse seriously.

As such, I'd like to formally request that da.gd be whitelisted in adguard to prevent it from being blocked in the future. Any abuse reports can be reported to abuse@da.gd and we will take down the bad redirects immediately.

### Privacy

- [X] I agree to follow this condition

**Comment by Aderullyakbar** [comment]
Okey

Pada Sen, 23 Okt 2023 21.42, Alex ***@***.***> menulis:
