### ISSUE TITLE
Incorrectly parental blocked matthew-is.gay

### ISSUE THREAD

**Issue by nexy7574** [AdguardTeam/AdGuardSDNSFilter#1513]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS, AdGuard Home

### Version

v0.107.40

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://dns.cloudflare.com/dns-query
https://dns.nextdns.io
https://anycast.dns.nextdns.io
https://dns.google/dns-query
https://dns.adguard-dns.com/dns-query
quic://dns.adguard-dns.com
https://doh.opendns.com/dns-query
https://dns.quad9.net/dns-query
https://doh.mullvad.net/dns-query
https://dns.nexy7574.co.uk/dns-query

### What DNS filters do you have enabled?

* https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
* https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
* https://adguardteam.github.io/HostlistsRegistry/assets/filter_12.txt
* https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt
* https://adguardteam.github.io/HostlistsRegistry/assets/filter_33.txt
* https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt
* https://adguardteam.github.io/HostlistsRegistry/assets/filter_9.txt
* https://adguardteam.github.io/HostlistsRegistry/assets/filter_10.txt
* https://adguardteam.github.io/HostlistsRegistry/assets/filter_8.txt

### What browser or app do you use?

Firefox, Other app

### Which device type do you use?

Other device

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://matthew-is.gay

### Add your comment and screenshots

This website is not an adult website, it is very safe for kids; it is quite literally a cube that spins. How did this even get flagged?

(I own this domain and the website its running, if you have any questions feel free to contact me. There has never been and never will be any NSFW content on this domain, it is an inside joke, hence the random badly rendered spinning cube.)

<details>
<summary>The website</summary>
![out1](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/53234499/f7b8cd30-989e-4a8e-ae2a-1e200499f08d)
</details>
<details>
<summary>The block page</summary>
![out2](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/53234499/35da225f-e6d1-46a3-b092-9761e1c48b09)
</details>
<details>
<summary>Query Log</summary>
![out3](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/53234499/ffa4353b-1f52-43fc-88aa-586e962d5431)
</details>
<details>
<summary>The filter must've been updated recently</summary>
![out4](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/53234499/fb7a136b-3b35-4997-ada2-c613eecf118f)
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
> How did this even get flagged?

Automatically. We have few sources of data.

Fixed. Please check after few hours.
