### ISSUE TITLE
Its not a NSFW website

### ISSUE THREAD

**Issue by HappyTea1** [AdguardTeam/AdGuardSDNSFilter#1515]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### What DNS filters do you have enabled?

I don't know

### What browser or app do you use?

Opera

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed analytics or tracker

### Where did you encounter the problem?

https://newgrounds.com

### Add your comment and screenshots

This sucks.
I was only trying to get some music. 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
You can use the default AdGuard DNS, without family protection.
