### ISSUE TITLE
When a website is blocked by DNS, it is not clear that this is so

### ISSUE THREAD

**Issue by rotu** [AdguardTeam/AdGuardSDNSFilter#1516]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

Adguard Home 7.15.1 (4386) (build 4386, CL 1.12.87)

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://dns.adguard-dns.com

### What DNS filters do you have enabled?

N/A

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://discuss.ardupilot.org/

### Add your comment and screenshots

When a website is blocked by Adguard DNS, it is not clear that it is blocked by the DNS. Adguard DNS blocked a page by redirecting it to https://94.140.14.33/

The text of the page says "This web page has been reported as a malware page and has been blocked based on your security preferences."

This misled me to think that it was blocked by the "Browsing Security" module of AdGuard blocking the site rather than the "DNS Protection" module. The error page should explicitly mention "Adguard DNS" and should possibly return an http status code other than 200 (400 Bad Request or 406 Not Acceptable, maybe?)

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/119948/2eb19430-6dbc-43f4-957d-6078daee388a)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It seems already unblocked.

**Comment by rotu** [comment]
@Alex-302 please reopen - you’ve misunderstood the issue. The problem is not with this one particular domain, but that, when *any* website is blocked, by AdGuard DNS, the page makes that fact unclear.

In particular if I need to access a blocked page, there’s no indication here how to *unblock* it with a narrowly tailored exception.

**Comment by Alex-302** [comment]
Please check after few hours.

**Comment by rotu** [comment]
@Alex-302 What am I checking? The site appears to have the same non-specific error message:

> This web page has been reported as a malware page and has been blocked based on your security preferences.

<img width="1219" alt="image" src="https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/119948/4654e6b8-acb9-46a8-8539-6059e8417417">

**Comment by Alex-302** [comment]
@rotu Damn) It must be unblocked. 
Please show `nslookup` / `dig` output it it is still blocked. Also try to restart the app, maybe it cached safebrowsing status.
