### ISSUE TITLE
Lowes.com is being blocked by the family filter

### ISSUE THREAD

**Issue by wqbang** [AdguardTeam/AdGuardSDNSFilter#1521]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Public Adguard Family DNS

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.lowes.com

### Add your comment and screenshots

www.lowes.com is being blocked by the Adguard Family Filter in error.  Lowes is a major US national home improvement box store.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Cannot reproduce. Probably already fixed.
