### ISSUE TITLE
Blocking https://webmail.apps.mil/mail/inbox incorrectly

### ISSUE THREAD

**Issue by adavis-soliel** [AdguardTeam/AdGuardSDNSFilter#1522]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://webmail.apps.mil/mail/inbox

### What DNS filters do you have enabled?

https://webmail.apps.mil/mail/inbox

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://webmail.apps.mil/mail/inbox

### Add your comment and screenshots

https://webmail.apps.mil/mail/inbox isn't working

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Hello. AdGuard DNS does not block `webmail.apps.mil` . Perhaps some other resource used to load the page is blocked. Could you provide a test account to check or if you are using DNS with an application that has DNS filtering log - send screenshots of the log ?
