### ISSUE TITLE
Unblock ift.tt

### ISSUE THREAD

**Issue by MDXDave** [AdguardTeam/AdGuardSDNSFilter#1524]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Public DNS

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://ift.tt

### Add your comment and screenshots

<details>

![Screenshot_20231102_102621_Brave](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/6099976/07f14988-b2a8-4293-9cec-9995ce0a19f5)

</details>

<details>
URL shortener
</details>

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@MDXDave Hello, could you please send an example where this domain is used?

**Comment by MDXDave** [comment]
For example: https://twitter.com/CaschysBlog/status/1720064331994276337

**Comment by jellizaveta** [comment]
Removed the phishing category for this domain, update will be available within 24 hours
