### ISSUE TITLE
Web blocked

### ISSUE THREAD

**Issue by agranapz** [AdguardTeam/AdGuardSDNSFilter#1525]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### Version

AdGuard for Windows, 7.15.1 (4386) (build 4386, CL 1.12.87)

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://d.adguard-dns.com/dns-query/xxxxxxxx - Private DNS

### What DNS filters do you have enabled?

https://big.oisd.nl

### What browser or app do you use?

Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://octopath.gg/

### Add your comment and screenshots

![Captura de pantalla 2023-11-03 123205](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/16371257/b8b05eaf-4f22-42ec-adb9-c87c6c745d94)

![Captura de pantalla 2023-11-03 123247](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/16371257/99d99a6e-b243-4aa6-bf11-0ec3ed55e9d1)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Probably fixed now.

**Comment by agranapz** [comment]
The same warning is displayed right now

**Comment by Alex-302** [comment]
@agranapz Do you use ТВК blocking option?
![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/8361299/411d902f-2ad3-41d8-b5c6-7948a33b98a0)

**Comment by agranapz** [comment]
@Alex-302 solved! Thanks
