### ISSUE TITLE
n watches forum “Orologi e Passioni” marked as NTFS

### ISSUE THREAD

**Issue by ilGimmy** [AdguardTeam/AdGuardSDNSFilter#1528]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

94.140.14.15
94.140.15.16

### What DNS filters do you have enabled?

AdGuard Family Filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://orologi.forumfree.it/

### Add your comment and screenshots

I’m using AdGuard Family DNS on my phone using DNS Override application

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Probably fixed. Not reproduced.
