### ISSUE TITLE
Goodreads blocked in public DNS 

### ISSUE THREAD

**Issue by pauliusbaranauskas** [AdguardTeam/AdGuardSDNSFilter#1529]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Family protection servers

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.goodreads.com/

### Add your comment and screenshots

Family protection servers are blocking goodreads.com. I also get the same error on Android mobile device.
![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/22965073/43f6d1d9-c190-46e9-98d0-26143b88f253)

### Privacy

- [X] I agree to follow this condition

**Comment by pauliusbaranauskas** [comment]
Not blocked anymore. Can access it today.
Keeping open in case you need to investigate

**Comment by Alex-302** [comment]
Yep, it was fixed 06.11
