### ISSUE TITLE
Odido.nl blocked by new domains security filter

### ISSUE THREAD

**Issue by Okselfris** [AdguardTeam/AdGuardSDNSFilter#1530]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

Adguard private dns https://**dguard-dns.com/dns-query

### What DNS filters do you have enabled?

Security, block newly registered domains

### What browser or app do you use?

Safari

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://odido.nl

### Add your comment and screenshots

Domain blocked by Newly registered domains while it is older than 30 days.

![CleanShot 2023-11-06 at 20 01 33@2x](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/95424415/462c0d8d-e3c3-46d7-af5c-b75cc650caee)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. Reported to the list maintainers.
You can add `@@||odido.nl^|` to user rules.

**Comment by Alex-302** [comment]
Also will fixed on our end. The fix will be applied in 2 hours.

**Comment by Okselfris** [comment]
Thanks! Issue solved
