### ISSUE TITLE
Debian repository blocked by parenthal control

### ISSUE THREAD

**Issue by cizordj** [AdguardTeam/AdGuardSDNSFilter#1531]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### What DNS filters do you have enabled?

I am using two blocklists in the private DNS server.

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts

and I am blocking Roblox through Adguard's dashboard.

### What browser or app do you use?

Other app

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

http://alcateia.ufscar.br/debian/dists/sid/InRelease

### Add your comment and screenshots

![2023-11-07_07-28](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/32869222/81b83614-79dd-4d11-8136-15d92fb2a351)

### Privacy

- [X] I agree to follow this condition

**Comment by cizordj** [comment]
Weird because now it's working again. Anyways, problem solved.

**Comment by Alex-302** [comment]
Maybe someone else also reported.
