### ISSUE TITLE
Неправильная блокировка

### ISSUE THREAD

**Issue by john22255** [AdguardTeam/AdGuardSDNSFilter#1533]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### Version

Не устанавливал Adguard

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

Не устанавливал Adguard

### What DNS filters do you have enabled?

Не устанавливал Adguard

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

http://project5875018.tilda.ws/

### Add your comment and screenshots

Не устанавливал программу adguard вообще, тем не менее. Срабатывает , не дает попасть на мой безобидный ссйт визитку http://project5875018.tilda.ws/

Не знаю откуда взялся на телефоне, в иконках установленых приложений его нет.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Мы этот сайт не блокируем. Точно AdGuard причастен к этому?

**Comment by john22255** [comment]
Да, разобрался. Стоял Ваш Dns в настойках телефона

ср, 8 нояб. 2023 г., 16:09 Alex ***@***.***>:

**Comment by Alex-302** [comment]
Мистика. У меня с нашими DNS он открывается.
