### ISSUE TITLE
blocking mail.aol.com

### ISSUE THREAD

**Issue by jeffn2001** [AdguardTeam/AdGuardSDNSFilter#1537]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Family protection servers
AdGuard DNS will block ads, trackers, adult content, and enable Safe Search and Safe Mode, where possible.
IPv4:
94.140.14.15
94.140.15.16
IPv6:
2a10:50c0::bad1:ff
2a10:50c0::bad2:ff

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://mail.aol.com

### Add your comment and screenshots

mail.aol.com shouldn't be blocked by the Family protection public DNS servers.
(or really aol.com?)

### Privacy

- [X] I agree to follow this condition

**Comment by jeffn2001** [comment]
Screenshot of issue
https://imgur.com/a/f4lXlpF

**Comment by Alex-302** [comment]
Not reproduced at the moment.
