### ISSUE TITLE
jorgesoporteit.rf.gd is a website true

### ISSUE THREAD

**Issue by jorgesoporteit** [AdguardTeam/AdGuardSDNSFilter#1538]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

94.140.14.15

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

DNS Public

### What DNS filters do you have enabled?

94.140.14.15
94.140.15.16

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

http://jorgesoporteit.rf.gd

### Add your comment and screenshots

http://jorgesoporteit.rf.gd/ is a website true

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/117950251/b1de1988-405e-4815-bc52-3d3282cf3045)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not preproduced. Maybe fixed.
