### ISSUE TITLE
find-a.jp - the image is blocked

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdGuardSDNSFilter#1540]
https://github.com/AdguardTeam/AdguardFilters/issues/166048#issuecomment-1810692889
### Issue URL (Incorrect Blocking)
 [https://find-a.jp/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Ffind-a.jp%2F)
### Comment
> ||seal.globalsign.com^
> 
> Sorry for reposting, but the "GMO GlobalSign Secure" icon at the bottom of the site is broken when the above rule in the AdGuard DNS filter is enabled.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://cdn.adguard.info/sitereports/hofix662cgg8kwoggo4gocwko84wk04o0crdpgacgg.png?nc=1)
</details>
<details>
  <summary>Screenshot 1 with AdGuard disabled</summary>

  ![Screenshot 1](https://cdn.adguard.info/sitereports/n21dhr929hc0cwsgkwgwkcow4c04kwkm8fpijdbp4g.png?nc=1)
</details>

### System configuration

Information | Value
--- | ---
AdGuard product: | AdGuard for Android v4.2.118
System version: | Android 14
Browser: | Chrome
License type: | paid
AdGuard mode: | VPN
HTTPS filtering: | enabled
Stealth mode options: | Send Do-Not-Track header, <br>Hide your Referrer from third-parties, <br>Hide your User-Agent, <br>Remove X-Client-Data header from HTTP requests, <br>Self-destructing third-party cookies (180), <br>Self-destructing first-party cookies (4320)
DNS filtering: | server: `https://dns.google/dns-query`<br>filters: `https://filters.adtidy.org/android/filters/15_optimized.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Cookie Notices, <br/>AdGuard Popups, <br/>AdGuard Mobile App Banners, <br/>AdGuard Other Annoyances, <br/>AdGuard Widgets<br/><br/><b>Language-specific:</b><br/>AdGuard Japanese
Custom filters: | https://raw.githubusercontent.com/Yuki2718/adblock2/main/japanese/jpf-plus.txt
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js<br>https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js

_Originally posted by @adguard-bot in https://github.com/AdguardTeam/AdguardFilters/issues/166048#issuecomment-1810692889_

**Comment by Alex-302** [comment]
It seems can be unblocked.

**Comment by Yuki2718** [comment]
Probably these too:
```
! Seals, Websecurity, Protection etc. Unnecessary third-party scripts
||antillephone.com^
||beyondsecurity.com^
||guarantee-cdn.com^
||nsg.symantec.com^
||privacy-policy.truste.com^
||scanverify.com^
||seal.digicert.com^
||seal.godaddy.com^
||seal.networksolutions.com^
||seal.qualys.com^
||secure.trust-guard.com^
||securitymetrics.com^
||shield.sitelock.com^
||shopperapproved.com^
||siteintercept.allegiancetech.com^
||smart-widget-assets.ekomiapps.de^
||trusted-web-seal.cybertrust.ne.jp^
||verify.authorize.net^
||verify.safesigned.com^
||websecurity.norton.com^
||widgets.trustedshops.com^
```

**Comment by Alex-302** [comment]
@Yuki2718 They are from Easyprivacy. I don't know why they are blocked.
