### ISSUE TITLE
diceware.dmuth.org is marked as adult

### ISSUE THREAD

**Issue by ossandcad** [AdguardTeam/AdGuardSDNSFilter#1542]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

v0.107.41

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

tls://1dot1dot1dot1.cloudflare-dns.com

### What DNS filters do you have enabled?

Parental control web service

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://diceware.dmuth.org/

### Add your comment and screenshots

<img width="414" alt="image" src="https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/138946/18bec2e3-df29-4436-b105-9772e6a93188">

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It seems fixed.
