### ISSUE TITLE
Nuance PowerShare incorrect blocking as malware

### ISSUE THREAD

**Issue by FortWIT** [AdguardTeam/AdGuardSDNSFilter#1544]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

94.140.14.15
94.140.15.16

### What DNS filters do you have enabled?

94.140.14.15
94.140.15.16

### What browser or app do you use?

Chrome, Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www1.nuancepowershare.com/

### Add your comment and screenshots

This website is being incorrectly blocked and marked as containing malware when it is a legitimate business use website.
![Nuance-PowerShare-Block](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/46198714/5ff23aa9-3115-4595-b35f-589f6cf4b2d4)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It seems already fixed.
