### ISSUE TITLE
api.thetvdb.com is incorrectly blocked

### ISSUE THREAD

**Issue by sycdan** [AdguardTeam/AdGuardSDNSFilter#1546]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

N/A

### What DNS filters do you have enabled?

N/A

### What browser or app do you use?

Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://api.thetvdb.com/login

### Add your comment and screenshots

I don't have a screenshot that would be useful to you. On my HTPC, which uses the family-safe public DNS (94.140.14.15, 94.140.15.16), AdGuard blocks https://api.thetvdb.com/login which means Kodi is not able to pull information for any shows.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It seems solved by our support.
