### ISSUE TITLE
noticias.uol.com.br

### ISSUE THREAD

**Issue by jakecharlie** [AdguardTeam/AdGuardSDNSFilter#1547]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

Adguard DNS Filter

### What browser or app do you use?

Firefox, Chrome, Microsoft Edge, Opera

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://noticias.uol.com.br/videos/2023/11/17/josias-lula-nao-pode-permitir-que-posicao-dele-se-confunda-com-a-da-esquerda.htm

### Add your comment and screenshots

Hello

I noticed that when I use Adguard public DNS, no videos from the Brazilian website Uol.com.br are being played. They keep loading the video forever and never start it. Maybe there is a domain inside Adguard DNS filter list that is being blocked incorrectly and preventing the video stream from playing.

On the other hand, if I disable Adguard public DNS and I use another DNS with a list, like Hagezi's DNS Pro Plus or Hagezi's DNS Ultimate, for example, all Uol.com.br videos play correctly.

Example:
https://noticias.uol.com.br/videos/2023/11/17/josias-lula-nao-pode-permitir-que-posicao-dele-se-confunda-com-a-da-esquerda.htm

https://noticias.uol.com.br/videos/2023/11/13/aviao-com-brasileiros-resgatados-da-faixa-de-gaza-chega-a-brasilia.htm

Thank you

### Privacy

- [X] I agree to follow this condition

**Comment by hagezi** [comment]
`tm.jsuol.com.br` must be unblocked so that the videos can be played.
