### ISSUE TITLE
www.instantreward.site

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdGuardSDNSFilter#155]
Hello first I want to ask where is the right place to report Ad domains related to the AdGuardHome SDNS filter. (pls give me a link)

Second I want to report an advertising domain, I use AGHome with SimplifiedDNS filter and AdAway filter on my RaspberryPi.

While browsing i get an Popup with "you won... million yoogle search request...." I found this domain in the request log of AGH:

www.instantreward.site
||www.instantreward.site^$important (created block rule with AGH)

Pls keep an eye on it
Thank you

AGH v0.99.2
Device Android 8 Smartphone
Browser Opera mobile

**Comment by Alex-302** [comment]
Hi. Better report to filters repository.
https://github.com/AdguardTeam/AdguardFilters/issues
I will move this issue and block this domain.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #43158](https://github.com/AdguardTeam/AdguardFilters/issues/43158) via [**ZenHub**](https://www.zenhub.com/)
