### ISSUE TITLE
adservice.google.com classified as Adult

### ISSUE THREAD

**Issue by lnlyssg** [AdguardTeam/AdGuardSDNSFilter#1553]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### What DNS filters do you have enabled?

Parental control web service

### What browser or app do you use?

Safari

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Add your comment and screenshots

<img width="808" alt="Screenshot 2023-11-22 at 14 08 11" src="https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/10902647/ae18760e-1d81-4232-9c36-cd41ec9be275">

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Unblocked.
