### ISSUE TITLE
Hope to get added some rules to the filter

### ISSUE THREAD

**Issue by Calvin328** [AdguardTeam/AdGuardSDNSFilter#156]
Hope to block this list of domain. The list inside the document is all about ads server and some malware site from china.
Thanks.
[Hosts.txt](https://github.com/AdguardTeam/AdGuardSDNSFilter/files/3787227/Hosts.txt)

**Comment by ameshkov** [comment]
@AdguardTeam/filters-maintainers  take a look plz

**Comment by Alex-302** [comment]
as I see, the most of domains cannot be resolved by DNS

**Comment by Alex-302** [comment]
https://gist.github.com/Alex-302/b7f60952bad4f355ba426a34182635f4

**Comment by padizar** [comment]
18+ 
[list.txt](https://github.com/AdguardTeam/AdGuardSDNSFilter/files/3812762/list.txt)

**Comment by slavaleleka** [comment]
@Chinaski1 could you please check it^ out?

**Comment by Alex-302** [comment]
@padizar Porn sites should not be blocked in SDN Filter.

**Comment by Chinaski1** [comment]
@padizar 
I added all these sites to the Adult category.
