### ISSUE TITLE
Website ndis.becomeaprovider.com.au is mistakenly marked as dangerous

### ISSUE THREAD

**Issue by harisrehmankhan** [AdguardTeam/AdGuardSDNSFilter#1568]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

Dns.adguard.com

### What DNS filters do you have enabled?

Dns.adguard.com

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

becomeaprovider.com.au

### Add your comment and screenshots

My websites https://becomeaprovider.com.au & https://ndis.becomeaprovider.com.au was attacked and hacked. Please recheck! The malware files have been removed. Visitors are seeing webpage as unsafe. Please change the status.

Thank you 

![IMG-20231220-WA0102](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/48333511/a0f62a6c-51d7-44e8-83bd-7dc7cb9443ef)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It seems unblocked now.
