### ISSUE TITLE
blocking site

### ISSUE THREAD

**Issue by sh770** [AdguardTeam/AdGuardSDNSFilter#1570]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

7.16.0 (4542) (CL 1.13.115, DL 2.4.37 )

### What DNS filters do you have enabled?

סינון משפחתי

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://katzr.net/2152f1

### Add your comment and screenshots

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/111239198/1ef67c56-7a8a-4374-8dfd-036796bdbf34)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reproduced at the moment.
