### ISSUE TITLE
Unblock Site

### ISSUE THREAD

**Issue by Dishit79** [AdguardTeam/AdGuardSDNSFilter#1571]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

v0.107.43

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://dns10.quad9.net/dns-query

### What DNS filters do you have enabled?

AdGuard DNS filter - https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.wahed.com/

### Add your comment and screenshots

1. The DNS is identifying wahed.com as a NSFW site but it is just a financial institute. 
![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/56460773/dac69cce-8e0f-4363-a287-14173c57d6d4)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Unblocked.
