### ISSUE TITLE
Could the anti-threat file(s) of hostsVN be considered for inclusion?

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardSDNSFilter#1575]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

I looked around on hostsVN's repo at https://github.com/bigdargon/hostsVN/tree/master some minutes ago, and came across https://github.com/bigdargon/hostsVN/blob/master/extensions/threat/filter-VN.txt

Seeing as the repo's anti-ad file has been included in AdGuard DNS Filter for 3-4 years by now, I presume the repo's anti-malware file would be suited to be added to DNS Filter's lineup too.

### Proposed solution

Add either https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/threat/filter.txt or https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/threat/filter-VN.txt to https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/configuration.json . There's not a whole lot of differences between the two, so I'd say it's a 55:45 call which one to add.

### Additional information

I haven't had the best of years in 2023, and as a result of that I began presuming that an issue report would seem less brash and criticisable than a PR.

The same repo also has an `ip` folder, but I presumed that adding more than 6,000 IPs from that particular folder to AdGuard DNS Filter would likely become a problem.

**Comment by Alex-302** [comment]
> https://raw.githubusercontent.com/bigdargon/hostsVN/master/extensions/threat/filter.txt

is ok.
@jellizaveta please add it to https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/configuration.json as a new section like https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/configuration.json#L296C16-L296C34

**Comment by bigdargon** [comment]
@DandelionSprout Thank you for your suggestion!
