### ISSUE TITLE
The EasyList files in configuration.json lack the corresponding files from the easylist_adult folder

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardSDNSFilter#1577]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

It randomly dawned on me that while https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/configuration.json contains the "adservers" files of the main EasyList folder, it seems the "adservers" files from https://github.com/easylist/easylist/tree/master/easylist_adult are missing from the configuration, presumably by accident. I can only presume it'd make full sense to add those files as well.

### Proposed solution

Presuming https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/configuration.json#L35-L49 is the guideline to follow up on, https://raw.githubusercontent.com/easylist/easylist/master/easylist_adult/adult_adservers.txt and https://raw.githubusercontent.com/easylist/easylist/master/easylist_adult/adult_thirdparty.txt should be added to the configuration.json file.

### Additional information

None of particular relevance. I just figured I should suggest this too since I had already proposed #1575 and figured out I should propose this too while I was on a momentum.

**Comment by Alex-302** [comment]
Hm. I see in https://github.com/easylist/easylist/blob/master/easylist_adult/adult_adservers.txt some sites, which are not ad servers. On DNS level they will be blocked. 
And it's only at first glance, saw some familiar sites:)

```
||runetki.com^$third-party
||vsexshop.ru^$third-party
```

**Comment by Alex-302** [comment]
@jellizaveta Please check https://github.com/easylist/easylist/blob/master/easylist_adult/adult_adservers.txt if there are any "useful" sites.
Then we can include raw versions of
adult_adservers.txt
adult_adservers_popup.txt
and add to `exclusions.txt`
```
||runetki.com^
||vsexshop.ru^
```
and maybe some other sites if you see something (no need to visit each site).
