### ISSUE TITLE
Block Toniebox Tracking

### ISSUE THREAD

**Issue by strausmann** [AdguardTeam/AdGuardSDNSFilter#1579]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

The Toniebox sends every action to the Tonie Cloud. By adding rtnl.bxcl.de this data collection will be prevented. 

### Proposed solution

Add the URL rtnl.bxcl.de to the Blocklist

**Comment by hagezi** [comment]
Details: https://toniebox-reverse-engineering.github.io/docs/wiki/general/protocol-analysis/#rtnlbxclde

**Comment by Alex-302** [comment]
Hi. Added.
Better report missed ads/tracking to https://github.com/AdguardTeam/AdguardFilters Domain rules will be automatically added to DNS filter.

**Comment by strausmann** [comment]
Thank you
