### ISSUE TITLE
Block Brightdata

### ISSUE THREAD

**Issue by r2fo** [AdguardTeam/AdGuardSDNSFilter#1580]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

brightdata.com
brightdata.de
bright-sdk.com
clientsdk.bright-sdk.com
perr.bright-sdk.com

### Proposed solution

Brightdata offers SDK’s for developers to put into their apps. These SDK’s abuse the user’s internet connection and turn it into a proxy. The developer earns money from it.

https://web.archive.org/web/20230601022816/https://old.reddit.com/r/privacy/comments/13wyc0c/bightdatacom_attempting_to_trick_child_into/

**Comment by Alex-302** [comment]
Hi.
Where can we check it?

```
bright-sdk.com
clientsdk.bright-sdk.com
perr.bright-sdk.com
```

in our case `||bright-sdk.com^` will block also subdomains.

**Comment by Alex-302** [comment]
Ok, added
```
||brightdata.com^
||brightdata.de^
||perr.l-agent.me^
||perr.l-err.biz^
||brdtest.com^
||brdtnet.com^
||luminati.io^
```

**Comment by Alex-302** [comment]
Ok.

**Comment by Alex-302** [comment]
@fenopa 

> "no normal users would want to visit it"

I did not say that.
