### ISSUE TITLE
Netease account login domain incorrect blocking

### ISSUE THREAD

**Issue by wzfdgh** [AdguardTeam/AdGuardSDNSFilter#1601]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

AdGuard Home v0.107.43

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

* `Cloudflare 1.1.1.1 DNS over HTTPS`

### What DNS filters do you have enabled?

* `AdGuard DNS filter`: https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt

### What browser or app do you use?

Firefox, Chrome, Microsoft Edge

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://mail.163.com

### Add your comment and screenshots

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/93830081/f83173f3-1b76-4b29-9572-c2e6361fe5a2)
![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/93830081/0fdec741-945f-4956-a986-03b880c61690)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Removed bad rule.
