### ISSUE TITLE
This is school site

### ISSUE THREAD

**Issue by Kaushik2562** [AdguardTeam/AdGuardSDNSFilter#1603]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

Don't know

### What DNS filters do you have enabled?

Don't know 

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

http://sxs-bwn.org/

### Add your comment and screenshots

This st. Xaviers school website

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Unblocked.
