### ISSUE TITLE
DNS rewriting issue

### ISSUE THREAD

**Issue by liuhome11** [AdguardTeam/AdGuardSDNSFilter#1608]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

How can we configure multiple IP addresses to enhance reliability for DNS rewriting, as the current setup only supports a single IP address and raises concerns about a single point of failure?

### Proposed solution

steamcommunity.com
45.114.11.25,118.193.240.37,210.56.51.192

**Comment by Alex-302** [comment]
Hi. You can use few `$dnsrewrite` rules.
