### ISSUE TITLE
AdGuard DNS breaks FlashAir app

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#162]
### Steps to reproduce
1. Use AdGuard DNS via Android Private DNS menu
2. Install the following app: **jp.co.toshiba.android.FlashAir**
3. As reported by user: _App will not connect to camera with DNS on, while being connected to WiFi created by memory card that doesn’t have access to Internet. I am also not able to get on FTP created by that app via browser._

### Expected behavior
App should be able to connect with the user's camera.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default
| How did you setup DNS configuration:| System
| Device model:| unspecified
| Operating system and version:| Android 9

**Comment by Alex-302** [comment]
@akmLaVx cannot check without FlashAir card.
Please ask for bebug log + time stamp.
Also ask to check for blocked requests in the filtering log.

**Comment by akmLaVx** [comment]
User has AdGuard DNS configured as Private DNS without the use of AdGuard app. Will try to get him install the application.

**Comment by akmLaVx** [comment]
No reply from user. Closing this one.
