### ISSUE TITLE
Non NSFW Website Flagged by AdGuard Home

### ISSUE THREAD

**Issue by ef7h** [AdguardTeam/AdGuardSDNSFilter#1620]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

AdGuard Home v0.107.43

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://dns10.quad9.net/dns-query
101.101.101.101
8.8.8.8
1.1.1.1
80.80.80.80
1.0.0.1
9.9.9.9
8.8.4.4
34.83.250.220

### What DNS filters do you have enabled?

AdGuard DNS filter
https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt
61,261
February 2, 2024 at 10:58
AdAway Default Blocklist
https://adguardteam.github.io/HostlistsRegistry/assets/filter_2.txt
6,540
February 2, 2024 at 10:58
Scam Blocklist by DurableNapkin
https://adguardteam.github.io/HostlistsRegistry/assets/filter_10.txt
1,207
February 2, 2024 at 10:58
Phishing Army
https://adguardteam.github.io/HostlistsRegistry/assets/filter_18.txt
167,895
February 2, 2024 at 10:58
Malicious URL Blocklist (URLHaus)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_11.txt
5,890
February 2, 2024 at 10:58
uBlock₀ filters – Badware risks
https://adguardteam.github.io/HostlistsRegistry/assets/filter_50.txt
2,700
February 2, 2024 at 10:58
WindowsSpyBlocker - Hosts spy rules
https://adguardteam.github.io/HostlistsRegistry/assets/filter_23.txt
347
February 2, 2024 at 10:58
Phishing URL Blocklist (PhishTank and OpenPhish)
https://adguardteam.github.io/HostlistsRegistry/assets/filter_30.txt
26,085
February 2, 2024 at 10:58
ShadowWhisperer's Malware List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_42.txt
34,110
February 2, 2024 at 10:58
Stalkerware Indicators List
https://adguardteam.github.io/HostlistsRegistry/assets/filter_31.txt
868
February 2, 2024 at 10:58
The Big List of Hacked Malware Web Sites
https://adguardteam.github.io/HostlistsRegistry/assets/filter_9.txt
13,468
February 2, 2024 at 10:58

#Custom Block

||wifi.h-w.i234.me^
||setn.com^
||www.setn.com^
||router. local^
||1205chh123csbc.baicuoa.com^
||zn728.tdg68.com^
@@||www.newgrounds.com^

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.newgrounds.com/audio/listen/1245665

### Add your comment and screenshots

It is locked by AdGuard Home Parent Control. 
<img width="1440" alt="Screenshot 2024-02-02 at 11 00 42" src="https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/157942818/466956fa-75a6-40e0-99ed-d1f5202f8c91">

### Privacy

- [X] I agree to follow this condition

**Comment by ef7h** [comment]
EDIT: After Unblocking the URL, it works, but the other parts of the website are still broken. Like the Artist URL : <artist>.newgrounds.com does not work normally.

**Comment by Alex-302** [comment]
Removed from DB.
Please check tomorrow.

**Comment by ictechz** [comment]
Hi there, it is still blocked. All of the stuff is up to date and It is still blocked by adguard home.

**Comment by ef7h** [comment]
Hi there, it is still blocked. All of the stuff is up to date and It is still blocked by adguard home.

**Comment by Alex-302** [comment]
Not reproduced at the moment. Applying DNS server filtering changes is not immediate. It may take from several hours to a day.

**Comment by Alex-302** [comment]
Weird. Unblocked again.
