### ISSUE TITLE
Cloudfront Block breaking Strava.com

### ISSUE THREAD

**Issue by solarisfire** [AdguardTeam/AdGuardSDNSFilter#1623]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### Version

 Pi-hole v5.17.3 

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

Google DNS, OpenDNS, and Cloudflare DNS upstream

### What DNS filters do you have enabled?

AdguardDNS.txt

### What browser or app do you use?

Firefox, Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://strava.com

### Add your comment and screenshots

All of these indiscriminate cloudflare blocks (d3nn82uaxijpm6.cloudfront.net in particular) are blocking content on any website that host it's assets on cloudflare (in my case strava.com)

![Screenshot_20240204_185933](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/420952/603fbaf4-3e62-4e20-b760-7222b1f3c131)
![9b729544d0ee36e0](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/420952/273588a5-2335-4bbb-a002-898e4062768d)

### Privacy

- [X] I agree to follow this condition

**Comment by mkasberg** [comment]
I came here to report the same issue. The problematic block is d3nn82uaxijpm6.cloudfront.net. This domain serves JS for strava.com when logged in to Strava.

**Comment by jellizaveta** [comment]
@mkasberg Hello. AdGuard DNS is not blocking this domain at the moment. Do you have only the AdGuard filter enabled, or do you have third-party filters as well? I see that this domain is blocked for example in [CHN: anti-AD filter](https://anti-ad.net/adguard.txt) .

**Comment by solarisfire** [comment]
It seems to be removed from the block list now.

I use this list here:

https://v.firebog.net/hosts/AdguardDNS.txt

Which is just downstream of this project.

I guess it was removed at some point!

**Comment by mkasberg** [comment]
It was included on the `02FEB24` blocklist at https://v.firebog.net/hosts/AdguardDNS.txt and it was removed on the `05FEB24` blocklist.

I suspect it's been fixed upstream since it's no longer present -- if it's still present on other blocklists, like [CHN: anti-AD filter](https://anti-ad.net/adguard.txt), it might be the case that those blocklists have not yet been updated with the upstream fix...

Since it's not currently present in the blocklist I was worried about, I think that the issue's probably resolved...

**Comment by jellizaveta** [comment]
If it loads fine now - then I will close it. Thanks for letting me know!

**Comment by jellizaveta** [comment]
@gentlyxu Hello. Could you please take a look?
