### ISSUE TITLE
Apple Music covers not loading

### ISSUE THREAD

**Issue by mxmfck** [AdguardTeam/AdGuardSDNSFilter#1624]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

DNS over TLS

### What DNS filters do you have enabled?

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

Apple Music App

### Add your comment and screenshots

<details>![IMG_0168](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/45181822/e283d1cc-d352-4b70-b7b6-de25c6a3af3c) </details>

The covers are not loading with AdGuard DNS enabled. 

### Privacy

- [X] I agree to follow this condition

**Comment by kvnhe** [comment]
> I can confirm this problem. Images are trying to load from is1-ssl.mzstatic.com and are being blocked.

In addition, this blocked domain is also affecting App Store images/icons.

**Comment by hagezi** [comment]
This was already fixed the day before yesterday, update the filter list.

**Comment by iTim314** [comment]
> This was already fixed the day before yesterday, update the filter list.

I can confirm this was fixed.

**Comment by jellizaveta** [comment]
`is1-ssl.mzstatic.com` is not blocked by AdGuard at the moment, closing the issue
