### ISSUE TITLE
Safe Site blocked

### ISSUE THREAD

**Issue by luh2** [AdguardTeam/AdGuardSDNSFilter#1630]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

AdGuard for Mac Version 2.13.0.1558 release

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

d.adguard-dns.com DoH in the DNS Settings of the mac

### What DNS filters do you have enabled?

* AdGuard DNS Filter
* Peter Lowe's Blocklist
* Dan Pollock's List
* POL: CERT Polska List of malicious domains
* The Big List of Hacked Malware Web Sites
* Malicious URL Blocklist (URLHaus)

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

www.4-tage-woche.ch

### Add your comment and screenshots

<details><img width="1171" alt="Screenshot 2024-02-08 at 16 05 56" src="https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/2047083/3c0cc02c-3cd1-4324-ae71-7780debf0c5e"></details>

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Not reproduced. Please show `nslookup` or `dig` output.

**Comment by luh2** [comment]
$ nslookup www.4-tage-woche.ch
Server:		192.168.1.1
Address:	192.168.1.1#53

Non-authoritative answer:
Name:	www.4-tage-woche.ch
Address: 217.26.63.20

**Comment by Alex-302** [comment]
> Address: 217.26.63.20

It seems ok. If still blocked - please try to flush DNS cache.
