### ISSUE TITLE
AdGuard DNS interferes with Remote Manipulator System

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#164]
Reported by 2374486:

> При использовании ПО для удаленного доступа Remote Manipulator System совместно с DNS AdGuard пропадает возможность подключения по Internet ID. Проблема на ПК, подключиться не получается только при использовании DNS AgGuard, при смене DNS на другой все работает.

Can someone please check how it works and troubleshoot the issue? The customer attached a screen recording to his latest email.

**Comment by Alex-302** [comment]
@Eugene-Savenko cannot reproduce with Windows+Android RMS apps.
