### ISSUE TITLE
hs-scripts.com

### ISSUE THREAD

**Issue by Bec-de-Xorbin** [AdguardTeam/AdGuardSDNSFilter#1643]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

dns.adguard-dns.com

### What DNS filters do you have enabled?

AdGuard

### What browser or app do you use?

Chrome, Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://aitofit.app/settings

### Add your comment and screenshots

Blocking hs-scripts.com breaks aitofit.app (only for members) in-built chat (made by HubSpot).

hs-scripts.com isn't blocked in any of uBlock Origin default filter lists.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
We have our own filters. hs-scripts.com is used for tracking purposes.
Third-party filters also block this domain

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/8361299/775f0b1e-8759-4b0e-9e0d-e6bad6cf4382)


</details>

You can unblock it using a private DNS on your device - adguard-dns.io
