### ISSUE TITLE
why www.googleadservices.com is whitelisted in the base dns filter

### ISSUE THREAD

**Issue by rochmind** [AdguardTeam/AdGuardSDNSFilter#1644]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

neatens over https

### What DNS filters do you have enabled?

https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt

### What browser or app do you use?

Safari

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed analytics or tracker

### Add your comment and screenshots

<img width="805" alt="Screen Shot 2024-03-03 at 09 09 12" src="https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/7104446/3add8fa9-adc3-415c-ab85-a8dcd73376e5">

I used to have pihole as my primary and recently setup AdGuardHome as primary and pihole as secondary. I noticed this morning when checking nextdns analytics that www.googleadservices.com is being blocked at upstream dns when I have 2 local blockers setup.

Noticed the AdGuard base filter whitelisted a bunch of domains - default should be blocked OR do not even have an entry for it. 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@rochmind These rules are related to context ads in Google Search

```adblock
@@||pagead.l.doubleclick.net^|
@@||www.googleadservices.com^|
@@||googleadapis.l.google.com^|
```

You can disable them by

```adblock
@@||pagead.l.doubleclick.net^|$badfilter
@@||www.googleadservices.com^|$badfilter
@@||googleadapis.l.google.com^|$badfilter
```

Which site made requests on your screenshot?

**Comment by rochmind** [comment]
I've removed the base dns filter instead and made adguard secondary
