### ISSUE TITLE
mlbpark.donga.com

### ISSUE THREAD

**Issue by Cannoli13** [AdguardTeam/AdGuardSDNSFilter#1647]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

- Using default adguard dns

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Add your comment and screenshots

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/155059613/7f1531a6-58f2-4b4b-b0c5-6c4a8f3997c1)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Cannot reproduce

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/8361299/a47f2fa4-7986-4620-be28-4495d90f97e5)


</details>

But I see blocked common ad/tracking servers. So it cannot be fixed when only DNS filtering is used.
