### ISSUE TITLE
dogdrip.net

### ISSUE THREAD

**Issue by Cannoli13** [AdguardTeam/AdGuardSDNSFilter#1648]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

- default adguard dns

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.dogdrip.net/

### Add your comment and screenshots

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/155059613/4c9c6a67-bad4-4ecd-8370-805a4f09c3d8)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Cannot reproduce.
Please use https://reports.adguard.com/new_issue.html for reporting issues.
