### ISSUE TITLE
api.yieldlove-ad-serving.net

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#165]
api.yieldlove-ad-serving.net is an ad server that isn't blocked by any lists

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #44349](https://github.com/AdguardTeam/AdguardFilters/issues/44349) via [**ZenHub**](https://www.zenhub.com/)
