### ISSUE TITLE
Adding entries from Serbo-Croatian List

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardSDNSFilter#1657]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

With [Serbo-Croatian List](https://github.com/DandelionSprout/adfilt/blob/master/SerboCroatianList.txt) being around 2½ years by now, and only has 13 entries that would be considered even remotely possible to convert to AdGuard's hostfiles syntax, it's safe for me to assume that there's not going to be a standalone DNS syntax version of it anytime soon.

As such, I propose adding as many of the following 13 entries as logistically possible to AdGuard DNS Filter:
```
||a.mabipa.com^
||avalaads.com^
||banner.mob.hr^
||klik-slider.morgancode.com^
||linker.hr^
||lupon.media^
||native.tportal.hr^
||redakcija.alo.rs^
||subs.vingd.com^
||traffic.styria.hr^
||widget.admiral.hr^
||widgets.jutarnji.hr^
://microbanner.
```

### Proposed solution

Add the above entries to AdGuard DNS Filter.

### Additional information

Can't come up with anything at the time of writing.

**Comment by Alex-302** [comment]
Thanks. Added. Few are dead or unused (can't find where used)
