### ISSUE TITLE
AdGuard DNS blocked access to www.beaconhealthsystem.org because it's a website with adult content

### ISSUE THREAD

**Issue by FortWIT** [AdguardTeam/AdGuardSDNSFilter#1665]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

94.140.14.15
94.140.15.16

### What DNS filters do you have enabled?

94.140.14.15
94.140.15.16

### What browser or app do you use?

Chrome, Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Add your comment and screenshots

https://www.beaconhealthsystem.org/
![adguard-beaconhealth](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/46198714/4b83523e-25c2-4811-9ccc-712eca72dbd0)

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Fixed. Update will be available in 1-2 hours.
