### ISSUE TITLE
Rule blocks Spectrum website Chat With Us

### ISSUE THREAD

**Issue by BoYanZh** [AdguardTeam/AdGuardSDNSFilter#1673]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

v0.107.48

### What DNS filters do you have enabled?

https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt

### What browser or app do you use?

Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://www.spectrum.net/support/general/chat-us

### Add your comment and screenshots

The rule `||collector.pi.spectrum.net^` will prevent this page from running properly. There will be no chat component on the page. The browser console says `POST https://collector.pi.spectrum.net/topics/sspp?bulk=true net::ERR_NAME_NOT_RESOLVED`.

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Works fine on my end with AdGuard DNS

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/8361299/b66881c4-447c-4934-adf2-368cdd8e7249)



</details>

**Comment by BoYanZh** [comment]
![image](https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/32470225/e28739bd-7c10-427a-a1cf-c7e0df164f6b)

**Comment by Alex-302** [comment]
I don't know why it does not work on your end.
But you can check with our private DNS https://adguard-dns.io/ where you can block/unblock any domain.
