### ISSUE TITLE
[false alarm] m.stripe.com

### ISSUE THREAD

**Issue by IceCodeNew** [AdguardTeam/AdGuardSDNSFilter#1674]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### What DNS filters do you have enabled?
```
!
! Title: AdGuard DNS filter
! Description: Filter composed of several other filters (AdGuard Base filter, Social media filter, Tracking Protection filter, Mobile ads filter, EasyList, EasyPrivacy, etc) and simplified specifically to be better compatible with DNS-level ad blocking.
! Homepage: https://github.com/AdguardTeam/AdguardSDNSFilter
! License: https://github.com/AdguardTeam/AdguardSDNSFilter/blob/master/LICENSE
! Last modified: 2024-04-23T12:01:27.657Z
!
! Compiled by @adguard/hostlist-compiler v1.0.24
!
!
! Source name: AdGuard Base filter ad servers
! Source: https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/BaseFilter/sections/adservers.txt

||m.stripe.com^
```

### What browser or app do you use?

Firefox

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Add your comment and screenshots

rule `||m.stripe.com^` is a false alarm, refer to https://support.stripe.com/questions/privacy-and-security-of-stripe-js?locale=en-US, here is the description:

> While you might see Stripe in a tracker list, we’re not building an individual > tracking profile on you. Stripe doesn’t—and won’t—share or sell this data to > advertisers. This data is securely exchanged between the following > Stripe-controlled hosts:
> 
>     js.stripe.com
> 
>     m.stripe.network
> 
>     m.stripe.com
> 
>     q.stripe.com
> 
> The data collected by these endpoints is designed to be secure and to not leave Stripe infrastructure. Access to this data is tightly controlled, and restricted to a small number of Stripe employees working on fraud prevention and security (and permissions are regularly reviewed)

This rule is included by the following configuration:
https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/820536f8aedde543a9d9504676cfbfe4281d3166/configuration.json#L100-L104
And the origin source is not proper proceeded:

> ||m.stripe.com^$third-party,domain=~stripe.network

https://raw.githubusercontent.com/easylist/easylist/3cd177207a7d717e282699c0d33f76406dda4dd4/easyprivacy/easyprivacy_thirdparty.txt

### Privacy

- [X] I agree to follow this condition

**Comment by BlazDT** [comment]
Not blocked anymore.
