### ISSUE TITLE
metrika.yandex.ru block it

### ISSUE THREAD

**Issue by userforsource** [AdguardTeam/AdGuardSDNSFilter#1679]
### Platform

Linux

### Protocol

DNS-over-TLS

### Do you use AdGuard app?

No I don't

### Issue Details

This is a ads website

### Actual Behavior

This should be blocked

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Alex-302** [comment]
It will block Metrika's admin panel.
