### ISSUE TITLE
Mirror with unblocked domains

### ISSUE THREAD

**Issue by ihurin** [AdguardTeam/AdGuardSDNSFilter#1689]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### Version

AdGuard Family DNS

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

dns.adguard.com

### What DNS filters do you have enabled?

AdGuard Family DNS

### What browser or app do you use?

Safari

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed analytics or tracker

### Where did you encounter the problem?

https://urporn.com

### Add your comment and screenshots

<img width="1120" alt="Screenshot 2024-05-28 at 08 13 46" src="https://github.com/AdguardTeam/AdGuardSDNSFilter/assets/33690072/638fe7dc-de8b-4bcd-87c4-b1f69827aea4">

### Privacy

- [X] I agree to follow this condition

**Comment by ihurin** [comment]
The website itself is a mirror to the porn domains. User reports that most of these domains are not blocked with AdGuard Family DNS. Please check.

**Comment by jellizaveta** [comment]
Thank you, added. Update will be available in 1–2 hours.

**Comment by ihurin** [comment]
Perfect! Thank you :pray::skin-tone-3:

**Comment by ihurin** [comment]
Perfect! Thank you :pray:
