### ISSUE TITLE
Consider blocking cryptoscam conndir.com

### ISSUE THREAD

**Issue by yscialom** [AdguardTeam/AdGuardSDNSFilter#1699]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

AdGuardHome v0.107.48

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

* 9.9.9.9
* 1.1.1.1

### What DNS filters do you have enabled?

* AdGuard DNS filter `https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt`
* AdAway Default Blocklist `https://adaway.org/hosts.txt`
* MalwareDomainList.com Hosts List `https://www.malwaredomainlist.com/hostslist/hosts.txt`
* Red Flag Domains `https://dl.red.flag.domains/red.flag.domains.txt`

**All updated today (2024-06-01).**

### What browser or app do you use?

Firefox, Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed ads

### Where did you encounter the problem?

https://conndir.com/

### Add your comment and screenshots

`conndir.com` is registered as part of a scam/ponzi scheme involving crypto investments. Advertising on social media is rampant since yesterday, leading to this website. Additionally, a WHOIS analysis shows the followng red flags:

* The identity of the owner of the website is hidden on WHOIS
* The Tranco rank (how much traffic) is rather low [Cryptocurrency services](https://www.scamadviser.com/scam-reports/cryptocurrency-bitcoins-scams/2589/is-this-cryptocurrency-website-a-scam-history-trends-and-experience) detected, these can be high risk [High risk financial services](https://www.scamadviser.com/scam-reports/investment-scams/3522/high-risk-forex-trading-services-how-to-recognize-a-scam-website) or content seems to be offered
* A [risk/high return financial services](https://www.scamadviser.com/scam-reports/investment-scams/3752/high-risk-financial-investment-scams) are offered
* The age of this site is (very) young.
* This website's data-sensitive services are hosted on a shared server.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
Thank you, added update will be available in 1–2 hours.
