### ISSUE TITLE
Adding dmp.one to blocklist

### ISSUE THREAD

**Issue by ingria** [AdguardTeam/AdGuardSDNSFilter#1705]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

`dmp.one` tracks, collects and sells user data (such as phone number, email, etc)

### Proposed solution

they are using their base domain as cdn (script location: `https://dmp.one/sync`), so the solution is to add `dmp.one` to blocklist along with its subdomains and mirrors:

- `dmp.one`
- `dmp-ai.ru`
- `dmp-one.ru`
- `dmp-1.ru`

### Additional information

- Details (in russian): https://habr.com/ru/articles/819595/

**Comment by jellizaveta** [comment]
@ingria Hello. Unfortunately, I can't find which sites/applications use these domains: 

- dmp-ai.ru
- dmp-one.ru
- dmp-1.ru

Could you please send some examples?

**Comment by jellizaveta** [comment]
Domains have been added to the TPF filter, will appear in the DNS filter in a couple of hours. Thanks for the report!
