### ISSUE TITLE
Implementation of Effective Block Lists

### ISSUE THREAD

**Issue by kelvinkad** [AdguardTeam/AdGuardSDNSFilter#1713]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

The efficiency of adguard sdns filter could be improved if some blocklists is merged. I run a malware test and an ad-blocking test and found some vulnerability when using Adguard Sdns.

### Proposed solution

My suggestion to improve the effectiveness of this filter is to merge some high reputation block lists. 

malware urlhaus - https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-hosts.txt
hagezi tif - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/tif-onlydomains.txt
jarellama - https://raw.githubusercontent.com/jarelllama/Scam-Blocklist/main/lists/wildcard_domains/scams.txt
hagezi pro (this is not mandatory to the improvement, but it would be usable to block ads) - https://raw.githubusercontent.com/hagezi/dns-blocklists/main/wildcard/pro-onlydomains.txt

With these lists mentioned above, Adguard Sdns could block 99% of newly registered malware and ads domains with very low risk of false positive, since these lists are daily updated and always clearing false positives with the help of a very big community of users.

**Comment by Alex-302** [comment]
Hi
Please try adguard-dns.io - it has a list of many filters, which can be enabled.
Default server is more user-friendly.
