### ISSUE TITLE
Lloyds Bank app doesn't pass authentication when AGDNS is on

### ISSUE THREAD

**Issue by dftf-stu** [AdguardTeam/AdGuardSDNSFilter#1720]
### Platform

Android

### Protocol

DNS-over-TLS

### Do you use AdGuard app?

No I don't

### Your configuration

DNS configured in Android 12 as follows: 

Homescreen > Apps Drawer > Settings > Network & Internet > Private DNS

Select option "Private DNS provider hostname"

Enter in the box below: dns.adguard-dns.com

Tap Save

### Traceroute to AdGuard DNS

Not sure how to do a Traceroot command on Android, sorry!

### Issue Details

1. Have dns.adguard-dns.com set as your DNS within the Android "Network & Internet" settings
2. Open the Lloyds Bank app
3. Observe it gets stuck on "Authenticating your device"
4. Try doing a Force Stop and Clear Cache of that app
5. Try opening it again, and observe the same issue
6. Turn off AdGuard DNS in the Android settings
7. Open the Lloyds Bank app again
8. Notice how it now works

### Expected Behavior

The Lloyds Bank app should be able to pass the "Authenticating your device" screen when dns.adguard-dns.com is set as the DNS for an Android device, as it used to until just recently

### Actual Behavior

The Lloyds Bank app is unable to get past the initial "Authenticating your device" screen whenever dns.adguard-dns.com is set as the DNS in the Android settings

### Screenshots

![Screenshot_20240630-094346](https://github.com/AdguardTeam/AdGuardDNS/assets/83965343/a6512e8d-94a2-454c-aa34-61e9ae36becf)

⚠️ I cannot take a screenshot of the error in the app, as the app does not allow screenshots

### Additional Information

DNS URL: dns.adguard-dns.com
Lloyds Bank app version: 141.03
App ID: com.grppl.android.shell.CMBlloydsTSB73
Android version: 12
Wi-Fi and mobile-data tasted: Yes: fails on both when AdGuard DNS is in use; works on both the moment it is switched off

**Comment by dftf-stu** [comment]
Hi @Chinaski1

Apologies: it wasn't clear to me I was being asked to do anything by @hagezi , as I wasn't directly asked to do so.  Might have been better had he said "Can you unblock this your-side and then re-test" or something.  I assumed he was adding a note for someone in your team to action, not me.

But regardless: how do I get to the "User rules" screen you linked to?  I don't use the AdGuard app, nor a browser extension, I just use the "AdGuard Public DNS" server-addresses found [here](https://adguard-dns.io/en/public-dns.html), under the "Our server addresses" heading, then "DNS-over-TLS" (as that is the one Android OS uses).  I'm not aware that it was possible to change settings for the public-servers, so can you explain how this is done?

Thanks

**Comment by Alex-302** [comment]
Fixed.

**Comment by dftf-stu** [comment]
Hi @Alex-302.  You say "fixed", but I've just restarted my Android phone, done a "Force Stop" and "Clear Cache" on the _Lloyds Bank_ app and it _still_ cannot get-past the "Authenticating your device" screen while using **dns.adguard-dns.com** as the DNS.

On _Windows_, I'm aware I could do a **IPCONFIG /FLUSHDNS** , but I'm not aware how to do this on _Android_ so... is there anything I can do to make it re-query against your server and find the correct IP?

As of now, I can still _only_ use the app if I disable your DNS service...

**Comment by Alex-302** [comment]
DNS server will be reconfigured soon (in few hours or tomorrow).

**Comment by dftf-stu** [comment]
Hi @Alex-302.  We're a week on now, but still the app doesn't work -- I still have to disable AdGuard DNS whenever I want to use it, otherwise it will not let me get to the sign-in screen.  Do you have any ETA on when the server-side rules will get updated to address this?  Thanks
