### ISSUE TITLE
branch.io - api3.branch.io

### ISSUE THREAD

**Issue by privacy-advo** [AdguardTeam/AdGuardSDNSFilter#1722]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [x] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS, AdGuard Home

### Version

AdGuard Home v0.107.52

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

tls://unfiltered.adguard-dns.com

### What DNS filters do you have enabled?

https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed analytics or tracker

### Add your comment and screenshots

`api3.branch.io` is not blocked. I guess they started using a new subdomain as `api.branch.io `and `api2.branch.io` are on several blocklists.

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
@privacy-advo Hello. In which application/site can I check this domain?

**Comment by privacy-advo** [comment]
I have around 20+ clients, a lot of familie member's devices, running on the server. I can try to find the source. Is it necessary?

**Comment by privacy-advo** [comment]
@jellizaveta 
I was able to reproduce it with Spotify app on both an iPhone and an iPad.

**Comment by hagezi** [comment]
Yes, it is a tracker, blocked in all my list versions. So far there have been no issues.

**Comment by jellizaveta** [comment]
Thanks, reproduced in Spotify, added to TPF will be in DNS filters within a day
