### ISSUE TITLE
app.chat.xiaomi.net  该域名是mipush的域名，拦截后无法将无法收到通知

### ISSUE THREAD

**Issue by DawnAleax** [AdguardTeam/AdGuardSDNSFilter#1726]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### Version

  v0.107.52

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

127.0.0.1:7874
openclash本地dns端口

### What DNS filters do you have enabled?

https://anti-ad.net/easylist.txt
https://easylist-downloads.adblockplus.org/easylist.txt
https://easylist-downloads.adblockplus.org/easyprivacy.txt

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://github.com/NihilityT/MiPushFramework

### Add your comment and screenshots

![image](https://github.com/user-attachments/assets/459cd336-8abc-486c-a3c4-ef6c173c3b8c)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@DawnAleax How to reproduce a problem?

**Comment by DawnAleax** [comment]
> @DawnAleax如何重现问题？

https://github.com/NihilityT/MiPushFramework In this app, the server will show "not connected"

**Comment by Alex-302** [comment]
No one's complaining. Apparently users are not affected by the described problem.
