### ISSUE TITLE
||buyeasy.by^

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#173]
Unable to open aliexpress links from the vk app

![image](https://user-images.githubusercontent.com/15856304/69520284-e9178380-0f64-11ea-892b-0a48a2f47e9e.png)

**Comment by Alex-302** [comment]
@Eugene-Savenko please provide original link before user click on it.

**Comment by Alex-302** [comment]
Сообщил авторам EasyList, которые его заблокировали:
https://github.com/easylist/easylist/issues/4338

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #44747](https://github.com/AdguardTeam/AdguardFilters/issues/44747) via [**ZenHub**](https://www.zenhub.com/)
