### ISSUE TITLE
Blocklist has many accidental(?) allow rules

### ISSUE THREAD

**Issue by levid0s** [AdguardTeam/AdGuardSDNSFilter#1730]
The default blocklist on new AdGuard installs I believe is [assets/filter_1.txt](../tree/main/assets/filter_1.txt).

Inspecting the file, I can see various allow rules that begin with `@@||`.
Some of these unblock rules might not be necessary and can also have unintended consequences.

Inspecting one rule at random:

`@@||adcdn.pingan.com^` - unblocks access to said domain.

The only reason I can image such rule present in a **block** list would be to override a more generic blocking rule, perhaps to `pingan.com`? But, no such rule exists, and even if it would, it would need the `$important` modifier in order to take precedence over the block rule.

Additionally, if someone has a generic block-all rule `/.*/` configured, these allow rules do override it!

Some allow rules have a mentions of a Github issue, assuming they were causing a problem in the past.
But why not just remove the blocking rule instead adding a specific allow rule?

Some interesting ones:
```
@@||ad.10010.com^
@@||ad.abchina.com^
@@||ad.kazakinfo.com^
@@||ad.ourgame.com^
@@||adcdn.pingan.com^
@@||advert.kf5.com^
@@||api.ads.tvb.com^
@@||app-advertise.zhihuishu.com^
@@||buyad.bi-xenon.cn^
@@||captcha.su.baidu.com^
@@||img.ads.tvb.com^
```

**Comment by Alex-302** [comment]
These rules are loaded from filter sources. They are may be redundant, but they don't break anything.
Some of these domains may be blocked in another DNS lists, and break sites.
