### ISSUE TITLE
Paypal issue - adjust.net.in

### ISSUE THREAD

**Issue by K-mikaZ** [AdguardTeam/AdGuardSDNSFilter#1731]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

dns.adguard-dns.com

### What browser or app do you use?

Chrome

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

link to download the PayPal app:
https://py.pl/AlA3tVY0Nfz

### Add your comment and screenshots

adjust.net.in closed here https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1478 but unresolved

>app marketing platform that includes fraud prevention, cybersecurity, and marketing automation products.
>[adjust.net.in (on www.netify.ai)](https://www.netify.ai/resources/domains/adjust.net.in)

If possible, could you please designate this domain as an exception to the AdGuard DNS filter?
Domains that prevent the PayPal app/website from launching

### Privacy

- [X] I agree to follow this condition

**Comment by jellizaveta** [comment]
The domain has been unlocked, changes will become available with the new filter update within 1-2 hours.

**Comment by vipink6845-gif** [comment]
Key

**Comment by vipink6845-gif** [comment]
Key
