### ISSUE TITLE
Not filtering Disney plus ad

### ISSUE THREAD

**Issue by SnAzZpOp** [AdguardTeam/AdGuardSDNSFilter#1733]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### Version

pihole

### What DNS filters do you have enabled?

https://v.firebog.net/hosts/AdguardDNS.txt

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed ads

### Where did you encounter the problem?

us-west-2.ads.digital.disneyadvertising.com

### Add your comment and screenshots

When you open a disney plus movie or whatever, it's still showing the ads
I found in the list it's set as ads.digital.disneyadvertising.com and it's not matching the full url
I've blacklisted the domain and it's working, but I would like to report this behaviour

![image](https://github.com/user-attachments/assets/2afc84e7-7584-4f0c-8f06-597dcfbb9d5b)

### Privacy

- [x] I agree to follow this condition

**Comment by Alex-302** [comment]
They don't use a separate domain for ads.
