### ISSUE TITLE
Disney+ Hotstar ad domains block 

### ISSUE THREAD

**Issue by KrinalPatel889** [AdguardTeam/AdGuardSDNSFilter#1741]
### Issue Details

Your dns service is not blocking ads in Disney+ hotstar app in android but manually blocking some domains with adaway works perfectly

### Proposed solution

Could you block following domains to work with adguard dns please.

https://fp-analytics.hotstar.com
https://hb-analytics.hotstar.com
https://settings-analytics.hotstar.com
https://events-analytics.hotstar.com
https://cws-hotstar.conviva.com
https://agl-intl.hotstar.com
https://service.hotstar.com
https://services.hotstar.com
https://brands.hotstar.com/
https://bifrost-api.hotstar.com
https://hses.hotstar.com
https://hses5.hotstar.com
https://vs.hotstar.com
https://videoads.hotstar.com
https://logs.hotstar.com
https://hesads.akamaized.net

**Comment by Alex-302** [comment]
![image](https://github.com/user-attachments/assets/a5d72008-78cc-43a0-a41a-c027c618006c)
