### ISSUE TITLE
[BLOCK] joinmassive.com

### ISSUE THREAD

**Issue by r2fo** [AdguardTeam/AdGuardSDNSFilter#1743]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS, AdGuard Home

### What DNS filters do you have enabled?

* AdGuard DNS Filter *

### What browser or app do you use?

Safari

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed analytics or tracker

### Where did you encounter the problem?

https://joinmassive.com

### Add your comment and screenshots

```
joinmassive.com
api.joinmassive.com
geo-network.joinmassive.com
network.joinmassive.com
```

### Why should these domain(s) be blocked?

Massive offers monetization SDK’s to developers to put in their Android app and Windows programs. This SDK will use the user’s internet connection as a proxy, in the past it used to mine cryptocurrency on the user’s pc too.

It seems like they use several subdomains under the joinmassive.com domain for C&C, but just to be safe I think it’s better to block *.joinmassive.com.

Their site advertises these services: https://joinmassive.com/

This video features a deep dive into a program which uses the Massive SDK: https://youtu.be/_Q_F04Wd23k

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Handled in AdguardFilters https://github.com/AdguardTeam/AdguardFilters/commit/2405a4321f372d048e479aa477fcf11a7d00be94
