### ISSUE TITLE
dns filter - ad block detection  is getting bypassed by tradingview 

### ISSUE THREAD

**Issue by pinkyellowed** [AdguardTeam/AdGuardSDNSFilter#1756]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### Version

AdguardDNS filter

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

[github.com/AdguardTeam/AdguardSDNSFilter](https://github.com/AdguardTeam/AdguardSDNSFilter)

### What DNS filters do you have enabled?

adguard dns filter

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Missed ads, Missed analytics or tracker, Website or app doesn't work properly

### Where did you encounter the problem?

when changing chart time frames. eg 1hour then 4hour etc

### Add your comment and screenshots

on tradingview IOS app. i am prompt that ad blocker app detected and i need to remove it to allow back into the chart. if i remove the setting i am spammed every 10 mins to download premium to go ad free. its already blocked as you can see, but some how its getting by passed 

https://github.com/user-attachments/assets/6c01da53-d490-4842-b4df-42f6a32b9a63
[IMG_5471](https://github.com/user-attachments/assets/c92b308a-3042-4ce4-8350-bff2019d6c3d)
its getting by passed by multiple ad blockers, i have contacted some already like hagezi.
it works fine on macos, this started occuring after the sequiona apple update 

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
We can't unblock that domains. You can use our private DNS, and block/unblock anything you want.

**Comment by pinkyellowed** [comment]
where can i locate the private DNS

**Comment by Alex-302** [comment]
@pinkyellowed https://adguard-dns.io/
