### ISSUE TITLE
Nol Pay App UAE

### ISSUE THREAD

**Issue by nuruszama** [AdguardTeam/AdGuardSDNSFilter#1757]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS, AdGuard private DNS

### What DNS filters do you have enabled?

dns.adguard.com

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://play.google.com/store/apps/details?id=com.snowballtech.rta

### Add your comment and screenshots

Nol Pay app in UAE is not working when using dns.adhuard.com or private block in android

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. Cannot check - not working on my end at all.
Does it work with https://unfiltered.adguard-dns.com/dns-query

**Comment by nuruszama** [comment]
![Screenshot_20240926-113954](https://github.com/user-attachments/assets/24faebe9-ef32-4bed-9d8b-4d97244dbc22)
![Screenshot_20240926-113941](https://github.com/user-attachments/assets/af7388f2-763c-40a1-b30e-5b39af8138b5)

No. it is not working in following settings also.

**Comment by Alex-302** [comment]
It seems the problem with the app's server DNS configuration or with AdGuard DNS server.
Better write here https://github.com/AdguardTeam/AdGuardDNS/issues if the app works with Google or Cloudflare.
