### ISSUE TITLE
imagesrv.adition.com

### ISSUE THREAD

**Issue by tipuraneo** [AdguardTeam/AdGuardSDNSFilter#1758]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [ ] You're using an up-to-date version of AdGuard DNS filter;
- [ ] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### What DNS filters do you have enabled?

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed ads

### Add your comment and screenshots

The following Domains are missing:
* imagesrv.adition.com e. g. https://imagesrv.adition.com/banners/3202/20644001/banner300-left.jpg or https://imagesrv.adition.com/banners/3784/files/00/2c/94/79/000002921593.jpeg on https://www.spiegel.de/

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It is related to antiadblocks. Will cause probmems.
