### ISSUE TITLE
Avoid blocking Google Ads and Google Analytics domains to avoid bugs and for normal operation of important and vital websites, services, apps... that need Google Ads and Google Analytics to function properly 

### ISSUE THREAD

**Issue by trimechee** [AdguardTeam/AdGuardSDNSFilter#1767]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Hi, i test with this famous site with my ad blocker extension disabled ::

https://d3ward.github.io/toolz/adblock

and unfortunately, some essential google services for the proper functioning of websites, apps....are blocked like Google Ads and Google Analytics domains, so our ultimate dream please is that the dns blocks malware viruses so no need to activate a heavy anti virus that destroys our battery and activates noisy fan and also a dns that avoid blocking Google Ads and Google Analytics to avoid bugs and for normal operation of important and vital websites, services, apps... that need Google Ads and Google Analytics to function properly, and no nedd that dns block ads because ublock origin extension manifest v2 in catsxp, brave, supermium, thorium , and firefox forks browsers can do that even in smartphones, and even in iphone ios and mac os with orion browser by kagi :

https://kagi.com/orion/

which supports the installation of extensions and adblockers like ublock origin in ios and mac os, thank you so much!

### Proposed solution

Avoid blocking vital Google Ads and Google Analytics domains please 

### Additional information

 Google Ads and Google Analytics domains blocked

**Comment by Alex-302** [comment]
Without Google ads and analytics blocking, the filtering server will become much less useful.

**Comment by Alex-302** [comment]
@trimechee Yes, our DNS has anti-phishing bases (few sources - free and paid). They loaded not as filters.

**Comment by Alex-302** [comment]
Using our private DNS you may enable also many third-party filters.
