### ISSUE TITLE
daraz.com.bd

### ISSUE THREAD

**Issue by lutfor-diu** [AdguardTeam/AdGuardSDNSFilter#1771]
### Prerequisites

- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard Home

### Version

AdGuardHome Version:  v0.107.53

### What DNS upstream(s) do you use in AdGuard apps or AdGuard Home?

unbound local dns server

### What DNS filters do you have enabled?

https://adguardteam.github.io/HostlistsRegistry/assets/filter_1.txt

### What browser or app do you use?

Microsoft Edge

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Missed analytics or tracker, Website or app doesn't work properly

### Where did you encounter the problem?

https://www.daraz.com.bd/

### Add your comment and screenshots

![Screenshot_10-10-2024_193923_www daraz com bd](https://github.com/user-attachments/assets/195e5924-c08c-49c3-81c6-41f5f8003236)
review and details missing
 product status and review not showing. "sg.mmstat.com" , "acs-m.daraz.com.bd" Blocked
### Privacy

- [X] I agree to follow this condition

**Comment by itsnotsaved** [comment]
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/1779
