### ISSUE TITLE
kooappslogs.com Incorrect Blocking

### ISSUE THREAD

**Issue by kooappsdevs** [AdguardTeam/AdGuardSDNSFilter#1772]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

Other

### What DNS filters do you have enabled?

https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

Snake.io mobile apps

### Add your comment and screenshots

Hello, we noticed that our website kooappslogs.com is being incorrectly blocked by AdGuard's DNS filter.

The website kooappslogs.com has nothing to do with ads.  We use it as a network endpoint to support save files and optimize user features for the mobile games we make.

Can you please remove kooappslogs.com from the DNS filter list?

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
Hi. I don't see kooappslogs.com in the network requests on Snake.io
