### ISSUE TITLE
daraz.com blocked by AdGuard DNS Filter

### ISSUE THREAD

**Issue by itsnotsaved** [AdguardTeam/AdGuardSDNSFilter#1779]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS filters do you have enabled?

AdGuard DNS Filter

### What browser or app do you use?

Chrome

### Which device type do you use?

Desktop

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://daraz.com/

### Add your comment and screenshots

![Screenshot from 2024-10-21 18-04-14](https://github.com/user-attachments/assets/217815fd-5844-4199-8d9b-eda17757c0e0)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
It redirects to daraz.pk
