### ISSUE TITLE
Teams Android App + IPv6

### ISSUE THREAD

**Issue by kohlerdominik** [AdguardTeam/AdGuardSDNSFilter#1782]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard public DNS

### What DNS filters do you have enabled?

AdGuard Public DNS

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

Microsoft Teams App

### Add your comment and screenshots

All connectivity of my Teams Android App breaks when using an IPv6 connection and `dns.adguard.com` as Private DNS. If I keep the Private DNS entry, but switch off Wifi, the App immediately starts to work (my provider uses only IPv4 over cellular). I think, for IPv4, the right domains are whitelisted, but for IPv6 some entries are missing.

Missing connectivity shows in:
- not beeing able to send or receive messages
- not beeing able to see other users statuses

What does work are notifications, though.

![grafik](https://github.com/user-attachments/assets/3769cd35-bccf-4b63-83d7-d914e3be6348)

### Privacy

- [X] I agree to follow this condition

**Comment by Alex-302** [comment]
@kohlerdominik Hi
Does it happen with non-filtering server?
`https://unfiltered.adguard-dns.com/dns-query`

**Comment by kohlerdominik** [comment]
Hi @Alex-302 
Thanks for the response.

Last week it started to work again; so I guess this was either resolved implicit, or an upstream problem. So this should be resolved.
