### ISSUE TITLE
AdGuard DNS breaks Nvidia account authentication on Shield Tablet

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#179]
### Steps to reproduce
1. Use AdGuard DNS (or AdGuard full app, protection enabled, DNS only)
2. Log out of existing NVIDIA account
3. Attempt to log in
4. Login attempt will never come through

### Actual behavior
AdGuard breaks Nvidia account authentication

<details><summary>Screenshot:</summary>

![IMG_20191201_121036](https://user-images.githubusercontent.com/33634917/70272938-c92c5f00-17b1-11ea-88c6-dcbe79ba3716.jpg)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default, Regular
| How did you setup DNS configuration:| System + In-app
| Device model:| NVIDIA Shield Tablet
| Operating system and version:| Unspecified Android (presumably 9)

**Comment by Alex-302** [comment]
I see no blocked requests on screenshot.

**Comment by Alex-302** [comment]
Maybe it is not caused by filters.

**Comment by ameshkov** [comment]
@akmLaVx we'll definitely need debug logs
