### ISSUE TITLE
Suggestions of some vital capital life saver rare blocklists to block more sophisicated nasty crypto jacking mining currency please !

### ISSUE THREAD

**Issue by trimechee** [AdguardTeam/AdGuardSDNSFilter#1793]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

Hi, I read a news article describing how sophisticated crypto highjacking miners uses new engineering ways to steal our cpu power by using just a tiny quality of cpu to mine cryptocurrencies without being detected, so I have a research and maybe these rare important blocklists can help our beloved Adguard dns to block even more crypto mining please, thanks! :

https://github.com/bogachenko/fuckfuckadblock
https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt
https://github.com/bogachenko/fuckfuckadblock/wiki/Mirror-lists
https://github.com/bogachenko/fuckfuckadblock/commit/f9476c881b7e0749badea1e3b095a02b3ec107c8

quad9 blocklist
https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/quad9_blocklist.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_50.txt
https://dnsforge.de/#blocklisthard

hoshsadiq shadowwhisperer olbat
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt

http://dsi.ut-capitole.fr/blacklists/
https://github.com/olbat/ut1-blacklists
olbat
https://github.com/olbat/ut1-blacklists/blob/master/blacklists/cryptojacking/domains
https://github.com/olbat/ut1-blacklists/blob/master/blacklists/cryptojacking/urls
https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/cryptojacking/domains
https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/cryptojacking/urls

https://github.com/blocklistproject/Lists
https://blocklistproject.github.io/Lists/adguard/crypto-ags.txt

https://github.com/hagezi/dns-blocklists
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt
https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/adblock/tif.txt

https://github.com/hoshsadiq/adblock-nocoin-list

https://github.com/ShadowWhisperer/BlockLists
https://github.com/ShadowWhisperer/BlockLists/blob/master/Lists/Cryptocurrency
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/refs/heads/master/Lists/Cryptocurrency

https://zerodot1.gitlab.io/CoinBlockerListsWeb/downloads.html
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list_browser.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists
https://zerodot1.gitlab.io/CoinBlockerLists/list_browser_AdBlock.txt
https://zerodot1.gitlab.io/CoinBlockerLists/list_browser.txt

https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist
https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt
https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists_browser

ZERODOT1
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list.txt

https://0xacab.org/my-privacy-dns/matrix/-/issues/new?issuable_template=CryptoMiner

https://github.com/abp-filters/abp-filters-anti-cv
https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv

### Proposed solution

https://github.com/bogachenko/fuckfuckadblock
https://raw.githubusercontent.com/bogachenko/fuckfuckadblock/master/fuckfuckadblock-mining.txt
https://github.com/bogachenko/fuckfuckadblock/wiki/Mirror-lists
https://github.com/bogachenko/fuckfuckadblock/commit/f9476c881b7e0749badea1e3b095a02b3ec107c8

quad9 blocklist
https://raw.githubusercontent.com/AssoEchap/stalkerware-indicators/master/generated/quad9_blocklist.txt
https://adguardteam.github.io/HostlistsRegistry/assets/filter_50.txt
https://dnsforge.de/#blocklisthard

hoshsadiq shadowwhisperer olbat
https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt

http://dsi.ut-capitole.fr/blacklists/
https://github.com/olbat/ut1-blacklists
olbat
https://github.com/olbat/ut1-blacklists/blob/master/blacklists/cryptojacking/domains
https://github.com/olbat/ut1-blacklists/blob/master/blacklists/cryptojacking/urls
https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/cryptojacking/domains
https://raw.githubusercontent.com/olbat/ut1-blacklists/refs/heads/master/blacklists/cryptojacking/urls

https://github.com/blocklistproject/Lists
https://blocklistproject.github.io/Lists/adguard/crypto-ags.txt

https://github.com/hagezi/dns-blocklists
https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/tif.txt
https://gitlab.com/hagezi/mirror/-/raw/main/dns-blocklists/adblock/tif.txt

https://github.com/hoshsadiq/adblock-nocoin-list

https://github.com/ShadowWhisperer/BlockLists
https://github.com/ShadowWhisperer/BlockLists/blob/master/Lists/Cryptocurrency
https://raw.githubusercontent.com/ShadowWhisperer/BlockLists/refs/heads/master/Lists/Cryptocurrency

https://zerodot1.gitlab.io/CoinBlockerListsWeb/downloads.html
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list_browser.txt
https://gitlab.com/ZeroDot1/CoinBlockerLists
https://zerodot1.gitlab.io/CoinBlockerLists/list_browser_AdBlock.txt
https://zerodot1.gitlab.io/CoinBlockerLists/list_browser.txt

https://github.com/Ultimate-Hosts-Blacklist/Ultimate.Hosts.Blacklist
https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists
https://zerodot1.gitlab.io/CoinBlockerLists/list.txt
https://github.com/Ultimate-Hosts-Blacklist/ZeroDot1_CoinBlockerLists_browser

ZERODOT1
https://gitlab.com/ZeroDot1/CoinBlockerLists/-/raw/master/list.txt

https://0xacab.org/my-privacy-dns/matrix/-/issues/new?issuable_template=CryptoMiner

https://github.com/abp-filters/abp-filters-anti-cv
https://gitlab.com/eyeo/anti-cv/abp-filters-anti-cv

**Comment by ShadowGaming100** [comment]
bump
