### ISSUE TITLE
Adguard-DNS is breaking Payoneer app on Android.

### ISSUE THREAD

**Issue by uncharted-user** [AdguardTeam/AdGuardSDNSFilter#1794]
### Prerequisites

- [X] This site DOES NOT contains sexually explicit material;
- [X] The problem occurs only when using AdGuard DNS or DNS filtering with AdGuard DNS filter, it is not caused by other ad blockers;
- [X] You're using an up-to-date version of AdGuard DNS filter;
- [X] Browser version is up-to-date;
- [X] If a website or an app is broken, disabling AdGuard DNS filter resolves the issue.

### What DNS server do you use?

AdGuard private DNS

### What DNS filters do you have enabled?

AdGuard DNS filter

### What browser or app do you use?

Other app

### Which device type do you use?

Mobile

### What type of problem have you encountered?

Website or app doesn't work properly

### Where did you encounter the problem?

https://play.google.com/store/apps/details?id=com.payoneer.android

### Add your comment and screenshots

Adguards-DNS is modifying api2.branch.io request even if I added this to unblock using user rule. I think this is the only reason the app is not even starting when using Adguard-DNS and working seamlessly with other DNS. This app is required for financial transactions.

### Privacy

- [X] I agree to follow this condition

**Comment by ameshkov** [comment]
Quick solution: add `@@||api2.branch.io^$dnsrewrite` to user rules.

Probably due to this:

```
!
! Special block section, requires explanation for the rule
!
! https://reddit.com/r/Adguard/comments/ztbv96/how_do_i_stop_this_my_phone_is_overheating_and/
! reddit app is unblocked in Mobile filter: https://github.com/AdguardTeam/AdguardFilters/commit/78dd815df59d98fb8b6d658330041b65269eabc2
||api2.branch.io^$dnsrewrite=0.0.0.0
```

@AdguardTeam/filters-maintainers could you please check how Reddit app works if we remove this?

**Comment by uncharted-user** [comment]
> Quick solution: add `@@||api2.branch.io^$dnsrewrite` to user rules.

It is blocking the URL.

**Comment by uncharted-user** [comment]
I am not sure what is causing this app not to start, but it is not running on AdGuard-DNS. I tried VPN, other network and both worked. Not only that, but I checked on multiple android devices and came up with the same result. On my end, I can reproduce it a million times.

**Comment by Alex-302** [comment]
Does it happen when you disable all filters?

**Comment by uncharted-user** [comment]
> Does it happen when you disable all filters?

Yes, it does happen even if the filter is disabled.


> I recommend also to send a message to their technical support.

I already did and still waiting for the response but, the support always says to contact with the dev team. This is why I created an issue here. Unfortunately, I wasn't able to find any issue tracker for AdGuard-DNS server.

**Comment by Alex-302** [comment]
> Yes, it does happen even if the filter is disabled.

It seems it is more complicated problem.

> Unfortunately, I wasn't able to find any issue tracker for AdGuard-DNS server.

Please also write here
https://github.com/AdguardTeam/AdGuardDNS/issues

**Comment by uncharted-user** [comment]
> Please also write here
> https://github.com/AdguardTeam/AdGuardDNS/issues

Thanks
