### ISSUE TITLE
webpower.eu blocked with AdGuard DNS

### ISSUE THREAD

**Issue by ihurin** [AdguardTeam/AdGuardSDNSFilter#1804]
### Platform

macOS

### Protocol

Regular

### Do you use AdGuard app?

Yes I am

### Issue Details

`I am not an employee of webpower.eu but this company is used for marketing and enquete mails as a forwarder so if they are blacklisted or do malicious stuff I need to know so I can either clear it up with them or we switch to a reliable company.`

### Expected Behavior

available

### Actual Behavior

blocked

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

In reference to 991095, please let us know if possible to remove website from our filter or why it is there, customer's interest.

**Comment by jordansworld** [comment]
@Alex-302

**Comment by NineliveZzZ** [comment]
Hello, I cannot seem to find the new thread after forwarding this case to the ADGuardTeam/ADGuardDNS by Chinaski1 one last week ?  
Can someone tell me where to find this please ?  The issue is still not resolved, or explained :)
Many thanks and Happy Holidays.
Best Regards,
Werner

**Comment by jellizaveta** [comment]
Hello, this domain got into `AdGuard DNS` filter from `Frellwits Swedish Filter` list. At the moment I don't see that this domain is involved in advertising and I think it can be unblocked.

**Comment by jellizaveta** [comment]
@NineliveZzZ As far as I can see from the sites this domain is used in mailing forms, may store or send some data. Is something broken due to the blocking of this domain?

**Comment by jellizaveta** [comment]
If I understand things correct, some newsletter management may be broken, so the domain is unlocked.

**Comment by NineliveZzZ** [comment]
hello, thanks, it see;ms I can resolve again :)
nslookup webpower.eu 94.140.14.15
Server:  family.adguard-dns.com
Address:  94.140.14.15

Non-authoritative answer:
Name:    webpower.eu
Addresses:  2a03:3400:7:1:80::25
          91.197.72.25
