### ISSUE TITLE
telemetry*.api.playstation.com^ breaks ps5 statistics

### ISSUE THREAD

**Issue by zerkms** [AdguardTeam/AdGuardSDNSFilter#1813]
### Prerequisites

- [X] I checked the documentation and found no answer;
- [X] I checked to make sure that this issue has not already been filed;
- [X] This is not an ad/bug report.

### Problem description

I understand it's a tricky case: this list explicitly states it's a `Tracking Protection filter`.

From the other hand - it's an example of "good" statistics :shrug: Most playstation players would prefer to have their gaming statistics recorded, rather than not (no scientific proof for that, but my assumption).

### Proposed solution

Unblock it. I personally created an unblock rule for the entire `playstation.com`.

**Comment by Alex-302** [comment]
Removed.
