### ISSUE TITLE
app.adjust.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardSDNSFilter#185]
@adguard-bot commented on [Tue Dec 10 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45739)

### Issue URL (Incorrect Blocking)
[https://app.adjust.com/6ypk9q?tracker_limit=200000&deep_link=spotify%3A%2F%2Fepisode%2F03EsYwXH0HbSyc3jVvE96j%3Fsi%3D-rA0t8qhRo6HMZ3pbU5S2A&redirect=https%3A%2F%2Fopen.spotify.com%2Fepisode%2F03EsYwXH0HbSyc3jVvE96j%3Fsi%3D-rA0t8qhRo6HMZ3pbU5S2A%26nd%3D1&label=sp_cid%3A181773442b74e23e582416b146969ae5](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fapp.adjust.com%2F6ypk9q%3Ftracker_limit%3D200000%26deep_link%3Dspotify%253A%252F%252Fepisode%252F03EsYwXH0HbSyc3jVvE96j%253Fsi%253D-rA0t8qhRo6HMZ3pbU5S2A%26redirect%3Dhttps%253A%252F%252Fopen.spotify.com%252Fepisode%252F03EsYwXH0HbSyc3jVvE96j%253Fsi%253D-rA0t8qhRo6HMZ3pbU5S2A%2526nd%253D1%26label%3Dsp_cid%253A181773442b74e23e582416b146969ae5)
### Comment
Username: @Krizzii
> Al those https://app.adjust.com/ links don't redirect to the Spotify app. Referral app = Telegram. Reddit apps also use this links. 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/A8D86QR.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/XabOBQ5.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 10
AdGuard version: | 3.3 beta 3.1 (188)
Browser: | Chrome (data compression)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/> AdGuard Dutch
Other extensions used: | AdGuard Home

---

@Krizzii commented on [Tue Dec 10 2019](https://github.com/AdguardTeam/AdguardFilters/issues/45739#issuecomment-564196415)

Referral link was actually a t.co link (Twitter) posted to Telegram.

**Comment by bogachenko** [comment]
@Alex-302 при использовании dns фильтра от вас не получается заблокировать все запросы от этого домена. Один или два запроса все ровно прорываются, получается повторить не всегда, а с раза 4 или 5.

Использую фильтр `@@||app.adjust.com^|$badfilter`. Сможешь воспроизвести, без флага `$important` ?


https://user-images.githubusercontent.com/8535285/153986459-54ea2dc9-cefa-42c7-84e8-7d71af1b9198.jpg
