### ISSUE TITLE
false positive on google shopping

### ISSUE THREAD

**Issue by RemedyOfNorway** [AdguardTeam/AdGuardSDNSFilter#189]
When searching for items the google shopping links very often will be blocked. 

This is the error message.  Seems the links go through "ad.doubleclick.net" which i assume is blocked. 

Dette nettstedet er ikke tilgjengeligFant ikke IP-adressen til tjeneren for ad.doubleclick.net.
Prøv å kjøre Windows Nettverksdiagnose.
DNS_PROBE_FINISHED_NXDOMAIN

**Comment by ameshkov** [comment]
Yeah, this indeed a false positive, but we cannot unblock this domain -- most of the doubleclick ads are also loaded from it. Unfortunately, on the DNS level we can either unblock or block it everywhere.
