### ISSUE TITLE
AdGuard DNS filters out MX records for Yandex emails

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#197]
# Steps to reproduce
1. Use AdGuard DNS
2. Try to send an email to @yandex.ru domain.
3. Email won't send
4. nslookup won't show any MX records

### Actual behavior
AdGuard blocks MX records for Yandex and (possibly) other mail servers

### Helpdesk ID
2433174

**Comment by ameshkov** [comment]
Hmm, but `nslookup` cannot show any MX records anyways. You should use `dig` instead.

What mail client do you use?

**Comment by akmLaVx** [comment]
Sent an inquiry to the user, waiting for reply now.
