### ISSUE TITLE
||targetspot.com^ 

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#199]
> podcast-redirect.radiofrance.fr is still wrongly listed by your DNS, could please do something about it? So that I would not have to disable dns.adguard.com as DNS to listen to my podcasts?

```
$ dig @dns.adguard.com podcast-redirect.radiofrance.fr
;; ANSWER SECTION:
podcast-redirect.radiofrance.fr. 3600 IN A 0.0.0.0
```

```
$ dig @8.8.8.8 podcast-redirect.radiofrance.fr
;; ANSWER SECTION:
podcast-redirect.radiofrance.fr. 21573 IN CNAME	radiofrance.targetspot.com.
radiofrance.targetspot.com. 93	IN	A	31.12.65.10
```
Reported by: 2448426

**Comment by Alex-302** [comment]
Fixed in https://github.com/AdguardTeam/AdGuardSDNSFilter/commit/efd860c7d36763eec98322b6c6be098b39ef592a
@Eugene-Savenko please ask user afrer 36 hours
