### ISSUE TITLE
ABC iView not working on Telstra TV (Roku)

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardSDNSFilter#20]
Thanks to AdGuard Home, it is now possible to report broken apps/websites or missed trackers. Where is the best place to report such things for the Simplified DNS Filter?

Reporting that **dc.webtrends.com** needed to be unblocked from the AdGuard SDNS filter in order to have the ABC iView app launch on a Telstra TV (Roku powered device), otherwise it crashes instantly.

`@@||dc.webtrends.com^$important`

**Comment by Alex-302** [comment]
Done https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/21
