### ISSUE TITLE
Breaking site: Video won't launch on beinsports.com

### ISSUE THREAD

**Issue by Nojevah** [AdguardTeam/AdGuardSDNSFilter#203]
My config: I use Adguard DNS on Windows 10.

### Steps to reproduce

1. Open Chrome
2. Use an incognito window
3. go to https://www.beinsports.com/france/bundesliga/video/bundesliga-lhorrible-sortie-kamikaze-de-nuebe/1370538?fbclid=IwAR2Y-sb2ur0sUCZ_qEfkYantIJivT5Yix6XMWhonSCCK9X0ErSrpma_TV5w
4. video is not present

### Expected behavior

Video should be here (and start with one click if you use ClickToPlay)

### Actual behavior

You won't see any video. If you don't use an incognito window, it's possible this site will find an element allowing video display, whereas incognito window does not search for cache.
I guess Adguard blocks a domain which creates a cookie (or something like that) which allows video launch. Vicious but can reproduct 100% with adguard DNS, no problem with Clouflare DNS.

<details><summary>Screenshot:</summary>

</details>

### Your environment

Windows 10
Adguard default DNS

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (e.g. Default, 176.103.130.130)
| How did you setup DNS configuration:| Control panel
| Device model:| PC
| Operating system and version:| Windows 10

**Comment by Alex-302** [comment]
Hi
This is caused by google-analytics.com blocking. We cannot whitelist this domain.
Please try to add new record to HOSTS file: 
`ip_address google-analytics.com`
`ip_address` you can get from `nslookup google-analytics.com` with Google DNS.

**Comment by Nojevah** [comment]
That's what I feared. Not easy to whitelist with DNS/hosts Blocking. That's a plan B solution (android for example). Thanks for your analyse.

**Comment by Alex-302** [comment]
@Nojevah you can use your own DNS - AdGuard Home(can be installed on many OS)
https://adguard.com/en/adguard-home/overview.html
In this case you can block or unblock anything you want.
