### ISSUE TITLE
AdGuard DNS blocks Nvidia GeForce Now cloud gaming service

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#207]
According to helpdesk ticket 2454648, AdGuard DNS (either set up as Private DNS or used w/AdGuard app) blocks GeForce Now cloud gaming service. We've been contacted by their representatives who have forwarded us a list of domains to be whitelisted so that the service works properly:

nvidia.com/
nvidiagrid.net/
tegrazone.com/

**Comment by ameshkov** [comment]
Hmm, I cannot reproduce this -- none of these domains are blocked.

@akmLaVx is there an app that we can use on our Android device to reproduce this on our side and figure out what went wrong?

**Comment by akmLaVx** [comment]
@ameshkov https://play.google.com/store/apps/details?id=com.nvidia.geforcenow

**Comment by Alex-302** [comment]
On my device I see this error only:
![image](https://user-images.githubusercontent.com/8361299/71207885-88a00b80-22b0-11ea-9405-0b21d36d2d4b.png)
It is caused by google analytics blocking.

**Comment by ameshkov** [comment]
@akmLaVx please let them know that the app is broken because it relies on Google Analytics.

AdGuard DNS does not block any of their domains.

We cannot unblock Google Analytics in AdGuard DNS because in this case it will be allowed globally.
