### ISSUE TITLE
||vortex.data.microsoft.com^

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#210]
> I recently found out that the Default DNS you provide blocks "web.vortex.data.microsoft.com" This blocks microsoft from getting achivements from, at least, in my particular case, Halo Master Chief Collection from registering. 

ID: 2461672

**Comment by ammnt** [comment]
> > I recently found out that the Default DNS you provide blocks "web.vortex.data.microsoft.com" This blocks microsoft from getting achivements from, at least, in my particular case, Halo Master Chief Collection from registering.
> 
> ID: 2461672

Hello,

just FYI. I 've had an xbox for 12 years and I can say with confidence that this host has nothing to do with xbox live achievements. Blocking these hosts may prevent them from being received:

`mobile.pipe.aria.microsoft.com`
`v10.vortex-win.data.microsoft.com`
`v20.vortex-win.data.microsoft.com`
`settings-win.data.microsoft.com`
`v10.events.data.microsoft.com`
`v20.events.data.microsoft.com`

Here is prooflinks:
https://www.reddit.com/r/pihole/comments/9ztxdx/psa_pihole_seems_to_be_blocking_xbox_achievements/
http://kamilslab.com/2017/01/02/fix-xbox-live-achievements-not-popping-up-when-using-pi-hole/

If they were blocked some time ago, after unlocking them, the achievements will not come immediately. But I can 't say anything about the registering Halo Master Chief Collection.

Thank you.
