### ISSUE TITLE
||pladform.ru^

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardSDNSFilter#211]
Hello,

it appears that the rule **||pladform.ru^** blocks video playback on the RuTube:
https://rutube.ru/video/156abdcc66f78aaa68bf4ba309e150cb/

More precisely, this host: video-318-1.pladform.ru. Please check and confirm.

Thank you.

**Comment by Alex-302** [comment]
Fixed. That's because EasyPrivacy filter blocks this domain.
