### ISSUE TITLE
360safe.com, 360.cn

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#218]
User ID 2499074:

> Recently, some spyware has been discovered on Samsung Android smartphones, and some apps are connecting to Chinese servers, specifically to 360safe.com and 360.cn here is the link where the info can be found : https://android.gadgethacks.com/how-to/prevent-samsungs-shady-360-storage-cleaner-from-phoning-home-china-0225941/
> 
> I would really appreciate if this domains are added to the blacklist, since many people also use your service on these devices and since the Huawei privacy scandal,� is better to avoid suspicious apps that send encrypted info to China.

**Comment by ameshkov** [comment]
1. It's unclear what data is exactly going through there
2. Blocking these domains would block all Qihoo apps

While I might be with the user here, we cannot afford to do that in AdGuard DNS, we're trying to make it not break legitimate things.
