### ISSUE TITLE
Format doesn't block DNS requests on Android

### ISSUE THREAD

**Issue by LewisLebentz** [AdguardTeam/AdGuardSDNSFilter#22]
I see that this filter blocks DNS requests on the Android app, so I tried to use another filter with the same format:

https://raw.githubusercontent.com/EnergizedProtection/block/master/bluGo/formats/filter

To block more domains via DNS, however once added to the app, it treats the list like a normal adblock list (blocking HTTP GET). Is there something special I can do to make Android treat it as a DNS block list?

I know it's not 100% related to this, but as the list uses the same format, I'd expect it to work in the same way. Not sure if it's a bug with Android, or if I'm doing something wrong. They provide block lists in other formats here: https://github.com/AdroitAdorKhan/Energized none seem to work.

The only thing that does seem to block DNS requests is if you click a DNS request from the log file, then choose to block it from there.

**Comment by ameshkov** [comment]
Which version of AdGuard do you use?

**Comment by ameshkov** [comment]
Ah, I think I got it.

So the thing is that the current version of AG uses the SDN filter AND your `User filter` for DNS-level requests blocking. Every other filter is ignored.

This is not a final solution, but this will not change in v3.0. The DNS part of the app will be reworked in the future and we will add support for custom hosts files and ad blocking filters, but the point is that these filters will be independent and DNS-specific.
