### ISSUE TITLE
rbbmediaadp-vh.akamaihd.net

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#221]
### Environment
AdGuard for iOS, AdGuard DNS - Standard

### Description
In-app video domain for the following application: https://apps.apple.com/de/app/unser-sandm%C3%A4nnchen/id561035119

### Screenshot

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/33634917/72697177-a8dd1780-3b47-11ea-9f91-14fdc480496f.png)

</details>

**Comment by Alex-302** [comment]
It is not blocked by DNS
![image](https://user-images.githubusercontent.com/8361299/72718074-e361a700-3b7d-11ea-801f-105ab6ab7991.png)
