### ISSUE TITLE
found similar domain should in blacklist 'beacons5.gvt3.com'

### ISSUE THREAD

**Issue by Mosney** [AdguardTeam/AdGuardSDNSFilter#228]
I notice a new domain which not in blacklist but similar with some item in blacklist, may be it is the latest deployment and should list in.
`beacons5.gvt3.com
`

Other items at the same time, may be relevant 
```
redirector.gvt1.com
r1---sn-i3belnez.gvt1.com
```
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22477230/73601883-5880a380-45a4-11ea-8bba-3670143cca89.png)
</details>

**Comment by ameshkov** [comment]
`redirector.gvt1.com` -- this one is used in many places and it's not a tracking domain.

We should check this "beacons" domain though.

**Comment by Alex-302** [comment]
"beacons" are blocked by DNS
![image](https://user-images.githubusercontent.com/8361299/73646646-89370a80-4682-11ea-9544-352b392b38f8.png)

"redirector" - not blocked
![image](https://user-images.githubusercontent.com/8361299/73646677-9c49da80-4682-11ea-957a-51bb9e4fdc67.png)

**Comment by ameshkov** [comment]
`beacons5.gvt3.com ` ?

**Comment by Alex-302** [comment]
beacons5.gvt3.com is also blocked(screenshot above)

**Comment by Mosney** [comment]
But in my side, `beacons5.gvt3.com` not blocked.

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/87427035-d8497a00-c5e8-11ea-8f5d-ed32966b46eb.png)

**Comment by Mosney** [comment]
![Screenshot_20200715-102722](https://user-images.githubusercontent.com/22477230/87496273-cff34c80-c685-11ea-9475-7194f425317e.jpg)

**Comment by Mosney** [comment]
Due to cname block for now it can be block.
```
Blocked by CNAME or IP in response
CNAME: beacons6.gvt2.com. (ttl=1)
A: 203.208.43.66 (ttl=1)
```
