### ISSUE TITLE
https://shop.euromaster.de/infos-Reifenwechsel

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdGuardSDNSFilter#239]
### Steps to reproduce

Okay, this one is a litte strange, because it seems to be sporadic and the Filterlog not shows exactly what gets blocked.

1. Enable Adguard Home with "AdGuard Simplified Domain Names filters" or Adguard DNS
2. Browse https://shop.euromaster.de/infos-Reifenwechsel 
3. Scroll down to "Kein passendes Paket dabei?__ Konfigurieren Sie sich Ihren Radwechsel einfach selbst."
4. See an infinite loading circle (maybe... because it seems sporadic)

Since my Adguard Home Filterlog not shows any blocked related to that, I tried Adguard DNS with same issue and result. So I tried 1.1.1.1 and 9.9.9.9 and had no issue. So the issue still had something to do with AdGuard Simplified Domain Names filters.

I was asking in Telegram and @ameshkov confirmed to have the same issue.

At the same moment, the page loaded fine again on my end. SDNS was still enabled. Strange.

He advised to try the following rules:
`@@||ssl.google-analytics.com^$important`
`@@||abtasty.com^$important`
`@@||manager.tagcommander.com^$important`

### Expected behavior

You get a filtermask to look for a shop

### Actual behavior

You only see a loading circle.

<details><summary>Screenshot:</summary>

- Actual behavior:

![euro](https://user-images.githubusercontent.com/6276915/75285057-33cfc280-5816-11ea-8027-707c509f7acb.png)

- Expected behavior:

![euro3](https://user-images.githubusercontent.com/6276915/75285123-4d710a00-5816-11ea-9a34-be157a5bfacc.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 1.1.1.1
| Operating system and version:| Windows 10, Firefox 73.0.1

**Comment by Alex-302** [comment]
@Morku please check it tomorrow.

**Comment by Morku** [comment]
@Alex-302 

In the morning, it worked for 2x times.

Now I checked again and the issue is the same. Loading circle.

When I disable SDNS, it's loading fine again. Enable back -> loading circle, but no blocked dns shows in the AGH Log.

When I subscribe SDNS in Adguard for Windows, bypass AGH -> the issue is the same -> loading circle, but here I get a filtered element:
[20200227_adguard_filtering_log_records.zip](https://github.com/AdguardTeam/AdGuardSDNSFilter/files/4261454/20200227_adguard_filtering_log_records.zip)

So I added `@@||try.abtasty.com/403fb16c20596e4691fbe9ec5db9720e.js$domain=shop.euromaster.de,third-party` offered by AGfW.

Reloaded -> working
Disabled custom filter -> not working anymore
Enabled back -> working
Diabled again -> not working
Enabled -> working
[...]

It seems to be related.

**Comment by Alex-302** [comment]
Please check tomorrow. Changed SDN filter.

**Comment by Alex-302** [comment]
@Morku

**Comment by Morku** [comment]
@Alex-302 
It worked 3 days ago, but I wanted to check at different times, since the issue is sporadic. 

Since 2 days I have issues to reach the page at all. 
I will try in 3 hours again.

**Comment by Morku** [comment]
`shop.euromaster.de` still has Timeout.

**Comment by Morku** [comment]
Page is running since 3 days again and every try was successful. 👍
