### ISSUE TITLE
ultracomp.ru

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardSDNSFilter#242]
Hello,

the rule ||51.77. blocks the domain **ultracomp.ru** (this is actually a former computer hardware store):
![image](https://user-images.githubusercontent.com/45385632/75332209-0e35ce00-5895-11ea-8511-ed9750428ab8.png)
Thank you.

**Comment by Alex-302** [comment]
duplicate
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/240
