### ISSUE TITLE
please in DNS filter add filter that enables removing of the ads from websites with Italian content

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardSDNSFilter#243]
@sviluppoSoftware commented on [Mon Feb 24 2020](https://github.com/AdguardTeam/AdguardFilters/issues/50401)

i have read  https://kb.adguard.com/en/general/adguard-ad-filters and seems there isn't an Italian filter to block ads from websites with Italian content not even in DNS filter, are you intent to add this in the future in particular in DNS filter?

thanks for your work and response.

**Comment by Alex-302** [comment]
ad servers from this filter(must be checked):
<details>

||24network.it^$third-party
||377d936c10e6811f484c-6402e46c712497f58e3f77a59f47bbd5.r17.cf2.rackcdn.com^
||4strokemedia.com^$third-party
||888.it^$popup,third-party
||98.130.248.39^$popup,third-party
||a.trend-online.it^
||ad.citynews.it^
||ad.edision-nord.it^
||ad.internapoli.it^
||ad.jamba.it^
||ad.ricevitori-digitali.com^
||ad4mat.it^$third-party
||adagiobanner.s3.amazonaws.com^
||adagionet.com^$third-party
||adbrawl.com^$third-party
||adbreak.ch^$third-party
||addyon.com^$third-party
||adnext.it^$third-party
||adpartner.it^$third-party
||adsolutions.nl^$third-party
||adultsadv.com^$third-party
||adv-italiana.net^$third-party
||adv2.spaziogames.it^$popup
||adventertainment.it^$third-party
||advhits.com^$third-party
||advit.it^$third-party
||advplace.com^$third-party
||advx.esprimo.com^
||aff.buonisconto.it^
||affiliago.it^$third-party
||affiliate2.hardstore.com^
||affiliatesys.interwetten.it^
||affiliati.bet2bet.it^
||affiliati.cellulare.net^
||affiliation.sostariffe.it^$third-party
||affiliationpartner.it^$third-party
||affiliazione.immobiliare.it^
||affiliazioni.me^$third-party
||affiliazioni.misterdomain.eu^$third-party
||affiliazioniweb.com^$third-party
||annuncivari.altervista.org^$third-party
||atomikad.com^$third-party
||banner-madai-com.s3.amazonaws.com^
||banner.aranzulla.it^
||banner.casino2k.com^
||banner.crol.it^
||banner.orizzontescuola.it^
||banneradmin.rai.it^
||bannerconnect.biz^$third-party
||bannerexplosion.it^$third-party
||bannergratis.it^$third-party
||bannerout.com^$third-party
||bannerplace.it^$third-party
||bannerporno.com^$third-party
||bannerpress.it^$third-party
||bannerpromotion.it^$third-party
||banzaiadv.it^$third-party
||beead.it^$third-party
||betclic.it/partner.aspx?$popup
||booking.fioccovacanze.it^$third-party
||brznetwork.com^$third-party
||bt.rcs.it^
||buyon.it^$third-party
||caniaddestrati.org^$third-party
||casadivita.despar.it^$third-party
||cdn.adultsadv.com^
||clacson24.com^$third-party
||click.html.it^
||clickadv.it^$third-party
||clickpoint.it^$third-party
||consigli.it^$third-party
||coreg-feed.com^$third-party
||creativita.gsf.rcs.it^
||crmpilot.it^$third-party
||d1a6pzosbglc5p.cloudfront.net^
||d1oaxhr280l1ho.cloudfront.net^
||d1yhzddoi8ev99.cloudfront.net^
||d2moz0h55szev9.cloudfront.net^
||d3qrbrazsnzdog.cloudfront.net^
||delosnetwork.it^$third-party
||digitaladv.despar.it^
||digitalbees.it^$third-party
||divascam.com^$third-party
||dzt1km7tv28ex.cloudfront.net^
||eadv.it^$third-party
||easymarketcrs.it^$third-party
||ebuzzing.it^$third-party
||edinetadv.com^$third-party
||epeex.io^$third-party
||erosadv.com^$third-party
||evolutionadv.it^$third-party
||exmarketplace.com^$third-party
||feed.yoodeal.net^
||firebanner.com^$third-party
||free.netsons.com^
||funpage.it^$popup,third-party
||gambling-italia.com^$third-party
||gbucket.ch^$third-party
||golandwin.it^$popup,third-party
||gooble.info^$popup
||heyos.com^$popup,third-party
||iads.iltrovatore.it^
||inaffiliago.it^$third-party
||insite.sconty.it^$third-party
||ioladv.it^$third-party
||iperbanner.com^$third-party
||laricettadellostudente.it^$third-party
||leaderaffiliation.com^$third-party
||leonardoadv.it^$third-party
||linkto.org^$third-party
||livepartners.it^$third-party
||lopfly.com^$third-party
||lupoporno.com^$popup,third-party
||maxiadv.com^$third-party
||mediaadv.mediaon.it^
||mediamond.it^$third-party
||mmvid.s3.amazonaws.com^
||mondoecommerce.it^$third-party
||mondojuventus.it^$third-party
||mperience.net^$third-party
||mycookies.it^$third-party
||nativery.com^$third-party
||netfilia.com^$third-party
||network.alfemminile.com^
||newclick.com^$third-party
||nextadv.eu^$third-party
||noddus.com^$third-party
||novadv.com^$third-party
||oas.repubblica.it^
||oasjs.kataweb.it^
||oipzyrzffum.ovh^
||okincontri.com^$popup,third-party
||ovoadv.com^$third-party
||p.italia-film.org^
||panea.it^$third-party
||partner.leguide.com^$third-party
||partners-aedgency.com^$third-party
||partypartners.it^$third-party
||payclick.it^$third-party
||paypublicity-system.com^$third-party
||paypublicity.it^$third-party
||perfcreatives.com^$third-party
||pipaoffers.com^$third-party
||pirchio.com^$third-party
||plavid.com^$third-party
||plx.pornototale.com^
||pop.virgilio.us^
||popspace.virgilio.us^
||promo.easy-dating.org^
||promo.ezstatic.com^
||prontocampaign.com^$third-party
||pubbli7.it^$third-party
||radxcomm.com^$third-party
||ragazzeinvendita.com^$third-party
||rcsadv.it^$third-party
||reachadv.it^$third-party
||resources.saldiprivati.com^$third-party
||rivenditori.aruba.it^$third-party
||rizzonelli.it^$third-party
||roi.ediscom.it^
||s-lab.it^$third-party
||s-p-o-n-s-o-r.com^$third-party
||samspot.softairmania.it^
||sbanner.com^$third-party
||scambiobanner.aruba.it^$third-party
||scambiobanner.it^$third-party
||scambiobanner.net-parade.it^$third-party
||scambiobanner.org^$third-party
||scambiobanner.tv^$third-party
||scambiositi.com^$third-party
||sda.quinews.net^
||secure.emp-online.it^$third-party
||seolabadv.it^$third-party
||shoppingbox.leguide.com^$third-party
||simpleview.it^$third-party
||softwareplanet.net^$third-party
||spazioautomobile.it^$third-party
||spicciolo.com^$third-party
||sponsor.imperiapost.it^
||spotmix.libero.it^
||spytwins.com^$popup,third-party
||stats.betradar.com^$third-party
||subito.paneaserver.net^
||sunaffiliation.com^$third-party
||superbanner.org^$third-party
||tagvideo.eu^$third-party
||tekno4advertising.com^$third-party
||tgadv.it^$third-party
||tgadvcdn.it^$third-party
||ticketcrociere.gazzettadelsud.it^
||ticketcrociere.lagazzettadelmezzogiorno.it^
||ticketcrociere.lasicilia.it^
||tomshw.corley.it^
||universosmartphone.it^$third-party
||uplink.aruba.it^$third-party
||upstory.it^$third-party
||vhf.tbiz.it^
||videomatictv.com^$third-party
||viralbeat.com^$third-party
||vitaquotidiana.com^$third-party
||wbusiness.fr^$third-party
||webpartner.mrcrawler.it^
||widebanner.com^$third-party
||widget.promoqui.it^
||ws.shoppydoo.com^$third-party
||wtpn.twenga.de^
||wtpn.twenga.it^
||yobee.it^$third-party
||zanox-affiliate.de^$third-party
||zodiakactive.com^$third-party
||zxadhosting.it^$popup
</details>

**Comment by ameshkov** [comment]
@Alex-302 wouldn't it be easier to add it to AdGuard Base filter for now?

**Comment by Alex-302** [comment]
These domain are not checked. Just prepared list.

**Comment by Alex-302** [comment]
Resulting list withour dead, duplicating and questionable domains:

<details>

||24network.it^
||4strokemedia.com^
||888.it^
||a.trend-online.it^
||ad.citynews.it^
||ad4mat.it^
||adagionet.com^
||adbrawl.com^
||adbreak.ch^
||addyon.com^
||adn.plxnt.com^
||adnext.it^
||adpartner.it^
||adsolutions.nl^
||adultsadv.com^
||advertisingaspiag-*.eu-west-1.elb.amazonaws.com^
||advhits.com^
||advit.it^
||advplace.com^
||advx.esprimo.com^
||affiliago.it^
||affiliati.bet2bet.it^
||affiliation.sostariffe.it^
||affiliationpartner.it^
||affiliazioni.me^
||affiliazioni.misterdomain.eu^
||affiliazioniweb.com^
||annuncivari.altervista.org^
||atomikad.com^
||banner.casino2k.com^
||banner.crol.it^
||banner.orizzontescuola.it^
||bannerconnect.biz^
||bannerexplosion.it^
||bannergratis.it^
||bannerout.com^
||bannerporno.com^
||bannerpress.it^
||bannerpromotion.it^
||banzaiadv.it^
||brznetwork.com^
||buyon.it^
||cdn.adultsadv.com^
||clacson24.com^
||clickadv.it^
||clickpoint.it^
||consigli.it^
||coreg-feed.com^
||delosnetwork.it^
||digitalbees.it^
||divascam.com^
||eadv.it^
||easymarketcrs.it^
||edinetadv.com^
||epeex.io^
||eu1.s4.xtremscores.com^
||evolutionadv.it^
||exmarketplace.com^
||firebanner.com^
||free.netsons.com^
||funpage.it^
||gbucket.ch^
||golandwin.it^
||gooble.info^
||heyos.com^
||html-aws.origin.html.it^
||iads.iltrovatore.it^
||inaffiliago.it^
||insite.sconty.it^
||iperbanner.com^
||italia-film.org^
||leaderaffiliation.com^
||leonardoadv.it^
||linkto.org^
||livepartners.it^
||lopfly.com^
||lupoporno.com^
||maxiadv.com^
||mediamond.it^
||mperience.net^
||mycookies.it^
||nativery.com^
||netfilia.com^
||newclick.com^
||noddus.com^
||oas.repubblica.it^
||oasjs.kataweb.it^
||oipzyrzffum.ovh^
||okincontri.com^
||ovoadv.com^
||panea.it^
||partner.leguide.com^
||partypartners.it^
||paypublicity.it^
||pirchio.com^
||plavid.com^
||pop.virgilio.us^
||popspace.virgilio.us^
||promo-vip.ezzed.com^
||prontocampaign.com^
||radxcomm.com^
||ragazzeinvendita.com^
||rcsadv.it^
||reachadv.it^
||redweb3.redfoxy.it^
||resources.saldiprivati.com^
||rivenditori.aruba.it^
||rizzonelli.it^
||roi.ediscom.it^
||s-lab.it^
||s-p-o-n-s-o-r.com^
||sbanner.com^
||scambiobanner.aruba.it^
||scambiobanner.it^
||scambiobanner.net-parade.it^
||scambiobanner.org^
||scambiobanner.tv^
||scambiositi.com^
||sda.quinews.net^
||seolabadv.it^
||simpleview.it^
||softwareplanet.net^
||spicciolo.com^
||spotmix.libero.it^
||spytwins.com^
||static-vip.ezzed.com^
||sunaffiliation.com^
||superbanner.org^
||tagvideo.eu^
||tgadv.it^
||tgadvcdn.it^
||ticketcrociere.gazzettadelsud.it^
||uplink.aruba.it^
||upstory.it^
||videomatictv.com^
||viralbeat.com^
||wbusiness.fr^
||widebanner.com^
||widget.promoqui.it^
||yobee.it^
||zodiakactive.com^

</details>

@AdguardTeam/filters-maintainers please take a look.

**Comment by Alex-302** [comment]
@AdguardTeam/filters-maintainers

**Comment by AdamWr** [comment]
I'm not sure about these rules:
```
||888.it^
||buyon.it^
||clacson24.com^
||consigli.it^
||delosnetwork.it^
||pirchio.com^
||reachadv.it^
||spytwins.com^
```
It seems that these websites are not advertising companies.

<hr>

Maybe instead of `||mediamond.it^` it would be better to add `||adv.mediamond.it^` - https://publicwww.com/websites/%22mediamond.it%22/

<hr>

`||oasjs.kataweb.it^` - as I recall blocking requests from this domain breaks video player on some websites.

<hr>

It seems that these are porn websites, so I'm not sure if should be blocked by DNS:
```
||divascam.com^
||lupoporno.com^
||ragazzeinvendita.com^
```

**Comment by Alex-302** [comment]
Thanks. Updated list. Will create pull request.
