### ISSUE TITLE
Whitelist required for disney plus to work

### ISSUE THREAD

**Issue by Thomas499** [AdguardTeam/AdGuardSDNSFilter#254]
### Steps to reproduce

1. Download disney plus app onto a firestick
2. Enable 176.103.130.130 as the DNS for the firestick
3. Try to open the disney plus app

### Expected behavior

Disney plus should work. This would happen if adguard whitelisted 
prod-ripcut-delivery.disney-plus.net

### Actual behavior

you will see the message below which clearly says unable to connect to disney plus

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/38442058/76165859-9464d680-6117-11ea-8753-2dd8009e3d58.png)
</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (176.103.130.130)
| How did you setup DNS configuration:| (System/DNSCrypt app/Router)
| Device model:| (4k firestick)
| Operating system and version:| (Fire OS 6.2.7.1 (NS6271.2493))

**Comment by xortim** [comment]
I had to apply the following to get Disney+ working on an AppleTV

```
@@||global.edge.bamgrid.com^$important
@@||search-api-disney.svcs.dssott.com^$important
@@||prod-ripcut-delivery.disney-plus.net^$important
@@||search-api-disney.bamgrid.com^$important
```

**Comment by owah** [comment]
bamgrid and dssott (disney streaming service over-the-top) are both subsidaries of Disney and are needed for streaming.

https://en.wikipedia.org/wiki/Disney_Streaming_Services
https://support.opendns.com/hc/en-us/articles/360037591112-Domains-to-Allow-for-Disney-Plus

**Comment by Alex-302** [comment]
@xortim which rules block that domains?

**Comment by xortim** [comment]
@Alex-302 I only have `AdGuard Simplified Domain Names filter` enabled, so it's something in there - didn't really  look through to identify which rules specifically match those.

**Comment by Alex-302** [comment]
I do not know how to check it outside USA.
Could you, please, do following steps?
- disable exclusions;
- close app;
- clear AdGuard filtering log(in menu);
- reproduce an issue and make copy triggered rules from filtering log(you can hide processed requests using filtering log options)

**Comment by owah** [comment]
Hi, your description mentions:

A filter composed of several other filters (English filter, Social media filter, Spyware filter, Mobile Ads filter, EasyList and EasyPrivacy)

This false positive is occuring upstream, at EasyPrivacy. I've notified them already that bamgrid.com is needed for Disney+

The problematic domain is:

||bamgrid.com^

**Comment by xortim** [comment]
I  looked through my query log for each, and the matching rule for all of them was `||bamgrid.com^`

**Comment by ameshkov** [comment]
@Alex-302 let's just exclude it, I am not sure why it's blocked in the first place
