### ISSUE TITLE
klaviyo.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#262]
Blocked by standard DNS. Was previously in safebrowsing blacklist (currently removed).

### DNS Servers
dns-vultr-fra-2, dns-vultr-fra-4

### nslookup
Non-authoritative answer:
Name: static.klaviyo.com
Addresses: ::
0.0.0.0

**Comment by Alex-302** [comment]
Why it is must be excluded?

**Comment by Alex-302** [comment]
Replaced by specific URL blocking rule.
