### ISSUE TITLE
appodeal.com, artifactory.appodeal.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#267]
### Server
dns-vultr-ny-1

### DNS
Standard IPv4

### nslookup
<details><summary>nslookup:</summary>

~ $ nslookup

> server 176.103.130.130

Default server: 176.103.130.130

Address: 176.103.130.130#53

> artifactory.appodeal.com

Server:        176.103.130.130

Address:    176.103.130.130#53

 

Non-authoritative answer:

Name:    artifactory.appodeal.com

Address: 0.0.0.0

> appodeal.com

Server:        176.103.130.130

Address:    176.103.130.130#53

 

Non-authoritative answer:

Name:    appodeal.com

Address: 0.0.0.0
</details>

**Comment by ameshkov** [comment]
`appodeal.com` is an ad network blocked by a lot of different lists:
https://urlfilter.adtidy.org/v1/checkDomain?domain=appodeal.com

**Comment by akmLaVx** [comment]
Thank you for specifying. We've been told this is an app development tool.

**Comment by ameshkov** [comment]
Well, `artifactory.appodeal.com` may be counted as one and we can make an exception for this one alone.

**Comment by BurgerZ** [comment]
So the only way to use AdGuard DNS and Appodeal network in projects is override hosts file (like I did)?
As a temporary workaround solution I use the following in my /private/etc/hosts (macOS):
```
23.83.127.103 artifactory.appodeal.com
104.17.92.108 appodeal.com
```

**Comment by ameshkov** [comment]
@BurgerZ well, most likely this is the best way.

Also, I guess unblocking `artifactory` is not a problem. Why do you need the top-level `appodeal.com` domain?

**Comment by Alex-302** [comment]
@BurgerZ you can try our DNS without domains blocking
https://adguard.com/en/adguard-dns/overview.html

**Comment by BurgerZ** [comment]
@ameshkov The top level domain I use to read documentation, sign in and check my balance, etc.
But it's not the problem if it will be blocked by your DNS.

@Alex-302 Yes, I could, but I'd like to go with blocking ones.

Anyway, thanks for your support. I think problem is solved (I'm good with hosts modification solution).

**Comment by ameshkov** [comment]
@Alex-302 anyways let's unblock `artifactory` subdomain, otherwise it will break build for apps that use appodeal.

@BurgerZ if you have a spare device or a VPS, you might want to give a try to [AdGuard Home](https://github.com/AdguardTeam/AdGuardHome), this way you'll be fully in control of what's blocked.

**Comment by BurgerZ** [comment]
@ameshkov Thanks for the AdGuard Home. Looks great!

**Comment by Alex-302** [comment]
> anyways let's unblock the `artifactory` subdomain

ok
