### ISSUE TITLE
||app.link^

### ISSUE THREAD

**Issue by k03mad** [AdguardTeam/AdGuardSDNSFilter#269]
Hello,

This rule breaks some redirects to Android apps on phone

### Steps to reproduce
List: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt, updated 22.05.20-16:58

1. open https://amp.reddit.com/r/Android/comments/b6nqme/adguard_is_amazing/
2. button "Open Reddit app" with reddit.app.link domain

1. open https://music.yandex.ru/album/9993404
2. button "Listen in app" with music.app.link domain

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| home
| How did you setup DNS configuration:| AdGuard Home
| Device model:| OnePlus 5, Chrome last
| Operating system and version:| Android 9

**Comment by Alex-302** [comment]
Will be fixed in https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/271
