### ISSUE TITLE
||branch.io^

### ISSUE THREAD

**Issue by k03mad** [AdguardTeam/AdGuardSDNSFilter#270]
Hello,

This rule breaks redirect to certain album in a Yandex Music Android app

### Steps to reproduce
List: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt, updated 22.05.20-16:58

1. open https://music.yandex.ru/album/9993404
2. click "Listen in app" button
3. app opens at home screen, not at album

After add `@@||api2.branch.io^$important` to user filters all works fine
I've always think that this is app bug... :)

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| home
| How did you setup DNS configuration:| AdGuard Home
| Device model:| OnePlus 5, Chrome last
| Operating system and version:| Android 9
| Yandex Music App:| Current stable from Play

**Comment by Alex-302** [comment]
Cannot reproduce.

**Comment by k03mad** [comment]
This is strange, api2.branch.io and app.link domains are using for deep links into apps.

Here is example [at branch repo](https://github.com/BranchMetrics/branch-deep-linking-public-api#structuring-a-dynamic-deep-link-for-applink-domains):
```
https://branch.app.link?$deeplink_path=article%2Fjan%2F123&$fallback_url=https%3A%2F%2Fgoogle.com&channel=facebook&feature=affiliate
```
If you open https://music.yandex.ru/album/9139480 with android emulation at Chrome, listen button has the similar href:
```
https://music.app.link/?campaign=yamusicweb&channel=musicSplashScreen&actions=deeplink&deeplink_url=yandexmusic%3A%2F%2Falbum%2F9139480%2F&tags[]=splash_album&sign_up_method=yandex&sign_up_login=..."
```
I think, after open this url at phone, music app try to reach api2.branch.io — it can't, and something goes wrong here. It's weird but reproduces at 3 different android phones, 2 at home with AdGH, and 1 another with tls://dns.adguard.com at wifi settings

**Comment by k03mad** [comment]
> Cannot reproduce.

Here is video: https://yadi.sk/i/PfR2W9So2nvuAw

With `dns.adguard.com` private dns enabled — button click opens main app screen
After disable dns — button opens correct album screen
After reenable — again, main screen

Google Chrome 80 (reproduces in other browsers too: FF, Ya.Bro)

**Comment by k03mad** [comment]
Now I can't reproduce it either
