### ISSUE TITLE
||minexmr.com^

### ISSUE THREAD

**Issue by 76561198327578881** [AdguardTeam/AdGuardSDNSFilter#273]
please consider removing ||minexmr.com^ rule

**Comment by Alex-302** [comment]
Where is it used?

**Comment by 76561198327578881** [comment]
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt

**Comment by Alex-302** [comment]
It is loaded from EasyPrivacy. Will be exluded from SDN filter.
