### ISSUE TITLE
Remove subdomains if thier parent domain is already included

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdGuardSDNSFilter#275]
Related: https://github.com/AdguardTeam/AdguardFilters/issues/47398#issuecomment-572889146
As DNS filter uses ABP syntax, there is no point to include subdomains if their parent domains are included. So why don't you add a removal process of subdomains when you compile the list as such a little bandwidth will be saved for those user.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/HostlistCompiler #3](https://github.com/AdguardTeam/HostlistCompiler/issues/3) via [**ZenHub**](https://www.zenhub.com/)
