### ISSUE TITLE
||googletagmanager.com^

### ISSUE THREAD

**Issue by mKoonrad** [AdguardTeam/AdGuardSDNSFilter#276]
It's very big ad/tracking scripts platform. I don't know why I can find this domain on exclusion list.

**Comment by ameshkov** [comment]
AdGuard SDN filter is supposed to be casual-user-friendly so if tracker breaks too many websites, we don't include it in the list. Blocking this domain, unfortunately, breaks a lot of websites.

**Comment by mKoonrad** [comment]
@ameshkov It's very bad news. Google Tag Manager is one of biggest tracking platforms. I don't see any issues with blocking this script for many months with any other method. It's bad news for privacy that you don't block it also in AdGuard DNS service. Please consider blocking again this domain.

**Comment by ameshkov** [comment]
@mKoonrad AdGuard DNS is supposed to be casual user friendly so we have to be careful with what's broken. I suggest you trying AdGuard Home if you want to be in full control over what's blocked.
