### ISSUE TITLE
||connect.facebook.net^

### ISSUE THREAD

**Issue by mKoonrad** [AdguardTeam/AdGuardSDNSFilter#277]
Facebook Pixel tracking code

**Comment by ameshkov** [comment]
We cannot afford to block it because blocking it breaks a lot of websites.

**Comment by mKoonrad** [comment]
@ameshkov It's domain for Facebook Pixel tracking code and Facebook Social plugins. Pixel tracking code is unnecessary. You keep this rule for plugins? Without adding this rule Facebook tracking isn't blocked in any way.

**Comment by ameshkov** [comment]
@mKoonrad 

> You keep this rule for plugins?

No, there we can avoid breaking websites while still continuing to block this. Unfortunately, DNS is not as flexible as a typical browser ad blocker.

**Comment by mKoonrad** [comment]
@ameshkov What about `||*fbevents.js` rule? It's more precise to block Facebook tracking script. Example URL `https://connect.facebook.net/en_US/fbevents.js`
