### ISSUE TITLE
Smart TV ADS

### ISSUE THREAD

**Issue by scafroglia93** [AdguardTeam/AdGuardSDNSFilter#278]
https://cloud.linuxfabrik.io/index.php/s/dJRTmz5aWQZgpFc

PDF from accademic research

(it's my nextcloud space) it's safe

**Comment by ameshkov** [comment]
Yeah, I read this paper. There are no new domains and the point of the research is not to find new domains, but to explain what limitations and issues simple DNS-level blocking has.
