### ISSUE TITLE
Blocked Keenetic update/help services

### ISSUE THREAD

**Issue by Quake4** [AdguardTeam/AdGuardSDNSFilter#280]
### Steps to reproduce
1. Установить модуль adguard на роутере keenetic
2. Включить  модуль adguard и установит Семейный фильтр
3. Перегрузить роутер.
4. Зайти на вкладку системы и убедится, что обновления прошивки и модули не выбираются, так же не работает помощь.

### Expected behavior
Должна провериться версия прошивки и доступны модули для выбора. 

### Actual behavior
Недоступны серверы обновлений, модули и справка.

### Your environment
Keenetic Speedster 3.3.15

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Family
| How did you setup DNS configuration:| keenetic router
| Device model:| speedster
| Operating system and version:| 3.3.15

**Comment by ameshkov** [comment]
А какие домены у них знаете?

**Comment by Quake4** [comment]
Сам намудрил с настройкой. Спасибо, моя ошибка.
