### ISSUE TITLE
my.tealiumiq.com/

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#287]
### nslookup
_nslookup my.tealiumiq.com 176.103.130.130
Server:  176-103-130-130.dns.adguard.com
Address:  176.103.130.130

Non-authoritative answer:
Name:    my.tealiumiq.com
Addresses:  ::
          52.52.43.226
          13.57.157.39_

### Actual behavior
Returns an NXDOMAIN error when opening the site.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default, 176.103.130.130
| How did you setup DNS configuration:| AdGuard Home
| Device model:| Unspecified
| Operating system and version:| Unspecified

**Comment by Snigeljagaren** [comment]
Router model is Ubiquity’s Amplifi, latest firmware. I use your .130 and .131 IP:s.

**Comment by Snigeljagaren** [comment]
Great work. This now works fine and as expected!
Thanks a lot!
