### ISSUE TITLE
||*.google-analytics.com^

### ISSUE THREAD

**Issue by mKoonrad** [AdguardTeam/AdGuardSDNSFilter#293]
It's not duplicate of ||google-analytics.com^ because current rule not working to
`https://www.google-analytics.com/analytics.js`

Please consider fix all rules `||example.com^` to `||*.example.com^`. Currently all rules not working for `www.` URL prefix.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| N/A
| How did you setup DNS configuration:| AdGuard Home
| Device model:| N/A
| Operating system and version:| N/A

**Comment by Alex-302** [comment]
`||google-analytics.com^` covers `https://www.google-analytics.com/analytics.js`
`||` means subdomains.

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/78925346-f5c7ee80-7aa3-11ea-9e7f-2e6f524ed331.png)

**Comment by mKoonrad** [comment]
@Alex-302 Hmm. So I probably found another bug with Check the filtering feature in AdGuard Home. AdGuard Home block these requests (I checked logs) but I was sure that typing URL to Check the filtering feature I can check it. Am I right?

![image](https://user-images.githubusercontent.com/11725227/78925672-19873680-7a9c-11ea-971d-23f8f517f0a0.png)

**Comment by ameshkov** [comment]
You should check the domain name, not a URL
