### ISSUE TITLE
False Positive -> bet at home

### ISSUE THREAD

**Issue by scafroglia93** [AdguardTeam/AdGuardSDNSFilter#294]
bet at home is a legit website (betting), please unlock

**Comment by Alex-302** [comment]
@scafroglia93 do you say about `bet-at-home.com`? Removed it from the filter.

**Comment by scafroglia93** [comment]
Yep

10 apr 2020 13:25:49 Alex <notifications@github.com>:

**Comment by Alex-302** [comment]
ok
