### ISSUE TITLE
Pulsar.ebay.com blocked

### ISSUE THREAD

**Issue by sysfu** [AdguardTeam/AdGuardSDNSFilter#302]
### Steps to reproduce

1. Click on an Ebay item in 'Similar sponsored items' below a product listing, and DNS fails to resolve
2. https://pulsar.ebay.com/plsr/clk/0/SADS/9?pld=%7B%22mecs%22%3A%22233540350682a36e25eba01d4b8983776ec806559b45%22%2C%22ampid%22%3A%22PL_CLK%22%2C%22enc%22%3A%22AQAEAAAD4HHpa5rrPQvlKDQHzgmUGPDdAlf%2Fo%2Bf8QaMWBxCugCwEV4PsGLblWV6SULNjf1ezuzUPWLOxhjuqhUb4%2BBLBvh2hyAssuW24efJ7KlDS2sHULkpbuCRVjj3MVaBq9IIdNWjhFu212rp8uo1r8cD5GOdYUPGfuRBTC7nZvZv9bbCuqetEA75yz1U5NR7RXgMminjtugsakje9SRoRB0qrjIBBOwqsor2foWnwj1xMbKFAnKaw%2BkTjzkzA2%2BR6jJQgrJn1%2BWAAlS7pAq%2BKfGYzDP32jc3S9m6eEAW6iFBknlKrmtxF5Kw2rRHamXyx3NG6GCttizxCKhTtxBeafuxIMbbo%2FOq9dzfa30wqqElsUGn6M1TeLI3dStyoUP5G2UKV8y%2BIODN7PFRTNKB1EBnRIeDTVfMRXX3CtdJ3b7Kt7KPV1I9BbJBVAAXvezTiADBXtFWt6TXW7dRtknpTXwu0nVxpp8aT%2BhT02M6h22tgK8A2XlqouoJySYxjNQBnHzvzUhric%2Fc96LxoV2059cBMZyv1wDrnPAR6k%2BZQ7uH7gdkkEqe7Wf7hMTdftD9PE52QNMJwmusT5Rz9v56dRFbKLVV5JbAmrCMgsHs1l4Ybm2E%2Bw87UNYbXGpBSlP9vvEGPUMaHH1aoWdgr8UxjamdwxpPPsmkHbeyB3yaU2RXNS0V5z4xdOoqGL4XjJrNnpW69NCR8GRtwrbN0etCHRvO6qVRYIfMxxS8NtyYqp%2FcPTmP5d8ekea0lj5m0%2FbsviG5FCFIjlrodJBzlhdHVJOo16VdjSTglAKZ9Yx3L%2FyI%2BaJLP08p2JCb7N3ZwJV1r9eAgAUtEz2YbfWxC39KBHJBFCs9IpU8o48g96H41W9zkO8xcRz1osHnTaQClDEjg9rPW%2BviAm56cAwJWyZVsRIgdpNEUJo4MdgHG%2BwQISn4LLzFlbvN8MoeJ1aX5h1w%2FonsYLT38K2zg5R1M3h%2FtLcLbSWt4XS0TysRlHWzZKU3kDyl98Um36bDUDOIO%2BOKjaEQo12o8XR%2BU24M0ZDmAHehkNB%2B2YRnUom1dLtRjo65WAmY03wSF5XKXsqadh8sSV%2BXeNVnJkYoiVNacHoD4vcOFv5Cpaoanfy0RfWPoAn%2FoaS40XfTLEPVqsB24ninCxEgZ7%2FkooC1FgNL%2FvYzbQrpgrczHzaC4ZcFcWjaY4sBJKiZVcueaVo4Ku3%2BZUlYuJKinBhTSFfbNy053NouCAgTf%2FmVIXiR6LpaUL0VL9VGuiTf7LcB8W3tJoXDm1yMQcRihIGgZY74%2FaS8AwmJKAK%2FczDhT15iTtkcpSVTBY0L3QC%2BL%22%7D

### Expected behavior
Should take me to view the product page

### Actual behavior
DNS fails to resolve

![pulsar ebay com-dns-error](https://user-images.githubusercontent.com/829699/79592652-2359fc80-808f-11ea-9b17-b485d357a74e.PNG)

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (176.103.130.130)
| How did you setup DNS configuration:| (Windows Server)
| Device model:| (Dell Precision 5810)
| Operating system and version:| (Windows 10 1909)

**Comment by Alex-302** [comment]
Cannot reproduce when clicked on sponsored item.
Please show on screenshot where I should to click.

**Comment by sysfu** [comment]
Try visiting [this listing](https://www.ebay.com/itm/Replacement-Foam-Earpads-Pillow-Cushions-Ear-Pads-for-Jabra-UC-VOICE-550-Headset/264285538539?hash=item3d88a548eb:g:NlEAAOSwMUtdQpFk) and then clicking on any of the sponsored items below.

![sponsored-items](https://user-images.githubusercontent.com/829699/79598091-3ae9b300-8098-11ea-81ad-e0a55374fccf.PNG)

**Comment by Alex-302** [comment]
Got it.
