### ISSUE TITLE
businesssuccessgiveaway.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardSDNSFilter#304]
@adguard-bot commented on [Fri Apr 17 2020](https://github.com/AdguardTeam/AdguardFilters/issues/53845)

### Issue URL (Incorrect Blocking)
 [https://businesssuccessgiveaway.com/?ap_id=connie](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fbusinesssuccessgiveaway.com%2F%3Fap_id%3Dconnie)
### Comment
Username: @johncrumpton
> Adguard is blocking the leadpages email capture popup on the green button.
> 
> This is a problem in Chrome on Android only. In Chrome on PC with Adguard enabled it's OK.
> 
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/8uVt9i6.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/NrRxoYj.png)
</details>
<details>
  <summary>Screenshot 3</summary>

  ![Screenshot 3](https://reports-img.adguard.com/c1FMepu.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 
AdGuard version: | 3.4.19
Browser: | Chrome
AdGuard mode: | null
Filtering quality: | null
HTTPS filtering: | disabled
DNS requests blocking: | disabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion

**Comment by Alex-302** [comment]
@johncrumpton Is it used for spam?

**Comment by johncrumpton** [comment]
Hi, no this isn't used for spam.
