### ISSUE TITLE
sajari.com is blocked

### ISSUE THREAD

**Issue by sampotts** [AdguardTeam/AdGuardSDNSFilter#317]
We are a search as a service provider and we appear in your blocklist which is used by other blocking tools. This means our customers can't use the search tools as XHR and other requests are blocked. We do not serve ads and any tracking is done anonymously via GA client-side which can be blocked separately anyway. 

### Steps to reproduce
Visit https://jsfiddle.net/1tp4uxfv/ which includes one of our scripts served via the sajari.com domain.  

### Expected behavior
You should get a 'Loaded!' alert. 

### Actual behavior
You get a 'Blocked!' alert. 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/719092/80785917-50e19280-8bc5-11ea-9796-64658650b336.png)

</details>

### Your environment

Anywhere this block list is used.

**Comment by Alex-302** [comment]
It is blocked as tracking service(also in EasyPrivacy)
https://www.sajari.com/solutions/features/analytics
https://www.sajari.com/docs/user-guide/analytics/click-tracking/

**Comment by sampotts** [comment]
Thanks. We’ll request it’s removed from there too. 

What’s the next step to get it removed from this list? As you’ll see, it’s simple click tracking and nothing personally identifiable.

**Comment by Alex-302** [comment]
Could you, please, provide a real example where it is used?
_as I see, it is still exists in EasyPrivacy_

**Comment by ameshkov** [comment]
@Alex-302 unity.com

Let's exclude it from the SDN filter, this is not a tracker.

**Comment by Alex-302** [comment]
Ok.

**Comment by sampotts** [comment]
Excellent, thanks! 👍
