### ISSUE TITLE
Xiaomi Tracking (Mint Browser)

### ISSUE THREAD

**Issue by scafroglia93** [AdguardTeam/AdGuardSDNSFilter#319]
Source ->
https://www.youtube.com/watch?v=62kxZunBQyI&feature=emb_title

Domain IoC ->
sa.api.intl.miui.com

We would need everyone's feedback to avoid malfunctions on the device

**Comment by Alex-302** [comment]
Is seens blocking can break something.
Please look on these forks of the list with this domain - it was removed from one fork.
