### ISSUE TITLE
Confused about using DNS filter and/vs. DNS server.

### ISSUE THREAD

**Issue by geoff-nixon** [AdguardTeam/AdGuardSDNSFilter#32]
So  i’m confused about how/if to use the DNS servers and the DNS filters. That is, whether I should or shouldn’t be using the DNS filters In conjunction with the DNS servers, or if this is redundant. Because the DNS filter is almost 25,000 rules. But the wording seems to indicate, to me, that it should be used in conjunction with the DNS servers... “simplified specifically to be compatible with DNS-blocking”. If I enable the AdGuard base filter, along with the DNS filter, I hit my filter limit. That’s it.

So I guess this is kind of a free-form feature request, that is for clarity in the documentation on how and when to use these. Because not being able to add any other filter beyond these two is kind of a bummer.

**Comment by Alex-302** [comment]
AdGuard DNS filter is redundant if you are using AdGuard DNS.
