### ISSUE TITLE
Alimama blocked?

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardSDNSFilter#323]
Hello,

I 'm not sure, but I think these rules are unnecessary, as they block one of Alibaba 's online stores - Alimama:

```
||alimama.cn^
||alimama.com^
||alimama.alicdn.com^
```
Please, check everything and remove them.
Thank you.

**Comment by Alex-302** [comment]
> alimama.cn

removed. 

alimama.com is not a store.
