### ISSUE TITLE
||kiderul.startlap.hu^

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#330]
Site currently blocked by Family Protection DNS. Is a legit weather site for Hungary.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Family Protection, 176.103.130.132 / 176.103.130.134
| How did you setup DNS configuration:| Router

**Comment by Chinaski1** [comment]
Can't reproduce with AdGuard DNS Family enabled.
Also this site is not in the category "For adults".
