### ISSUE TITLE
com.androidyou.wifiloginnew

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#339]
This is an app: https://play.google.com/store/apps/details?id=com.androidyou.wifiloginnew

### Steps to reproduce
1. Enable AdGuard DNS as a Private DNS in your phone's settings
2. App will stop working

### Expected behavior
App works and connects to Wi-Fi hotspots while bypassing captive portal authentication

### Actual behavior
App does not work while AdGuard DNS is enabled

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 176.103.130.130
| How did you setup DNS configuration:| Private DNS
| Device model:| Unspecified Android
| Operating system and version:| Android 9+

**Comment by ryandh** [comment]
Can AdGuard bypass the filtering of all the requests initiated from this app?

**Comment by ameshkov** [comment]
If you use AdGuard for Android, this is possible. But not with AdGuard DNS, it is not aware of what app makes this or that DNS request.

**Comment by drdedus** [comment]
Are you sure?
I have exactly the same problem.
When i use dns.adguard.com in private dns option in Android 9 this app it doesn't work.

**Comment by Alex-302** [comment]
Cannot download this app. 
Using filtering log of AdGuard for Android you can find which domain is blocked and must be excluded(DNS filtering => ON, AdGuard DNS => OFF(select system DNS) )
