### ISSUE TITLE
Add logger.tv.telstra.com.au

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardSDNSFilter#34]
I notice that the Telstra TV devices ping to ‘logger.tv.telstra.com.au’ often and I was wondering if this could be added to the AdGuard SDNS Filter? Not sure what information is being sent to it but it doesn't affect functionality, could either be for analytics or tracking.

Can continue to blacklist this myself, but it might benefit others to have this blocked as well on a broader spectrum.

**Comment by ameshkov** [comment]
@Alex-302 let's add it to the spyware filter maybe? It'll be added to the SDN filter automatically then

**Comment by Alex-302** [comment]
done
