### ISSUE TITLE
location.services.mozilla.com & incoming.telemetry.mozilla.org

### ISSUE THREAD

**Issue by Voltairine-de-Cleyre** [AdguardTeam/AdGuardSDNSFilter#344]
- [x] I checked to make sure that this issue has not already been filed
- [x] I checked to make sure that this sub/domain is not already included in **AdGuardSDNSFilter**

**I'm suggesting 2 additions to the filter list**:

`location.services.mozilla.com`
**EDIT: Also:**
`||telemetry.mozilla.org^`
which would take care of `incoming.telemetry.mozilla.org`

### Steps to reproduce

*N/A*
#### Expected behavior

*N/A*
### Actual behavior

*N/A*
<details><summary>Screenshot:</summary>

*N/A*

*N/A*
</details>

*N/A*
### Your environment

*N/A*
|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (e.g. Default, 176.103.130.130)
| How did you setup DNS configuration:| (System/DNSCrypt app/Router)
| Device model:| (e.g. Google Pixel)
| Operating system and version:| (e.g. Android 7.1.2)
*N/A*

**Comment by Alex-302** [comment]
Not sure about that
https://wiki.mozilla.org/Telemetry/Testing

**Comment by Voltairine-de-Cleyre** [comment]
> Not sure about that
> https://wiki.mozilla.org/Telemetry/Testing

- https://wiki.mozilla.org/index.php?title=Firefox/Services/&mobileaction=toggle_view_desktop
- https://wiki.mozilla.org/CloudServices/Location
- https://www.ghacks.net/2020/04/09/mozilla-installs-scheduled-telemetry-task-on-windows-with-firefox-75/#comments
- https://blog.secureideas.com/2018/10/silencing-firefoxs-chattiness-for-web-app-testing.html
- https://superuser.com/questions/1003201/how-do-i-stop-mozilla-telemetry

And semi-related in that it regards AdGuard's native Windows installation - specifically the prevention of telemetry data by Microsoft regarding Windows usage ::

- https://www.ghacks.net/2020/07/27/adguard-7-5-beta-introduces-dns-filtering-and-windows-telemetry-blocking-support/

Telemetry is tracking irregardless of who or what is collecting it and irregardless of the supposed needs given for doing so. Please, when you're the time, read a bit more regarding Mozilla's use of its own telemetry (data harvesting).

Thank-you.

**Comment by ameshkov** [comment]
* `location.services.mozilla.com` - as I understand, this is not a telemetry domain. Firefox uses it for Location API, but note that this API requires explicit user permission and it's not allowed by default. Therefore blocking this domain would be counter-productive, the user just granted the permission and they may need this API to work, but it won't because we block it.
* `telemetry.mozilla.org` - I think it makes sense to add it to the Tracking Protection filter so that AdGuard for Win/Mac was blocking telemetry. However, I am not sure about the DNS filter as it's more "casual" and we try not to hurt other developers with what we block.

A couple of questions about Mozilla telemetry:

1. As I recall, Mozilla asks for user permission before enabling Telemetry. Is it still true?
2. Do you know where crash reports are being sent? Is it the same domain or something else? I'd like to avoid breaking crash reporting as it's crucial for development and has nothing to do with tracking.

**Comment by Voltairine-de-Cleyre** [comment]
> • telemetry.mozilla.org - I think it makes sense to add it to the Tracking Protection filter so that AdGuard for Win/Mac was blocking telemetry. However, I am not sure about the DNS filter as it's more "casual" and we try not to hurt other developers with what we block.
A couple of questions about Mozilla telemetry:

As I recall, Mozilla asks for user permission before enabling Telemetry. Is it still true?
Do you know where crash reports are being sent? Is it the same domain or something else? I'd like to avoid breaking crash reporting as it's crucial for development and has nothing to do with tracking.

- Adding it to the Tracking Protection filter definitely makes more sense. 🙂
- On mobile devices (at least iOS/iPadOS) Firefox automatically sends "usage data" unless the user explicitly opts-out. As for the actual desktop browser, one must change settings in `about:config` so that says usage data is sent to nowhere by removing the string `https://incoming.telemetry.mozilla.org` from `toolkit.telemetry.server`; the string `https://incoming.telemetry.mozilla.org/submit` from `browser.newtabpage.activity-stream.telemetry.structuredIngestion.endpoint`; or by changing specific Booleans from true to false; or by explicitly opting out of data collection within `Preferences > Privacy & Security`.
I hope this information is helpful.

**Comment by Voltairine-de-Cleyre** [comment]
> • telemetry.mozilla.org - I think it makes sense to add it to the Tracking Protection filter so that AdGuard for Win/Mac was blocking telemetry. However, I am not sure about the DNS filter as it's more "casual" and we try not to hurt other developers with what we block.
A couple of questions about Mozilla telemetry:

As I recall, Mozilla asks for user permission before enabling Telemetry. Is it still true?
Do you know where crash reports are being sent? Is it the same domain or something else? I'd like to avoid breaking crash reporting as it's crucial for development and has nothing to do with tracking.

- Adding it to the Tracking Protection filter definitely makes more sense. 🙂
- On mobile devices (at least iOS/iPadOS) Firefox automatically sends "usage data" unless the user explicitly opts-out. As for the actual desktop browser, one must change settings in `about:config` so that says usage data is sent to nowhere by removing the string `https://incoming.telemetry.mozilla.org` from `toolkit.telemetry.server`; the string `https://incoming.telemetry.mozilla.org/submit` from `browser.newtabpage.activity-stream.telemetry.structuredIngestion.endpoint`; or by changing specific Booleans from true to false; or by explicitly opting out of data collection within `Preferences > Privacy & Security`.
I hope this information is helpful.

**Comment by Voltairine-de-Cleyre** [comment]
> • telemetry.mozilla.org - I think it makes sense to add it to the Tracking Protection filter so that AdGuard for Win/Mac was blocking telemetry. However, I am not sure about the DNS filter as it's more "casual" and we try not to hurt other developers with what we block.
A couple of questions about Mozilla telemetry:

As I recall, Mozilla asks for user permission before enabling Telemetry. Is it still true?
Do you know where crash reports are being sent? Is it the same domain or something else? I'd like to avoid breaking crash reporting as it's crucial for development and has nothing to do with tracking.

- Adding it to the Tracking Protection filter definitely makes more sense. 🙂
- On mobile devices (at least iOS/iPadOS) Firefox automatically sends "usage data" unless the user explicitly opts-out. As for the actual desktop browser, one must change settings in `about:config` so that says usage data is sent to nowhere by removing the string `https://incoming.telemetry.mozilla.org` from `toolkit.telemetry.server`; the string `https://incoming.telemetry.mozilla.org/submit` from `browser.newtabpage.activity-stream.telemetry.structuredIngestion.endpoint`; or by changing specific Booleans from true to false; or by explicitly opting out of data collection within `Preferences > Privacy & Security`.
I hope this information is helpful.

**Comment by Voltairine-de-Cleyre** [comment]
> • telemetry.mozilla.org - I think it makes sense to add it to the Tracking Protection filter so that AdGuard for Win/Mac was blocking telemetry. However, I am not sure about the DNS filter as it's more "casual" and we try not to hurt other developers with what we block.
A couple of questions about Mozilla telemetry:

As I recall, Mozilla asks for user permission before enabling Telemetry. Is it still true?
Do you know where crash reports are being sent? Is it the same domain or something else? I'd like to avoid breaking crash reporting as it's crucial for development and has nothing to do with tracking.

- Adding it to the Tracking Protection filter definitely makes more sense. 🙂
- On mobile devices (at least iOS/iPadOS) Firefox automatically sends "usage data" unless the user explicitly opts-out. As for the actual desktop browser, one must change settings in `about:config` so that says usage data is sent to nowhere by removing the string `https://incoming.telemetry.mozilla.org` from `toolkit.telemetry.server`; the string `https://incoming.telemetry.mozilla.org/submit` from `browser.newtabpage.activity-stream.telemetry.structuredIngestion.endpoint`; or by changing specific Booleans from true to false; or by explicitly opting out of data collection within `Preferences > Privacy & Security`.
I hope this information is helpful.

**Comment by ameshkov** [comment]
@Alex-302 let's add `||telemetry.mozilla.org^` to the tracking protection filter. However, exclude it from the DNS filter for now (with a link to this issue). If one day we make a more aggressive DNS configuration, we'd include it there.

**Comment by Voltairine-de-Cleyre** [comment]
@Alex-302 👍🏼 Sent from ProtonMail Mobile On Fri, Aug 14, 2020 at 3:25 AM, Andrey Meshkov <notifications@github.com> wrote:  
@Alex-302 let's add ||telemetry.mozilla.org^ to the tracking protection filter. However, exclude it from the DNS filter for now (with a link to this issue). If one day we make a more aggressive DNS configuration, we'd include it there.

**Comment by Alex-302** [comment]
Done.

**Comment by Voltairine-de-Cleyre** [comment]
Here's some more information as well, directly from Mozilla, for anyone who may be interested:
- https://www.mozilla.org/en-US/privacy/firefox/
The amount and depth of information collected by default is, in one word, shocking.
I appreciate the addition to AdGuard's tracking filter. 🙂 Thank-you @Alex-302

**Comment by krystian3w** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/141708
