### ISSUE TITLE
thewirecutter.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardSDNSFilter#347]
@adguard-bot commented on [Wed May 27 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56193)

### Issue URL (Incorrect Blocking)
 [https://thewirecutter.com/out/link/38600/162100/4/114981?merchant=Costco](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fthewirecutter.com%2Fout%2Flink%2F38600%2F162100%2F4%2F114981%3Fmerchant%3DCostco)
### Comment
Username: @carlylemiii
> DNS filter breaks opening this Wirecutter link

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/sxMEAQM.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/0D1s36x.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | And 10
AdGuard version: | 3.4 (120)
Browser: | Chrome
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances
Custom filter subscriptions: |

**Comment by Alex-302** [comment]
@carlylemiii Is not it an ad? Please provide the source url or screenshot with that url.

**Comment by carlylemiii** [comment]
https://www.nytimes.com/wirecutter/reviews/best-mens-underwear/

Under "Best pair under $5" click the product link.

**Comment by Alex-302** [comment]
Not sure if it must be excluded
kqzyfj.com => https://www.conversantmedia.com/legal/privacy
