### ISSUE TITLE
mp4upload.com assets.revcontent.com Adblock detection

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdGuardSDNSFilter#353]
### Steps to reproduce

Regarding to https://github.com/AdguardTeam/AdguardFilters/issues/56611
With Adguard SDNS (tested with AdGuard Home), the page refuse to start download, because of Adblocker detection. The issue is solved, when allow assets.revcontent.com

### Expected behavior

<details><summary>Screenshot-1:</summary>

![mp4 2](https://user-images.githubusercontent.com/6276915/83863856-38184f80-a724-11ea-8006-a992b6f6d701.jpg)

</details><br/>

### Actual behavior

<details><summary>Screenshot-2:</summary>

![mp4 1](https://user-images.githubusercontent.com/6276915/83863874-40708a80-a724-11ea-8524-e5065c064d30.jpg)

</details><br/>

**Comment by Alex-302** [comment]
We cannot exclude this domain for these pirate file hostings.

**Comment by Morku** [comment]
@Alex-302 
Since when this is an argument?
Why was ticket https://github.com/AdguardTeam/AdguardFilters/issues/56611 handled and solved then?

**Comment by Alex-302** [comment]
Solved, but any domain was not excluded for all sites.
