### ISSUE TITLE
argos.co.uk - Unable to play product video

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardSDNSFilter#356]
### Steps to reproduce

1. Visit https://www.argos.co.uk/product/2017541
2. Flip through the images until you get to video
3. Click on play

### Expected behavior

Able to click on play to play the promotional video

### Actual behavior

Firefox throws an error message saying `No video with supported format and MIME type found`

This is because the video is loaded from the below URL which is blocked by `||flix360.com^` filter.

```
https://embed.flix360.com/MTU2MDgwNiYxMDYmZW4meDNEWmZYODU.mp4
```

Suggested filter
```
@@||embed.flix360.com^|
```

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/62358249/83878854-a8c76800-a734-11ea-9309-f24f9fc6620f.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| AdGuard Home
| How did you setup DNS configuration:| Router
| Device model:| Macbook
| Operating system and version:| Macos 10.15

**Comment by Alex-302** [comment]
Will be fixed when DNS server will load fresh filter.
