### ISSUE TITLE
v.youku.com

### ISSUE THREAD

**Issue by Yuki2718** [AdguardTeam/AdGuardSDNSFilter#358]
URL: `https://v.youku.com/v_show/id_XNDY2MzQxMjQ4NA==.html`
Issue: video can't be played.

![youku1](https://user-images.githubusercontent.com/58900598/84155533-6474f880-aaa3-11ea-8437-ce6215cb2051.png)

### Steps to reproduce

1. Visit the site and play the video.

### Expected behavior

Video works fine.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default
| How did you setup DNS configuration:| Firefox' DoH
| Device model:| Windows PC
| Operating system and version:| Windows 10

### Notes
Due to `||mmstat.com^` and `@@||log.mmstat.com^|` needs to be added. I'll make a PR soon.

**Comment by Alex-302** [comment]
This is a populat tracking service. Not sure about whitelisting.

**Comment by ameshkov** [comment]
Well, Youku is basically a Chinese Youtube, I guess it'd be better not to break it even if we'll have to unblock one analytics service. We would have done that for Youtube, for instance.

**Comment by Yuki2718** [comment]
As I mentioned in the uAssets issue, it seems now `log.mmstat.com` can be blocked - but it needs more tests/confirmation.

**Comment by Alex-302** [comment]
@Yuki2718 does it work with `||log.mmstat.com^$document,important`?

**Comment by Yuki2718** [comment]
The requests are for scripts and images, but no, now I need to allow it again. I wonder they serve slightly different pages on some condition such as IP.
