### ISSUE TITLE
Remove sematext.com from tracking_servers.txt

### ISSUE THREAD

**Issue by otisg** [AdguardTeam/AdGuardSDNSFilter#366]
I found our domain - sematext.com - listed in https://github.com/AdguardTeam/AdguardFilters/blob/2a3ba7a123c79c097abc395d32256796688b3663/SpywareFilter/sections/tracking_servers.txt#L2432
I am not really sure why we are there. We don't serve or display any ads or anything like this (we run a SaaS).  I looked for a few other companies in our space and they are not listed there either.  I believe we were added in error.  Would it be possible to remove sematext.com from there?
Your help would be greatly appreciated.

Actually, not that I look better, I see sematext.com in a number of other files: https://github.com/search?q=org%3AAdguardTeam+sematext&type=Code

I tried looking for a commit/PR to understand why we were added, but as you can see from the above search, there are no matching commits.  

I'd be happy to do the legwork, remove sematext.com and submit the PR.

**Comment by ameshkov** [comment]
Actually, it comes from EasyPrivacy so removing it won't be that easy.

I don't mind unblocking it in AdGuard DNS, though. It is a developer tool and not a tracking system, and our policy is not that strict, we don't want to block developer tools.

**Comment by otisg** [comment]
@ameshkov if you don't mind unblocking it in AdGuard DNS, I'd greatly appreciate it.

Thank you for the EasyPrivacy pointer.  I opened https://github.com/easylist/easylist/issues/5557.

**Comment by Alex-302** [comment]
Let's wait for result in https://github.com/easylist/easylist/issues/5557 (few days)

**Comment by otisg** [comment]
Just wanted to say thank you, @Alex-302
