### ISSUE TITLE
False positive - tns-sifo.se - 15.txt

### ISSUE THREAD

**Issue by zappe** [AdguardTeam/AdGuardSDNSFilter#367]

**Comment by Alex-302** [comment]
What is wrong?

**Comment by zappe** [comment]
Your list is blocking the domain.

**Comment by Alex-302** [comment]
Blocking rule is loaded from EasyPrivacy, so it is blocked as tracker.

**Comment by zappe** [comment]
And it’s not a tracker.

**Comment by Alex-302** [comment]
Ok, checked, it seems their tracking sub-domain(sifomedia.tns-sifo.se) is not used anymore
