### ISSUE TITLE
Убрать домен из блока

### ISSUE THREAD

**Issue by skipik** [AdguardTeam/AdGuardSDNSFilter#371]
||leohd59.ru^
||geracbv.leohd59.ru^
Просьба убрать эти 2 правила из блока, иначе невозможно зайти на абсолютно безобидный торрент-трекер leohd59.ru.

**Comment by Alex-302** [comment]
Изилистам написал, посмотрим что решал. Если что - с нашей стороны уберём.

**Comment by Alex-302** [comment]
Скоро пропадёт.

**Comment by skipik** [comment]
@Alex-302 большое спасибо!
