### ISSUE TITLE
[NSFW] ||ebalka.one^

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#372]
### Actual behavior
Adult website not blocked by AdGuard Family Protection DNS.

### NSLOOKUP
nslookup ebalka.one dns.adguard.com
Server:  176-103-130-130.dns.adguard.com
Address:  176.103.130.130

Non-authoritative answer:
Name:    ebalka.one
Addresses:  2606:4700:20::681a:74d
          2606:4700:20::681a:64d
          2606:4700:20::ac43:4923
          104.26.7.77
          172.67.73.35
          104.26.6.77

**Comment by ameshkov** [comment]
Added
