### ISSUE TITLE
Can't open www.fontanka.ru

### ISSUE THREAD

**Issue by Joss** [AdguardTeam/AdGuardSDNSFilter#383]
### Steps to reproduce

1. Try to open https://www.fontanka.ru/ with enabled AdguardDNS on Keenetic router via any browser (from PC or mobile device)
2.
3.
4.

### Expected behavior
Site opens

### Actual behavior
Can't find IP-address for www.fontanka.ru.
DNS_PROBE_FINISHED_NXDOMAIN

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default
| How did you setup DNS configuration:| Router
| Device model:| Windows-PC, Android
| Operating system and version:| Android 9.0, Windows 10 64x

**Comment by ameshkov** [comment]
Не могу что-то повторить

```
$ nslookup www.fontanka.ru. 176.103.130.130
Server:		176.103.130.130
Address:	176.103.130.130#53

Non-authoritative answer:
Name:	www.fontanka.ru
Address: 195.19.220.6
```
