### ISSUE TITLE
saturn.de [iOS] [Breakage]

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdGuardSDNSFilter#391]
### Steps to reproduce

1. Subscribe AdGuard DNS filter
2. Got to saturn.de (loads fine)
3. press on a product to load it
4. -> endless loading circle

### Expected behavior

Without AdGuard DNS, the product pages loads fine

### Actual behavior

When you press a product, a loading circle appears, but never finish and does not load.

<details><summary>Screenshot-1:</summary>

![2020-07-10 18 31 42](https://user-images.githubusercontent.com/6276915/87207116-71d40b80-c30b-11ea-8ea7-80a11ad21d30.png)

</details><br/>

Sadly, I can't figure out which DNS is cause of the breakage. When I browse the page, this DNS gets loaded and blocked by AdGuard DNS:

<details><summary>Screenshot-2:</summary>

![Screenshot_2020-07-11 AdGuard Home](https://user-images.githubusercontent.com/6276915/87207283-db541a00-c30b-11ea-93d8-29659771d02e.png)

</details><br/>

Even when I allowed every blocked DNS, it still not load. Maybe I just missed something. I have to disable AdGuard Home, then the proucts load fine.

Important: This only happens on my iPhone (and another iPhone) iOS with Safari. With Windows Desktop, I have no issue, still with active AdGuard DNS.

When I disable AdGuard Home, the product pages loads fine. When I activate after, the product still loads fine. So something stays in Cache then. So when try to verify, make sure to have AdGuard DNS filter active before browse the page the first time.

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| How did you setup DNS configuration:| connected in WLAN with AdGuard Home filtering (Adguard DNS filter)
| Device model:| iPhone XS 13.5.1
| Operating system and version:| AdGuard for iOS 4.0.1

**Comment by Alex-302** [comment]
@Morku You can try to exclude domains one by one.

**Comment by Morku** [comment]
Now I found it directly.
It's solved when unblock `@@||www.google-analytics.com^$important`
The products loads fine then.

I was hoping it's not Google, because I am sure, there is no way to fix it.

**Comment by Morku** [comment]
And as I said in opening post. When it loads fine, it will load fine for a while, even when the whole AG DNS filter is running again.

I removed the google-analytics custom rule from AG Home, cleaned the Browser Cache on iPhone (all Google data, Saturn, dynamicyield), browse saturn.de again and the procuts still load fine.
When I check the Home filtering log, there is no request to google-analytics anymore. Maybe the data is stored in another DNS, I have no idea, I am just an average user.

**Comment by Alex-302** [comment]
Got it. So it cannot be fixed. We cannot unblock google-analytics.com
