### ISSUE TITLE
[False-Positive] Bytedance

### ISSUE THREAD

**Issue by Rru247** [AdguardTeam/AdGuardSDNSFilter#396]
`bytedance.com`
sub domains `job.bytedance.com`

source: https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/385

**Comment by Alex-302** [comment]
Why we need to unblock it?
It also blocked in EasyPrivacy.

**Comment by Rru247** [comment]
Not about others block but I cannot find good reason why block that site.
Anyway let's ignore this. close the issue.
