### ISSUE TITLE
geoloc.arte.tv - False positive

### ISSUE THREAD

**Issue by lyrad87** [AdguardTeam/AdGuardSDNSFilter#397]
The ARTE.tv app cannot be used with [this](https://github.com/AdguardTeam/AdguardSDNSFilter) list. It blocks `geoloc.arte.tv` which is needed for the app to function. Once added to the allowlist, the app works as intended.

### Steps to reproduce

1. Add the "AdGuard DNS filter" via the NextDNS service
2. Open the [ARTE.tv app](https://apps.apple.com/de/app/arte-tv/id405028510?l=en) on tvOS (latest version)
3. The app throws an error right away
4. Allow `geoloc.arte.tv`, flush DNS cache and notice the app working again

### Expected behavior
The ARTE tvOS app can be opened and play videos.

### Actual behavior
The ARTE tvOS app starts but throws an error right away so the app is unusable.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| How did you setup DNS configuration:| I'm using the NextDNS service on my FritzBox router
| Device model:| AppleTV 4K
| Operating system and version:| tvOS 13.4.8

**Comment by Alex-302** [comment]
fixed
