### ISSUE TITLE
NSFW sites

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#399]
A few NSFW sites are currently not blocked by AdGuard family DNS:

**Example 1**
nslookup pornohd.porn 176.103.130.134
Server:  176-103-130-134.dns.adguard.com
Address:  176.103.130.134

Non-authoritative answer:
Name:    pornohd.porn
Address:  137.74.57.139

**Example 2**
nslookup lenporno.net 176.103.130.134
Server:  176-103-130-134.dns.adguard.com
Address:  176.103.130.134

Non-authoritative answer:
Name:    lenporno.net
Address:  176.103.130.135

**Comment by valaria247** [comment]
https://recurbate.com/

**Comment by valaria247** [comment]
#1133

**Comment by Rru247** [comment]
https://github.com/AdguardTeam/AdGuardHome/issues/1133

**Comment by akmLaVx** [comment]
added
