### ISSUE TITLE
acquia.com is blocked

### ISSUE THREAD

**Issue by Retia-Adolf** [AdguardTeam/AdGuardSDNSFilter#4]
### Expected behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/34053927/46124421-11d1ab00-c1f2-11e8-9780-8f51c3b319aa.png)

![image](https://user-images.githubusercontent.com/34053927/46124435-3463c400-c1f2-11e8-8f4b-545d0c13b0bb.png)
</details>

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/34053927/46124509-9f14ff80-c1f2-11e8-90b9-153922235fbe.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 1.1.1.1
| How did you setup DNS configuration:| System
| Device model:| PC
| Operating system and version:| Windows 10 1803

**Comment by Alex-302** [comment]
fixed
