### ISSUE TITLE
wiesentbote.de

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardSDNSFilter#406]
### Steps to reproduce

1. Turn on *AdGuard DNS Filter*.
2. Ensure the browser isn't using any browser-based adblockers that'd block `/www/delivery/*`
3. Visit `https://www.wiesentbote.de/2020/07/27/einbruch-in-bayreuther-firmengebaeude-die-kriminalpolizei-ermittelt/`
4. See that there's an ad below the article that isn't blocked.
5. Add `||kunner.wiesentbote.de^` to your custom entries.
6. Switch to a different browser or hardware unit to test with, because that particular domain is only loaded once per browser session.
7. Go to the same site as above.
8. See that the ad is gone.

### Expected behavior
The ad does not show up, presumably accomplished with `||kunner.wiesentbote.de^`.

### Actual behavior
The ad shows up.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/88532206-78999880-d004-11ea-8e3e-4b0455517b2a.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| AdGuard Home
| How did you setup DNS configuration:| System
| Device model:| Motorola One Zoom / Nintendo Wii U
| Operating system and version:| Android 9 / Wii U System Software 5.5.4 E

**Comment by Alex-302** [comment]
added
