### ISSUE TITLE
The DNS Filter list is not using AdGuard German Filter as a source, merely EasyList Germany

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardSDNSFilter#410]
### Steps to reproduce
1. Open https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/GermanFilter/sections/adservers.txt in one tab.
2. Open https://filters.adtidy.org/windows/filters/15.txt in another tab.
3. Go to the latter tab, and textsearch with any of the domains from the former tab.
4. See that it can't find the domains.

### Expected behavior

[AdGuard German Filter's adserver list](https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/GermanFilter/sections/adservers.txt) is utilised as a source in AdGuard DNS Filter.

### Actual behavior

Since only [EasyList Germany's adserver list](https://raw.githubusercontent.com/easylist/easylistgermany/master/easylistgermany/easylistgermany_adservers.txt) is used as a source in [configuration.json](https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/configuration.json), and not [AdGuard German Filter's adserver list](https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/GermanFilter/sections/adservers.txt), the latter's entries against 20~25 German-language adservers are not being used by AdGuard DNS Filter.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/88792324-59813f00-d19b-11ea-9b9f-290adbefb515.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| AdGuard Home
| How did you setup DNS configuration:| N/A
| Device model:| N/A
| Operating system and version:| N/A

**Comment by ameshkov** [comment]
Good catch, thank you!
