### ISSUE TITLE
dorama.kr

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#411]
Site is currently NXDOMAIN'd by AdGuard DNS.

### nslookup
nslookup dorama.kr 176.103.130.130
Server:  176-103-130-130.dns.adguard.com
Address:  176.103.130.130

Name:    dorama.kr

### Configuration
AdGuard DNS (Default), router install

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/89274788-10713500-d64a-11ea-8710-6ca0698fd9fc.png)
I cannot open it with any other DNS + VPN.
