### ISSUE TITLE
DNS Simplified Filters

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdGuardSDNSFilter#413]
Because I never got an answer from AG support team I have a question more than a tech issue. 

If "Use Simplified Filters" is ON in AG "Advanced Settings", do we have to add "AG Simplified Filters" to "DNS Filters" list?

![image](https://user-images.githubusercontent.com/49731083/89179702-8a44e800-d590-11ea-9ede-9c6d08f37a80.png)

**Comment by ameshkov** [comment]
These are different settings so yes, you should

**Comment by Quorum75** [comment]
Thanks Andrey for your prompt answer! Greatly appreciate.
