### ISSUE TITLE
Donations to World Food Programme blocked...

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#419]
@truthsword commented on [Sat Aug 08 2020](https://github.com/AdguardTeam/AdGuardHome/issues/2008)

![](https://i.imgur.com/HLQO73U.png)
![](https://i.imgur.com/3nkQ7sG.png)
data/adguard-simplified/list.txt
AdGuard Home version v0.103.3

---

@JustHmmmm commented on [Sun Aug 09 2020](https://github.com/AdguardTeam/AdGuardHome/issues/2008#issuecomment-671013641)

Just remove that rule. It is not AdGuardHome's issue.

---

@RonKhondji commented on [Sun Aug 09 2020](https://github.com/AdguardTeam/AdGuardHome/issues/2008#issuecomment-671018260)

Well, it is in AdGuard's DNS filter list.

As a work arround you can add:
@@||iraiser.eu^$important
to your 'custom filtering rules'.

---

@truthsword commented on [Sun Aug 09 2020](https://github.com/AdguardTeam/AdGuardHome/issues/2008#issuecomment-671043907)

I did that however this site does not belong in the filter list. How does that get corrected?

On Aug 9, 2020, 3:29 AM, at 3:29 AM, RonKhondji <notifications@github.com> wrote:
>Well, it is in AdGuard's DNS filter list.
>
>As a work arround you can add:
>@@||iraiser.eu^$important
>to your 'custom filtering rules'.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/AdguardTeam/AdGuardHome/issues/2008#issuecomment-671018260

---

@RonKhondji commented on [Sun Aug 09 2020](https://github.com/AdguardTeam/AdGuardHome/issues/2008#issuecomment-671044956)

Maybe [https://github.com/AdguardTeam/AdGuardSDNSFilter/issues](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues) is the best place.
Though I think that leaving it here for the devs to find it will work just as well.

**Comment by Alex-302** [comment]
Fixed in our filters.
