### ISSUE TITLE
Ads not blocked on Crunchyroll and VRV

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#422]
@jimmysofat6864 commented on [Tue Aug 11 2020](https://github.com/AdguardTeam/AdGuardDNS/issues/103)

I noticed that ad's aren't blocked on any videos on Crunchyroll when I use AdGuard DNS. Same thing with VRV. I haven't tried funimaiton but I'm pretty sure ads still go through on Funimation.

**Comment by Alex-302** [comment]
Crunchyroll does not uses separate ad domain.
