### ISSUE TITLE
Consider blocking the Luminati network

### ISSUE THREAD

**Issue by durablenapkin** [AdguardTeam/AdGuardSDNSFilter#427]
https://old.reddit.com/r/pihole/comments/edc11v/blocking_luminati/

You can find more discussion in the above thread. Essentially Luminati is used by some apps in order to use your device(s)/connection when idle as a VPN node, which can be seen as a botnet.

While I created a more thorough list of Luminati domains here - https://github.com/durablenapkin/block/blob/master/luminati.txt - it also includes some Hola domains as they are under the same company/owner.

Below is a list of Luminati-only root domains for your convenience:

```
lumtest.com
l-err.biz
l-agent.me
luminatinet.com
lum-sdk.io
luminati-china.io
lum-bext.com
lum-cn.io
lum-ext.io
lum-int.io
lum-lpm.com
luminati-china.biz
luminati-china.co
luminati.io
luminatichina.net
```

Thank you!

**Comment by ameshkov** [comment]
Despite the obvious controversy, they're not malware and we can't include them into a general-purpose blocklist.

We can add Luminati to the list of blockable "Services" in AdGuard Home, though: https://github.com/AdguardTeam/AdGuardHome/issues/1913#issuecomment-675415044

**Comment by durablenapkin** [comment]
Makes sense, thank you for taking the time to look into this and for your consideriation re: AdGuard Home!
