### ISSUE TITLE
Critical: m^

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdGuardSDNSFilter#431]
@sfionov @Revertron @ameshkov @adguard Please reverse filter `m^` which is **_insanely_** broad! 🙇🏾‍♂️

**Comment by Alex-302** [comment]
I don't see this string

**Comment by Alex-302** [comment]
@TPS where  do you see it?

**Comment by TPS** [comment]
![Screenshot_20200820-132518](https://user-images.githubusercontent.com/185902/90805949-55ec5e00-e2ea-11ea-8af2-a85abb578b0a.png)

**Comment by Alex-302** [comment]
I can't reproduce.

**Comment by Alex-302** [comment]
Try to backup settings, reset, and check with clean config.

**Comment by TPS** [comment]
It has resolved on its own after some time (I'm assuming after a filter update), so maybe it was a transitory glitch. 🤷🏾‍♂️  Thanks for taking the time to look into it, @Alex-302. 🙇🏾‍♂️

**Comment by TPS** [comment]
Apparently, handled via https://github.com/AdguardTeam/AdguardForAndroid/issues/3548.
