### ISSUE TITLE
Unblock chat application domain

### ISSUE THREAD

**Issue by KizunaH** [AdguardTeam/AdGuardSDNSFilter#432]
Domain: stc.za.zaloapp.com
Description: Unable to load web interface after login

**Comment by Alex-302** [comment]
Where exactly broken?

**Comment by KizunaH** [comment]
I was using unofficial-zalo version published on snapcraft (it use the zalo-web as electron app). it doesn't load the web interface when login to account using QR code. (that's the thing broken) however i tested again and it didn't occur. i'll reopen this issue again if really necessary.
