### ISSUE TITLE
ads.viber.com

### ISSUE THREAD

**Issue by target123** [AdguardTeam/AdGuardSDNSFilter#435]
### Steps to reproduce
```
> server 176.103.130.131
Default server: 176.103.130.131
Address: 176.103.130.131#53
> ads.viber.com
Server:		176.103.130.131
Address:	176.103.130.131#53

Non-authoritative answer:
ads.viber.com	canonical name = ads.aws.viber.com.
ads.aws.viber.com	canonical name = ads-alb-1954136449.us-east-1.elb.amazonaws.com.
Name:	ads-alb-1954136449.us-east-1.elb.amazonaws.com
Address: 54.86.219.200
Name:	ads-alb-1954136449.us-east-1.elb.amazonaws.com
Address: 54.81.179.169
```

### Expected behavior
Domain should be blocked. Ads domain of Viber.

### Actual behavior
Domain is not blocked and is resolving normally.

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 176.103.130.131
| How did you setup DNS configuration:| System/Router
| Device model:| Apple Macbook Air 2011
| Operating system and version:| MacOS Catalina 10.15.6

**Comment by Alex-302** [comment]
added
