### ISSUE TITLE
az416426.vo.msecnd.net

### ISSUE THREAD

**Issue by beerisgood** [AdguardTeam/AdGuardSDNSFilter#437]
### Steps to reproduce

1. Go to https://haveibeenpwned.com/
2. Try checking a "pwned" mail adress
3. "Oh no - catastrophic failure! is displayed

### Expected behavior

Should work

### Actual behavior

Site doesn't work because of blocked DNS (az416426.vo.msecnd.net)
az416426.vo.msecnd.net is owned by Microsoft

<details><summary>Screenshot:</summary>
<img width="306" alt="blocked" src="https://user-images.githubusercontent.com/9625159/91661166-8a2a0080-eada-11ea-9371-773e513b2627.png">

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| NextDNS with your "https://github.com/AdguardTeam/AdguardSDNSFilter" list
| How did you setup DNS configuration:| Router
| Device model:| not relevant
| Operating system and version:| not relevant

**Comment by Alex-302** [comment]
It works on my end
![image](https://user-images.githubusercontent.com/8361299/91894788-e2a9fb00-ec9e-11ea-8697-bf2155a604ec.png)

**Comment by beerisgood** [comment]
Looks like it was a error on https://haveibeenpwned.com side.
Today it works
