### ISSUE TITLE
Adguard blocking Disconnect.me list

### ISSUE THREAD

**Issue by guinhas** [AdguardTeam/AdGuardSDNSFilter#44]
Hi,
When using https://filters.adtidy.org/windows/filters/15.txt as a dns-level ad blocking list, I can't access https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt. Is this the expected behaviour? Could these two domain names/rules be the cause?
||amazonaws.com^*.kissinsights.com/
||amazonaws.com^*.kissmetrics.com/

Thank you.

**Comment by ameshkov** [comment]
I doubt it. What product do you use for DNS-level ad blocking?

**Comment by guinhas** [comment]
Hi,
Thank you for your reply. I use openwrt's adblock with kresd as Dns Backend. I'm only able to reach https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt when I disable Adguard's list as a source. What should I do? Thank you for your help.

**Comment by ameshkov** [comment]
Hm, frankly, I don't know if openwrt supports the syntax we use in AdGuard SDN filter. It might be better to report it to them.

I am pretty sure there are no issues in the list when it is used by AdGuard Home, AdGuard DNS or AdGuard for Android.

**Comment by guinhas** [comment]
Ok, I'll report it in openwrt's Adblock. Thank you very much for your help!

**Comment by guinhas** [comment]
Hi,
Obviously, you were right! I was using an old version of openwrt's Adblock and in the new version everything is working as expected! I found a 3 month old commit fixing regex for Adguard's blocklist source! Added the change to my config and everything is working. Sorry for the trouble! And thank you for your help!
