### ISSUE TITLE
(whitelist) reachedhb.afl.rakuten.co.jp

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#441]
@kylehase commented on [Sat Sep 05 2020](https://github.com/AdguardTeam/AdGuardDNS/issues/105)

Many product search results on google.co.jp link to Rakuten which uses the URL http://reachedhb.afl.rakuten.co.jp which is blocked.

This query may help to test. https://www.google.co.jp/search?q=楽天%20靴

**Comment by Alex-302** [comment]
@kylehase This domain is not working without AdGuard
![image](https://user-images.githubusercontent.com/8361299/92589754-b47e7980-f2a3-11ea-8fc0-72a1a1de100c.png)
please provide description where I can find it.

**Comment by kylehase** [comment]
Hi Alex,

Apologies, not sure how 'reached' got added but it seems the problematic
domain is just hb.afl.rakuten.co.jp <http://reachedhb.afl.rakuten.co.jp/>

Kyle

**Comment by Alex-302** [comment]
I don't see `hb.afl.rakuten.co.jp` on that page.
@Yuki2718 could you please take a look?

**Comment by kylehase** [comment]
Not sure if this will help but I just ran that Google search
<https://www.google.co.jp/search?q=楽天%20靴> in an incognito window and found
this link to hb.afl.rakuten.co.jp which is broken.

https://pasteboard.co/JqrZP6F.png

**Comment by Yuki2718** [comment]
I see the links leading to `afl.rakuten.co.jp` ( there seems to be some patterns) but the original href are `item.rakuten.co.jp`. If you use Adblocker they're hidden by cosmetic filtering.

**Comment by Alex-302** [comment]
It seems we cannot remove it from DNS filters. It is used for advertising on sites
https://publicwww.com/websites/afl.rakuten.co.jp/

**Comment by Yuki2718** [comment]
Well, but apparently `hb.afl.rakuten.co.jp` is always in href, meaning it only matters when user clicked an affiliate link. Automatically served ads are delivered through `hbb.afl.rakuten.co.jp` (notice the additional "b"). So probably it'll be okay to add an exception only for `hb.afl.rakuten.co.jp`.

**Comment by Yuki2718** [comment]
Whoops, I found allowing `hb.afl.rakuten.co.jp` only doesn't work, `pt.afl.rakuten.co.jp` also needs to be allowed to reach the destination. According to publicwww this seems to be href only too.

**Comment by Yuki2718** [comment]
@Alex-302 Having observed `afl.rakuten.co.jp` for short time, I'm getting convinced that ads from this domain are delivered through either `hbb.afl.rakuten.co.jp` or `ba.afl.rakuten.co.jp`. So far no evidence that allowing `hb.afl.rakuten.co.jp` and `pt.afl.rakuten.co.jp` causes third-party ads to pass through.

**Comment by Alex-302** [comment]
Thanks, merged.
