### ISSUE TITLE
Ads on "https://kathmandupost.com"

### ISSUE THREAD

**Issue by SeriousHoax** [AdguardTeam/AdGuardSDNSFilter#442]
Issue: 
Is it possible to block the ad at the bottom of the page through dns? Adguard dns is not blocking it at the moment.

Step to reproduce: 
Visit: "https://kathmandupost.com/columns/2020/08/03/where-are-nepal-india-relations-heading" 

Scroll down and there's an ad at the bottom. 

Device: Android
Browser: Chrome/Edge
Dns: Adguard default filter
(Sorry I had to create this issue via the mobile app so format isn't correct).

**Comment by Yuki2718** [comment]
Impossible to block on DNS; the same domain serves that image of Nepal x India flags and they are directly called from HTML document. It requires more granular blocking.

**Comment by SeriousHoax** [comment]
> Impossible to block on DNS; the same domain serves that image of Nepal x India flags and they are directly called from HTML document. It requires more granular blocking.

Thanks for testing and explaining. Ok, I'm gonna close the issue now.
