### ISSUE TITLE
Please block the following ads api server

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#445]
@DavidTai780 commented on [Sun Sep 13 2020](https://github.com/AdguardTeam/AdGuardDNS/issues/107)

here is some of the ads server.

me.com.x9wj2.cn
zvb.z7wq1.cn
y4m.s9wf3.cn
x0o.d2wl1.cn
uf7.t7wp8.cn
sx2.f7wn6.cn
re.baidu.com.r2wb3.cn
r6t.b3wg2.cn
pc5.b6wq9.cn
en3.r2wm5.cn
df8.l5wt5.cn
bbq.y7wr7.cn
al1.t7wl8.cn
9ns.g1wn5.cn
8xc.p2wq1.cn
d3n.q9ww5.cn
y1.d2wl1.cn
x3z.g1wn5.cn
v2j.r2wm5.cn
ttl8.l5wt5.cn
ry4.s9wf3.cn
rm.baidu.com.r2wb3.cn
q01.t7wp8.cn
k99.b6wq9.cn
h36.y7wr7.cn
d7g.p2wq1.cn
ciu1.z7wq1.cn
8p3.f7wn6.cn
5nm.t7wl8.cn
f2.q9ww5.cn
v.tysjkw.cn
v.tlscqw.cn
v.tgslww.cn
v.sssgbw.cn
v.pcswtw.cn
v.lbsbbw.cn
v.jsbgh.cn
v.cqpsf.cn
c.tysjkw.cn
c.tlscqw.cn
c.tgslww.cn
c.lbsbbw.cn
so6.b3wg2.cn

**Comment by ameshkov** [comment]
@DavidTai780 please explain where these servers are used.

We don't just block domains without any information on how exactly they're used and without reproducing this by ourselves.

**Comment by DavidTai780** [comment]
These server was used in some of the chinese novel site for ads purpose.

When you visit chinese novel site like m.xbiquge.cc with mobile phone only(view with pc would not come out these ads), then you will get those ads shown in image attached below. Some of the site like chinese sites will also show this kind of ads.

The content in the ads will point user's browser to gambing site or pornography site and etc.

Hope this could be the support reason to block the following domain.

![photo_2020-09-14_11-08-03](https://user-images.githubusercontent.com/26398101/93039642-a2715200-f67a-11ea-9691-fd7d1702d631.jpg)

**Comment by Alex-302** [comment]
As I see, the most ad servers are dead.

**Comment by DavidTai780** [comment]
I think the ads server address very often to changes, and today checked their server list updated as below(some address did not changes, some of them replaced with new domain):

v.rssnzw.cn
c.cqpsf.cn
c.jsbgh.cn
c.lbsbbw.cn
c.pcswtw.cn
c.rssnzw.cn
c.sssgbw.cn
c.tgslww.cn
c.tlscqw.cn
c.tysjkw.cn
v.cqpsf.cn
v.jsbgh.cn
v.lbsbbw.cn
v.pcswtw.cn
v.sssgbw.cn
v.tgslww.cn
v.tlscqw.cn
v.tysjkw.cn

Ads's image file resource domain:

fn.sdduofen.com.cn
hl.lfjinyan.cn
or.hananoka.cn

**Comment by Alex-302** [comment]
Added some domains.
