### ISSUE TITLE
Please block ad

### ISSUE THREAD

**Issue by zaku490** [AdguardTeam/AdGuardSDNSFilter#448]
It only shows up on the home page.

https://hexus.net/

![image](https://user-images.githubusercontent.com/64332197/93534154-1ffec180-f90a-11ea-9eab-274d01da5a26.png)

Reddit - comes up when you scroll down.
![image](https://user-images.githubusercontent.com/64332197/93536930-d618da00-f90f-11ea-9338-dcddc554f69a.png)

**Comment by ameshkov** [comment]
These can't be blocked via DNS, to have them blocked you need to use AdGuard browser extension or program
