### ISSUE TITLE
Please Fix page layout

### ISSUE THREAD

**Issue by zaku490** [AdguardTeam/AdGuardSDNSFilter#449]
https://www.tweaktown.com/

![image](https://user-images.githubusercontent.com/64332197/93534679-293c5e00-f90b-11ea-9d79-ba01e0394cf1.png)

Should be

![image](https://user-images.githubusercontent.com/64332197/93534733-41ac7880-f90b-11ea-9080-8cecc0681e45.png)

**Comment by BlazDT** [comment]
Not possible with DNS. On AdGuard Extension it is clean.
