### ISSUE TITLE
FP: blocked ping to Quad9 DNS

### ISSUE THREAD

**Issue by military1** [AdguardTeam/AdGuardSDNSFilter#458]
Adguard DNS / Adguard Home
Blocked ping to 9.9.9.9 and 149.112.112.112 (Quad9 DNS)
![2020-09-25_095544](https://user-images.githubusercontent.com/10153037/94237136-0a475880-ff17-11ea-9e9c-9b1d52ee9541.png)

**Comment by ameshkov** [comment]
Neither AdGuard DNS nor AdGuard Home can cause anything like this.
