### ISSUE TITLE
www.scarabresearch.com

### ISSUE THREAD

**Issue by beerisgood** [AdguardTeam/AdGuardSDNSFilter#459]
### Steps to reproduce

1. go to https://www.nuclearblast.de/en/shop/general/privacy.html#content-element-chapter-21692
2. under Cookies click on Scarap Research
3. get blocked site

### Expected behavior

Site should work

### Actual behavior

Site is blocked

<details><summary>Screenshot/ Infos:</summary>
<img width="305" alt="NextDNS" src="https://user-images.githubusercontent.com/9625159/94351779-aaa79500-005d-11eb-943c-b05a14619ac7.png">

On the site also this info is listed for Scarap Research:
Control cookie used in conjunction with the website's Content Delivery Network (CDN)

So is this domain really bad? NextDNS doesn't block it.
</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| How did you setup DNS configuration:| Router

**Comment by DandelionSprout** [comment]
The entry seems to be sourced from [EasyPrivacy Tracking Servers](https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_trackingservers.txt), and AdGuard DNS Filter seems to me to have a pretty high focus on blocking trackers.

**Comment by beerisgood** [comment]
> AdGuard DNS Filter seems to me to have a pretty high focus on blocking trackers

You mean it's more affected for false positives. Sadly nobody care. Bye

**Comment by DandelionSprout** [comment]
I'm not a fan of tracker-blocking either, to the point where I don't even actually use AdGuard DNS Filter.

You see, my intention was to imply to first ask EasyPrivacy about removing their entry against that site. However, since their entry against it uses `$third-party`, this makes the matter a bit more complicated than I had originally thought.
