### ISSUE TITLE
freepornpicss.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#460]
### Steps to reproduce
1. Use AdGuard Family DNS

### Expected behavior
Site should be blocked.

### Actual behavior
Site is not blocked.

### nslookup
nslookup freepornpicss.com dns-family.adguard.com
Server:  UnKnown
Address:  94.140.14.15

Non-authoritative answer:
Name:    freepornpicss.com
Addresses:  2606:4700:3032::681b:ab74
          2606:4700:3036::681b:aa74
          2606:4700:3035::ac43:c570
          172.67.197.112
          104.27.170.116
          104.27.171.116

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Family Protection, IPv4
| How did you setup DNS configuration:| Router
| Device model:| Unspecified

**Comment by Alex-302** [comment]
@lolka4toli

**Comment by lolka4toli** [comment]
Added to adult filter.
