### ISSUE TITLE
schools.madrasati.sa

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#461]
### Expected behavior
Site is a legit educational resource in Saudi Arabia; shouldn't be blocked.

### Actual behavior
AdGuard DNS blocks it.

### nslookup
nslookup schools.madrasati.sa dns.adguard.com
Server:  UnKnown
Address:  94.140.15.15

Non-authoritative answer:
Non-authoritative answer:
Name:    schools.madrasati.sa

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| default, IpV4
| How did you setup DNS configuration:| System
| Device model:| repro=Windows 10 desktop PC
| Operating system and version:| Windows 10

**Comment by DandelionSprout** [comment]
I can't find `||schools.madrasati.sa^` or `||madrasati.sa^` in the list, nor are they shown as blocked in the logger when testing with AdGuard Home.

So I think the site's server is simply down.

**Comment by ameshkov** [comment]
Yep, AG DNS does not block it

**Comment by Martialart** [comment]
our educational system uses https://login.microsoftonline.com/ with i think we use sub domain or something
