### ISSUE TITLE
block tapsell.ix

### ISSUE THREAD

**Issue by 3xploiton3** [AdguardTeam/AdGuardSDNSFilter#462]
https://github.com/notracking/hosts-blocklists/issues/424#issue-706533130

tracking site

https://play.google.com/store/apps/details?id=ir.ilmili.telegraph&hl=en

**Comment by Alex-302** [comment]
I can't reproduce. In the log I see `tapsell.ir`(blocked)

**Comment by 3xploiton3** [comment]
tapsell.ix

owner change domain

**Comment by 3xploiton3** [comment]
@AdamWr

**Comment by AdamWr** [comment]
Is `.ix` even a correct domain?
https://www.iana.org/domains/root/db
