### ISSUE TITLE
NSFW > camabi.com

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#464]
### nslookup

nslookup camabi.com dns-family.adguard.com
Server:  UnKnown
Address:  94.140.15.16

Non-authoritative answer:
Name:    camabi.com
Addresses:  207.246.147.249
          207.246.147.250
          207.246.147.189
          207.246.147.190

### Your environment

Original Report
|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| family-protection-ipv4
| How did you setup DNS configuration:| router
| Device model:| unspecified
| Operating system and version:| unspecified

Reproduction
|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| family-protection-ipv4
| How did you setup DNS configuration:| OS
| Device model:| r=TP-Link Archer A6
| Operating system and version:| Windows 10 Insider Preview - Beta Ring 19042.546

**Comment by Alex-302** [comment]
@lolka4toli please take a look.

**Comment by lolka4toli** [comment]
Added to adult category.
