### ISSUE TITLE
Set static IP for fritz.box as 192.168.178.1

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdGuardSDNSFilter#465]
Standard IP address for fritz.box is 192.168.178.1. When user selects our DNS, user cannot access the router unless IP address is specified.

**Comment by ameshkov** [comment]
I really don't think we should handle this domain on our DNS, resolving local domains is kinda not our responsibility. We should advise users to enter it in the hosts file instead.

**Comment by BlazDT** [comment]
Some users are not tech-savy and on mobile devices user does not have access to hosts file equivalent.

**Comment by ameshkov** [comment]
I understand, but resolving fritz.box to a specific LAN IP might be even considered malicious behavior despite it being it being useful to some users.

**Comment by BlazDT** [comment]
That url is only used by default by Fritz!Box router and not anywhere else (if user changes IP address of the router he/she will likely type IP address). More tech-savy users are typing the IP into the address, but in that router's manual it says to type into fritz.box into address bar and the normal Joe is doing it and then wondering why it does not work (which can result in angry emails/phone calls to AVM (manufacturer of Fritz!Box router)).
