### ISSUE TITLE
DNS False Positive Rule

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdGuardSDNSFilter#474]
Since today I cannot share pictures or links to Twitter or LinkedIn using Buffer iOS application (https://apps.apple.com/us/app/buffer-social-media-manager/id490474324) because of this rule:

buffer-media-uploads.s3.amazonaws.com

Which looks legetimate to me.

**Comment by Alex-302** [comment]
@Quorum75 family DNS?
