### ISSUE TITLE
tracking.epicgames.com #DNS #Tracking Servers

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardSDNSFilter#475]
@privacy-advo commented on [Thu Oct 15 2020](https://github.com/AdguardTeam/AdguardFilters/issues/65620)

***Description***:
* **tracking.epicgames.com is not blocked by https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/SpywareFilter/sections/tracking_servers.txt**: 

---

@Alex-302 commented on [Thu Oct 15 2020](https://github.com/AdguardTeam/AdguardFilters/issues/65620#issuecomment-709472743)

Hi. That's because of an issue:
https://forum.adguard.com/index.php?threads/epicgames-for-windows-not-loading.35325/

---

@privacy-advo commented on [Thu Oct 15 2020](https://github.com/AdguardTeam/AdguardFilters/issues/65620#issuecomment-709546856)

Thank you @Alex-302 for the fast response.
Right now I'm blocking this domain with my local dnscrypt-proxy and Epic Games Launcher works fine. I just would like to have it included and not manually blacklisted.

I *don't want* to accuse someone, but sometimes I wonder about really active users who only ask for whitlistings of obvious domains as adjust.com etc. [https://github.com/EnergizedProtection/block/issues/313]
The person in the forum post just posted this single post. [https://forum.adguard.com/index.php?members/french_cmm.28015/]

What is your opinion on this and or experience?

**Comment by privacy-advo** [comment]
Thanks for the removal from the exclusions. 
But tracking.epicgames.com ist not yet part of AdGuard's filters.
