### ISSUE TITLE
||jp.sharp^

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#477]
### nslookup
nslookup jp.shard dns.adguard.com
Server:  UnKnown
Address:  94.140.15.15

*** UnKnown can't find jp.shard: Non-existent domain

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default, dns.adguard.com
| How did you setup DNS configuration:| nslookup only
| Device model:| Windows PC
| Operating system and version:| Windows 10 20H2

**Comment by Alex-302** [comment]
Hm. Do not understand why it is blocked by DNS. I can visit it with AD Home on my NAS with AG DNS filter and CF upstream. 
@ameshkov could you please assist?

**Comment by ameshkov** [comment]
It is not blocked, there's a SERVFAIL response from AdGuard DNS:

```
nslookup jp.sharp 94.140.15.15
Server:		94.140.15.15
Address:	94.140.15.15#53

** server can't find jp.sharp: SERVFAIL
```

**Comment by ameshkov** [comment]
We'll see what can be done with this on AG DNS side.
