### ISSUE TITLE
Disney+ hotstar app issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#479]
@agdw18 commented on [Fri Oct 30 2020](https://github.com/AdguardTeam/AdGuardDNS/issues/116)

I have issued with app disney+ hotstar, it's shown error if i change with other dns it's work perfectly

![Screenshot_20201028-180302075](https://user-images.githubusercontent.com/73678090/97651827-aa048300-1a8f-11eb-8de1-650fbfde561d.jpg)

**Comment by Alex-302** [comment]
@agdw18 could you please check with "Non-filtering" DNS?
```
94.140.14.140
94.140.14.141
```
On my device it does not work(without Indian VPN video geo-blocked, with VPN - app does not start, infinite loading)

**Comment by agdw18** [comment]
It's work without filtering

Pada tanggal Sab, 31 Okt 2020 20.30, Alex <notifications@github.com>
menulis:

**Comment by Alex-302** [comment]
Did you check with this DNS?
94.140.14.140
94.140.14.141

**Comment by agdw18** [comment]
Yes i change with non filtering dns
94.140.14.140
94.140.14.141

Pada tanggal Sab, 31 Okt 2020 22.06, Alex <notifications@github.com>
menulis:

**Comment by Alex-302** [comment]
Do you use AdGuard for Android?

**Comment by agdw18** [comment]
No i used doh on mikrotik

Pada tanggal Min, 1 Nov 2020 00.12, Alex <notifications@github.com> menulis:

**Comment by Alex-302** [comment]
Not sure If it can be fixed, because cannot even play videos without DNS.
