### ISSUE TITLE
footballua.tv

### ISSUE THREAD

**Issue by qwertyuiop2k20** [AdguardTeam/AdGuardSDNSFilter#480]
Hello. I want you to block those sites, domains, cookies from those sites that are highlighted in red. This is advertising, analytics, and so on. Can you do this at the DNS level? Thank you.
![Screenshot_20201104-090123](https://user-images.githubusercontent.com/62207349/98080819-f411ae00-1e6d-11eb-99a6-398e65b09d7c.png)
![Screenshot_20201104-090305](https://user-images.githubusercontent.com/62207349/98080841-fffd7000-1e6d-11eb-8bd4-3ce7bc9f7055.png)
![Screenshot_20201104-090324](https://user-images.githubusercontent.com/62207349/98080878-11df1300-1e6e-11eb-87d8-98ebf87a42ab.png)
![Screenshot_20201104-090345](https://user-images.githubusercontent.com/62207349/98080907-202d2f00-1e6e-11eb-8b81-facb98de7bfc.png)
![Screenshot_20201104-090404](https://user-images.githubusercontent.com/62207349/98080934-2b805a80-1e6e-11eb-8bab-73eaa5abb8ff.png)

**Comment by Alex-302** [comment]
Please copy that domains as text.

**Comment by qwertyuiop2k20** [comment]
2mdn.net
s0.2mdn.net
admixer.net
cdn.admixer.net
inv-nets.admixer.net
adtcdn.com
player.adtcdn.com
adtelligent.com
ghb.adtelligent.com
player.adtelligent.com
sync.adtelligent.com
sync2.adtelligent.com
ahacdn.me
cdn53833466.ahacdn.me
player.adtelligent.com
bidr.io
match.prod.bidr.io
clarity.ms
www.clarity.ms
doubleclick.net
pubads.g.doubleclick.net
securepubads.g.doubleclick.net
facebook.net
connect.facebook.net
gemius.pl
gaua.hit.gemius.pl
ua.hit.gemius.pl
geodns.me
ghb-adtelligent-com.geodns.me
ghb.adtelligent.com
google-analytics.com
www.google-analytics.com
adservice.google.com
googletagmanager.com
www.googletagmanager.com
idealmedia.io
jsc.idealmedia.io
imasdk.googleapis.com
recreativ.ru
sharethis.com
platform-api.sharethis.com
t-msedge.net
standard.t-0001.t-msedge.net
yadro.ru
counter.yadro.ru

**Comment by Alex-302** [comment]
I mean domains, which are not blocked by DNS.

**Comment by qwertyuiop2k20** [comment]
I want you to block this all domains. I don't know which the domains blocked by DNS. But, i think, this domains is bad and included advertising. I hate ads. I can to block ads, but i want to help other people, which can't this to do.
