### ISSUE TITLE
Adguard DNS blocking BBC iPlayer

### ISSUE THREAD

**Issue by Perfectlynk** [AdguardTeam/AdGuardSDNSFilter#482]
### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

![PXL_20201108_161250810](https://user-images.githubusercontent.com/72349391/98470432-7509d600-21dd-11eb-9571-aa1d63704dcd.jpg)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (e.g. Default, 176.103.130.130)
| How did you setup DNS configuration:| (System/DNSCrypt app/Router)
| Device model:| (e.g. Google Pixel)
| Operating system and version:| (e.g. Android 7.1.2)

Hello, I cannot access BBC iPlayer on Chromecast with Google TV. Everything else works fine. I read that some people with pi hole had to whitelist 'mybbc-analytics.files.bbci.co.uk'. Is there a possibility that this is being blocked?

Thanks

**Comment by Alex-302** [comment]
Hi. I don't have Google TV.
Do you know how to install AdGuard Home(personal local DNS service with filtering log)?

**Comment by Perfectlynk** [comment]
Hey. No I don't know how to install Adguard Home.

**Comment by Alex-302** [comment]
Ok. Please describe how to reproduce it, with download link and other requirements.

**Comment by Perfectlynk** [comment]
There's no way to reproduce it unless you grab Chromecast w/ Google TV try to open BBC iPlayer. And have Adguard DNS on your router. 
People with Pi hole had to add a rule to whitelist. That's why I asked if Adguard was  blocking the rule.

**Comment by Alex-302** [comment]
Ok. Changed our rule.

**Comment by Perfectlynk** [comment]
Hello. Okay thanks I'll test it and see if it works.

**Comment by Alex-302** [comment]
@Perfectlynk Please check. Now this domain is not blocked.

**Comment by Perfectlynk** [comment]
I checked it still has an error so it must be on Google's end. Thanks for all the help.

**Comment by Alex-302** [comment]
Ok, restored that rule.

**Comment by Perfectlynk** [comment]
Hello. I can confirm Adguard DNS is blocking BBC iPlayer on Chromecast with Google TV. After resetting my router, I kept my router with Google DNS and tried BBC iPlayer and low and behold the app open without problems. When I changed my DNS on my router to Adguard DNS it blocked the app giving me the same error as before I reset the router. So this is something you have to look into.
