### ISSUE TITLE
Adguard Dns filtering bug

### ISSUE THREAD

**Issue by unununium1232** [AdguardTeam/AdGuardSDNSFilter#488]
### Steps to reproduce

1. Set DNS settings on and set to Adguard DNS over https
2. Reboot
3. Use of chrome 86.0.42.40.183 64 bit (lastest) and adguard 7.5.2 (lastest) Windows 10 1909 Home SL
4. https://tr.investing.com/currencies/usd-try

### Expected behavior
Values should be updating.

### Actual behavior
Values aren't until I disable dns filtering
 I need to refresh everytime I wanted to see new values
Video: [2020-11-06 10-40-47.zip](https://github.com/AdguardTeam/AdguardForWindows/files/5499845/2020-11-06.10-40-47.zip)
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/73962085/98340655-c15ae780-201e-11eb-80ac-046f27b8a10a.png)

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59)
* Operating system and version: (e.g. Windows 10, v.1703, build 15063.413)

**Comment by Alex-302** [comment]
Not reproduced.
