### ISSUE TITLE
downdetector.com or for me allestoringen.nl. -- Adguard dns filtered

### ISSUE THREAD

**Issue by ijuliank** [AdguardTeam/AdGuardSDNSFilter#489]
https://ibb.co/mzF3QRr im getting this (picture) if i want see the comments behind it, also if i click on consent its not working

**Comment by Alex-302** [comment]
@ijuliank Hi. Do you still have this issue?
Please provide the links to pages.

**Comment by ijuliank** [comment]
It doesn't matter what page, its just downdetector of one of the services https://downdetector.com/status/wow/ just the comment section fron disqus, yes still the issue

**Comment by krystian3w** [comment]
So few filters block load evidon pop-up?

**Comment by ijuliank** [comment]
I checked myself, it not going to work until you let google ads thruw, this issue can be closed
