### ISSUE TITLE
Please add ||scorecardresearch.com^  in AdGuard DNS filter list

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdGuardSDNSFilter#492]
Hi guys,

Is there a possibility to add the below rule in adGuard DNS filter used by adGuard DNS?

||scorecardresearch.com^

This is to block ads in Yahoo App and Yahoo Mail app:

sb.scorecardresearch.com

The reason is I’ve been installing and recommending adGuard DNS in all my friends and family’s router and also helping them install the ios 14 AdGuard DNS profile in their phone, but they always complain that  their Yahoo Mail app always has ads. 

I tested it using my machine and its because sb.scorecardresearch.com is not being blocked by the AdGuard DNS filter but is being blocked by other third party blocklist.

I did a bit of check also and it seems that website is a tracker that really needs to be blocked.

PS, if the suggestion is to use other filters, I can’t do that in my friends and familiy’s router. I can only change their DNS.

Thanks!

**Comment by Alex-302** [comment]
Hi. Blocking of this domain will break a lot of sites:(

**Comment by zznosar** [comment]
Do you know what sites does it block? I wonder why other blocklist block it and i just check their github pages, no one is complaining.

**Comment by zznosar** [comment]
https://www.theguardian.com/technology/2012/apr/23/scorecardresearch-tracking-trackers-cookies-web-monitoring

It seems to be very dodgy though.

**Comment by BourbonCrow** [comment]
I've been using Pete lows block list for a long time and it's on there.. And I never noticed any site breaking..

**Comment by zznosar** [comment]
@Alex-302 @ameshkov, any chance adding this tracker? I have been checking around and asking people about it and they said, nothing was broken as per them... i really think its good idea to include it in adGuard DNS and the adGuard DNS filter. If someone complains, then we can remove it?

**Comment by BourbonCrow** [comment]
@zznosar it seems to be added now in adguard tracking protection it's in there for me

**Comment by zznosar** [comment]
@BourbonCrow, i think it’s already in the other filter. But was hoping it to be added in adGuard DNs and adguard dns filter since adguard dns filter is a combination or mix of multiple filters. Also, I can’t add filter in a router level.

**Comment by ameshkov** [comment]
The problem is that the AdGuard DNS filter is supposed to be casual-user-friendly so we tend to not block trackers when blocking them leads to breaking popular apps or websites.
