### ISSUE TITLE
@@||app.adjust.com^

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#493]
Domain is part of a tracking network, but seems to be whitelisted for some reason.

### NSLOOKUP
nslookup app.adjust.com dns.adguard.com
╤хЁтхЁ:  dns.adguard.com
Address:  94.140.15.15

Untrustworthy response:
╚ь :     app.adjust.com
Addresses:  185.151.204.11
          185.151.204.10
          185.151.204.9
          185.151.204.12

### Screenshot
<details>
![Screenshot_20201124-173738_AdGuard](https://user-images.githubusercontent.com/33634917/100387166-15f6ee80-3030-11eb-8af7-9510b87af632.jpg)
</details>
### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default, DNSCrypt
| How did you setup DNS configuration:| AdGuard for Android app

**Comment by ameshkov** [comment]
Blocking it breaks a lot of apps and that's why we don't block in AG DNS.

**Comment by Alex-302** [comment]
Blocking of this domain breaks a lot of stuff.
