### ISSUE TITLE
please block these gambling websites

### ISSUE THREAD

**Issue by DiAnTTA** [AdguardTeam/AdGuardSDNSFilter#494]
```
qc.x8vn.com
1126bet.com
bong99.vip
ak9.6895588.com
one88.me
vz888.me
dd7.xyz
```
These are 3rd party websites that often have gif ads:
![x8](https://user-images.githubusercontent.com/74956696/100451355-d987c900-30e9-11eb-9345-6ab7a925b01c.gif)
**Screenshot on mobile:**
![Screenshot_20201127-194946](https://user-images.githubusercontent.com/74956696/100451409-f0c6b680-30e9-11eb-955d-cddb05df07b9.png)

**Comment by ameshkov** [comment]
Sorry, but this is out of scope of AdGuard DNS filter
