### ISSUE TITLE
Google Play: au.com.auspost.android

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardSDNSFilter#496]
@adguard-bot commented on [Wed Dec 02 2020](https://github.com/AdguardTeam/AdguardFilters/issues/69064)

### Issue URL (Incorrect Blocking)
 [https://play.google.com/store/apps/details?id=au.com.auspost.android](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dau.com.auspost.android)
### Comment
Username: @planet0
> Australia Post now seems to rely on using geo.captcha-delivery.com which is currently blocked on the DNS Filter as: 
> 
> ||datadome.co^
> 
> --
> The information below is automatically generated. Do not delete it.
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
> https://userscripts.adtidy.org/release/disable-amp/1.0/disable-amp.meta.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/F4X5XrR.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/Q1M5gzo.jpg)
</details>

### System configuration

Information | value
--- | ---
Platform: | Android 9
AdGuard product: | AdGuard for Android v3.5.2 (66)
AdGuard mode: | VPN
Filtering quality: | High-quality
HTTPS filtering: | enabled
DNS requests blocking: | enabled
Filters: | <b>Ad Blocking:</b><br/> AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>Spam404, <br/>NoCoin Filter List
Custom filter subscriptions: | 

---

@planet0 commented on [Wed Dec 02 2020](https://github.com/AdguardTeam/AdguardFilters/issues/69064#issuecomment-737193120)

Forgot to mention that unblocking only geo.captcha-delivery.com resolves the issue.

**Comment by planet0** [comment]
@Alex-302 Thank you for unblocking **datadome.co**, they have also used this domain on their website login page that prevents logging in. So that rule covers them all.

Domains found in AdGuard Home query log:
- sslgen-auspost.datadome.co
- js.datadome.co
- api-js.datadome.co
