### ISSUE TITLE
filter breaks isp app

### ISSUE THREAD

**Issue by ijuliank** [AdguardTeam/AdGuardSDNSFilter#498]
please whitelist omsc.kpn.com, its breaks a isp app

**Comment by Alex-302** [comment]
What is "isp app"?

**Comment by jordanelliott23** [comment]
@ijuliank can you paste the direct app store link if its an app in the app store? that way we can install the app and figure out the problem

**Comment by TPS** [comment]
[Minimal Googl](https://google.com/search?q=kpn%20isp)ing [shows](https://en.m.wikipedia.org/wiki/KPN) that KPN is a telecom & ISP in the Netherlands.  Not speaking Dutch myself, the best I can find for the app is [their entire listing on the Play store](https://play.google.com/store/apps/dev?id=7055666745377742739).

**Comment by ameshkov** [comment]
Blocked by CNAME (points to Adobe analytics).

We can make an exception since it's just for one app.
