### ISSUE TITLE
||mangaqq.com/qc-new/

### ISSUE THREAD

**Issue by DiAnTTA** [AdguardTeam/AdGuardSDNSFilter#499]
- ||mangaqq.com/qc-new/

![IMG_20201207_215644~2](https://user-images.githubusercontent.com/74956696/101367386-ae1a9080-38d8-11eb-8889-59b7a8f0af3f.jpg)
![IMG_20201208_001858](https://user-images.githubusercontent.com/74956696/101382892-0d819c00-38eb-11eb-8c1b-0c2c18a22483.jpg)

- ||ff.imacdn.com^

![IMG_20201207_235130](https://user-images.githubusercontent.com/74956696/101379887-63ecdb80-38e7-11eb-934b-e1948fdd142f.jpg)

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (Default, 94.140.14.14)

**Comment by bigdargon** [comment]
Hầu hết các tên miền này đã bị chặn rồi! Có vấn đề cần thảo luận bạn sang đây nhé https://github.com/bigdargon/hostsVN/issues/271
