### ISSUE TITLE
Links in skyeng emails don't work

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#506]
@andreynovikovrelef commented on [Tue Dec 08 2020](https://github.com/AdguardTeam/AdGuardDNS/issues/126)

![2020-12-08_08-48](https://user-images.githubusercontent.com/42645327/101445608-db942800-3932-11eb-856a-a80994b5f67a.png)
![2020-12-08_08-47](https://user-images.githubusercontent.com/42645327/101445617-e058dc00-3932-11eb-9141-458e6958a1ca.png)
![2020-12-08_08-54](https://user-images.githubusercontent.com/42645327/101445680-fbc3e700-3932-11eb-819e-081436f9b35d.png)

I try open link but get network error.  Links work fine If I disable dns ip in my router settings.

http://email.corp.skyeng.ru/e/c/eyJlbWFpbF9pZCI6IlJObTZBZ01BQVhZOVhpNTdET0FQNndNN2R4NFlsQT09IiwiaHJlZiI6Imh0dHBzOi8vc2t5ZW5nLXNjaG9vbC50eXBlZm9ybS5jb20vdG8vZzhCb3N5c0IiLCJsaW5rX2lkIjo3NTAwNjYzMywicG9zaXRpb24iOjJ9/5cece4fa98557463c39be504a17a642da22cae50743320f7ed792d5f4f2593eb

**Comment by andreynovikovrelef** [comment]
Thanks!
