### ISSUE TITLE
Block ads in Yahoo Mail app on Android

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#512]
@alexkararo commented on [Thu Dec 17 2020](https://github.com/AdguardTeam/AdGuardDNS/issues/128)

Hi, 

Using Adguard DNS, setup as Private DNS in Android 9 or newer, does not block ads in the Yahoo Mail app. 
I found this suggestions here, on how to block them: https://www.reddit.com/r/Adguard/comments/iibmdd/block_ads_on_yahoo_mail_app/

I tested those rules, I blocked them using a Mikrotik router and the DNS service included in these routers, they seem to work. 
Can those rules be included in the Adguard DNS service?

Thank you!

**Comment by zznosar** [comment]
I guess this will not be fixed anytime soon? 
Its been almost 2 months and still open...

This also happens in Yahoo Mail app for ios.

the m.yap.yahoo.com needs to be blocked...

**Comment by ameshkov** [comment]
@Alex-302 we really need to test this first using AGH or similar means.

I see some of the domains are blocked in StevenBlack's and EasyPrivacy so there's a chance:
https://urlfilter.adtidy.org/v1/checkDomain?domain=m.yap.yahoo.com
https://urlfilter.adtidy.org/v1/checkDomain?domain=b.gemini.yahoo.com

Blocking `s.yimg.com` is a no go, obviously. 
`analytics.query.yahoo.com` - should be tested.

**Comment by Alex-302** [comment]
@zznosar Hi. Could you please show screenshot with ads?

**Comment by zznosar** [comment]
This is without adGuard With Blocklist. This will show some adds:

<img width="375" alt="PNG image" src="https://user-images.githubusercontent.com/27464836/107434808-5a9a1c80-6b7f-11eb-948b-3ef6060f69a6.png">

this is with adGuard DNS is On  with m.yap.yahoo.com added in the blocklist:

<img width="375" alt="Ubertas Melbourne" src="https://user-images.githubusercontent.com/27464836/107434914-89b08e00-6b7f-11eb-852f-7b8d556b9be7.png">

<img width="375" alt="PNG image 2" src="https://user-images.githubusercontent.com/27464836/107434934-9208c900-6b7f-11eb-83f1-ab492f1b86c9.png">

**Comment by Alex-302** [comment]
Ok. Added(fixed a typo in existing rule).
But it cannot be blocked by DNS, because breaks Yahoo Finance app for iOS https://github.com/AdguardTeam/AdguardFilters/issues/63354
