### ISSUE TITLE
ATP/WTA Live

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#513]
App link: https://apps.apple.com/ec/app/atp-wta-live/id395227928?l=en

### Steps to reproduce
1. Set up AdGuard DNS on your iPhone (through system settings, not through app)
2. Try to open the app
3. App will crash to desktop upon launch

### Actual behavior
Insta-crashes

<details><summary>Screen Recording:</summary>

See helpdesk ticket 3065132.

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default IPv4
| How did you setup DNS configuration:| System
| Device model:| unspecified iPhone
| Operating system and version:| iOS 14

**Comment by jordanelliott23** [comment]
from my end it looks like the filter causing the problem is www.google-analytics.com but i dont think we can unblock. it is too widely used. could you just add this to your allow list section on adguard app and see if it works.

@@||www.google-analytics.com^|$important

**Comment by ameshkov** [comment]
Yeah, unblocking Google Analytics is not an option.

**Comment by hadjisoteriou** [comment]
> @akmLaVx from my end it looks like the filter causing the problem is [www.google-analytics.com](http://www.google-analytics.com) but i dont think we can unblock. it is too widely used. could you just add this to your dns allow list section on adguard app and see if it works.
> 
> @@||www.google-analytics.com^|$important

ah, this is for AdGuard DNS on the iPhone (through system settings, not through app) so i’m guessing you can’t add to the white list in that case..?
