### ISSUE TITLE
Logentries.com is blocked by AdGuardDNS

### ISSUE THREAD

**Issue by ryanzidago** [AdguardTeam/AdGuardSDNSFilter#514]
Hey all,

**Would it be possible to remove logentries.com from the blocked-list?**

I have configured AdGuardDNS on my Ubuntu 20.04 by adding the nameserver' addresses:
```
94.140.14.14
94.140.15.15
```
to the `/etc/resolvconf/resolv.conf.d/head` file and restarting the `resolvconf` service with:
```
$ sudo systemcl restart resolvconf.service
$ sudo resolvconf -u
```

For most of the websites, I can see that AdGuardDNS works fine except that it blocks [logentries.com](https://logentries.com).
Before configuring AdGuardDNS I could access logentries. Once I removed AdGuardDNS's configuration, I could access logentries.com again. I know that the issue of me not accessing logentries.com is not browser related because I tried with both Firefox and Chrome. I also tried with cURL and logentries could not be reached.

**Comment by ameshkov** [comment]
Yep, a false positive indeed.

**Comment by ryanzidago** [comment]
Thank you ! :heart:
