### ISSUE TITLE
cdn.rozetka.com.ua

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#515]
This domain is used in Rozetka marketing emails.

### nslookup
Server:  dns.adguard.com
Address:  94.140.15.15

Untrustworthy response:
URL :     cdn.rozetka.com.ua
Addresses:  ::
          0.0.0.0

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default, IPv4
| How did you setup DNS configuration:| Original submission: Android app / Reproduction: NSLOOKUP
| Device model:| Sony G8342
| Operating system and version:| Android 9

**Comment by zloyden** [comment]
https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/516
