### ISSUE TITLE
Links in skyeng emails don't work

### ISSUE THREAD

**Issue by andreynovikov95** [AdguardTeam/AdGuardSDNSFilter#517]
### Steps to reproduce

1. @andreynovikovrelef commented on Mon Dec 21 2020

I try open link but get network error. Links work fine If I disable dns ip in my router settings.
http://email.content.skyeng.ru/e/c/eyJlbWFpbF9pZCI6ImRnT0xzd1NMc3dRQkFBRjJlYkQ1XzFLOHNFUV9vZEJFdm1JPSIsImhyZWYiOiJodHRwczovL3Byb21vLnNreWVuZy5ydS9hbGx0aW1lcz9zb3VyY2VfdHlwZT1lbWFpbFx1MDAyNnV0bV9tZWRpdW09ZW1haWxcdTAwMjZ1dG1fc291cmNlPWVtYWlsXHUwMDI2dXRtX2NhbXBhaWduPWJyYW5kLXNreWVuZyU3Q2F1ZGllbmNlLWFkdWx0X3N0dWRlbnQlN0N0aXRsZS1hY3Rpb25cdTAwMjZ1dG1fY29udGVudD1zdWJjb250ZW50LW55MjAyMSU3Q251bWJlci1sZXR0ZXIxXHUwMDI2dXRtX3Rlcm09Zm9ybWF0LWJ1dHRvblx1MDAyNndvcmtmbG93PWFkdWx0c1x1MDAyNnByb2R1Y3Q9dHlwZS1hY3Rpb24lN0NuYW1lLW55MjAyMVx1MDAyNm1hbmFnZXI9eWV2dGVldmFcdTAwMjZzdHVkeT1pbmRpdmlkdWFsXHUwMDI2c2VydmljZT1lbmdsaXNoIiwibGlua19pZCI6ODQ1MDAsInBvc2l0aW9uIjoxfQ/0fe5329fc6a492bfea1a5233cc7999b9a540ca8c2244276f9928895548cd9c95

### Expected behavior

http://email.content.skyeng.ru^ is opening
### Actual behavior

http://email.content.skyeng.ru isn't opening

<details><summary>Screenshot:</summary>

![2020-12-21_11-52_1](https://user-images.githubusercontent.com/64052598/102765677-fbddd100-438d-11eb-90a4-4a9bc1769ad4.png)
![2020-12-21_11-52](https://user-images.githubusercontent.com/64052598/102765680-fc766780-438d-11eb-8883-af4e54041181.png)
![2020-12-08_08-47](https://user-images.githubusercontent.com/64052598/102765681-fda79480-438d-11eb-9d7c-708051716927.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 94.140.14.14; 94.140.15.15
| How did you setup DNS configuration:| Router
| Device model:| HP 250 G5
| Operating system and version:| Linux Mint 20

**Comment by andreynovikov95** [comment]
I'm trying to push
![2020-12-21_13-26](https://user-images.githubusercontent.com/64052598/102767363-7c9dcc80-4390-11eb-8da8-6ba555e513c9.png)

**Comment by ameshkov** [comment]
@andreynovikov95 you'll need to fork it first to your own repo and push there. Then you'll be able to submit a pull request.

**Comment by ameshkov** [comment]
Anyway, it seems @zloyden has already pull requested the solution: https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/518/files

**Comment by andreynovikov95** [comment]
Yes, but his solution doesn't provide other possible cases

**Comment by andreynovikov95** [comment]
Yes, perfect. @ameshkov, @zloyden thanks!

**Comment by zloyden** [comment]
You are welcome. Thanks for your participating :)

**Comment by andreynovikov95** [comment]
@ameshkov, @zloyden  Why their links are blocking? May be there is another solution without adding in extension list?

**Comment by zloyden** [comment]
Unfortunately, no. It was blocked by `CNAME` and this is the most optimal solution.
