### ISSUE TITLE
web.whatsapp.com blocked

### ISSUE THREAD

**Issue by tonicofonico** [AdguardTeam/AdGuardSDNSFilter#526]
Seems doesn't resolve
### Steps to reproduce

1.[web,whatsapp.com](https://web.whatsapp.com)
2.
3.
4.

### Expected behavior
DNS BLOCKING SITE

### Actual behavior
Page don't load

<details><summary>Screenshot:</summary>

![Screenshot](https://user-images.githubusercontent.com/20930461/103168636-35eb1f00-4835-11eb-9eb0-6247cefe06c8.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| DNS Crypt
| How did you setup DNS configuration:| Router dns ssl
| Device model:| Firefox 84.0.1
| Operating system and version:| Windows 10 20H2 build 19042.685

**Comment by ameshkov** [comment]
I cannot reproduce this.

Please show this command output: `nslookup web.whatsapp.com 94.140.14.14`

**Comment by tonicofonico** [comment]
`nslookup web.whatsapp.com 94.140.14.14
Server:  dns.adguard.com
Address:  94.140.14.14

Risposta da un server non autorevole:
Nome:    mmx-ds.cdn.whatsapp.net
Addresses:  2a03:2880:f2ff:c0:face:b00c:0:167
          69.171.250.60
Aliases:  web.whatsapp.com`

**Comment by ameshkov** [comment]
Well, so it returns an answer -- there're IP addresses in the response.

There should be something else blocking it on your side.

**Comment by tonicofonico** [comment]
If I add the ip address in hosts file the webpage loads correctly. but without the page doesn't.
Also if i change dns to google dns the page loads correctly

**Comment by ameshkov** [comment]
I don't see how it can be possible. Do you use `dnscrypt-proxy`? Could you please enable logging there and find out what happens with that DNS query?

**Comment by tonicofonico** [comment]
Rebooted the router and the connection and now it's working
