### ISSUE TITLE
Incorrect adguard DNS filter

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#531]
@jimger commented on [Sun Jan 03 2021](https://github.com/AdguardTeam/AdGuardHome/issues/2516)

The problem is with
https://online.novasports.gr/

Although to adguard developers it may seems it is blocking it correctly, it breaks the site when using the adguard DNS, as streaming never loads. The only way is to use another DNS. As it is difficult for me to saw u the problem (it is paid streaming service), I can assure that the site breaks. It seems adguard for Android works ok.

**Comment by Alex-302** [comment]
I don't see how to check it without paid subscription.
@jimger Is it possible?

**Comment by hmdqrbn320** [comment]
> @jimger commented on [Sun Jan 03 2021](https://github.com/AdguardTeam/AdGuardHome/issues/2516)
> 
> The problem is with
> https://online.novasports.gr/
> 
> Although to adguard developers it may seems it is blocking it correctly, it breaks the site when using the adguard DNS, as streaming never loads. The only way is to use another DNS. As it is difficult for me to saw u the problem (it is paid streaming service), I can assure that the site breaks. It seems adguard for Android works ok.

**Comment by jimger** [comment]
@ameshkov Why did u close that? I wasn't able yet to verify completely. But it is in my todo list

@Alex-302 I will try to check all the stages. I will comment back on that when I will be able to verify. As a first step it would be nice to visit the site and check if actually u can check the content

**Comment by Alex-302** [comment]
Ok. Could you please try another our DNS - without filtering?
`94.140.14.140`
`94.140.14.141`
