### ISSUE TITLE
Blacklisting gemaltodigitalbankingidcloud.com is breaking banking site login

### ISSUE THREAD

**Issue by ewanda** [AdguardTeam/AdGuardSDNSFilter#532]
I recently started having problems with my bank – Coventry Building Society – and their login procedure, which uses a 2-factor authentication by calling the user to enter a number on the phone.

After talking with their support team, it seems they are trying to use Thales’ ID verification which calls a script on

signal-collector.gemaltodigitalbankingidcloud.com

... but when AdGuard DNS is enabled, the browser fails to access as it does not resolve.

When switching to ISP-provided DNS, it resolves OK to

34.255.186.94 signal-collector.gemaltodigitalbankingidcloud.com

 Is there a way of white-listing this URL so it doesn’t get blocked?

 

### Steps to reproduce

1. Try to resolve signal-collector.gemaltodigitalbankingidcloud.com

When using AdGuard DNS

### Expected behavior
Resolve IP

### Actual behavior
No IP address returned

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default, 176.103.130.130
| How did you setup DNS configuration:| broadband router and DHCP

**Comment by Alex-302** [comment]
@ewanda please check tomorrow(after ~24 hours).
