### ISSUE TITLE
||chtbl.com^

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#533]
### Steps to reproduce
nslookup chtbl.com dns.adguard.com
Server:  dns.adguard.com
Address:  94.140.15.15

Untrustworthy response:
chtbl.com
Addresses:  ::
          0.0.0.0

### Expected behavior
This service is used by Pocket Casts to embed podcast metadata to the podcasts hosted on the platform.

### Actual behavior
Service mistakenly identified as a tracker.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| regular, dns.adguard.com
| How did you setup DNS configuration:| through nslookup
| Device model:| Windows PC
| Operating system and version:| Windows 10 Insider Preview

**Comment by akmLaVx** [comment]
We're getting swarmed by tickets with this problem - apparently, it affects multiple podcast vendors. @AdguardTeam/filters-maintainers @AdguardTeam/qa-team any chance you could expedite this?

**Comment by ameshkov** [comment]
@akmLaVx sorry for the late reply, this should be fixed in an hour or two.
