### ISSUE TITLE
False positive: Oukitel OTA domain

### ISSUE THREAD

**Issue by k03mad** [AdguardTeam/AdGuardSDNSFilter#535]
Hello,

Rule `||adups.com^` from https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt blocks Oukitel OTA updates

<details><summary>Screenshot:</summary>
<img width="214" alt="_oukitel_ota" src="https://user-images.githubusercontent.com/3288444/104105032-9316b400-52bc-11eb-939c-87544868543a.png">

</details>

It seems there are more Oukitel OTA domains (found in AdAway blocklist):
```
fota5.adups.com
fota5db.adups.com
fota5p.adups.com
fota5s.adups.com
fota5t.adups.com
fota5tbk.adups.com
```

refs: https://github.com/AdAway/AdAway/issues/2440

**Comment by ameshkov** [comment]
Thank you for reporting it!
