### ISSUE TITLE
digianalytics.airtel.in

### ISSUE THREAD

**Issue by cantunborn** [AdguardTeam/AdGuardSDNSFilter#536]
`digianalytics.airtel.in` not blocked while using  https://play.google.com/store/apps/details?id=com.myairtelapp.

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #72066](https://github.com/AdguardTeam/AdguardFilters/issues/72066) via [**ZenHub**](https://www.zenhub.com/)
