### ISSUE TITLE
Unable to connect cc.loginfra.com

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdGuardSDNSFilter#538]
### URL: `https://www.webtoons.com/en/comedy/cursed-princess-club/list?title_no=1537`
![Screenshot](https://user-images.githubusercontent.com/37463155/104303531-19e8ae00-54c2-11eb-9350-b7b05804b08c.png)

if you want to reproduce it, please click one of those like the screenshot.

AdGuard Server: Default

**Comment by piquark6046** [comment]
Please check this: https://raw.githubusercontent.com/easylist/easylist/master/easyprivacy/easyprivacy_trackingservers.txt

**Comment by Alex-302** [comment]
What is wrong?

**Comment by piquark6046** [comment]
> 
> 
> What is wrong?

Did you see like this picture, after click one of these.
![Screenshot](https://user-images.githubusercontent.com/37463155/104335953-cc813680-54eb-11eb-919d-ee26eb10ddaa.png)

**Comment by piquark6046** [comment]
I think you can reproduce it like this:
![Screenshot](https://user-images.githubusercontent.com/37463155/104336710-9d1ef980-54ec-11eb-8b93-4531a3eeb823.png)
