### ISSUE TITLE
plausible.io false positive

### ISSUE THREAD

**Issue by smac89** [AdguardTeam/AdGuardSDNSFilter#548]
### Steps to reproduce

1. Try navigating to plausible.io with your filter rules in place

### Expected behavior

Should be able to browse the page

### Actual behavior

Page is blocked

<details><summary>Screenshot:</summary>

![ArcoLinux_2021-01-18_22-56-50](https://user-images.githubusercontent.com/8305511/104989630-7ecf6700-59e0-11eb-8d09-05589d0a70aa.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Local Unbound DNS
| How did you setup DNS configuration:| System
| Device model:| Laptop
| Operating system and version:| Linux ArcoB 5.10.7-arch1-1

```sh
➜ dig @localhost 'plausible.io'

; <<>> DiG 9.16.10 <<>> @localhost plausible.io
; (2 servers found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 52716
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;plausible.io.			IN	A

;; ANSWER SECTION:
plausible.io.		30	IN	A	54.177.0.157
plausible.io.		30	IN	A	104.248.63.231

;; Query time: 0 msec
;; SERVER: ::1#53(::1)
;; WHEN: Mon Jan 18 22:58:20 CST 2021
;; MSG SIZE  rcvd: 73
```

**Comment by Alex-302** [comment]
It is blocked as analytics.
