### ISSUE TITLE
Android app Hades Star is unable to connect when dns.adguard.com enabled

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#549]
@mrlucas commented on [Wed Jan 20 2021](https://github.com/AdguardTeam/AdGuardDNS/issues/135)

The android app/game Hades star http://www.hadesstar.com/
Is unable to launch when I have dns.adguard.com enabled.
I'm using a Google Pixel 4 with private dns.

![Screenshot_20210119-163618](https://user-images.githubusercontent.com/290109/105102936-5180c880-5a75-11eb-9ae9-cfbca06aa9da.jpg)

**Comment by Alex-302** [comment]
@mrlucas Hi. I cannot reproduce this issue. Could you please check when HTTPS filtering is disabled?

**Comment by mrlucas** [comment]
Thanks for looking into this.  I made a quick screen record of the
behavior.
https://lubois.com/hades.mp4
I'm not aware of a way to enable or disable HTTPS filtering when just using
your vanilla dns service.
I believe it is something that needs to be removed from your block list.
Regards,
Lucas

**Comment by Alex-302** [comment]
@mrlucas I cannot reproduce when AdGuard DNS entered in Android settings.
Please check with `dns-unfiltered.adguard.com`
https://kb.adguard.com/en/general/dns-providers#non-filtering

**Comment by Alex-302** [comment]
@mrlucas Hi. Any news?

**Comment by mrlucas** [comment]
I'm afraid there's no change when using the unfiltered dns.
I made a new screen recording:
https://lubois.com/hades.mp4

**Comment by Alex-302** [comment]
Probably some domain cannot be resolved from your location.
Do you have VPN app? Where do you live(region or country)?

**Comment by mrlucas** [comment]
This is using T-Mobile, I'm in the Chicago Suburbs.
When using adguard private dns while on wifi, it works.
I created a wifi network using the adguard DNS IP addresses, and it works
when using that.
Only when on the cellular network, with adguard private dns enabled does it
fail.
When I disable adguard private dns on the cellular network, it works.
Here's the error message for Android's logcat when it fails, it looks like
it's rejecting the ssl certificate.  I don't know why it would only reject
it when using your dns though.

02-27 17:01:44.044  5217  5269 E Unity   : UnityWebRequest:
sslCannotConnectCallback with
error=javax.net.ssl.SSLPeerUnverifiedException: Hostname www.hadesstar.com
not verified:
02-27 17:01:44.044  5217  5269 E Unity   :     certificate:
sha1/Ob8yaGJMyNcWcz/KwLG06vNNG7Q=
02-27 17:01:44.044  5217  5269 E Unity   :     DN: CN=hadesstar.com
02-27 17:01:44.044  5217  5269 E Unity   :     subjectAltNames: [
hadesstar.com] url=https://www.hadesstar.com/news/server-status.json

I looked at the certificate, it is valid.

[image: Screen Shot 2021-03-01 at 1.07.42 PM.png]

**Comment by Alex-302** [comment]
@ameshkov DNS bug? An issue also with `dns-unfiltered.adguard.com`

**Comment by ameshkov** [comment]
Hm, I don't understand what could it be yet.

@mrlucas what do you see when you open `https://dns.adguard.com/info.txt` in your browser?

**Comment by mrlucas** [comment]
dns2-vultr-chi-1.node.eu.consul

**Comment by ameshkov** [comment]
@mrlucas is it the same when you're on T-Mobile?

**Comment by ameshkov** [comment]
Tbh, it seems to be an issue with the server itself:
`https://www.hadesstar.com/news/server-status.json`

The SSL certificate they're using is not valid for `www.hadesstar.com` and it does not depend on the DNS server I am using.

**Comment by ameshkov** [comment]
Well, it should fail with any DNS if you try this command: `curl -I https://www.hadesstar.com/news/server-status.json`
