### ISSUE TITLE
honeybadger.io

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#55]
Blocked by the ||honeybadger.io^ rule

> I frequently have to turn it off to go look at errors reported for software I develop at HoneyBadger. Is that something you’d consider whitelisting? It’s just an error reporting tool, not really a tracker per se…

```
nslookup honeybadger.io 176.103.130.130
Server:		176.103.130.130
Address:	176.103.130.130#53

** server can't find honeybadger.io: NXDOMAIN
```

**Comment by scafroglia93** [comment]
Confirm, it's a false positive
