### ISSUE TITLE
Closure of Issue #530 leads to permanent DNS request storm from Wifire equpment switched on.

### ISSUE THREAD

**Issue by Another-1** [AdguardTeam/AdGuardSDNSFilter#558]
### Steps to reproduce
Implement fresh blocking list.

### Expected behavior
DNS request to sas53netbynet.visualon.info from Wifire STB is blocked from time to time.

### Actual behavior
Wifire STB generates DNS requests to sas53netbynet.visualon.info as fast as it can as long as it is switched on. This was discussed with vendor, no changes to firmware will be applied. The purpose of this requests is described as STB performance and health monitoring. So, as STB itself does not store any personal info and has no way to even enter such data, maybe it's worth removing from blocklist to avoid constant DNS flood, logs overflow etc.

![104857141-7ff08d80-5927-11eb-97b4-a7a3570d87d6](https://user-images.githubusercontent.com/9990899/105872822-e3f01180-600b-11eb-8976-8d02b84b073b.png)

![104857143-7ff08d80-5927-11eb-970e-43b645c1f7c4](https://user-images.githubusercontent.com/9990899/105872845-e8b4c580-600b-11eb-9f20-b3833a6b6eb7.png)

Tried different locking modes (0,0,0,0, NXDOMAIN, NODATA), issue stays the same.

**Comment by ameshkov** [comment]
@Alex-302 let's unblock it

**Comment by Alex-302** [comment]
We do not block it
![image](https://user-images.githubusercontent.com/8361299/105982365-d97f5780-609f-11eb-8543-d1f657d85af5.png)

**Comment by ameshkov** [comment]
@Alex-302 we actually do:
```
nslookup sas53netbynet.visualon.info 94.140.14.14
Server:		94.140.14.14
Address:	94.140.14.14#53

Non-authoritative answer:
Name:	sas53netbynet.visualon.info
Address: 0.0.0.0
Name:	sas53netbynet.visualon.info
Address: ::
```

**Comment by Alex-302** [comment]
Ok, found that rule. Removed.
