### ISSUE TITLE
www2.watchseriess.co

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#559]
### Steps to reproduce
1. Open the site when AdGuard DNS is enabled
2. Site will work extremely slow
3. Disabling AdGuard DNS immediately restores it back to normal speed

<details><summary>nslookup:</summary>

nslookup watchseriess.co dns.adguard.com
Server:  dns.adguard.com
Address:  94.140.14.14

Non-authoritative answer:
Name:    watchseriess.co
Addresses:  2606:4700:20::681a:e6b
          2606:4700:20::ac43:49d9
          2606:4700:20::681a:f6b
          104.26.15.107
          104.26.14.107
          172.67.73.217

nslookup www2.watchseriess.co dns.adguard.com
Server:  dns.adguard.com
Address:  94.140.14.14

Non-authoritative answer:
Name:    www2.watchseriess.co
Addresses:  2606:4700:3039::6815:c023
          2606:4700:3039::6815:c022
          104.21.192.35
          104.21.192.34

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default, 92.140.14.14
| How did you setup DNS configuration:| App
| Device model:| Amazon Fire Stick
| Operating system and version:| unspecified Android

**Comment by Alex-302** [comment]
@akmLaVx Please check with non-filtered AdGuard DNS.
