### ISSUE TITLE
ab.auone-net.jp

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#56]
Blocked by ||ab.auone-net.jp^

> With AdGuard DNS, mail server domain names are blocked and can not be sent or received. Why is AdGuard DNS Blocking? The domain name of the mail server is as follows.
> 
> POP: pop.ab.auone-net.jp
> SMTP: msa.ab.auone-net.jp

ID: 2138034

**Comment by Alex-302** [comment]
fixed
