### ISSUE TITLE
some ad redirections

### ISSUE THREAD

**Issue by uservictor** [AdguardTeam/AdGuardSDNSFilter#561]
I am using AdGuardHome with AdGuardSDNSFilter list, maybe you can look on this adresses. While browsing on an website, those adresses open and show ads.

https://android-protection.net
https://nglanzasa.top
https://www.armory-boomer-bishop-arcana.club
https://www.prizedaysuperexcellenttheday.club
https://www.luckydayprogramexcellentcongratulate.club
https://correry.com
https://offersqualitys.com
http://setsec.xyz
https://mobileeex.com
https://www.captain-ironman-ares-antman.space
http://d.nurera.com
https://ggresses.top
https://eu.new-fresh-news.com

_Edit: Upper mentioned url's are from browsing with an Smartphone, while browsing this site on PC there are diffrent ad redirections._ For example:
https://emagazing.fun
https://planduringe.fun
https://productionutility.com
https://lp1.stop-ads.xyz

Please note that I removed the text after .com\ because the advertisements are related to my device, for example "android-protection.net" delivers app download for my smartphone.

Have a nice day

**Comment by ameshkov** [comment]
What exact website these URLs pop-up on?

**Comment by uservictor** [comment]
https://www.ps3jailbreakdownloadfree.com/
If you browse on this website, those sites open in tabs.

**Comment by Alex-302** [comment]
@uservictor Hi. I can't reproduce. Do you use AdGuard DNS only, without ad blocker?

**Comment by uservictor** [comment]
yes

**Comment by uservictor** [comment]
I have turned off AdGuard Broswer addon (Windows) and AdGuard app (Android) and just run AGH for testing and get this redirections.

**Comment by Alex-302** [comment]
Checked this site with DNS only - ad redirects are blocked on my end.
Also some ads can be blocked by https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/585
