### ISSUE TITLE
USAA Membershop extension

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#563]
Ext: https://chrome.google.com/webstore/detail/usaa-membershop%C2%AE-button/iigenfhikbgbmkfaanejgdpbkgfcenjo

### Steps to reproduce
1. Install the extension on Chrome (reported on Mac)
2. Enable AdGuard DNS
3. Extension will slow down to a halt

### Actual behavior
Extension loads extremely slowly with AdGuard DNS enabled

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| AdGuard DNS, IPv4, regular
| How did you setup DNS configuration:| macOS, through System Preferences
| Device model:| unspecified MBP
| Operating system and version:| macOS 11

**Comment by Alex-302** [comment]
@akmLaVx Which country?

**Comment by Alex-302** [comment]
![image](https://user-images.githubusercontent.com/8361299/109316369-36635e80-7854-11eb-96c4-44abb903a745.png)
