### ISSUE TITLE
com.advanzia.android

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#567]
### Steps to reproduce
1. Install the app
2. App will fail to connect to the internet

### Actual behavior
Fails to connect to the internet with AdGuard DNS on

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| DoH, dns.adguard.com
| How did you setup DNS configuration:| System - Private DNS
| Device model:| Unspecified
| Operating system and version:| Android 9

**Comment by stanislav-atr** [comment]
@akmLaVx, hi! I wasn't able to install this app from my region, could you please clear your Filtering log, open your app and then send me the screenshot of the filtering log?

**Comment by akmLaVx** [comment]
The app is region-locked for me as well. I'll relay this to the customer.

**Comment by tyteen4a03** [comment]
I'm using Private DNS on Android so there's no logs, probably best to try https://www.apkmonk.com/app/com.advanzia.android/
