### ISSUE TITLE
open spotify link from tiktok broken.

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdGuardSDNSFilter#570]
@@||app.adjust.net.in^
@@||ulink.adjust.com^

these two filters fix it.

go here: 
(https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https://vm.tiktok.com/ZMeeh4VQh/)

then click open app in right hand corner then click the link in bio to reproduce once in tiktok app. (only reproduces in app)

**Comment by Alex-302** [comment]
Reverted https://github.com/AdguardTeam/AdguardFilters/issues/65919
