### ISSUE TITLE
Blocking relevant-digital.com blocks cookie notice and breaks website

### ISSUE THREAD

**Issue by baujahr** [AdguardTeam/AdGuardSDNSFilter#574]
www.vi.nl serves a cookie banner via relevant-digital.com,
blockage of this domain breaks the website with no way of interacting.

Unblocking the domain relevant-digital.com solves the problem.

**Comment by Alex-302** [comment]
What exactly is broken?

**Comment by baujahr** [comment]
You aren't able to access the website because blocking the domain doesn't bypass the cookie notice.
With the blocking of the domain there is just a transparent empty page with no way to interact.
