### ISSUE TITLE
web page not loading but works if i switch to different dns

### ISSUE THREAD

**Issue by jordanelliott23** [AdguardTeam/AdGuardSDNSFilter#579]
hello, i am trying to reach this page https://flow.page/trethofficial but it gives me this message
![3076593C-42BE-46C8-BADB-6860620ABE72](https://user-images.githubusercontent.com/71462072/107806908-12b8f800-6d2d-11eb-93ac-ab473e5af9f4.png)

if i switch to a different dns server in the app it works fine though. cant figure out why it load the page

**Comment by ameshkov** [comment]
Should be okay in an hour or so
