### ISSUE TITLE
Optimized DNS filter causes a CNN app crash

### ISSUE THREAD

**Issue by lolka4toli** [AdguardTeam/AdGuardSDNSFilter#584]
### Steps to reproduce

1. Install https://filters.adtidy.org/ios/filters/15_optimized.txt as a DNS filter
2. Download CNN app for iOS
3. Launch the app

### Expected behavior
CNN app should work as always

### Actual behavior
It crashes

### Your environment
Device model: iPhone
Operating system and version: 14.4

**Comment by Alex-302** [comment]
I can't reproduce on iPad.
Try to unblock domains one by one.

**Comment by slavaleleka** [comment]
I've reproduced the issue. and adding a few domains to allowlist helped:
```
cdn.krxd.net
consumer.krxd.net
```

@AdguardTeam/filters-maintainers 
I suppose that exclusion of `krxd.net` isn't really good idea, so we may add those domains to exceptions
