### ISSUE TITLE
Android app: com.viva.kidsflix

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardSDNSFilter#588]
### Steps to reproduce

1. Download the app.
2. Choose any movie or show in particular, for instance "Speed Racer: The Next Generation".
3. The app attempts to display preroll and midroll ads every ~8min. With the entry, this leads to short hiccups; while without the entry, I have reason to believe that the ads are shown.

### Expected behavior

Liste FR's adservers are implemented in AdGuard DNS Filter, because it has the entry `||getpublica.com^`, which blocks `pbs.getpublica.com`, the adserver currently used by that app. I admit this'd be difficult, because the list is not fragmented into category files the way most AdGuard- and EasyList-affiliated lists are.

Alternately that the entry is added to AdGuard Base's adserver list.

### Actual behavior

Since AdGuard DNS Filter currently does not have such an entry, I presume the ads are not blocked if only that list is being used, such as on stock AdGuard Home setups.

However, since I normally use [my own compilation list](https://raw.githubusercontent.com/DandelionSprout/adfilt/master/AdGuard%20Home%20Compilation%20List/AdGuardHomeCompilationList.txt), I admittedly haven't actually tested this assumption. I am instead submitting this report for the sake of other users of that app.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/22780683/108312728-7ae95d00-71b7-11eb-8e0d-9d4735cac399.png)

![image](https://user-images.githubusercontent.com/22780683/108314610-783c3700-71ba-11eb-8943-03a660f5f875.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| AdGuard Home
| How did you setup DNS configuration:| System (AdGuard for Android's DNS blocking functionality)
| Device model:| Motorola One Zoom
| Operating system and version:| Android 10

**Comment by Alex-302** [comment]
Only `pbs.getpublica.com` is blocked? Not sure, if it must be whitelisted in DNS.

**Comment by DandelionSprout** [comment]
No, the idea is to blacklist `pbs.getpublica.com`, not whitelist it.

But I'm short on time today to test this.
