### ISSUE TITLE
tracker on muasamcong.gov.vn / muasamcong.mpi.gov.vn

### ISSUE THREAD

**Issue by vhpcdpgl** [AdguardTeam/AdGuardSDNSFilter#592]
### Steps to reproduce

1. `http://muasamcong.gov.vn/` or `http://muasamcong.mpi.gov.vn/`
2. there is a tracker: `stats.muasamcong.gov.vn`
3. more info: `https://github.com/easylist/easylist/issues/7234`

### Expected behavior

adding this domain `stats.muasamcong.gov.vn` to AdGuard DNS Filter blocklist.
### Actual behavior

It tracks our private info.
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/59459998/108644999-c9626880-74e3-11eb-88aa-2b8360579db1.png)
</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (NextDNS with Adguard DNS filter)
| How did you setup DNS configuration:| (DNSCrypt-proxy)
| Device model:| (Windows 7/10 PC)
| Operating system and version:| (Chromium)

**Comment by Alex-302** [comment]
Added
