### ISSUE TITLE
Blocking video.intl.xiaomi.com domain breaks the functionality of multiple MIUI apps (MI Video, MI Browser, MI Weather)

### ISSUE THREAD

**Issue by Chilace** [AdguardTeam/AdGuardSDNSFilter#593]
### Steps to reproduce

1. Set "dns.adguard.com" as a Private DNS Server.
2. Open MI Weather app (https://play.google.com/store/apps/details?id=com.miui.weather2).
3. Tap on weather forecast video thumbnail.

### Expected behavior

Should open the weather forecast video in MI Video app (https://play.google.com/store/apps/details?id=com.miui.videoplayer).
### Actual behavior

Weather forecast video in MI Video app is blocked.

<details><summary>Screenshot:</summary>

![Screenshot_2021-02-23-04-11-12-564_com miui weather2](https://user-images.githubusercontent.com/22879802/108797428-39342a00-759c-11eb-9981-85e72e55d868.jpg)
![Screenshot_2021-02-23-04-10-06-555_com miui videoplayer](https://user-images.githubusercontent.com/22879802/108797456-481adc80-759c-11eb-8e2d-8870e08c51b1.jpg)
![Screenshot_2021-02-23-04-07-55-876_com miui videoplayer](https://user-images.githubusercontent.com/22879802/108797477-536e0800-759c-11eb-9654-bfbade1c7cd2.jpg)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| dns.adguard.com
| How did you setup DNS configuration:| Private DNS system settings
| Device model:| Xiaomi Redmi Note 7
| Operating system and version:| Android 10

**Comment by Alex-302** [comment]
fixed
