### ISSUE TITLE
Adguard DNS filter is breaking Micorosft Teams on NextDNS

### ISSUE THREAD

**Issue by nishaddesilva** [AdguardTeam/AdGuardSDNSFilter#594]
Microsoft Teams is not functioning properly with Adguard DNS enable on NextDNS

**Comment by adrianvanderwal** [comment]
This has broken all sites related to Azure cloud services.
![image](https://user-images.githubusercontent.com/6479661/108962792-3a587a80-76b4-11eb-94ea-8c8d78c2ee1b.png)

**Comment by autarchprinceps** [comment]
It also breaks outlook mail login, at least within mac OS accounts page.

**Comment by bakgwei** [comment]
Same here - is there any quick way to fix this? I have added teams.microsoft.com to the the NextDNS allowlist, so at least I get statu updates in MS Teams. Which other domains re recommended to set on the allowlist to fix this?

**Comment by autarchprinceps** [comment]
For my part *.login.live.com & *.login.microsoftonline.com helped.

**Comment by lyrad87** [comment]
I'd just disable the Adguard DNS filter for the moment. Skype was also affected. What autarchprinceps suggested worked as well in case you don't want to remove the whole list.

**Comment by stachdude** [comment]
portal.azure.com, bing.com also affected

**Comment by bakgwei** [comment]
> 
> 
> I'd just disable the Adguard DNS filter for the moment. Skype is also affected. What autarchprinceps suggested worked as well in case you don't want to remove the whole list.

Yep, same here. I started allowing individual domains, but the problem keeped re-appearing on other services (Ondrive etc), so seems pretty tedious. I wonder what went wrong at adguard, seems like a major flaw to me.

**Comment by nishaddesilva** [comment]
Try whitelisting *.trafficmanager.net . That domain shows up on every blocked item.
![lVOnuK](https://user-images.githubusercontent.com/74057395/108972675-91a51d80-76a9-11eb-8f31-a481be837df8.png)

**Comment by candiesdoodle** [comment]
*.login.live.com & *.login.microsoftonline.com helped for the thick clients and mobile apps too
but bing.com and portal.azure.com are blocked

**Comment by nishaddesilva** [comment]
> Try whitelisting *.trafficmanager.net . That domain shows up on every blocked item.
> ![lVOnuK](https://user-images.githubusercontent.com/74057395/108972675-91a51d80-76a9-11eb-8f31-a481be837df8.png)

This method works on NextDNS

**Comment by FloThinksPi** [comment]
On AdGuard whitelisting *.teams.microsoft.com made id work again. It shows all requests to this domain are blocked by this Filterlist. The Rule to unblock is:
```
@@||teams.microsoft.com^$important
```
However i am curious which entry causes this to be blocked.
I cannot make out any rule in the Filterlist that would block *.teams.microsoft.com.

**Comment by ameshkov** [comment]
Fixed this, thanks for reporting it!
