### ISSUE TITLE
Tracker from *<dot>gov<dot>vn

### ISSUE THREAD

**Issue by vhpcdpgl** [AdguardTeam/AdGuardSDNSFilter#596]
### Steps to reproduce

When running the program `vSignPDF_3.1.8` from `https://ca.gov.vn/documents/20182/6768590/vSignPDF_3.1.8.zip/6a5ed276-21ef-49f1-93fd-7558ec918294`
The tracker appears: `log.ca.gov.vn`

_More info:_
```
https://github.com/easylist/easylist/issues/7282
https://www.mypdns.org/rMATRIX447851cb5053d914a5e6517bbf379cdc7b8f9753
```
### Expected behavior

Add the tracker `log.ca.gov.vn` to Adguard DNS blocklist
### Actual behavior

It tracks who use program `vSignPDF`

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (94.140.14.14)
| How did you setup DNS configuration:| (pi-hole/DNSCrypt/NextDNS CLI/Adguard DNS filtering...)
| Device model:| (Android/Windows/iPhone)
| Operating system and version:| (Android 10/Windows 7/Windows 10)

**Comment by Alex-302** [comment]
Blocked.
