### ISSUE TITLE
False Positive for publish0x.com in AdGuard DNS Block List

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#597]
@bongochong commented on [Fri Feb 26 2021](https://github.com/AdguardTeam/AdGuardDNS/issues/141)

Just reporting that publish0x.com is erroneously blocked by AdGuard's DNS filter. It's a legitimate platform, but I can see why it would set off alarms for some people. Thanks for the great work guys!

**Comment by Alex-302** [comment]
Blocking rule will be changed in Easylist. Will check later.

**Comment by Alex-302** [comment]
Fixed.
