### ISSUE TITLE
Consider adding more filter sources

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#6]
https://github.com/AdguardTeam/AdguardDNS/issues/95#issuecomment-426868812

**Comment by bigdargon** [comment]
@ameshkov Approved request. You can close it! Thanks you!

**Comment by Yuki2718** [comment]
@ameshkov Having seen configuration.json, it seems currently AdGuard Spanish/Portuguese filter is not included, right? It's surprising given the popularity of the languages, see [Top Ten Languages Used in the Web](https://www.internetworldstats.com/stats7.htm).

**Comment by ameshkov** [comment]
Yeah, you're right, it's a good idea to add it.
https://github.com/AdguardTeam/AdGuardSDNSFilter/commit/8c9270dd4c9a7f30c93782a3730197df1b7cc26f
