### ISSUE TITLE
Dead domains

### ISSUE THREAD

**Issue by RicoHeat** [AdguardTeam/AdGuardSDNSFilter#603]
According to the creator of the OISD lists.. 
They have Removed 7718 dead domains, and 472 false positives / other domains. Used: 29345 domains from your Adguard DNS filters..
https://filters.adtidy.org/windows/filters/15.txt 
Is it common to have so many "dead domains"?
![20210228_224150](https://user-images.githubusercontent.com/41478458/109422381-3c08a200-7a16-11eb-8df6-d3b5906dfda3.jpg)

**Comment by ameshkov** [comment]
Considering that most of them aren't dead, that's okay.

Here's a version of the list that contains domains that were blocked at least a few times by AdGuard DNS during the last month: https://filters.adtidy.org/windows/filters/15_optimized.txt

**Comment by RicoHeat** [comment]
As always, you guys are always on point answering the community's questions.. It's always a pleasure.. Thanks for  the info.. 👍
