### ISSUE TITLE
oa.tr.line.me

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#604]
### Steps to reproduce
nslookup oa.tr.line.me dns.adguard.com
╤хЁтхЁ:  dns.adguard.com
Address:  94.140.14.14

Untrustworthy response:
╚ь :     oa.tr.line.me
Addresses:  ::
          0.0.0.0

### Expected behavior
oa.tr.line.me is a link redirection mechanism for the Line Messenger. Shouldn't be blocked.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| default
| How did you setup DNS configuration:| nslookup query

**Comment by Alex-302** [comment]
Fixed.
