### ISSUE TITLE
9Now app being blocked when trying to watch show

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdGuardSDNSFilter#606]
It seems the app [9Now ](https://play.google.com/store/apps/details?id=au.com.mi9.jumpin.app&hl=en&gl=US) app is having issues connecting properly.
On the TV app, it won't connect at all when a show is selected.
On the Android app there are frequent lost connection messages displayed at the bottom of the app.

### Steps to reproduce

1. Open 9Now app
2. Login
3. Select a show to watch
4. Connectivity lost or broken

### Expected behavior
Show plays

### Actual behavior
Connectivity to app lost or broken, depending on device

<details><summary>Screenshot:</summary>

![photo6187976292536789965](https://user-images.githubusercontent.com/6005161/109432718-4d729e00-7a58-11eb-9dfd-736dfcad8a4f.jpg)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| dns.adguard.com
| How did you setup DNS configuration:| Router/System/App - Depending on device. Android is filterered via AG TLS via AG, TV is filtered via AG TLS via router.
| Device model:| Oneplus 6, LG TV
| Operating system and version:| Android 10

**Comment by Alex-302** [comment]
@jslawler Hi. Does it work witn "Non-filtering" DNS?
https://adguard.com/en/adguard-dns/overview.html

**Comment by Alex-302** [comment]
On my device I see the same error with AdGuard VPN and any DNS(without ad blocker).

**Comment by jslawler** [comment]
Apologies on how long it took to reply.

This is primarily in regards to the TV app. See attached for issue.
When "Non-filtering" DNS is used, it works.

When I add `@@||nd.demdex.net^$important` to my custom filtering rules, the TV app works again.

![2021-03-24 06 21 13](https://user-images.githubusercontent.com/6005161/112212802-2713dd00-8c69-11eb-8305-ca53c0967238.jpg)

**Comment by jslawler** [comment]
@Alex-302 Any chance on getting this one added?

**Comment by Alex-302** [comment]
@jslawler Hi. We cannot unblock this domain for all users, because it is popular like Adobe or Google analytics.
Better write to their support - crash on blocked analytics is bad behavior.
