### ISSUE TITLE
Tracker on ttbc<hyphen>hcm<dot>gov<dot>vn

### ISSUE THREAD

**Issue by vhpcdpgl** [AdguardTeam/AdGuardSDNSFilter#609]
### Steps to reproduce

1. Open link: `ttbc-hcm.gov.vn`
2. Tracker appears: `log.ttbc-hcm.gov.vn`. Script: `<script src="https://log.ttbc-hcm.gov.vn/analytics.js?v=0.0.1"></script>`
3. More info: `https://github.com/easylist/easylist/issues/5750`

### Expected behavior

Adding the tracker `log.ttbc-hcm.gov.vn` to Adguard blocklists.
### Actual behavior

It tracks our private info.

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (94.140.14.14, 94.140.14.15)
| How did you setup DNS configuration:| (pi-hole/DNSCrypt NextDNS)
| Device model:| (PC, smartphones, smart TVs)
| Operating system and version:| (Windows, Android, iOS)

**Comment by Alex-302** [comment]
Fixed.
