### ISSUE TITLE
Whitelist cloudfront

### ISSUE THREAD

**Issue by Dalcinrafa** [AdguardTeam/AdGuardSDNSFilter#620]
Please whitelist https://d335luupugsy2.cloudfront.net. This is a server used for rdstation, which is a marketing app we use in my corporation. Thanks!

**Comment by Alex-302** [comment]
How can we check it?

**Comment by Dalcinrafa** [comment]
I'm assembling a newsletter right now. These are some of the resources I'm going to use.
https://d335luupugsy2.cloudfront.net/cms/files/65830/1615397127/$onr3f8rp98
https://d335luupugsy2.cloudfront.net/cms/files/65830/1615397127/$3me1xh3zwz5
And this is a screenshot of what it looks like in the web app.
https://drive.google.com/file/d/11Zhys3MXPJZ_FaoVsfgLrGAiFDDBMOUC/view?usp=sharing
