### ISSUE TITLE
dc-unlocker/hcu-client issue

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#622]
@hooddy commented on [Tue Mar 09 2021](https://github.com/AdguardTeam/AdGuardDNS/issues/144)

Have hard traffic blocking while tryin to accessing to dc-unlocker services from within dc-phoenix utility. It checks account first and its okay. Next its trying to download some servise information and a this stage its hard freeze. By scientific poke method i have found that reason is in AdGuard DNS filter at my router. As I disable it all turns to okay. Please check it out.

**Comment by Alex-302** [comment]
@hooddy Hi. Is it still actual?
