### ISSUE TITLE
pictalk.xyz

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdGuardSDNSFilter#634]
### Steps to reproduce
1. Set up AdGuard DNS (default)
2. Open pictalk.xyz
3. "Oops, site blocked"

### nslookup

nslookup pictalk.xyz dns.adguard.com
Server:  dns.adguard.com
Address:  94.140.14.14

*** dns.adguard.com can't find pictalk.xyz: Server failed

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| dns.adguard.com
| How did you setup DNS configuration:| nslookup / original: Android private DNS

**Comment by ameshkov** [comment]
Well, this is not our issue:

```
% nslookup pictalk.xyz 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find pictalk.xyz: SERVFAIL
```
