### ISSUE TITLE
edt.macworld.com blocked AdGuard DNS

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#639]
It's mapped to **edt-macworld-com.msgfocus.com** which is, as I understand, blocked by **||msgfocus.com^**

Google DNS:
```
;; ANSWER SECTION:
edt.macworld.com.	300	IN	CNAME	edt-macworld-com.msgfocus.com.
edt-macworld-com.msgfocus.com. 60 IN	A	65.9.66.3
edt-macworld-com.msgfocus.com. 60 IN	A	65.9.66.11
edt-macworld-com.msgfocus.com. 60 IN	A	65.9.66.65
edt-macworld-com.msgfocus.com. 60 IN	A	65.9.66.36
```
and AdGuard DNS:

```
;; ANSWER SECTION:
edt.macworld.com.	3600	IN	A	0.0.0.0
```

**Comment by ldi006** [comment]
Hi  I already forwarded a second email with subject "Follow up on ticket 501383".  This email includes:
Dear Support,

In addition to the earlier reporting, the same is also valid for “edt.macworld.co.uk"

Kind regards,

Luc Dierick

------------------


ldierick@mbpro-16 ~ % dig @176.103.130.130 edt.macworld.co.uk

; <<>> DiG 9.10.6 <<>> @176.103.130.130 edt.macworld.co.uk
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59236
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;edt.macworld.co.uk.		IN	A

;; ANSWER SECTION:
edt.macworld.co.uk.	3600	IN	A	0.0.0.0

;; Query time: 568 msec
;; SERVER: 176.103.130.130#53(176.103.130.130)
;; WHEN: Thu Apr 08 17:14:31 CEST 2021
;; MSG SIZE  rcvd: 63





ldierick@mbpro-16 ~ % dig @1.1.1.1 edt.macworld.co.uk

; <<>> DiG 9.10.6 <<>> @1.1.1.1 edt.macworld.co.uk
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 28073
;; flags: qr rd ra; QUERY: 1, ANSWER: 5, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;edt.macworld.co.uk.		IN	A

;; ANSWER SECTION:
edt.macworld.co.uk.	300	IN	CNAME	edt-macworld-co-uk.msgfocus.com.
edt-macworld-co-uk.msgfocus.com. 60 IN	A	54.192.86.10
edt-macworld-co-uk.msgfocus.com. 60 IN	A	54.192.86.42
edt-macworld-co-uk.msgfocus.com. 60 IN	A	54.192.86.48
edt-macworld-co-uk.msgfocus.com. 60 IN	A	54.192.86.63

;; Query time: 24 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Thu Apr 08 17:14:50 CEST 2021
;; MSG SIZE  rcvd: 156
