### ISSUE TITLE
adregain.com 

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdGuardSDNSFilter#640]
done

no 
 okay

### Steps to reproduce

1. go to adregain.com 
2. this site have some important tools.
3.
4.

### Expected behavior

site should open 
### Actual behavior

site not open

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| https://dns.adguard.com/dns-query in chrome

**Comment by Alex-302** [comment]
It is blocked as analytics.

**Comment by chirag127** [comment]
did you opened the website. this site provide good tools . in that way many other websites like facebook.com ,twitter.com and google.com should also be blocked as they are used as trackers.

**Comment by ameshkov** [comment]
Unfortunately, DNS is not that flexible, we have to block the whole domain if it's used in third-party context, and simply cannot block it partially.
