### ISSUE TITLE
Xiaomi tracking servers

### ISSUE THREAD

**Issue by jtechpro** [AdguardTeam/AdGuardSDNSFilter#644]
### Steps to reproduce

The following websites are tracking websites of Xiaomi for mobile devices.

They are blocked by Adaway, Energized Ultimate lists.

127.0.0.1 tracking.india.miui.com
127.0.0.1 sa.api.intl.miui.com
127.0.0.1 tracking.intl.miui.com
127.0.0.1 tracking.rus.miui.com
127.0.0.1 api.sec.miui.com
127.0.0.1 logupdate.avlyun.sec.miui.com
127.0.0.1 tracking.miui.com
127.0.0.1 fcanr.tracking.miui.com

127.0.0.1 api.ad.xiaomi.com
127.0.0.1 log.ad.xiaomi.com
127.0.0.1 sdkconfig.ad.xiaomi.com
127.0.0.1 track.ad.xiaomi.com
127.0.0.1 zeus.ad.xiaomi.com
127.0.0.1 data.mistat.india.xiaomi.com
127.0.0.1 api.ad.intl.xiaomi.com
127.0.0.1 diagnosis.ad.intl.xiaomi.com
127.0.0.1 sdkconfig.ad.intl.xiaomi.com
127.0.0.1 zeus.ad.intl.xiaomi.com
127.0.0.1 data.mistat.intl.xiaomi.com
127.0.0.1 data.mistat.rus.xiaomi.com

**Adaway reference**
https://github.com/AdAway/adaway.github.io/blob/master/hosts.txt

### Expected behavior
These should be blocked

### Actual behavior
They are not blocked

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default
| How did you setup DNS configuration:| System and Router
| Device model:| Xiaomi Redmi Note
| Operating system and version:| Android 11

**Comment by chirag127** [comment]
I think it blocked most of them

**Comment by Alex-302** [comment]
Ads I see, they are blocked by our DNS.

**Comment by chirag127** [comment]
data.mistat.intl.xiaomi.com is not blocked in dns. but data.mistat.*.xiaomi.com^ is in AdGuard Tracking Protection filter .

**Comment by ameshkov** [comment]
I see this rule in the DNS filter: `||data.mistat.*.xiaomi.com^`

And it's blocked by AdGuard DNS:
```
 % nslookup data.mistat.intl.xiaomi.com 94.140.14.14
Server:		94.140.14.14
Address:	94.140.14.14#53

Non-authoritative answer:
Name:	data.mistat.intl.xiaomi.com
Address: 0.0.0.0
Name:	data.mistat.intl.xiaomi.com
Address: ::
```

**Comment by chirag127** [comment]
By the way, what does this rule do ?
Because there are some reports that blocking this Stops the miui system
apps updates can you confirm it.

**Comment by ameshkov** [comment]
Well it blocks requests like `data.mistat.india.xiaomi.com ` and `data.mistat.intl.xiaomi.com `.

Regarding stopping the MIUI update, I haven't heard about that before.

**Comment by chirag127** [comment]
oisd recently unblocked it
https://www.reddit.com/r/oisd_blocklist/comments/m6j6fg/oisd_domain_blocklist/gxe4f7d?utm_source=share&utm_medium=web2x&context=3

**Comment by ameshkov** [comment]
Interesting, thanks for the link!

@Alex-302 plz take a look

**Comment by Alex-302** [comment]
not reproduced
![image](https://user-images.githubusercontent.com/8361299/117717956-25d04c80-b1e4-11eb-8b1a-ba22c80aa064.png)

**Comment by Alex-302** [comment]
Changed blocking rules.

**Comment by Alex-302** [comment]
I don't have xiaomi device and cannot check.
