### ISSUE TITLE
Click-through domains: info.smartdeploy.com, goto.walmart.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#645]
@Hammerfest commented on [Sun Apr 18 2021](https://github.com/AdguardTeam/AdGuardDNS/issues/151)

AdGuard DNS seems to have developed some issues as of, I want to say 3-6 months ago (maybe longer and I didnt notice)

It doesnt like quite a few subdomains!

As an example, a few months ago I was trying to fiddle with SmartDeploy and they sent me links to watch the setup video which was:
http://info.smartdeploy.com/hjPEY3Y00H000gkcJ030ULR
It would not resolve, and I could not ping info.smartdeploy.com, but I could ping smartdeploy.com

At the time, I figured it was an issue on their side as I tried it in 3 vastly different locations, but after trying again recently, I noticed, still not working, so I sent it to a friend who advised it works, and resolves to:
https://www.smartdeploy.com/demo/
Working just fine! Turn AdGuard DNS back on, flush/restart all the things, not working again!

Now that I am posting this, I recall several other sites that did this same thing (but cannot remember exact sites) and I have figured many other sites where just broken because of this, this is very concerning!

Why did I only make a ticket today?
I found another one that wouldn't work and had a friend online to doublecheck for me:
https://goto.walmart.com/c/159047/568844/9383?veh=aff&sourceid=imp_000011112222333344&prodsku=928494927&u=https%3A%2F%2Fwww.walmart.com%2Fip%2F928494927&subId1=cn-615e4f426d084d1299368dcdb26c45c6-dtp
Resolves to:
https://www.walmart.com/ip/I7-Barebone-WHITEBOOK-W-GTX1660TI-BLK/928494927?irgwc=1&sourceid=imp_T3AW%3AyW0UxyLRQ%3AwUx0Mo3Z2UkB0yjWZUTyFxo0&veh=aff&wmlspartner=imp_159047&clickid=T3AW%3AyW0UxyLRQ%3AwUx0Mo3Z2UkB0yjWZUTyFxo0&sharedid=&affiliates_ad_id=568844&campaign_id=9383

Same issue, it's AdGuard DNS!
Once I switch to any other DNS, it works just fine, but once AdGuard DNS is back in place and everything is cleared/restarted, its KAPUT again!

**Comment by Hammerfest** [comment]
To be clear since the title was changed to only these two domains, it impacts many more, I just don't have them on hand as I had not thought it to be an AdGuard DNS issue.

**Comment by ameshkov** [comment]
@Alex-302 both are blocked by CNAME.

When unblocking, we should probably start grouping these click-through domains.

**Comment by ameshkov** [comment]
@Hammerfest

> it impacts many more, I just don't have them on hand as I had not thought it to be an AdGuard DNS issue.

Well, false positives happen especially often with such click-through domains since they're actually pointing to a third-party tracking domain.

We usually unblock them one-by-one to avoid hurting users experience, but we need to learn about those cases to do that.

**Comment by Hammerfest** [comment]
explore.amd.com
