### ISSUE TITLE
https://freecoursesite.com/

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdGuardSDNSFilter#646]
### Steps to reproduce

1. go to the site https://freecoursesite.com/the-complete-web-developer-course-2-0-2/?__cf_chl_jschl_tk__=2ba25d60a49ec673707a2e5c3c8d67a6c8f3167a-1618761338-0-Aaq5f_ZcDlxFaJkhorWD_9_PtTJgFjsvsUEgb1i6pkrcJ5EY8CBn7Ja0j0U204LNOd97654xex91CmL5J2KyKdvhkcQSzGDapoGIxCVhLZdF8AaA5STcz8G5XDUQJWaGzF_AkAN0oSU9B_G6ctMdZuKvGCHFDhumRBWRf1oCy3KC9Hs2ASSwYgORZIpo-4biRGZD-RzlTzXnCaeRkudVogOAE-F5nXg2nevaM0oieAppSWHSNTniZzh56reZVxHMMTsd9MKg3XDqSUsB4toR2ZxMEEe5in3jF5Zbe4n6-IPMfZ7aY4_fUDY5heCVlqy8WJ-fgzrQFw5gqxxfrUfXp_pOJM9cAta1hK_QXYN6aWQty0GwM_DMtFgjAW8p7RMDTAgYNs_0o8jvVnbgY0VXn0E8TsI6lv7U1qQQ4l3WKy-0tR6W5rAG9TTbVk5tYI7djw
2. wait
3.
4.

### Expected behavior

Ad Blocker not get detected
### Actual behavior

Ad blocker not gets detected

<details>  <summary> 
![image](https://user-images.githubusercontent.com/76880977/115188190-32d8af00-a102-11eb-86e6-357bb42e6da3.png)
</summary>

![image](https://user-images.githubusercontent.com/76880977/115188460-96fb7300-a102-11eb-8231-8362df304a27.png)

</details>

### Your environment
https://dns.adguard.com/dns-query in chrome .

**Comment by Alex-302** [comment]
Cannot be fixed by DNS.

**Comment by chirag127** [comment]
but this anti adblock warning do not  by changing the adguard dns to google dns.

**Comment by Alex-302** [comment]
AdGuard DNS block ads and analytics.

**Comment by chirag127** [comment]
Okay, are you trying to say that  it is necessary to turn off adguard dns
to access this web site? And you can not remove the rule which is creating
the anti adblock banner from the adguard dns filter list?

By the way, which rule is creating the anti adblock warning.

**Comment by Alex-302** [comment]
That script is triggered when google ads are blocked. It is fixed in Base filter, also if AdGuard DNS enabled.

**Comment by chirag127** [comment]
And what about when only adguard dns enabled.
