### ISSUE TITLE
AdGuard DNS breaks IDAGIO iOS app

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdGuardSDNSFilter#653]
### Steps to reproduce

1. Open IDAGIO app on iPhone - https://apps.apple.com/app/idagio-classical-music/id1014917700 (I use Premium subscription, you might need to use a free trial to test the issue).
2. Play any album (e.g. any of the featured albums on _Discover_ tab).
3. Go to _My Collection_ tab.
4. Look at the _Recently Played_ list.

### Expected behavior

The album you played should appear in the _Recently Played_ list.

### Actual behavior

_Recently Played_ list never updates, it looks like AdGuard DNS is blocking some tracker IDAGIO uses to remember recently played albums. With AdGuard DNS disabled the albums appear correctly in the _Recently Played_.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default, DNS over HTTPS
| How did you setup DNS configuration:| iOS configuration profile from https://adguard.com/en/blog/encrypted-dns-ios-14.html
| Device model:| iPhone SE 2020
| Operating system and version:| iOS 14.4.2

**Comment by Alex-302** [comment]
Not sure what causes it. I see new records after relaunch app. Also I don't see blcoker domains, which can be unblocked. Better write to their support.
