### ISSUE TITLE
dcinside.com posting error

### ISSUE THREAD

**Issue by piquark6046** [AdguardTeam/AdGuardSDNSFilter#659]
AG DNS filter blocks the connection of `google-analytics.com` domain on `m.dcinside.com` and `mupload.dcinside.com`.
Therefore, I cannot post a posting on `dcinside.com`

https://github.com/AdguardTeam/AdguardFilters/issues/81513

https://github.com/AdguardTeam/AdguardFilters/issues/81513#issuecomment-831140747
https://github.com/AdguardTeam/AdguardFilters/issues/81513#issuecomment-831291549
https://github.com/AdguardTeam/AdguardFilters/issues/81513#issuecomment-831320935
https://github.com/AdguardTeam/AdguardFilters/issues/81513#issuecomment-831334818

**Comment by ameshkov** [comment]
We really cannot unblock GA even though it breaks a website, even if it's a popular one.

Maybe this should instead be reported to `dcinside.com` developers, their website is broken by literally any tracking blocking tool, probably they would like to fix this.
