### ISSUE TITLE
[Question] Can I use this with pihole?

### ISSUE THREAD

**Issue by gurgun-dayioglu** [AdguardTeam/AdGuardSDNSFilter#66]
I was wondering if I could extract this as a hosts file (ex: https://v.firebog.net/hosts/AdguardDNS.txt) and use it with pihole?

**Comment by BlazDT** [comment]
If pihole understands it, it should.

**Comment by gurgun-dayioglu** [comment]
It only understands domain names and the AdguardDNS has some basic syntax on it. That’s what Im curious about

**Comment by ameshkov** [comment]
Tbh, I don't think it is possible to properly extract this filter as a hosts file.

It might be possible to transform it into a list of regular expressions.
