### ISSUE TITLE
Ads show on euroweeklynews.com

### ISSUE THREAD

**Issue by xyzz4** [AdguardTeam/AdGuardSDNSFilter#664]
Ads on euroweeklynews.com are not blocked while using AdGuard DNS (Default servers). They are however blocked when using the AdGuard Browser Extension.

### Steps to reproduce

1. Visit [euroweeklynews.com](https://euroweeklynews.com)
2. Ads provided by EuroWeeklyNews themselves will show up

### Expected behavior
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/80607901/117584206-e8988b80-b10b-11eb-9132-0e6056ed7dd1.png)

</details>

### Actual behavior
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/80607901/117584224-f9e19800-b10b-11eb-97fb-b6e1145c6fbe.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (AdGuard DNS - Default, 94.140.14.14)
| Operating system and version:| Windows 10

**Comment by Alex-302** [comment]
Added to Spanish filter. Also domain will be blocked by DNS.
