### ISSUE TITLE
Whitelist images.primaryarms.com

### ISSUE THREAD

**Issue by jmeeter** [AdguardTeam/AdGuardSDNSFilter#669]
Please whitelist images.primaryarms.com - it doesn't break the website but makes the browsing experience a lot more miserable as none of the product images will show up.

Thanks

**Comment by Alex-302** [comment]
It redirects to https://www.bc0a.com/
![image](https://user-images.githubusercontent.com/8361299/119332913-eac52300-bc91-11eb-8d62-3e60d2728db3.png)
Please open issue here(fill the template)
https://github.com/AdguardTeam/AdguardFilters/issues/new?assignees=&labels=&template=Ad_report.md
