### ISSUE TITLE
Micosoft 'Your Phone' app unable to connect to mobile device.

### ISSUE THREAD

**Issue by Wizardling** [AdguardTeam/AdGuardSDNSFilter#675]
### Steps to reproduce

1. Install MS 'Your Phone' app in Android and in Windows 10.
2. Link the two apps.
3. Enable AdGuard DNS filter in NextDNS used for Windows 10 and Android Private DNS.
4. Wait for DNS change to propagate.
5. Relaunch both apps.

### Expected behavior

No connection errors between the 'Your Phone' apps should occur.

### Actual behavior

The Windows 'Your Phone' app is unable to connect to the mobile app.

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| https://nextdns.io/
| How did you setup DNS configuration:| Windows network settings manual IPv4 DNS entry, and Android Private DNS.
| Device model:| Custom build i5 8400 PC, and Pixel 2.
| Operating system and version:| Windows 10, and Android 11.

**Comment by ameshkov** [comment]
Do you have this issue when AdGuard DNS is used?

**Comment by Wizardling** [comment]
No, I've not tried AdGuard DNS as it doesn't meet my needs, sorry. I did just briefly tested your IPv4 AdGuard DNS servers with Windows 10. They seem to work okay, without affecting MS's 'Your Phone' app for Windows. That would suggest the problem occurs on the Android side, where unfortunately I can't set insecure DNS, sorry.

**Comment by ameshkov** [comment]
I cannot be sure that this is not a NextDNS issue interpreting the filter list. If this works with AdGuard DNS then probably needs to be reported to NextDNS

**Comment by Wizardling** [comment]
I have indeed advised their support, in case that is happening. Though it seems a rather slight chance. If anyone else can test this, I'd be most appreciative :-)

**Comment by Alex-302** [comment]
Please provide download links for both apps. I don't see "Your Phone" in MS store. Or show at least icons.

**Comment by Wizardling** [comment]
As requested:
https://www.microsoft.com/en-nz/p/your-phone/9nmpj99vjbwv?activetab=pivot:overviewtab
https://play.google.com/store/apps/details?id=com.microsoft.appmanager

**Comment by Wizardling** [comment]
Allowing `*.continuum.dds.microsoft.com` enabled the MS 'Your Phone' companion app to work again, with this and other blocklists I've been trying out, that were not compatible.

**Comment by Alex-302** [comment]
We do not block this domain. 
It an issue reproducible with AdGuard DNS?

**Comment by Wizardling** [comment]
Hmmm... well, that is odd. I hadn't yet found a culprit when I was initially experiencing this issue. But later on, when I whitelisted `*.continuum.dds.microsoft.com` all the blocklists (including AdGuard) that stopped MS 'Your Phone' from connecting, were no longer giving me grief.

I haven't tried AdGuard DNS on my phone, but enabling it in Windows saw no issues with 'Your Phone'. So perhaps it is a NextDNS issue - something screwy it is doing interpreting certain blocklist entries? *shrug*

Either way, I'm sorry for wasting your time, if that is what I've done :-)

BTW - though I realise this might not be the appropriate place to ask, is AdGuard DNS going to open a NZ server? If you did, I'd consider trying your service in a serious fashion. NextDNS is good, but far from perfect.

Oh, and FWIW, after trying yet more blocklists, I've discovered some block `signalr-relayhub-prod-as01-1.service.signalr.net` and `signalr-relayhub-prod-as01-2.service.signalr.net` which MS 'Your Phone' also depends upon. NextDNS reports AdGuard not blocking them, but I thought I'd mention them if someone else experiencing the same annoyance, runs across this comment...

**Comment by Alex-302** [comment]
>  is AdGuard DNS going to open a NZ server?

I don't know:(

> So perhaps it is a NextDNS issue - something screwy it is doing interpreting certain blocklist entries?

Maybe it applies own filters. Never used it.

**Comment by ameshkov** [comment]
> is AdGuard DNS going to open a NZ server

The closest we have is in Sydney and as far as I can tell, NZ users are all routed there. Should be good enough.

I doubt we'll be considering more PoPs in the nearest time, from our experience locations matters less than the overall stability of the hosting providers.
