### ISSUE TITLE
pdst.fm blocking breaks podcast download

### ISSUE THREAD

**Issue by carlylemiii** [AdguardTeam/AdGuardSDNSFilter#677]
### Steps to reproduce

1. Try to stream the latest episode of The Daily in Pocket Casts.

### Expected behavior

It would work.

### Actual behavior

pdst.fm being blocked makes the app think it’s offline and the episode can’t download.

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (e.g. Default, 176.103.130.130)
| How did you setup DNS configuration:| (System/DNSCrypt app/Router)
| Device model:| (e.g. Google Pixel)
| Operating system and version:| (e.g. Android 7.1.2)

**Comment by Alex-302** [comment]
How to reproduce it?
