### ISSUE TITLE
dit.whatsapp.net

### ISSUE THREAD

**Issue by cantunborn** [AdguardTeam/AdGuardSDNSFilter#682]
`dit.whatsapp.net`

[Whatsapp Telemetry](https://faq.whatsapp.com/general/what-is-dit-whatsapp-net/?lang=en)

**Comment by Alex-302** [comment]
@cantunborn I don't see this domain in my log. Is nothing broken when this domain is blocked?

**Comment by cantunborn** [comment]
This domain was present in OISD some days ago, then it was removed. I too am not seeing it right now in the logs.

While it was being blocked, chats, chat backups, audio and video calls worked fine. But may need more testing in terms of broken features.

**Comment by cantunborn** [comment]
It's appearing in the logs now. Maybe you are not seeing it because it's being used in some places only?

**Comment by Alex-302** [comment]
Please describe steps to reproduce.

> This domain was present in OISD some days ago, then it was removed.

Do they have commits history or something like that?

**Comment by cantunborn** [comment]
No idea about any specific way to reproduce, just need the app running in background or foreground.

OISD is a combination of multiple lists so I don't know which list was the origin.

**Comment by chirag127** [comment]
@Alex-302 just a Google search gave me this result. 

https://faq.whatsapp.com/general/what-is-dit-whatsapp-net/?lang=en


In this article they themselves mentioned that this is a telemetry domain. By the way, this domain is present in OISD from many days.

**Comment by Alex-302** [comment]
Ok.

**Comment by chirag127** [comment]
> Ok.
> [AdguardTeam/AdguardFilters@ba781ff](https://github.com/AdguardTeam/AdguardFilters/commit/ba781ff6f261ad88c7a280e4e43eb5ef222cdacf)

By the way, this domain is not mobile specific as it is also used by desktop WhatsApp and WhatsApp web.
