### ISSUE TITLE
iOS ad in app not blocked

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdGuardSDNSFilter#689]
For instance ads within iOS App are not blocked. :

https://apps.apple.com/us/app/mac4ever/id459374554

See screen shot:
 ![image](https://user-images.githubusercontent.com/49731083/122066816-59118700-cdf3-11eb-9682-b7d0b1309e21.png)

**Expected behavior**

Should blocked all ads within iOS applications

**Actual behavior**

Nothing is blocked.

**Your environment**

**DNS server in use**:	
AG DNS over QUIC
**How did you setup DNS configuration:**	
AG Pro Beta 4.2.0 (704)
**Device model:**	
iPhone 11 Pro Max
**Operating system and version:**
iOS 14.6

**Comment by ameshkov** [comment]
Probably caused by https://github.com/AdguardTeam/AdguardForiOS/issues/1755

Switch to the full tunnel mode to get it fixed right away or wait until iOS 14.7.

**Comment by Quorum75** [comment]
Sorry can't do because I am using Windscribe. 
However with Windscribe activated I don't get the ad anymore.
