### ISSUE TITLE
web.de gmx.ch gmx.at ||united.uimserv.net^

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdGuardSDNSFilter#693]
### Steps to reproduce

1. Browse https://web.de/logoutlounge/ or https://www.gmx.ch/logoutlounge/ or https://www.gmx.at/logoutlounge/
- the bottom articles are blocked which aren't all Ads. It's a mix of articles of the homepage https://web.de/ (and gmx), but for some odd reason, the logout page (loads when you logout from your Email) will need this DNS request to load the articles.

### Expected behavior
<details><summary>Screenshot-1:</summary>

![web3](https://user-images.githubusercontent.com/6276915/122637294-17802500-d0ee-11eb-9e3c-dd20358ee0ee.png)

</details><br/>

### Actual behavior
<details><summary>Screenshot-1:</summary>

![web1](https://user-images.githubusercontent.com/6276915/122637295-1b13ac00-d0ee-11eb-9c87-44b6df6a4ac1.png)

</details><br/>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| AdGuard Home with AdGuard DNS filter

**Comment by Alex-302** [comment]
This is an ad server, and cannot be removed.
On my end site loads fine after reploading.
@BlazDT Please take a look.

**Comment by BlazDT** [comment]
After a while I get redirected to https://web.de/?status=logoutlounge&sc=0101 and loading fine.

**Comment by Alex-302** [comment]
@Morku Please test with following rule in AdGuard `web.de,gmx.net,gmx.at,gmx.ch,gmx.com#%#//scriptlet('set-constant', 'window.AdService', 'undefined')`

**Comment by Morku** [comment]
@Alex-302 
This rule does nothing for me. All the bottom articles are still empty.

@BlazDT 
The redirect only happns for me when I scroll around. And yes, the homepage is not the issue. The issue is the logoutlounge.
It only loads fine when I allow this DNS.

**Comment by Alex-302** [comment]
Without my rule and with DNS blocking
![image](https://user-images.githubusercontent.com/8361299/122815521-3a712b80-d2de-11eb-8088-763da66502bf.png)

**Comment by Morku** [comment]
@Alex-302 
I don't see your URL bar. Pretty sure you are not loading https://web.de/logoutlounge/

Most markable is the green bar with "Sie haben sich erfolgreich ausgeloggt. Vielen Dank für Ihren Besuch bei WEB.DE!"

The page https://web.de/?status=logoutlounge&sc=0101 is no the same as https://web.de/logoutlounge/
This are just tracking(?) parameter where the user came from to the homepage.
But I am not reporting the homepage:

![web](https://user-images.githubusercontent.com/6276915/122820741-3ba15900-d2dc-11eb-8087-0225af9331a8.png)

**Comment by Alex-302** [comment]
This is not a reason to remove the rule from DNS filter.
If I wait few seconds, page loads, and I can't reproduce until clear site's storage.

**Comment by Morku** [comment]
This is up to you. The logoutlounge might be not important, but actually this DNS request is necessary to load useful content for this sepcific page.
This page are articles mixed with Ads which already got fixed by @BlazDT 

And you are wrong, if you wait, the articles on logoutlounge won't load. You get redirected to the homepage which is **not the issue**


https://user-images.githubusercontent.com/6276915/122920979-44d50900-d362-11eb-9c73-9042ef357839.mp4

**Comment by Morku** [comment]
Feel free to close the ticket if the main purpose of this DNS request is for serving Ads.

But you are now also informed that blocking this DNS does partial break the page. Luckily on an unrelated Logout page (it get's loaded when you Logout from your Email) and the information on this subpage are very similar to the articles on homepage which loads fine.
But people might get confused why the articles after Email Logout won't load.
