### ISSUE TITLE
false positive: scroll.in affected by broad Singapore digitalocean spaces filter

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardSDNSFilter#700]
### Steps to reproduce

Visit ```https://scroll.in/```

### Expected behavior

Images are displayed on the website

### Actual behavior

Images fail to load

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/62358249/124388980-1e598b00-dcdd-11eb-9c12-8a89b463b058.png)

</details>

Images are hosted on Digitalocean Spaces

```
https://s01.sgp1.cdn.digitaloceanspaces.com/thumbnail/161115-vcsfgithzc-1625396040.jpg
https://s01.sgp1.cdn.digitaloceanspaces.com/book/161117-rbmahacbbn-1625396809.jpeg
https://s01.sgp1.cdn.digitaloceanspaces.com/article/161092-bjxsfslykw-1625311331.jpg
```

The following filter is too broad which blocks all resources hosted in Singapore Digitalocean spaces

```
||sgp1.cdn.digitaloceanspaces.com^
```

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:|  Adguard Home
| How did you setup DNS configuration:| Router
| Device model:| N/A
| Operating system and version:| N/A

**Comment by Alex-302** [comment]
Hi. Removed the rule from our filters.
