### ISSUE TITLE
miro.com

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardSDNSFilter#701]
### Steps to reproduce
URL: `https://miro.com/changelog/`

```
https://track.realtimeboard.com/api/v1/t
https://track.realtimeboard.com/api/v1/p
```

Suggested filter
```
||track.realtimeboard.com^
```

URL: `https://miro.com/app/board/<removed>/?fromRedirect=1` Requires a login

```
https://track.miro.com/api/v1/t
```

Suggested filter
```
||track.miro.com^
```

### Expected behavior

`segment.io` first party proxying to be blocked

### Actual behavior

`segment.io` masked as first party isn't blocked

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Adguard Home
| How did you setup DNS configuration:| Router
| Device model:| N/A
| Operating system and version:| N/A

**Comment by Alex-302** [comment]
1, 2 added. 
3 is already blcoked.
