### ISSUE TITLE
trackingshipment.apple.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#703]
@Eugene-Savenko commented on [Sun Jun 27 2021](https://github.com/AdguardTeam/AdGuardDNS/issues/169)

My iPhone detected a UPS tracking number in an iMessage chat, and it offered up a link to track the package. Unfortunately, AdGuard DNS blocked the link to trackingshipment.apple.com. I hope you consider unblocking it.

```
nslookup trackingshipment.apple.com
Server:		192.168.0.1
Address:	192.168.0.1#53

Non-authoritative answer:
Name:	trackingshipment.apple.com
Address: 0.0.0.0
Name:	trackingshipment.apple.com
Address: ::
```

**Comment by Alex-302** [comment]
Reported to Easylist.

**Comment by Alex-302** [comment]
Well, opened PR
https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/705

**Comment by Alex-302** [comment]
Fixed in Easyprivacy.
