### ISSUE TITLE
Hulu will not autoplay next episode

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#712]
@shibbityboo commented on [Fri Jul 09 2021](https://github.com/AdguardTeam/AdGuardDNS/issues/173)

I've set my router to use the Adguard DNS servers and it has worked perfectly for everything except in one instance. Hulu will no longer autoplay the next episode after the current one is finished. It will seem to time out and give error code P-DEV 328. Adguard DNS worked perfectly last year when I left the country (US) in early August for 6 months, and when I came back in late February it no longer would autoplay while my router was configured to use Adguard DNS servers. This issue only occurs on my two Samsung Smart TVs. When streaming from other devices it's fine.

**Comment by Alex-302** [comment]
No other complaints.
