### ISSUE TITLE
producthunt.com

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardSDNSFilter#713]
### Steps to reproduce

Visit `https://www.producthunt.com/`

### Expected behavior

Segment tracker disguised as first party is blocked

### Actual behavior

Segment tracker not blocked

Calls it makes. First one is the JavaScript which makes subsequent API calls
```
https://segment-cdn.producthunt.com/
https://segment-api.producthunt.com/v1/p
https://segment-api.producthunt.com/v1/t
https://segment-api.producthunt.com/v1/t
https://segment-api.producthunt.com/v1/m
```
Suggested filters. Maybe the second one might not be needed as blocking javascript means API calls are not made. 
```
||segment-cdn.producthunt.com^
||segment-api.producthunt.com^
```

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Adguard Home
| How did you setup DNS configuration:| Router
| Device model:| N/A
| Operating system and version:| N/A

**Comment by Alex-302** [comment]
Fixed.
