### ISSUE TITLE
Ads not blocked

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdGuardSDNSFilter#714]
### Issue Details

- **AdGuard version:**
  - AG Pro Beta iOS 4.2.1 (710)
- **Device model and storage size:**
  -  iPhone 11 Pro Max and iPad 11 Pro. 
- **Operating system and version:**
  -  iOS 14.6
- **Browser or App:**
  -  [iGénération](https://apps.apple.com/tr/app/igeneration/id346175650)

### Expected Behavior

 Ads used to be blocked but not anymore.   

### Actual Behavior

 Ads are now visible between comments.

### Screen Shot

![image](https://user-images.githubusercontent.com/49731083/125868842-072ecf81-3bff-4a9d-9b71-82990b1104f3.png)

**Comment by Alex-302** [comment]
Hi. Please try to switch tunnel mode in low level settings to Full Tunnel. In iOS 14.7 you could select Split Tunnel mode.
