### ISSUE TITLE
||events.data.microsoft.com^ breaks Xbox's achievements

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardSDNSFilter#716]
Hello,

this rule breaks Xbox's achievements::

`||events.data.microsoft.com^`

More information here:
https://github.com/nextdns/metadata/issues/334
and here:
https://www.reddit.com/r/pihole/comments/9ztxdx/psa_pihole_seems_to_be_blocking_xbox_achievements/
http://kamilslab.com/2017/01/02/fix-xbox-live-achievements-not-popping-up-when-using-pi-hole/

Please, unblock it ASAP. Or replace it with the old rule: `||browser.events.data.microsoft.com^`

Thank you.
Best regards🖐🏻

**Comment by Alex-302** [comment]
@ammnt Hi. Done.
Which domain was blocked?(subdomain for events.data.microsoft.com)

**Comment by ammnt** [comment]
@Alex-302:
![image](https://user-images.githubusercontent.com/45385632/126835653-9f200514-aca9-4155-959a-3e4580dc54e7.png)

**Comment by Alex-302** [comment]
Ok.
