### ISSUE TITLE
Sinefy.com betting sites ads are not blocked

### ISSUE THREAD

**Issue by edwardmorton** [AdguardTeam/AdGuardSDNSFilter#722]
AdGuard plugin can block ads when we log in via Chrome PC.AdGuard over DNS cannot block these ads. I usually log in from my phone and don't want to see ads. If the Chrome PC plugin can do that, I'm sure nextDNS can.
https://sinefy.com/
Unblockable ad sites;
https://www.bahsegel307.com/tr/sportsbook?partner=p294p16170p9a06#registration

<details><summary>Screenshot:</summary>

![IMG_20210728_234655](https://user-images.githubusercontent.com/88113598/127393754-f9183783-02fd-40f0-a00a-24487d4fed3c.jpg)
</details><br/>

**Comment by zloyden** [comment]
We can't block those ads via DNS because they are placed on `sinefy.com`. But you can use our extension / app to block them.
