### ISSUE TITLE
loggly.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdGuardSDNSFilter#723]
### Steps to reproduce

1. go to https://www.loggly.com/solution/log-analyzer/

### Expected behavior

not blocked
### Actual behavior

blocked

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/76880977/127751502-fc7707ec-162a-4c88-901c-3dea69a91233.png)
https://www.loggly.com/solution/log-analyzer/
![image](https://user-images.githubusercontent.com/76880977/127751503-7ec95a20-a2b7-41ca-ac60-93e6605edbd8.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| **(94.140.14.15,94.140.15.16)**
| How did you setup DNS configuration:| (Router)
| Device model:| (APPLE MacBook Pro M1 - (8 GB/256 GB SSD/Mac OS Big Sur) MYD82HN/A  (13.3 inch, Space Grey, 1.4 kg)))
| Operating system and version:| (Mac OS Big Sur)

**Comment by ameshkov** [comment]
This is just some log analyzing software, it is not a tracker.

**Comment by chirag127** [comment]
> This is just some log analyzing software, it is not a tracker.

So, you removed this domain from the list? Same thing is written in the issue by me.

**Comment by ameshkov** [comment]
Ah, my bad. @AdguardTeam/filters-maintainers please take a look.

**Comment by chirag127** [comment]
> my bad.

I was also thinking that why you are telling me the same thing that I wrote wrote in the issue.
