### ISSUE TITLE
analytics.google.com blocked?

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#724]
@gingerbeardman commented on [Fri Jul 30 2021](https://github.com/AdguardTeam/AdGuardDNS/issues/180)

I need to access this domain to check my website analytics.

Previously that worked just fine.

However recently this has begun to be blocked? 

https://analytics.google.com

**Comment by ameshkov** [comment]
@AdguardTeam/filters-maintainers is there any point in blocking `analytics.google.com`? I don't think it is used as a tracker domain, it just hosts the Google Analytics admin panel.

**Comment by chirag127** [comment]
> @AdguardTeam/filters-maintainers is there any point in blocking `analytics.google.com`? I don't think it is used as a tracker domain, it just hosts the Google Analytics admin panel.

Ya I also think the same never seen this domain on any website.

**Comment by gingerbeardman** [comment]
Thanks!
