### ISSUE TITLE
bam-cell.nr-data.net

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/AdGuardSDNSFilter#730]
### Steps to reproduce

1. Opened the Bendigo Bank app on Android
2. Unable to login as get no connection error
3. Whitelist bam-cell.nr-data.net
4. Reopen Bendigo Bank app and now able to login

### Expected behavior

I should be able to open the Bendigo Bank app without issues

### Actual behavior

Bendigo Bank app is not able to be used unless the domain 'bam-cell.nr-data.net' is whitelisted

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 192.168.0.2 (This IP hosts my Raspberry Pi 4 with AdGuard)
| How did you setup DNS configuration:| Router
| Device model:| Google Pixel
| Operating system and version:| Android 11

**Comment by Alex-302** [comment]
@gyCfjSnO Hi. Could you please show log record?

**Comment by gyCfjSnO** [comment]
> @gyCfjSnO Hi. Could you please show log record?

|   Description  |     Value    |
| -------------- | ------------ |
Time | 22:50:53.854
Date | 04/08/2021
Status | Blocked
Domain | bam-cell.nr-data.net
Type | A
Protocol | Plain DNS
Known tracker Name | New Relic
Category | Site Analytics
Tracker source | Whotracks.me
Elapsed | 1 ms
Rule(s) | `nr-data.net^` AdGuard DNS filter
Response | A: 0.0.0.0 (ttl=10)
Response code | NOERROR
IP address | 192.168.0.145

**Comment by gyCfjSnO** [comment]
> @gyCfjSnO Hi. Could you please show log record?

I came to the realisation it was `bam-cell.nr-data.net` causing issues as I would load the Bendigo Bank app and monitor the logs on my AdGuard Home at the same time.

Then any queries that were blocked I would unblock and try again - bit of like trial and error, this would be done one at a time but out of the three domains queried when trying to open the Bendigo Bank app only two were blocked.

**Comment by gyCfjSnO** [comment]
> @gyCfjSnO Hi. Could you please show log record?

These are the other two logs for a total of three queries when trying to open the Bendigo Bank app.

1/2

|   Description  |     Value    |
| -------------- | ------------ |
Time | 22:50:48.358
Date | 04/08/2021
Status | Processed
Domain | app2.bendigobank.com.au
Type | A
Protocol | Plain DNS
DNS server | tls://dns-unfiltered.adguard.com:853
Elapsed | 15 ms
Response | CNAME: app2.wip.bendigobank.com.au. (ttl=432) A: 103.211.240.29 (ttl=30)
Response code | NOERROR
IP address | 192.168.0.145 Validated with DNSSEC

**Comment by gyCfjSnO** [comment]
> @gyCfjSnO Hi. Could you please show log record?

2/2

|   Description  |     Value    |
| -------------- | ------------ |
Time | 22:50:58.600
Date | 04/08/2021
Status | Blocked
Domain | mobile-collector.newrelic.com
Type | A
Protocol | Plain DNS
Known tracker Name | New Relic
Category | Site Analytics
Tracker source | Whotracks.me
Elapsed | 0.26 ms
Rule(s) | `mobile-collector.newrelic.com^` OISD
Response | A: 0.0.0.0 (ttl=10)
Response code | NOERROR
IP address | 192.168.0.145

**Comment by gyCfjSnO** [comment]
> @gyCfjSnO Hi. Could you please show log record?

I came to the realisation it was `bam-cell.nr-data.net` causing issues as I would load the Bendigo Bank app and monitor the logs on my AdGuard Home at the same time.

Then any queries that were blocked I would unblock and try again - bit of like trial and error, this would be done one at a time but out of the three domains queried when trying to open the Bendigo Bank app only two were blocked.

**Comment by Alex-302** [comment]
Hm.. It is used for analytics, and it is popular. Not sure if we can unblock it.
Please report to Bendigo Bank authors. Breakage when analytics are blocked is bad behavior.

**Comment by gyCfjSnO** [comment]
Any update on this?

**Comment by gyCfjSnO** [comment]
Any update on this?

**Comment by AdamWr** [comment]
Unfortunately we can not unblock it - https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/730#issuecomment-893425078

**Comment by gyCfjSnO** [comment]
> Unfortunately we can not unblock it - [#730 (comment)](https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/730#issuecomment-893425078)

From the documentation for the URL on Newrelic website (https://docs.newrelic.com/docs/browser/new-relic-browser/performance-quality/security-browser-monitoring/#spa-data)

> Browser monitoring provides insights into how your application or site behaves when it is loaded in a web browser. Browser only records performance data, as explained in this document. It does not record any data used or stored by the monitored application unless you explicitly configure it to do so.

Does the above sufficiently explain that it's not used for analytics? Seems it's only for gathering data on how a site or app behaves. I'm unsure what your criteria is for deciding if a URL should be blocked or not.

**Comment by Deses** [comment]
"Seems it's only for gathering data" "it's not used for analytics".

A bit of an oxymoron there.
