### ISSUE TITLE
DNS filtering not working with proxy/VPN enabled

### ISSUE THREAD

**Issue by fsheidaiee** [AdguardTeam/AdGuardSDNSFilter#731]
Hi
apparently DNS filtering is not working with Proxy enabled.
when using proxyswitchyOmega or when I set http proxy in windows or on any client, dns adblocker fails to block ads. (see the picture for example)
![image](https://user-images.githubusercontent.com/74687186/128330575-74ac56d8-06e9-48b9-8450-4a2a9a60321a.png)

but without enabling proxy, the dns filtering works perfect (see the picture the same page reloaded without proxy)
![image](https://user-images.githubusercontent.com/74687186/128330715-332c50aa-4691-4dd2-a315-f6ecc27eb778.png)

I think thats maybe somehow related to domain resolving, maybe the proxy server gets to resolve the domain first and the adguard dns filter or adguard home, doest get to read the domain and block it faster.

Can you solve this issue?
thanks

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (adguard DOH)
| How did you setup DNS configuration:| (Adguard Home DNS filtering enabled)
| Operating system and version:| (Windows 10 x64)

**Comment by Alex-302** [comment]
Hi. It seems Proxyswitchy Omega uses DNS of proxy server. This is not incorrect behavior, more like a [privacy]feature.

**Comment by Alex-302** [comment]
For example, our VPN extension allows to select custom DNS server.
