### ISSUE TITLE
Disabling of push-notifications list

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardSDNSFilter#733]
Hello,

please, include this list also:
https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/AnnoyancesFilter/sections/push-notifications.txt

Thank you.
Cheers!

**Comment by Alex-302** [comment]
Not sure about that. But personally for myself I would do it)

**Comment by ameshkov** [comment]
This needs to be a different blocklist, AG DNS filter is only about ads and tracking
