### ISSUE TITLE
hashnode.com

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardSDNSFilter#737]
### Steps to reproduce

Visit `https://hashnode.com/explore`

### Expected behavior

Trackers should be blocked

### Actual behavior

Tracker not blocked as they have switch from `ping` to `analytics` subdomain. Although `ping` is still active and has A & AAAA records. So not sure if existing filter should be left.

Also, additional tracker

Follow up to https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/704 request.

```
https://analytics.hashnode.com/api/data-event
https://analytics.hashnode.com/api/gamp
https://analytics.hashnode.com/api/data-event
https://analytics.hashnode.com/api/gamp
https://prairiedog.hashnode.com/script.js
https://prairiedog.hashnode.com/?p=%2Fexplore&h=https%3A%2F%2Fhashnode.com&r=&sid=DFHSISAS&qs=%7B%7D&cid=2829121
```

Suggested filter

```
||analytics.hashnode.com^
||prairiedog.hashnode.com^
```

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| AdGuard Home
| How did you setup DNS configuration:| Router
| Device model:| N/A
| Operating system and version:| N/A

**Comment by Alex-302** [comment]
Added.
