### ISSUE TITLE
App-Measurement.com - sends device ID used for ads

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#739]
@EntropySmoke commented on [Fri Aug 20 2021](https://github.com/AdguardTeam/AdGuardDNS/issues/185)

App-Measurement.com links Google Accounts to Android Device RDID (Resettable  Device  Identifier), also known as "Ad  ID". AdGuardDNS filter comments say that it is problematic to block/black-hole it.  Is that still the case? That domain is blocked in almost every major ad-block list. 

There is more information here - https://www.scss.tcd.ie/doug.leith/apple_google.pdf .

---

@ameshkov commented on [Mon Aug 23 2021](https://github.com/AdguardTeam/AdGuardDNS/issues/185#issuecomment-903509417)

As I recall, if we have this domain blocked, Android devices may start to make thousands of queries to it.

@AdguardTeam/filters-maintainers guys, could you please check if that's the case now on your Android devices?

**Comment by BlazDT** [comment]
My Android did not requested that domain for a while (ans with Apps I use).

**Comment by Alex-302** [comment]
Blocked it[again].
