### ISSUE TITLE
||startup.mobile.yandex.net^

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#74]
Reported by: 2179306

> 
> Возникла проблема в  работе приложений для Android от компании Яндекс, а именно Музыка, Радио и  Беру. Иногда не воспроизводится, не запускается абсолютно, заявляя о отсутствии интернета и то же самое в отношение последнего приложения при 
> кладке товара в корзину соответственно.  
> 
> Анализ показал, что адрес startup.mobile.yandex.net отвечает за работоспособность, в особенности при первом запуске после инсталляции  одного из этих приложений. Для проверки запись сопоставления с IP внес в  hosts и работа сервисов восстановилась.

<details> <summary> Скриншот </summary>

![image](https://user-images.githubusercontent.com/15856304/57358017-1b09f980-717d-11e9-9791-84000a3cf956.png)

</details>

**Comment by ameshkov** [comment]
@Alex-302 please take a look

**Comment by Alex-302** [comment]
Может вообще удалить правило? Уже пятое приложение с проблемой
`||startup.mobile.yandex.net^$app=~com.edadeal.android|~ru.beru.android|~ru.yandex.red.market|~com.yandex.launcher`

**Comment by ameshkov** [comment]
@Alex-302 давай удалим, похоже реально слишком проблемное.

**Comment by Alex-302** [comment]
Удалил.
