### ISSUE TITLE
go-mpulse.net

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/AdGuardSDNSFilter#751]
Unable to checkout and pay for groceries when domain `go-mpulse.net` is blocked when using the Woolworths (large Australian grocery chain) App on Android.

Whitelisting `go-mpulse.net` allowed me to pay, when it isn't whitelisted the text box to input CVV disappears.

**Comment by gyCfjSnO** [comment]
Any update on this?

**Comment by AdamWr** [comment]
`go-mpulse.net` is a tracking service used on many websites, so unfortunately we can not unblock it.

**Comment by gyCfjSnO** [comment]
> `go-mpulse.net` is a tracking service used on many websites, so unfortunately we can not unblock it.

Can you please review this comment https://github.com/StevenBlack/hosts/issues/1756#issuecomment-912130050 from another Blocklist, they came to the conclusion of removing it.

**Comment by AdamWr** [comment]
As far as I understand, it has been removed only from AdAway list - https://github.com/AdAway/adaway.github.io/commit/08f5fe8363385a28c4dc72c807cd205808a2f4cd and it is still blocked by other filter lists (https://urlfilter.adtidy.org/v1/checkDomain?domain=go-mpulse.net) like `EasyPrivacy`, `Peter Lowe's Blocklist`, `StevenBlack's list`, so at the moment I don't see any reason to remove it.

> mPulse is Akamai’s Real User Measurement (RUM) solution. mPulse collects detailed data directly from a user’s browser or mobile application, including performance timers such as first paint time, visually ready, and page load times as well as business metrics like bounce rate, conversion rates, or session lengths. **mPulse also gathers mobile user metrics like user location, device type, carrier speed and application usage.**

https://community.akamai.com/customers/s/article/mPulse-FAQ?language=en_US#whatis
