### ISSUE TITLE
||organicfruitapps.com^

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardSDNSFilter#752]
Hello, 

1. Go to https://redeem.apple.com/svasnoymusicinstore
2. ||organicfruitapps.com^ - this rule breaks layout

This host is iTunes Store API - Developers may use promotional content in the API, including previews of songs, music videos, album art and App icons only to promote store content bla-bla-bla...

Please, check and correct.
Thank you.

**Comment by bigdargon** [comment]
@Alex-302 removed
