### ISSUE TITLE
filmux.to

### ISSUE THREAD

**Issue by iibett** [AdguardTeam/AdGuardSDNSFilter#758]
### Steps to reproduce

1. When watching videos on filmux.to ads aper on the video player. If I manually block (ads.adfox.ru) ads diaper.
Would it be posible to add this domane to a blocklist

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (dns.adguard.com)
| How did you setup DNS configuration:| (android private dns)

**Comment by Alex-302** [comment]
Fixed, but ads.adfox.ru not blocked, because creates more problems than it solves.
