### ISSUE TITLE
Remove ".cdn.ampproject.org" from blocklist or Redirect to non AMP version.

### ISSUE THREAD

**Issue by Rexadev** [AdguardTeam/AdGuardSDNSFilter#766]
### Steps to reproduce

1. Sites like www-theverge-com.cdn.ampproject.org can't be opened
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (e.g. Default, )
| How did you setup DNS configuration:| (NextDNS)
| Device model:| (e.g. )
| Operating system and version:| (e.g. )

**Comment by ameshkov** [comment]
We don't block it, might be a NextDNS bug.
