### ISSUE TITLE
www.booktickets.disneylandparis.com @@||cdn.tagcommander.com^

### ISSUE THREAD

**Issue by Morku** [AdguardTeam/AdGuardSDNSFilter#776]
### Steps to reproduce

1. Browse https://www.booktickets.disneylandparis.com/
2. now proceed as you would like to buy a ticket (but no need to buy)
3. chose any language, e.g. 1-Day ticket, 1 adult, any date and so on
4. click Add to cart, Continue
5. Now you are on a page where you have to create an account, or Sign-In, both are broken, due `||tagcommander.com^`
6. After whitelist `@@||cdn.tagcommander.com^` the Pop-up appears as expected
7. Notice that it is necessary to go through the ticket buyment steps (but of course no need to buy...), because if you click on Sign In on this page directly, you get redirected to `www.disneylandparis.com`, leaving `www.booktickets.disneylandparis.com`. For whatever reason, the Pop-up is fine on the real homepage

### Expected behavior
<details><summary>Screenshot-1:</summary>

![disney2](https://user-images.githubusercontent.com/6276915/135768210-8bbd1c9e-eb09-4e3e-8ad3-f48a2cfc6c91.png)

</details><br/>

### Actual behavior
<details><summary>Screenshot-1:</summary>

![disney](https://user-images.githubusercontent.com/6276915/135768215-ab9aab6e-343f-4a3e-b56f-f463fbfb3054.png)

</details><br/>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| AdGuard Home with AdGuard DNS filter

**Comment by Alex-302** [comment]
Tracker is popular, cannot be fixed.
