### ISSUE TITLE
autopilothq.com

### ISSUE THREAD

**Issue by gyCfjSnO** [AdguardTeam/AdGuardSDNSFilter#777]
### Steps to reproduce

1. Go to Gmail
2. Open email I received from Upside (Real Estate Agent)
3. Click on link to view/track/manage selling of my home
4. Unable to access due to the domain `||autopilothq.com^` appearing on this filter list which AdGuard Home uses

### Expected behavior

I should be able to click on the link in the email and go through to the portal for my real estate agent
### Actual behavior

AdGuard blocks me from managing the sale of my home

### Screenshot

![image](https://user-images.githubusercontent.com/49738152/136316934-8ed03f1e-8360-4300-895e-c015be3b290f.png)
![image](https://user-images.githubusercontent.com/49738152/136316943-8a0d3a54-e804-480e-ab9a-e9ee1441900e.png)

### Your environment

My Raspberry Pi4 filters all DNS queries on the network by using AdGuard Home

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 192.168.0.2
| How did you setup DNS configuration:| Router
| Device model:| Any device on the network
| Operating system and version:| Mixed

**Comment by Alex-302** [comment]
Fixed.
