### ISSUE TITLE
Remove ||stc.oa.zalo.me^ ||oa-stc.zdn.vn^ ||store-stc.zdn.vn^

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdGuardSDNSFilter#795]
The domains below are no longer available for tracking. You can remove it from the `Adguard Tracking filter`. Thank you!

```
||stc.oa.zalo.me^
||oa-stc.zdn.vn^
||store-stc.zdn.vn^
```

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (e.g. Default, 176.103.130.130)
| How did you setup DNS configuration:| (System/DNSCrypt app/Router)
| Device model:| (e.g. Google Pixel)
| Operating system and version:| (e.g. Android 7.1.2)

**Comment by Alex-302** [comment]
But domains are still existing.

**Comment by bigdargon** [comment]
They still exist. But these domains to contain images. For example, if the domain name `store-stc.zdn.vn` is blocked, it will not display product images
