### ISSUE TITLE
ln24.be

### ISSUE THREAD

**Issue by dnovitskyi** [AdguardTeam/AdGuardSDNSFilter#797]
### Steps to reproduce
1. Go to the site, ln24.be/live, and try to watch something w/AdGuard DNS enabled
2. When AdGuard DNS is on, nothing works

<details><summary>Screenshot:</summary>

DNS OFF
![ln24 dns off](https://user-images.githubusercontent.com/33634917/137749986-0df5a042-5fd4-4116-816b-508ea7e9da47.png)
DNS ON
![ln24 dns on](https://user-images.githubusercontent.com/33634917/137749991-0227e417-4089-4274-9b8c-9b586aeccfa3.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Default
| How did you setup DNS configuration:| System
| Device model:| PC
| Operating system and version:| Linux, unspecified distro

**Comment by BlazDT** [comment]
Opened pull request.
