### ISSUE TITLE
Imou Life IP cams offline if AdGuard DNS on

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#798]
@Tkachenkoart commented on [Mon Oct 18 2021](https://github.com/AdguardTeam/AdGuardDNS/issues/200)

https://www.imoulife.com/support/downloadCenter/app
This apps and Imou Life IP cams (Dahua) can't work properly if AdGuard DNS on

**Comment by Alex-302** [comment]
Cannot check without device.
