### ISSUE TITLE
Need to block

### ISSUE THREAD

**Issue by edtw** [AdguardTeam/AdGuardSDNSFilter#81]
### Steps to reproduce
https://sp.aifei0755.net

Advertising supply chain:
https://sp.aifei0755.net/123/

### Expected behavior
Send a lot of ads, please block it.

### Your environment
 DNS server in use:| (e.g. Default, 176.103.130.130)

**Comment by ameshkov** [comment]
Could you please also tell me what exact website is using it?

**Comment by edtw** [comment]
> Could you please also tell me what exact website is using it?
![ScreenShot-2019-5-27-10-23-13](https://user-images.githubusercontent.com/50857725/58391692-869f0280-8069-11e9-8132-3c92398789fa.png)

This site needs to be logged in with the mobile version.

**Comment by ameshkov** [comment]
@edtw sorry, I meant the website address.

**Comment by edtw** [comment]
I'm sorry, but that's what I've found out so far:

www.khlgauqt2000.com
www.zhy333.com
www.bihutg.com
m.yyfymj.com
m.zhaibei112.top
www.r1oman.com
ww.zry8181.com

**Comment by Alex-302** [comment]
@edtw 
http://ww.zry8181.com/ is not working - `DNS_PROBE_FINISHED_NXDOMAIN`
http://m.zhaibei112.top/ and http://m.yyfymj.com/ - I see blank page only
http://www.zhy333.com/ and http://www.r1oman.com/ - some servers, not a sites
http://www.bihutg.com/ - blocked by EasyList China
https://www.khlgauqt2000.com/ - also advertising site

We need to know which sites using these domains for advertising.

**Comment by edtw** [comment]
I want to ask, do you want to look at the original code directly?

**Comment by Alex-302** [comment]
Yes)
Are these 5 domains - ad servers?

**Comment by edtw** [comment]
> Yes)
> Are these 5 domains - ad servers?

https://sp.aifei0755.net/123/7.js
https://sp.aifei0755.net/123/9.js
https://sp.aifei0755.net/123/24.js
https://sp.aifei0755.net/123/25.js
https://sp.aifei0755.net/123/26.js
https://sp.aifei0755.net/123/27.js

This is the code of his ad server, all in "JS", you can debug and see!

**Comment by Alex-302** [comment]
ok, blocked it
