### ISSUE TITLE
Unblock itxqzymj.micpn.com

### ISSUE THREAD

**Issue by timkgh** [AdguardTeam/AdGuardSDNSFilter#815]
It's used in legit CapitalOne emails. Not sure if just this domain needs to be unblocked or all its subdomains too. The subdomain I ran into looks pretty random.

```
> dig itxqzymj.micpn.com @94.140.14.15

;; ANSWER SECTION:
itxqzymj.micpn.com.	3600	IN	A	0.0.0.0
```

**Comment by BlazDT** [comment]
Opened pull request.

**Comment by Alex-302** [comment]
Where?

**Comment by BlazDT** [comment]
Above, just forgot to close this one.

**Comment by Alex-302** [comment]
Ok

**Comment by Supercurlz** [comment]
thank u
