### ISSUE TITLE
Adguard Android and Flipp Flyer Loading Times

### ISSUE THREAD

**Issue by pkyee** [AdguardTeam/AdGuardSDNSFilter#818]
I continue to have the issue that is described in #97 and #98 when using the Android Flipp App. It takes 30-60s to load any flyer. 

I have added flipp.com, f.wishabi, f.wishabi.net, adn wishabi.net under the Allowlist. I also have DNS filters where I am only using OISD but have added @@IIflipp.com, @@||wishabi.net and  @@||f.wishabi^. I have tried switching the DNS server which does not seem to make a difference either. If I chose to not route the application through Adguard the same issue persists. If I pause Adguard then load one flyer, then resume Adguard, all future flyers seem to load properly for a variable duration of time before recurrence of the above issue.

### Steps to reproduce
1. Adguard with no Ad blocking filters on. DNS filtering with AdGuard DNS and OISD basic filter.
2. Allowlist and DNS user rules as above.
3. Flipp application, loads initial flyers to browse, but opening any flyer takes a long period of time.
4. Pausing Adguard allows for loading of flyers, then resuming lets flyers load normally for a variable duration of time.

### Expected behavior
Using the recommended Allow list or white list, flyers should load quickly. Or, if not routing any traffic through Adguard or ad blocking, the flyers should just load normally.

### Actual behavior
Persistent or recurrent prolonged loading times for flyers.

### Your environment
Pixel 4a, Android 11 and the most recent Adguard. Issue exists on different wifi networks and mobile data.

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Adguard
| Device model:| (e.g. Google Pixel) Pixel 4a
| Operating system and version:| Android 11

**Comment by Alex-302** [comment]
What breaks an app - our DNS or OISD? Check everything separately.

**Comment by pkyee** [comment]
I've tried both DNS and OISD individually but both so not allow for normal loading times. Of note, when all ad blocking filters are disabled and there are no DNS filters active, the flyers do load properly.

**Comment by Alex-302** [comment]
Please try with AdGuard "non-filtered" and compare result.

**Comment by pkyee** [comment]
Unfortunately getting the same issue with either. Slow load times for all flyers.

**Comment by Alex-302** [comment]
It seems this app uses domains with different regional servers, and domain resolved with a far server's IP. It cannot be fixed by filters devs.
Where do you live?

**Comment by pkyee** [comment]
I am located in Ontario, Canada. That is unfortunate with this application, works well without Adguard but not a huge loss. Thanks!
