### ISSUE TITLE
validate.perfdrive.com

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#819]
@Tagiru commented on [Mon Nov 01 2021](https://github.com/AdguardTeam/AdGuardDNS/issues/202)

Cant Login in telmex isp provider page because it redirects to this strange captcha protection page when I try login using adguard dns defaut protection:
94.140.14.14
94.140.15.15

https://mitelmex.telmex.com/web/mitelmex-hogar/home

![imagen](https://user-images.githubusercontent.com/10904176/139607879-8a8d2a7f-2d00-4e8c-9bc5-ad1ef8ace71c.png)

![imagen](https://user-images.githubusercontent.com/10904176/139638743-c727df39-5d36-454f-8b21-e81eba97d592.png)

And when I go back to default dns
![imagen](https://user-images.githubusercontent.com/10904176/139608033-542ec32d-0cdf-47a4-b670-68b99067982e.png)

**Comment by Alex-302** [comment]
It was reported to EasyList, just not replaced an old rule.
