### ISSUE TITLE
Released domains

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdGuardSDNSFilter#83]
Hello. In attached the file you will find the list of domains which were released. You can delete them from the SDNS filter if you want to optimize it a little. I left the addresses of WHOIS servers if you want to check result. Thank you.

[result.txt](https://github.com/AdguardTeam/AdGuardSDNSFilter/files/3226159/result.txt)

**Comment by Alex-302** [comment]
Some domains are loaded from third-party filters(EasyList. EasyPrivacy). Removed a part from our filters.
<details>
to do:
adsnext.net
adspoi.com
adspread.net
adspring.to
adst.biz
adstizer.com
adswm.com
adtaily.eu
adtbomthnsyz.com
adtology1.com
adtology2.com
aduacni.com
adult-click.ru
againclence.com
againscan.com
againstein.com
agentcenters.com
alargery.com
bjzcyqezwksznxxhscsfcogugkyiupgjhikadadgoiruasxpxo.com
canaanita.com
canadasungam.net
clickmyads.info
clickprofi.com
clicksurvey.mobi
clicktizer.ru
clievise.com
colleable.info
crazyvideosempire.com
crocspaceoptimizer.com
dariku.ru
dealdestages.me
dearerfonder.info
dedenye.ru
deepattention.com
definitial.com
defiques.com
degotmo.ru
deguiste.com
delo-teh.ru
deluxe-ads.net
deluxeads.net
derploime.com
dobgfkflsnmpaeetycphmcloiijxbvxeyfxgjdlczcuuaxmdzz.com
dobjgpqzygow.com
dolgelo.info
domaingid.ru
dorenga.com
doubleclicks.me
excellenceads.com
exclusivecpms.com
exerciale.com
expebtu.com
farkkbndawtxczozilrrrunxflspkyowishacdueiqzeddsnuu.com
fastates.net
fastnewsis.net
fasttracktech.biz
fatayvywbebgdn.com
fathern.info
fdbqwtqdgcsceh.com
fddbdlolkxgc.com
fdepobamndfn.com
fdvmskmentjob.com
fearer.info
fegyacmbobil.com
fembsflungod.com
feqlklwaafgc.com
feropt.de
ferrellis.com
fjfxpykp.com
gateway-02.com
gateway-03.com
ghtroafchzrt.com
gkgdqahkcbmykurmngzrrolrecfqvsjgqdyujvgdrgoezkcobq.com
gotarget.su
gottimuch.com
governmenttrainingexchange.com
grey-eyes.info
holidaytravelguide.org
holysts.com
homechader.com
homeri.de
hommunit.com
hoomefodl.com
hoomezip.biz
hostgit.net
hostingcloud.review
igupodzh.com
ihqht.com
ijdenha.ru
ijtozat.ru
iklandiweb.com
iklangratismu.com
iklanonlinemu.com
iklanpasanggratis.com
iklantop.net
ikritis.ru
ilsivrexvpyv.com
iltevo.info
integritystat.com
intelevance.com
intelliad-tracking.com
interactivespot.net
irtula.ru
iwantmoar.net
kartinuly.ru
kjgh5o.com
kjnsfgkjn.ru
kjplmlvtdoaf.com
kldwitfrqwal.com
knkxnwscphdk.com
knorex.asia
ksbklucaxgbf.com
ksdifdd.com
ksdnf.com
ktcltsgjcbjdcyrcdaspmwqwscxgbqhscmkpsxarejfsfpohkk.com
kthdreplfmil.com
kug-74.com
kurtgcwrdakv.com
kutabi.info
kylqpeevrkgh.com
lacemme.com
ladiesnadosuge.com
ladyzxxyz.com
lagrobe.ru
lakidar.net
lalagop.info
lamalama.top
lapumo.com
largestable.com
larotret.ru
lativil.co
lavetawhiting.com
lazynerd.info
lcyxmuhxroyo.com
lead-tracking.biz
legscare.ru
leleorix.ru
lemfama.ru
lengthi.net
leplena.ru
lerester.com
lerova.ru
lerrex.ru
levitatsia.ru
lightad.co.kr
lightspeedtop.com
limo20.ru
limo21.ru
limonadsources.ru
linkbuy.biz
linktausch-pagerank.de
liosawitskzd.com
litthecho.pro
litthegre.com
ljngencgbdbn.com
lkbvfdgqvvpk.com
lmuxaeyapbqxszavtsljaqvmlsuuvifznvttuuqfcxcbgqdnn.com
luke-forelegs0.asia
lundered.info
lwenrqtarmdx.com
lyhowtot.ru
lyifwfhdizcc.com
lymantriacypresdoctrine.biz
lytpdzqyiygthvxlmgblonknzrctcwsjycmlcczifxbkquknsr.com
lzmovatu.com
lzoloro.info
m3gadeth.ru
mabirol.com
macarier.review
mqwkqapsrgnt.com
namezones.ru
narrangel.com
nasdak.in
nastoverewess.pro
natsety.info
nbrwtboukesx.com
optiad.net
optimalroi.info
optreadetrus.info
oqkuwkax.com
oqmjxcqgdghq.com
pnoss.com
pointclc.com
popcpv.com
pserhnmbbwexmbjderezswultfqlamugbqzsmyxwumgqwxuerl.com
qfrpehkvqtyj.com
qixlpaaeaspr.com
qljczwei.com
qnqrmqwehcpa.com
qnrzmapdcc.com
qnxilhyvvd.biz
qotwtnckqrke.com
qpiyjprptazz.com
quickcash500.com
rabela.info
rabilitan.com
radicalwealthformula.com
radiomanlibya.com
rkelvtnnhofl.com
rnuhavi.ru
roitracking.net
roivista.com
roninex.ru
rootmedia.ws
ropsinde.com
roukel.com
rpczohkv.com
rpmstatic.net
rss20.ru
rt-image.ru
rtbpops.com
russervisbest.ru
sadecereklam.net
sadreno.com
safari-lock.com
securewebboard.com
seedrug.ru
seekads.net
selipuquoe.com
sellously.info
selloweb.com
skywarts.ru
sptag3.com
squartedo.info
squarterun.com
tech1515983.ru
tech2648159.ru
tech4215978.ru
tech517283.ru
tech547789.ru
tech5877413.ru
tech9638514.ru
techdomain01.ga
technical-rtl.ru
tedlrouwixqq.com
tedobe.com
tedpasit.com
tedverspar.com
teen-porn-portal.com
thetraffic-translate.com
theylike.org
thomized.co
tibrashadow.ru
tightexact.net
tighting.info
tisadama.com
tiveriches.pro
tivisla.ru
tizer-bazar.com
tizer-click.biz
tizerda.net
tizerelite.net
tizerget.net
tizergo.net
tizerka.info
tizernet.biz
tizershop.ru
tizersmaster.ru
tizertraf.com
tizinfo.ru
tizka.ru
tjbgiyek.com
tkarkbzkirlw.com
tldadserv.com
tldredenter.com
tlr1.biz
tlzhxxfeteeimoonsegagetpulbygiqyfvulvemqnfqnoazccg.com
tmdcfkxcckvqbqbixszbdyfjgusfzyguvtvvisojtswwvoduhi.com
tmkbpnkruped.com
tmpjmp.com
tnyzin.ru
to330.com
todaytodo.ru
todich.ru
togru.ru
tonsperning.ru
tonsunjo.com
top4wap.ru
tophotoffers.com
toptrackers.ru
toraccept.ru
torads.me
trktrk011.com
tromen.ru
truesecurejump.com
trunderka.ru
truthfulhead.com
truthfulturn.com
truvacdn.com
trygen.co.uk
userlog.synapseip.tv
useronlinecounter.com
usoqghurirvz.com
uspostly.info
utilient.com
uwrzafoopcyr.com
uxyofgcf.com
uyqzlnmdtfpnqskyyvidmllmzauitvaijcgqjldwcwvewjgwfj.com
uytichas.ru
uzreuvnlizlz.com
valuecontent.net
viddirect.ru
video103.ru
video1404.info
videohube.eu
videojune.ru
videolansoftware.com
videoliver.com
videoseed.by
videoselfer.com
videovfr.com
vidkoz.com
vidmsc.com
vidozex.ru
vidshm.com
viedeo2k.tv
wallacemaloneymindanao.info
walternsa.com
walternse.com
warfacco.com
wkhychiklhdglppaeynvntkublzecyyymosjkiofraxechigon.com
wmjdnluokizo.com
wmrlinks.ru
wmwkwubufart.com
</details>

**Comment by Alex-302** [comment]
Done
