### ISSUE TITLE
Samsung/LG/Philips smart-TV ad(?) domains

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardSDNSFilter#830]
### Steps to reproduce

N/A

### Expected behavior

Both of the following:
1) AdGuard DNS begins promoting itself as having support for smart-TVs, for which there's a potentially huge market.
2) The current entries for smart-TVs get expanded as far as feasible.

### Actual behavior

AdGuard DNS has (a heavily underadvertised) support for blocking smart-TV ads (Primarily on Samsung TVs), so I figured I'd add a few more entries based on https://blog.malwarebytes.com/privacy-2/2021/11/smart-tv-adverts-put-a-wrinkle-in-your-programming/ and https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV-AGH.txt

I propose:
```
||ad.nettvservices.com^
||ad.lgappstv.com^
||lgad.cjpowercast.com.edgesuite.net^
||lgsmartad.com^
||ads.samsung.com^
||gpm.samsungqbe.com^
||samsungacr.com^
```

<details><summary>Screenshot:</summary>

N/A

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| https://filters.adtidy.org/windows/filters/15.txt
| How did you setup DNS configuration:| System
| Device model:| Samsung ≥2019 TVs in particular
| Operating system and version:| Tizen OS (unknown versions)

**Comment by pgl** [comment]
Just a quick note - some of these were already on my list, but now they all are.

**Comment by Alex-302** [comment]
No need to add them. `@ryanbr` already added them to EL:) Just wait for DNS filter compiler.

**Comment by pgl** [comment]
Hey I got there first

**Comment by xlionjuan** [comment]
BLOCK "gpm.samsungqbe.com" this domain will cause my SAMSUNG Smart TV can't login Samsung account and make the device can't install any app on it. (But if you installed already, the installed app still works) I need to whitelisted this domain in order to use any Samsung SmartThing's feature.

**Comment by DandelionSprout** [comment]
Thanks for the headsup. Seems like `https://twitter.com/mattpbarlow/status/1453751474836709376` was wrong about suggesting that people should block that domain, then.
