### ISSUE TITLE
Viafree on smart-TVs

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/AdGuardSDNSFilter#831]
### Steps to reproduce

1. Somehow get access to Viafree's TV app with a VPN and whatnot.
2. Play any episode, e.g. of `Luksusfælden Danmark`.
3. Scroll forward to one of the timestamps in the player timebar that is marked with a notch.
4. See that mid-roll ads begin to play.

### Expected behavior

Mid-roll ads (which can stretch up to 4 minutes) are blocked in the various regional smart-TV and phone apps of `Viafree`.

### Actual behavior

Currently, `||freewheel-mtgx-tv.akamaized.net^$media,domain=viafree.*` in AdGuard Base is not being applied to AdGuard DNS Filter.

Simply `||freewheel-mtgx-tv.akamaized.net^` would be an absolute lifesaver for smart-TV and phone users of `Viafree`, but would cause problems with blank video players for PC users without browser extensions (for which `viafree.*##.player-wrapper .viafree-player .vjs-tech:style(display: initial !important)` should be added to AdGuard Base).

<details><summary>Screenshot:</summary>

None at the moment; can get one on demand.

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 94.140.14.14
| How did you setup DNS configuration:| System
| Device model:| Samsung UE65RU7455
| Operating system and version:| Tizen OS (unknown version)

**Comment by Alex-302** [comment]
Need sample link and screenshot of an issue on PC, including devtools with `.player-wrapper .viafree-player .vjs-tech`
With blocked domain I still see ad on desktop, and no request to that domain
![image](https://user-images.githubusercontent.com/8361299/141309295-c40f612b-6de8-4b94-aa78-8556f9d21ace.png)

Video ad link
https://gcdn.2mdn.net/videoplayback/id/bdb9c5a11dd0a79e/itag/344/source/doubleclick_dmm/ctier/L/acao/yes/ip/0.0.0.0/ipbits/0/expire/3754563503/sparams/id,itag,source,ctier,acao,ip,ipbits,expire/signature/5C39ECABCCE0E16ECBFD37B3653E8AC82CBBBEC9.2CC091888E22746D22C9FF2838BC0BAC8A1E1D4D/key/ck2/file/file.mp4

Maybe `gcdn.2mdn.net` also may be blocked, like in https://github.com/lassekongo83/Frellwits-filter-lists/blob/master/Frellwits-Swedish-Hosts-File.txt

**Comment by DandelionSprout** [comment]
That's perfectly possible, now that you mention it.

**Comment by Alex-302** [comment]
Please test if you using AdGuard Home or Pihole
```
||freewheel-mtgx-tv.akamaized.net^
||gcdn.2mdn.net^
```

**Comment by DandelionSprout** [comment]
I was able to test with [Dandelion Sprout's DNS Server](https://github.com/DandelionSprout/adfilt/tree/master/Dandelion%20Sprout's%20Official%20DNS%20Server) too when I wrote the OP, which has those two entries. The ads were indeed blocked during that testing.

**Comment by Alex-302** [comment]
Ok, added these rules.

**Comment by Alex-302** [comment]
@DandelionSprout Does it cause ad block detection on https://www.tv3sport.dk/sport/fodbold/nyheder/dramaer-venter-i-arets-sidste-3-f-superliga-runde-sadan-sender-vi-fra-weekendens-kampe?(desktop)

**Comment by DandelionSprout** [comment]
I recall that was a problem I was aware of at the time I wrote the OP: The entry was *fantastic* on TVs and phones, but was much less good on PCs (be it due to AAB or the video players failing to work at all at worst).
