### ISSUE TITLE
Android app crashes [E-devlet]

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#836]
@saurane commented on [Sun Nov 21 2021](https://github.com/AdguardTeam/FiltersRegistry/issues/544)

Android app: E-devlet (Turkish government app)
Subdomain: analitik.edevlet.gov.tr
Client: NextDNS
When this subdomain is blocked, the application gives an error. Please remove from the list.

## LIST
https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/filter_3_Spyware/filter.txt

**Comment by Alex-302** [comment]
Removed from filters.
