### ISSUE TITLE
tgt.tamedia.ch

### ISSUE THREAD

**Issue by brknkfr** [AdguardTeam/AdGuardSDNSFilter#842]
When using the app **12app** (https://12app.ch/ - an app with the best stories of swiss newspapers) with a login, the login process needs access to `tgt.tamedia.ch`, otherwise login will fail.

### Expected behavior

Login with **12app** should work.

### Actual behavior

Login with **12app** fails when using Adguard DNS Filter, because the domain `tgt.tamedia.ch` is blocked.

**Comment by Alex-302** [comment]
@brknkfr Please check tomorrow.
