### ISSUE TITLE
wearetopple.com

### ISSUE THREAD

**Issue by dcm** [AdguardTeam/AdGuardSDNSFilter#843]
I saw this site unblocked in my NextDNS logs (I use this filter in my NextDNS config). I'm not sure what site/service I was using when this host was looked up.

Their website shows it's an ad network with the slogan "Reach the unreachable". Perhaps they're using some sly method of slipping ads into sites, or perhaps they're just new. Either way it doesn't seem like they do anything other than ads, so maybe it wouldn't hurt to add them to this list.

**Comment by Alex-302** [comment]
Which domain exaclty? I guess they use some subdomain for loading ads.

**Comment by dcm** [comment]
Just `wearetopple.com` was in my log. I hadn't visited the site directly in a web browser.

**Comment by Alex-302** [comment]
Ok, blocked.
