### ISSUE TITLE
EE iOS App

### ISSUE THREAD

**Issue by emlimap** [AdguardTeam/AdGuardSDNSFilter#850]
Not sure if you accept reports for iOS app. If you don't, please let me know.

### Steps to reproduce

1. Install & open this app https://apps.apple.com/gb/app/my-ee/id567457151

### Expected behavior

Endpoint monitoring from dynatrace is blocked

### Actual behavior

Endpoint monitoring from dynatrace is not blocked. Similar service from newrelic is already blocked

Below is the domain it connects to
```
bf27921kpd.bf.dynatrace.com
```
More info 
```
https://www.dynatrace.com/support/help/how-to-use-dynatrace/real-user-monitoring/setup-and-configuration/web-applications/troubleshooting/beacon-forwarder/
```

Suggested filter

```
||bf.dynatrace.com^
```
### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| AdGuardHome
| How did you setup DNS configuration:| Router
| Device model:| iPhone 11
| Operating system and version:| 15.1

**Comment by Alex-302** [comment]
It seems this service used by app developers for catching [performance]bugs.
