### ISSUE TITLE
Santander bank app doesn't work when AdGuard DNS is enabled. 

### ISSUE THREAD

**Issue by sdgrs546547Q** [AdguardTeam/AdGuardSDNSFilter#852]
### Steps to reproduce

1. Set AdGuard DNS in your settings
2. Open Santander Bank
3. App shows an error and closes
4.

### Expected behavior

It should load the status of the bank
### Actual behavior

It closes

<details><summary>Screenshot:</summary>

I can't screenshot because personal data appears

</details>

You need to whitelist this domains to solve the issue
wup-7b4df495.santander.cl
api-7b4df495.us.v2.we-stats.com

Thanks

### Your environment
I tried in iOS

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use: Default
| How did you setup DNS configuration: iOS profile
| Device model: iPhone 12
| Operating system and version: iOS 13

**Comment by Alex-302** [comment]
@sdgrs546547Q Hi. Sorry for the late reply. Please check tomorrow.
