### ISSUE TITLE
cts.businesswire.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdGuardSDNSFilter#853]
### Steps to reproduce

1. Go to https://cts.businesswire.com/ct/CT?id=smartlink&url=https%3A%2F%2Fwww.similarweb.com%2Ftop-websites%2F&esheet=52548524&newsitemid=20211209006132&lan=en-US&anchor=on+the+web&index=3&md5=f299e1fa57858b0c006f0d413a942f25
2. See bug

### Expected behavior

Not Blocked

### Actual behavior

Blocked

**Comment by Alex-302** [comment]
Need source of the link.
