### ISSUE TITLE
Block v[dot]fwmrm[dot]net subdomains

### ISSUE THREAD

**Issue by superlex** [AdguardTeam/AdGuardSDNSFilter#854]
![dd](https://user-images.githubusercontent.com/1375223/145682532-8adb0748-bec4-431c-98e5-3fa63a9a3b4d.jpg)

It should be blocked because of ads in some italian apps.

Thanks.

**Comment by Alex-302** [comment]
99% of sites with these ads will be broken. 
Blocking rule was excluded from DNS filter.

**Comment by Alex-302** [comment]
Better report about ads in filters repo. We will try to make app-specific rules.
