### ISSUE TITLE
cdn.adjust.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdGuardSDNSFilter#857]
### Steps to reproduce

1. Go to https://www.sololearn.com/Discuss/2574612/create-a-timer-program-that-will-take-the-number-of-seconds-as-input-output-the-remaining-time-and
2. See bug https://i.imgur.com/2kbAH9o.png

### Expected behavior

Not Blocked

### Actual behavior

Blocked

**Comment by Alex-302** [comment]
Not reprodcued.
