### ISSUE TITLE
pubfinity.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdGuardSDNSFilter#859]
### Steps to reproduce
1. Go to https://pubfinity.com/

### Expected behavior
Blocked

### Actual behavior
not Blocked

**Comment by Alex-302** [comment]
Need the site where ads loaded from this domain.

**Comment by chirag127** [comment]
It is used in https://www.google.com/url?sa=t&source=web&rct=j&url=https://www.microsoft.com/en-us/p/freda-epub-ebook-reader/9wzdncrfj43b&ved=2ahUKEwikvKGM44j1AhWXFbkGHekKD0kQFnoECAcQAQ&sqi=2&usg=AOvVaw2BpikV2QmP285IK6_wrucH

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #105031](https://github.com/AdguardTeam/AdguardFilters/issues/105031) via [**ZenHub**](https://www.zenhub.com/)
