### ISSUE TITLE
||promoted.soundcloud.com^

### ISSUE THREAD

**Issue by Sergskd** [AdguardTeam/AdGuardSDNSFilter#86]
promoted.soundcloud.com

Is one of the domains that’s leaking ads on free version of SoundCloud. I was wondering if it could be added to a list?

I am testing adguard 3.0.1 (143) using dns adgurds DOH 

Ads still load between tracks on SoundCloud 5.56

**Comment by Alex-302** [comment]
@Sergskd hi. I don't see this request. Please describe how to reproduce this issue.
I see this domain is not blocked in
https://github.com/wilzhu/hosts/blob/master/hosts

**Comment by Sergskd** [comment]
Hi, Alex to reproduce my issue you need to have the following:
iPhone iOS 12.3.1 
Bata version AdGuard v. 3.0.1 (143) with AdGuard DOH switched on 
to listen to music you'll need SoundCloud v. 5.56 
To reproduce ads you can just listen to any music or podcasts. Ads will come on between the tracks. To explain a little bit more; its the end of the currently playing music track and a beginning of the new music track. You can skip or fast forward to reproduce advertisements.
AdGurds DOH blocks a good amount of ads, here is a screenshot to prove.
![ads](https://user-images.githubusercontent.com/31105646/59459514-f7c11280-8dea-11e9-91e5-6e5c715308db.jpg)


I believe `promoted.soundcloud.com` is responsible for promotional content. I have tested it with AdGuard Pro iOS 2.1 and seems to be working well.

**Comment by Alex-302** [comment]
I don't see this domain:(

**Comment by Sergskd** [comment]
Hi Alex, I have provided a screenshot as proof. The reason you don't see ads is you don't allow enough time to pass. It's like fishing, you have to wait for a little while before an ad pops up.  
here is more proof with the timestamp and proof of AdGuard Pro blocking it:
![ad1](https://user-images.githubusercontent.com/31105646/59474894-b181a880-8e16-11e9-86de-026b5bcf684d.jpg) ![ad2](https://user-images.githubusercontent.com/31105646/59474898-b47c9900-8e16-11e9-9559-0f6964f01ab7.jpg)
![log](https://user-images.githubusercontent.com/31105646/59474900-b7778980-8e16-11e9-8cc4-50fa71f745fb.jpg)
![adguard pro](https://user-images.githubusercontent.com/31105646/59474908-c3fbe200-8e16-11e9-9756-fd1d29ba8616.jpg) 
![info](https://user-images.githubusercontent.com/31105646/59474917-cf4f0d80-8e16-11e9-9a9f-ddd6387399c7.jpg) ![sound promo](https://user-images.githubusercontent.com/31105646/59474918-d118d100-8e16-11e9-9d2e-72e4fb4f45e0.jpg)

If you look up `promoted.soundcloud.com` you learn its an AWS CDN that delivers ads for Soundcloud.

The difference between Adguard 3.0.1 (143) & Adguard Pro 2.1 one is going through your DNS and the other one is going through local VPN filter. 

I have included screenshots of AdGuard Pro to show you that I have blocked it on my phone and it didn't break anything, except it blocked ads pictured above that are still leaking through Adguard 3.0.1 (143) DOH that I am currently beta testing. 
if you add `promoted.soundcloud.com` master hosts list, it'll be awesome! 🤓

**Comment by Alex-302** [comment]
I just want co check content of requests using Fiddler.
Ok, added.
