### ISSUE TITLE
Azure Portal not working properly when using ADGuard DNS servers

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#860]
@flavio-neves commented on [Thu Dec 23 2021](https://github.com/AdguardTeam/AdGuardDNS/issues/209)

Hi, 

Whenever I try to use Log analytics or application insights, both use specific URLs outside azure domain, I got a timeout error.

More details here:

![image](https://user-images.githubusercontent.com/35963484/147264276-1287ddc6-a3ac-43fc-bd3f-e5621adb1cc8.png)

**Comment by ameshkov** [comment]
@Alex-302 what we need to know is whether this domain is used for third-party analytics somewhere. If it does, we should keep it blocked.

**Comment by Alex-302** [comment]
@flavio-neves Hi. Need steps to reproduce and description what exactly is broken.
Errors in console is ok, when network requests are blocked or domain cannot be resolved(blocked by DNS).
