### ISSUE TITLE
Remove `download.db-ip.com`

### ISSUE THREAD

**Issue by agneevX** [AdguardTeam/AdGuardSDNSFilter#863]
`download.db-ip.com`, `geoip-db.com` should be removed from the block list because its required by apps to download the DB that allows them to display country origins of IP addresses.

**Comment by Alex-302** [comment]
> by apps

Which apps?

**Comment by agneevX** [comment]
qBittorrent.

**Comment by agneevX** [comment]
Not sure why it was blocked in the first place.

**Comment by Alex-302** [comment]
> Not sure why it was blocked in the first place.

Because EasyPrivacy used as one of upstreams.
