### ISSUE TITLE
Airdrop issue with AdGuard?

### ISSUE THREAD

**Issue by macuros** [AdguardTeam/AdGuardSDNSFilter#865]
Just checking... is this also an issue with AdGuardDNSFilter? 

https://forum.adguard.com/index.php?threads/airdrop-not-working-with-adguard.45314/

I'm using this sin Docker and I can see an issue with AirDrop from iPhone to iPad.

**Comment by ameshkov** [comment]
Nope, that was a bug of AG for Mac, has nothing to do with the filter.
