### ISSUE TITLE
Add 'AdGuard DNS Filter' to AdGuard services check-page

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardSDNSFilter#866]
### Problem Description
Some users like to keep using the System Default DNS server, but use the AdGuard DNS filter for on-device DNS blocking.

AdGuard DNS is able to be checked on the AdGuard services check-page via https://adguard.com/en/test.html but there is no way to check if the AdGuard DNS filter is working on this page.

### Proposed Solution
Add 'AdGuard DNS Filter' to AdGuard services check-page to allow the user to check if DNS filtering is currently working as expected on their device or network that is using the filter, such as in AdGuard for Mac/Windows/iOS/Android. This could be done by adding a single exclusive dummy domain to the filter (e.g. `dnsfiltercheck.adguard.com`) that the website checks if blocked or not.

**Comment by ameshkov** [comment]
Starting with a single filter list would eventually cause requests to add other lists detection and this is just not the road we would like to take.
