### ISSUE TITLE
telematicsdirect.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdGuardSDNSFilter#871]
### Steps to reproduce

1. Go to https://telematicsdirect.com/
2. See bug

### comments 
it is used in https://play.google.com/store/apps/details?id=com.kafuiutils&hl=en_IN&gl=US

### Expected behavior

Not Blocked

### Actual behavior

Blocked

**Comment by chirag127** [comment]
What invalid

**Comment by Alex-302** [comment]
No screenshot or description what happens.
