### ISSUE TITLE
dsar.ziffdavis.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdGuardSDNSFilter#872]
### Steps to reproduce

1. Go to 
2. See bug

it is used in speed test app https://play.google.com/store/apps/details?id=org.zwanoo.android.speedtest&hl=en_IN&gl=US
### Expected behavior

Not Blocked

### Actual behavior

Blocked

**Comment by Alex-302** [comment]
Cannot reproduce.
