### ISSUE TITLE
Why aren't tracking referral links blocked?

### ISSUE THREAD

**Issue by muchqs** [AdguardTeam/AdGuardSDNSFilter#873]
https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/190

Things like this one. Why was it unblocked? Why shouldn't it be blocked when it tracks? If you unblock every tracking service, then what is the point of having the filter on AdGuard Home when it doesn't block anything?

A user should manually unblock these types of links themselves if needed, and shouldn't be unblocked by default by the filter.

**Comment by ameshkov** [comment]
AdGuard DNS filter is supposed to be a casual-user-friendly blocklist, e.g. we try not to break users' navigation if possible even when it means that an intermittent tracking domain should be unblocked for that.

**Comment by muchqs** [comment]
That's rather unfortunate. IMO I think the user should either unblock on his/her own or use a more forgiving list like oisd.nl
But I respect your decision. Thank you for the answer.

**Comment by Alex-302** [comment]
@muchqs You will be able to remove exceptions and block anything after starting AdGuard cloud DNS
https://adguard-dns.com/

**Comment by chrcoluk** [comment]
> That's rather unfortunate. IMO I think the user should either unblock on his/her own or use a more forgiving list like oisd.nl But I respect your decision. Thank you for the answer.

For what its worth I agree with these decisions, most dns lists seem to be made with blocking as priority, and it doesnt matter if functionality breaks, some of us want filtering that doesnt break anything, even if it means its a much lower percentage getting blocked, this seems to be almost the only whitelist on the net.

A list that requires someone to be adding manual exceptions all the time is nigh on useless, as it just gets unloaded to fix the net.
