### ISSUE TITLE
PayPal payment method blocked on AliExpress

### ISSUE THREAD

**Issue by muchqs** [AdguardTeam/AdGuardSDNSFilter#874]
This URL `retcode-us-west-1.arms.aliyuncs.com` is being blocked by AdGuard DNS Filter. Blocking this URL prevents PayPal from working on AliExpress and will result in an error message saying "system is busy please try again".

<details><summary>Screenshot:</summary>

https://i.imgur.com/ZRKYkrr.png
https://i.imgur.com/gEzvCMZ.png

</details>

DNS server: Unbound + AdGuard Home on RPi

**Comment by Alex-302** [comment]
@muchqs Please record video or describe. I don't see PayPal in payment methods
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/149778238-6a916349-10f0-4548-87b6-5e949298be28.png)

</details>

**Comment by Alex-302** [comment]
I don't see PayPal with US and EU IPs.

**Comment by muchqs** [comment]
Thanks for replying. I'm from Canada. Interesting you don't see PayPal with US IPs. This is what I see when selecting a payment method:
https://i.imgur.com/uSkwx8M.png

I also reuploaded the first screenshot showing the error message with PayPal selected:
https://i.imgur.com/ZRKYkrr.png

This error message screenshot was taken at 17:46, you can see the timestamp shown in AGH's log when the URL was blocked is 17:45:59.

I tried several times at first, but every time the transaction would fail. Then I noticed this URL being blocked by AGH, the timestamps corresponded with when I clicked on the "pay" button. After unblocking this URL, the payment went through successfully. I also noticed this URL sometimes shows up in the log as blocked during normal browsing on AliExpress, but it does not affect anything. I have purchased from AliExpress before and did not have to unblock anything from AGH, so I'm not sure if this is a recent change from Ali or something.

**Comment by Alex-302** [comment]
Ok, removed `||retcode-*.arms.aliyuncs.com^`
Please check tomorrow(I hope no need to pay during this process).

**Comment by muchqs** [comment]
Thank you.
