### ISSUE TITLE
Website false positive ilto.run

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#877]
@SelaO commented on [Tue Jan 25 2022](https://github.com/AdguardTeam/AdGuardDNS/issues/215)

https://ilto.run is being used by a very popular shipping company in Israel to send a link to customers to pick a pickup location for their packages.
Please remove it from the blacklist.

I'm using dns.adguard.com and it's blocked there.

**Comment by Alex-302** [comment]
It seems it is dead
![image](https://user-images.githubusercontent.com/8361299/151020087-776e70eb-ed7f-4bd2-a652-10a71c46d8d6.png)

**Comment by SelaO** [comment]
see this for example https://ilto.run/aOnu8Jft0c

it works

**Comment by Alex-302** [comment]
No
![image](https://user-images.githubusercontent.com/8361299/151221633-244a1587-4c6f-4ce3-be8f-6f57f3adc57f.png)

Please show `nslookup` output

**Comment by SelaO** [comment]
![image](https://user-images.githubusercontent.com/21977571/151238638-48346442-341c-4abc-bad8-e3c174d3ac6b.png)

it's probably blocked for traffic out of Israel, a lot of sites here do that.

**Comment by Alex-302** [comment]
I see. But this domain is absent in DNS filter.
Mayby DNS issue. Better write here https://github.com/AdguardTeam/AdGuardDNS/issues
