### ISSUE TITLE
https://ilto.run false positive

### ISSUE THREAD

**Issue by SelaO** [AdguardTeam/AdGuardSDNSFilter#882]
https://ilto.run is being used by a very popular shipping company in Israel to send a link to customers to pick a pickup location for their packages.
Please remove it from the blacklist.

I'm using `dns.adguard.com` and it's blocked there.

see this, for example, https://ilto.run/aOnu8Jft0c to see that the site works, it redirects to https://run.hfd.co.il/SpotSelect/?rnum=77333264701432

![image](https://user-images.githubusercontent.com/21977571/151220638-3de62bb1-8169-4ed0-890c-aecfec662753.png)

**Comment by Alex-302** [comment]
We do not block it.
![image](https://user-images.githubusercontent.com/8361299/151243158-48e69726-3fe0-43ac-86cf-8e43eefd7479.png)
