### ISSUE TITLE
Mac App Store is getting blocked

### ISSUE THREAD

**Issue by tcurdt** [AdguardTeam/AdGuardSDNSFilter#887]
### Steps to reproduce

1. have the list active
2. open the App Store app on macOS
3.
4.

### Expected behavior

The App Store app on macOS and it should still load content.

### Actual behavior

The Mac App Store does not load anything.
I had to disable to the list for the content to load.

The IPs are now seemingly cached on the machine and unfortunately I didn't take a screenshot before disabling the block list.

### Your environment

macOS 12.1
Adguard home DNS server IP provided via DHCP

**Comment by ameshkov** [comment]
Hi, we cannot reproduce the issue. As I understand, you're using AdGuard Home. Could you please check what's getting blocked in the Query log?

**Comment by tcurdt** [comment]
I tried to reproduce it by clearing the DNS cache - but that did not work.

    dscacheutil -flushcache
    killall -HUP mDNSResponder

I am not sure how much caching the App Store app does in itself. So for the moment I cannot reproduce it anymore.
Just FTR here is a list of domains that seem to be related to the Mac App Store.

<img width="639" alt="Screenshot 2022-02-08 at 10 58 47" src="https://user-images.githubusercontent.com/13697/152964343-f159b813-537e-427f-9681-026f2d3363d0.png">

Maybe it was just a glitch. So I close this for now.
We can re-open when I can reproduce.
