### ISSUE TITLE
my.equifax.ca

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#893]
I use your public adguard dns and found that adguard is blocking me from signing in to the following URL:

https://my.equifax.ca/

When I fill in my credentials, it just spins and spins and spins.  To troubleshoot, I tried on my cell phone, connected to my home wifi and same thing. When I turn off my wifi and use cellular data, it works.

When I tried accessing the URL on my desktop connected to my home network by ethernet, same spinning problem. 

I then thought to change my DNS to 1.1.1.1 and I am able to successfully log in. So I believe your DNS servers are blocking some function the Equifax website needs.

Here are the IP addresses I use:

IPv4:
94.140.14.140
94.140.14.141

Can someone look into this, and have https://my.equifax.ca/ white listed?

**Comment by Eugene-Savenko** [comment]
CRM ID of the user: 576558

**Comment by Alex-302** [comment]
Cannot register without CA phone number.

**Comment by ameshkov** [comment]
@Alex-302 you don't need to sign up there to reproduce the issue, just use some random credentials.

**Comment by ColtonYYZ** [comment]
Or you. An use 647-495-0088 if you really need to register. It's a free Toronto number I just got using FreeTone App that does texts and calls

**Comment by Alex-302** [comment]
It is broken by EasyPrivacy's rule
`||iovation.com^$third-party`
@ameshkov Is it worth deleting a rule because of one site?

**Comment by ameshkov** [comment]
This is not a major tracking system so I guess it's okay to exclude it.

In general, our policy is not to break things when it can be avoided without massive concessions.
