### ISSUE TITLE
Whitelist vortex.data.(microsoft|msn).com

### ISSUE THREAD

**Issue by bigdargon** [AdguardTeam/AdGuardSDNSFilter#895]
> Unable to login into your phone app on android when vortex.data.microsoft.com is blocked 

App: https://play.google.com/store/apps/details?id=com.microsoft.appmanager

Source: https://github.com/StevenBlack/hosts/issues/1881

Please check this and add to whitelist. Thank you!

**Comment by Alex-302** [comment]
Need steps to reproduce.

**Comment by bigdargon** [comment]
- Download the app, then sign in with your microsoft account.
- Can't login when blocking domain `vortex.data.microsoft.com` 
- Whitelist is working properly https://github.com/StevenBlack/hosts/issues/1881#issuecomment-1031109391
- Removed in recent commit https://github.com/shreyasminocha/shady-hosts/commit/8a8c67e798b12de05c8543f4ea1ab43aa3e02803

**Comment by Alex-302** [comment]
Not working without AdGuard
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/154298818-a23b1d87-0695-4df4-884e-16ee15f11455.png)

</details>
