### ISSUE TITLE
log-upload-os.hoyoverse.com

### ISSUE THREAD

**Issue by hpacleb** [AdguardTeam/AdGuardSDNSFilter#899]
The current list currently has the following :
log-upload-eur.mihoyo.com
log-upload.mihoyo.com
log-upload-os.mihoyo.com

The company has [rebranded](https://genshin.hoyoverse.com/en/news/detail/19431) and seems like they have added new urls that they use along with the current list. 
I am unsure if this also applies to other regions since I have only encountered log-upload-os.hoyoverse.com

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/a2f373dc31cb2cfeb48cb376bc0fbe4f47601a81
