### ISSUE TITLE
Android showing Internet unavailable when AdGuard DNS in use

### ISSUE THREAD

**Issue by Toontje** [AdguardTeam/AdGuardSDNSFilter#90]
### Steps to reproduce

1. Configure AdGuard DNS (176.103.130 and 131) in router DHCP.
2. Connect to router Wifi

### Expected behavior
I will be able to use services on the internet without any notifications.

### Actual behavior
Android Pi tells me there is no internet connectivity and switches to Mobile data and doesn't use AdGuard DNS. It uses the Mobile providers DNS instead. 

<details>
In reality Android is connected properly to the internet and i can use internet services including the use of AdGuard DNS over Wifi. I can confirm this by switching Mobile data off and accessing the Adguard Test page (https://adguard.com/en/adguard-dns/overview.html).
What i think is happening is that the moment Android connects to Wifi it checks for a to-me-unknown URL to check if internet connectivity is there. I suspect this URL is blocked by AdGuard DNS.
</details>

### Your environment
Samsung Note 8 running Android 9.
ISP router DHCP
Local IP addesses (192.168.1.0/24)
DNS Servers Default (176.103.130 and 131)

**Comment by Alex-302** [comment]
Maybe your device checks connection using advertising/tracking domain. The similar issue is on my old TV - it cays that Internet is not working, but it is working.
Not sure if I can help you without DNS log.
