### ISSUE TITLE
Dovetale Tracking Pixel: dttrk.com

### ISSUE THREAD

**Issue by TPS** [AdguardTeam/AdGuardSDNSFilter#911]
Per https://support.dovetale.com/support/solutions/articles/48000956369-using-the-dovetale-tracking-pixel, `dttrk.com` is used solely for tracking.  Maybe add `||dttrk.com^`  here **_&_** in the tracking list?

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #112962](https://github.com/AdguardTeam/AdguardFilters/issues/112962) via [**ZenHub**](https://www.zenhub.com/)
