### ISSUE TITLE
dns.adguard.com pikabu.ru

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#913]
@arturas953 commented on [Thu Mar 17 2022](https://github.com/AdguardTeam/AdGuardDNS/issues/222)

проверьте пожалуйста, не режет рекламу с вашим DNS на https://pikabu.ru/
Только DNS установлен.

**Comment by Alex-302** [comment]
@arturas953 Реклама загружается с главного домена yandex.ru Без блокировщика, одним лишь DNS, не заблокировать.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/159077126-b605e420-10f1-4d44-85e8-4fb783f11137.png)

</details>

**Comment by bogachenko** [comment]
@Alex-302 вопрос не по теме.

Что это за браузер такой у тебя?

**Comment by Alex-302** [comment]
Это отладчик, Fiddler.
