### ISSUE TITLE
adc.api.nine.com.au

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdGuardSDNSFilter#916]
Although previously excluded, it seems that it has come back to the DNS filter.

Blocking `adc.api.nine.com.au` again has made the 9Now app unusable across all platforms.

Could we have this domain excluded once again?

https://github.com/AdguardTeam/AdguardFilters/issues/113780
https://github.com/AdguardTeam/AdguardFilters/issues/71865

https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/542

**Comment by planet0** [comment]
```
!
! Source name: Additional rules
! Source: Filters/rules.txt
!
!
! Tracking
!
! This domain does not exist and is used for health checks
||adc.api.nine.com.au^
```

**Comment by Alex-302** [comment]
Maybe a bug of DNS filter compiler
![image](https://user-images.githubusercontent.com/8361299/160110161-2cee0728-6231-4fcb-a020-471070139eb3.png)

Removed from `rules.txt`
