### ISSUE TITLE
battle.net tracking domain not blocked

### ISSUE THREAD

**Issue by RouterCFW** [AdguardTeam/AdGuardSDNSFilter#918]
`telemetry-in.battle.net`
Is a Domain used by blizzard to track telemetry overwatch seems to send data to this domain every second and seems to have gone unnoticed

**Comment by Alex-302** [comment]
Did you check when it is blokced?

**Comment by RouterCFW** [comment]
> Did you check when it is blokced?

Yeah I’ve had it blocked for weeks and no issues

**Comment by Alex-302** [comment]
Issue moved to [AdguardTeam/AdguardFilters #114308](https://github.com/AdguardTeam/AdguardFilters/issues/114308) via [**ZenHub**](https://www.zenhub.com/)
