### ISSUE TITLE
events-service.coinbase.com

### ISSUE THREAD

**Issue by terrorist96** [AdguardTeam/AdGuardSDNSFilter#919]
### Steps to reproduce

1. Use Coinbase app

### Expected behavior

Normal use
### Actual behavior

Noticable lag/delay when doing anything. It is fixed by whitelisting `events-service.coinbase.com`

<details><summary>Screenshot:</summary>

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| Google
| How did you setup DNS configuration:| Blokada
| Device model:| Samsung Galaxy S21U Ultra
| Operating system and version:|Android 12

**Comment by Alex-302** [comment]
Removed. https://github.com/AdguardTeam/AdguardFilters/issues/100288
