### ISSUE TITLE
hsdn.org

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardSDNSFilter#920]
@adguard-bot commented on [Tue Jan 11 2022](https://github.com/AdguardTeam/AdguardFilters/issues/106426)

### Issue URL (Incorrect Blocking)
 [https://www.ntp-servers.net/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.ntp-servers.net%2F)
### Comment
> Проблема с Adguard DNS

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/rQbLX7A.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/kdMNUS2.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.8
Browser: | Opera
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Disable cache for third-party requests, <br>Block WebRTC, <br>Block Push API, <br>Block Location API, <br>Block Flash, <br>Block Java
DNS filtering: | server: `https://dns.adguard.com/dns-query`<br>filters: `User rules`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js

---

@Alex-302 commented on [Thu Feb 10 2022](https://github.com/AdguardTeam/AdguardFilters/issues/106426#issuecomment-1035144669)

Мы не блокируем этот домен.

---

@BOR-LAND commented on [Mon Mar 28 2022](https://github.com/AdguardTeam/AdguardFilters/issues/106426#issuecomment-1080399343)

> Мы не блокируем этот домен.

![Desktop_2022_03_28_14_43_28_047 (1)](https://user-images.githubusercontent.com/93826441/160366639-8afcd49d-3f8b-443d-86b8-6ac09e9e95bf.png)

---

@Alex-302 commented on [Thu Mar 31 2022](https://github.com/AdguardTeam/AdguardFilters/issues/106426#issuecomment-1084937705)

В жалобе же совсем другой домен.

**Comment by BOR-LAND** [comment]
> В жалобе же совсем другой домен.

Домен ntp-servers.net открывается без проблем, а домен www.ntp-servers.net не работает.
На скрине я указал какое правило мешает открытию домена www.ntp-servers.net.

**Comment by Alex-302** [comment]
Заработает, когда https://github.com/AdguardTeam/AdGuardSDNSFilter/pull/921 внесём в фильтр.
