### ISSUE TITLE
initjs.rfk.petco.com — tracking server

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#922]
`initjs.rfk.petco.com` is a tracking server that gets blocked by EasyPrivacy, but not in DNS blocking. I suggest blocking all of rfk.Petco.com. I rarely use github so please create an entry for this. CRM ID: 585823

**Comment by Alex-302** [comment]
It used for recommendations. Not sure if it is a good idea to break it
<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/8361299/161557931-41ec52bc-8cc9-4b85-8559-8710857b2234.png)

</details>

**Comment by Alex-302** [comment]
Blocked another tracking script.
