### ISSUE TITLE
TEST MALWARE SITE!

### ISSUE THREAD

**Issue by burgerpatty11** [AdguardTeam/AdGuardSDNSFilter#931]
Update SafeBrowsing to Latest or add new rule ||malware.wicar.org^

**Comment by NaylyaM** [comment]
@burgerpatty11 Could you please specify why you wish us to add such rule? From our side, everything looks like there's no malware under this domain.

**Comment by burgerpatty11** [comment]
malware.wicar.org is a test sites for security solutions, so AdGuard should add it. On conclusion, only AdGuard DNS Filter or AdGuard DNS Beta doesn't consider it as "Malware". You may right that it doesn't contains malware but it's a test site for malware detection.

**Comment by burgerpatty11** [comment]
> @burgerpatty11 Could you please specify why you wish us to add such rule? From our side, everything looks like there's no malware under this domain.

malware.wicar.org is a test sites for security solutions, so AdGuard should add it. On conclusion, only AdGuard DNS Filter or AdGuard DNS Beta doesn't consider it as "Malware". You may right that it doesn't contains malware but it's a test site for malware detection.
