### ISSUE TITLE
Scam Site 

### ISSUE THREAD

**Issue by burgerpatty11** [AdguardTeam/AdGuardSDNSFilter#932]
This site targets facebook users especially during Christmas and New Years

https://surprise4u.me/

**Comment by NaylyaM** [comment]
Blocked.

**Comment by burgerpatty11** [comment]
> Blocked.

Thank you for your response!

**Comment by burgerpatty11** [comment]
> Blocked.
Hi! I found another but similar to https://surprise4u.me

SCAM SITES:
surprise4u.site
surprise4u.xyz

Please be noticed, look up for any similar websites, i know there are lots of them. I cannot specify them all.
