### ISSUE TITLE
Update; Scam Sites

### ISSUE THREAD

**Issue by burgerpatty11** [AdguardTeam/AdGuardSDNSFilter#935]
This is Similar to surprise4u.me

SCAM SITES:
surprise4u.site
surprise4u.xyz

Please be noticed, look up for any similar websites, i know there are lots of them. I cannot specify them all.

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk

**Comment by AlKulagin23** [comment]
These sites have been blocked.
