### ISSUE TITLE
A dozen websites unblocked in filter list

### ISSUE THREAD

**Issue by nichicon01** [AdguardTeam/AdGuardSDNSFilter#940]
### Steps to reproduce

1. View Adguard DNS Filter list in browser (Firefox for iOS) | https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
2. Find in page “@@“

### Expected behavior

Websites in this list should be blocked.
### Actual behavior

12 websites unblocked, about half of which appear to be Chinese in origin.

@@||ad.10010.com^
@@||ad.abchina.com^
@@||ad.kazakinfo.com^
@@||ad.ourgame.com^
@@||adcdn.pingan.com^
@@||advert.kf5.com^
@@||api.ads.tvb.com^
@@||app-advertise.zhihuishu.com^
@@||buyad.bi-xenon.cn^
@@||captcha.su.baidu.com^
@@||img.ads.tvb.com^
@@||newad.mail.wo.cn^

<details><summary>Screenshot:</summary>

[6E0E4222-95B5-4CD8-9D16-93A7D443ED3B](https://user-images.githubusercontent.com/89224156/165014152-0fb7a936-1222-4bbf-8df4-2f17258f3601.png)

</details>

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (e.g. Default, 176.103.130.130)
Adguard DNS | 94.140.14.14
| How did you setup DNS configuration:| (System/DNSCrypt app/Router)
Adguard app for iOS | DNS over TLS
| Device model:| (e.g. Google Pixel)
Apple | iPhone12
| Operating system and version:| (e.g. Android 7.1.2)
iOS | 15.4.1

**Comment by Alex-302** [comment]
It seems these rules just for fixing some issues.
