### ISSUE TITLE
www.sape.ru

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardSDNSFilter#941]
@adguard-bot commented on [Mon Apr 25 2022](https://github.com/AdguardTeam/AdguardFilters/issues/116478)

### Issue URL (Incorrect Blocking)
 [https://www.sape.ru/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.sape.ru%2F)
### Comment
> При включённом Adguard и фильтре DNS Adguard "Без рекламы" сайт не открывается. После отключения открывается. После обратного включения защиты по-прежнему открывается. Могу предположить, что в DNS фильтре что-то избыточно заблокировано из-за того, что это биржа всякой-разной рекламы.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/26e7gpg.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/pJfMcLQ.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.9.1
Browser: | Vivaldi
AdGuard driver: | WFP
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Block WebRTC, <br>Block Push API, <br>Block Location API, <br>Block Flash, <br>Hide your Referrer from third-parties (https://ya.ru), <br>Hide your IP address (218.54.104.184)
DNS filtering: | server: `Adguard`<br>filters: `Без рекламы`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js

**Comment by jellizaveta** [comment]
Добрый день! 
Данный сайт используется для показа рекламы на других сайтах. Поэтому мы не можем добавить его в исключения. 
В [облачном сервисе Adguard-DNS ](https://adguard-dns.io/ru/welcome.html) можно настраивать фильтрацию и дополнять фильтры собственными правилами.
