### ISSUE TITLE
Ava (ios)

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdGuardSDNSFilter#943]
@hitechtalk69 commented on [Tue Apr 26 2022](https://github.com/AdguardTeam/AdguardFilters/issues/116564)

### Prerequisites

- [X] This site DOES NOT contains sexually explicit material, otherwise use [NSFW-specific form](./new?template=bug_report_NSFW.yml);
- [X] Filters were updated before reproducing an issue;
- [X] AdGuard product version is up-to-date;
- [X] Browser version is up-to-date;
- [X] If the site or app is broken, disabling AdGuard protection resolves an issue.

### What product do you use?

AdGuard for iOS

### AdGuard version

4.3.3 (947)

### What type of problem have you encountered?

Website or app doesn't work properly

### Which browser(s) do you use?

Safari

### Which device do you use?

Mobile

### Where is the problem encountered?

https://apps.apple.com/us/app/ava-credit-building/id1584183782

### What filters do you have enabled?

AdGuard DNS filter

### Add your comment and screenshots

api2.branch.io should be whitelisted it breaks the app from opening

### Privacy

- [X] I agree to follow this condition

**Comment by jordanswrld23** [comment]
somehow it is still blocked the filter being blocked now is ||api2.branch.io^ even after updating filters @Alex-302

**Comment by Alex-302** [comment]
@jordanswrld23 Is the app still broken?

**Comment by jordanswrld23** [comment]
> @jordanswrld23 Is the app still broken?

yeah. idk how the exclusion isnt overriding it. i updated my filters even

**Comment by jordanswrld23** [comment]
@Alex-302

**Comment by Alex-302** [comment]
Well, we cannot remove this domain, because it is a popilar tracker.
But you can use https://adguard-dns.io/ (our custom DNS, plain and encrypted) and unblock or block any domain.
