### ISSUE TITLE
AdGuard DNS - YouTube not working 

### ISSUE THREAD

**Issue by cat174** [AdguardTeam/AdGuardSDNSFilter#945]
With Adguard dns active, youtube web page is not opening on any device on the network since yesterday. It opens when I enter CF and Google dns.

![resim](https://user-images.githubusercontent.com/49676345/166105770-08425e44-bde4-457d-a8ef-6cedba1625bc.png)
![resim](https://user-images.githubusercontent.com/49676345/166105724-15d04689-bfa5-432d-9644-76711ec31472.png)
![resim](https://user-images.githubusercontent.com/49676345/166105627-b409a4a9-7ae3-4067-b89d-806f8604167c.png)
![resim](https://user-images.githubusercontent.com/49676345/166105686-87cfc822-c90d-4848-88bf-d1460cc0b748.png)
![resim](https://user-images.githubusercontent.com/49676345/166105620-a35c871d-9fae-47ea-b59f-75a089d37921.png)
![resim](https://user-images.githubusercontent.com/49676345/166105871-30943644-af44-4789-acf4-027f96b43963.png)

**Comment by ameshkov** [comment]
Okay, since yesterday means that it does not open exactly when we rolled out the new version.

As I understand, AG DNS is configured in your router? Could you please show me the results of `nslookup www.youtube.com`?

**Comment by cat174** [comment]
> Okay, since yesterday means that it does not open exactly when we rolled out the new version.
> 
> As I understand, AG DNS is configured in your router? Could you please show me the results of `nslookup www.youtube.com`?

I'm on vacation right now and it will take me more than a week to get home.  Unfortunately I can't help.

**Comment by cat174** [comment]
> 

I noticed this when I woke up the day before I opened this ticket on GitHub.

**Comment by cat174** [comment]
> The strange thing is that it shows only IPv4 addresses and I don't really understand why it happens.
> 
> Please try these two commands:
> 
> ```
> nslookup www.youtube.com 1.1.1.1
> nslookup www.youtube.com 94.140.14.14
> ```
> 
> Is there any difference in the results?

![ss2](https://user-images.githubusercontent.com/49676345/168635364-8c22d215-20ed-48c6-91a2-1a4286c273a7.jpg)

**Comment by ameshkov** [comment]
Okay so the server itself works as expected, all kinds of IP addresses are returned properly.

My only guess is that something is wrong with how it's configured in your router.
Could it be that it somehow is configured for IPv6 only?

**Comment by cat174** [comment]
> Okay so the server itself works as expected, all kinds of IP addresses are returned properly.
> 
> My only guess is that something is wrong with how it's configured in your router. Could it be that it somehow is configured for IPv6 only?

The ipv6 feature is disabled.
![ss3](https://user-images.githubusercontent.com/49676345/168637679-be0e2ad3-bf0f-454d-ae74-667662ba7265.jpg)

**Comment by ameshkov** [comment]
I am not sure where exactly it is configured in your router, but here's what I see: with the AdGuard DNS profile it only resolves IPv6 addresses of `www.youtube.com`, not IPv4.

**Comment by cat174** [comment]
The problem is due to the router dns-proxy, so I'm closing the issue. I will contact the modem company, thank you for your help.

**Comment by ameshkov** [comment]
The screenshots are rather strange.

First of all, on the Wireshark screenshot it shows that the request was made for the `account-public-service-prod03.ol.epicgames.com.zydata.ru` domain which indeed does not exist.

![image](https://user-images.githubusercontent.com/5947035/176389376-53a57aaf-6da4-45c3-856e-923597cf8984.png)


The normal domain `account-public-service-prod03.ol.epicgames.com` exists though and can be resolved via AdGuard DNS.

Where does this `zydata.ru` postfix come from? It must have something to do with Keenetic itself.

**Comment by cat174** [comment]
Google Translate:
that picture threw me keenetic support. I didn't pay attention to that part. By the way, when opening support, I wrote the link of this topic to support.

**Comment by cat174** [comment]
> One more thing. Maybe it makes sense to send a link to this thread to Keenetic support so that we could discuss this issue here.

Google Translate:
I wrote to Keenetic support and such an answer is written.

-The last screenshot I sent is wrong screenshot, zydata.ru is my computer's suffix, so I actually sent two queries. The first one is for account-public-service-prod03.ol.epicgames.com.zydata.ru, yes it doesn't really exist, but the second one for account-public-service-prod03.ol.epicgames.com is rejected:

![11111](https://user-images.githubusercontent.com/49676345/176885824-6b7c212f-b2ba-4af1-8e71-75cbf2f46740.png)

-The same query response in Cloudflare DoT is as follows.

![222222](https://user-images.githubusercontent.com/49676345/176885859-926f95fb-ae50-4259-a98f-84fc756f68dc.png)

[capture-Bridge0-Jun 30 17-50-34.zip](https://github.com/AdguardTeam/AdGuardSDNSFilter/files/9028467/capture-Bridge0-Jun.30.17-50-34.zip)

**Comment by ameshkov** [comment]
@cat174 could you please somehow link me to that discussion with Keenetic support?

My email is `am@adguard.com`. I guess it'd be easier if I could ask them some questions directly.

**Comment by cat174** [comment]
> @cat174 could you please somehow link me to that discussion with Keenetic support?
> 
> My email is `am@adguard.com`. I guess it'd be easier if I could ask them some questions directly.

Google Translate:
I wrote to keenetic support this morning. Did they contact you?

**Comment by ameshkov** [comment]
Nope, not yet

**Comment by cat174** [comment]
@ameshkov  keenetic support team would like to contact you via this e-mail address. They want you to start a ticket by sending them a message from this e-mail address. They will talk to you through that ticket.
support@keenetic.com

**Comment by ameshkov** [comment]
@cat174 I've discussed this with Keenetic and it appears to be a bug of the firmware that will soon be fixed on their side.
