### ISSUE TITLE
email.propertybeforeprada.com being blocked

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#946]
@gGkAC3qfszbdViFkw4Fk9ooS2u commented on [Fri Apr 29 2022](https://github.com/AdguardTeam/AdGuardDNS/issues/243)

Hi,

email.propertybeforeprada.com is being blocked within AdGuard DNS with the only filter being the AdGuard DNS filter. This breaks functionality for a mortgage broker portal.

This issue was raised here as I could not find it within the AdGuard DNS filter source.

<img width="540" alt="Screen Shot 2022-04-29 at 13 22 32" src="https://user-images.githubusercontent.com/95468948/165880954-c082c64a-b027-46d4-95b5-8fecf86f3102.png">
.

**Comment by Alex-302** [comment]
Confirmed.
