### ISSUE TITLE
Add to blocklist pls - Phishing domain

### ISSUE THREAD

**Issue by kickass42zer0** [AdguardTeam/AdGuardSDNSFilter#947]
Malious domain that should be added to your filter list/s.
Attempted phishing domain.
Pretends to be a courier service that has a package to deliver (Apple laptop in this case).
Sends a mail to the recipients email address with links to the pretend courier site.

Link in email: https://ch-trk.advancessarily.com/ga/click/ _{uuid}_
Redirects to: https://ripper.epicentrodigital.com/ _{uuid}_

Asks a bunch of questions about delivery and times when no one is at the address provided -> then redirects to:
https://yoursecure.online/ with a bunch of GET parameters where the victim is then expected to provide personal information like phone number, address and email.

Unfortunately I cannot provide the exact URL as it exposes personal information - the UUID links to the personal info of the reporting user.

Please private me if this info is **REQUIRED**

PS: Antivirus (ESET IS) warns of potential phishing site when connecting to the final redirect (yoursecure.online) 

### Expected behavior
The block filter list should block this domain.

### Actual behavior
Not in blocklist

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| (AdGuardHome Server)
| How did you setup DNS configuration:| (AdGuard Server)
| Device model:| ()
| Operating system and version:| ()

**THANK YOU**

**Comment by kickass42zer0** [comment]
> Hi. We need proofs. At least screenshots or URLs.

Understood.

Can I send you the original email privately? 
I just don't want the original reporters private info in the public domain.

**Comment by kickass42zer0** [comment]
I have forwarded the mail to your email.  You can just follow the links there to get the proof you need.  I did not find any malware only phishing links so it should be safe.

**Comment by Alex-302** [comment]
> Can I send you the original email privately?

Yes, please send to filters@adguard.com or ajrypuphhn1l@blurmail.net (write here where you sent)
