### ISSUE TITLE
Edeka.de "Marktsuche"

### ISSUE THREAD

**Issue by hagezi** [AdguardTeam/AdGuardSDNSFilter#950]
cdn.tagcommander.com required for Edeka.de "Marktsuche": https://www.edeka.de/marktsuche.jsp#/?searchstring=K%C3%B6ln

### Steps to reproduce
1. https://www.edeka.de/marktsuche.jsp#/?searchstring=K%C3%B6ln

### Expected behavior
List with found markets is displayed.

### Actual behavior
List of found markets is not displayed because cdn.tagcommander.com is blocked.

### Your environment
AdGuard Home with AdGuardDNS Blocklist.

**Comment by Alex-302** [comment]
It is too popular. Not sure if this is a good idea to unblock it.
But you can try our cloud DNS https://adguard-dns.io/ and block/unblock whatever you see fit.

Same for https://github.com/AdguardTeam/AdGuardSDNSFilter/issues/951
