### ISSUE TITLE
Phishing domain

### ISSUE THREAD

**Issue by krax1337** [AdguardTeam/AdGuardSDNSFilter#954]
### Steps to reproduce

1. Open the https://denkukan.com/

### Expected behavior

This site should be blocked.

### Actual behavior

Site is not blocked.

<details><summary>Screenshot: 

</summary>

![изображение](https://user-images.githubusercontent.com/20024303/169201943-14b0163a-91c0-4b9e-9dd8-80526548815e.png)
![изображение](https://user-images.githubusercontent.com/20024303/169202165-7fd9a2e5-9f77-465c-ab20-3fe4976d8601.png)
![изображение](https://user-images.githubusercontent.com/20024303/169202704-2f9b864e-6e5b-43a6-b90f-4f0e6636e1bf.png)
</details>

### Proofs

First, there is ton of spams on my email of this. Second, site tries looking like it has relation with National Bank of Kazakhstan, but actually not. Here is the official site https://www.nationalbank.kz/ru, it has paid SSL. 

Also, it has subdomains. So better block the entire *.denkukan.com.

Also, I wrote the email to national bank. I will post it later after answer.

### Your environment

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| AdGuard Home v0.107.6 |
| How did you setup DNS configuration:| AdGuard Home v0.107.6
| Device model:| AdGuard Home v0.107.6
| Operating system and version:| AdGuard Home v0.107.6

**Comment by Oniqqqq** [comment]
blacklisted
