### ISSUE TITLE
AdGuard blocks previews on Avito

### ISSUE THREAD

**Issue by maxikuzmin** [AdguardTeam/AdGuardSDNSFilter#961]
If AdGuard is enabled, not all product photos (previews) are displayed when you scroll through the ads in the Avito app.
Only the original filters are enabled, there are no additional filters. 
When AdGuard is disabled, all pictures (previews) are displayed 
Also sometimes don't displayed pictures in ad 

Android 10 
Don't reproduce on IOS

**Comment by zloyden** [comment]
@maxikuzmin I can't reproduce it on my end with or without our DNS.
Please provide steps to reproduce or show which request needs to be unblocked.

**Comment by maxikuzmin** [comment]
@zloyden connect to a mobile network

**Comment by zloyden** [comment]
It does not matter whether Wi Fi or mobile network is used. I do not see that their request is blocked.

**Comment by maxikuzmin** [comment]
I tried disabling all filters and DNS, the problem remains

**Comment by zloyden** [comment]
Issue moved to [AdguardTeam/AdguardForAndroid #4183](https://github.com/AdguardTeam/AdguardForAndroid/issues/4183) via [**ZenHub**](https://www.zenhub.com/)
