### ISSUE TITLE
Domain dsbm.easysol.net should not be blocked

### ISSUE THREAD

**Issue by danielbernalappgate** [AdguardTeam/AdGuardSDNSFilter#963]
You are blocking one of our domains. This domain should not be blocked because it is used in our product DSB. This is a tool created to protect end users from electronic fraud modalities commonly used on the Internet. Within the protection capabilities of our system, our customers find the Internet browsing analysis and system-scanning features, which seek to identify the following possible attacks: Phishing, Pharming and Malware.

If you need extra information, please let me know.

### Steps to reproduce

1. The DNS service when is active it doesn’t allow navigate into the URL [dsbm.easysol.net](http://dsbm.easysol.net/)

### Expected behavior

When I navigate to the URL, I should see the following:

In PC browser:
![image](https://user-images.githubusercontent.com/64555412/172468347-b065326a-7883-42ef-9de2-85620c44214b.png)

In cellphone:
![image](https://user-images.githubusercontent.com/64555412/172468401-a22156b1-f27b-4fc4-bb04-7c199f1bc3b5.png)

### Actual behavior

When the configuration with private DNS dns.adguard.com is active or is setup through of IP address 94.140.15.15 is not possible to have connectivity to the URL.
![image](https://user-images.githubusercontent.com/64555412/172468472-df42754c-cb33-46ac-acb1-b126b3b310a1.png)

<details><summary>Screenshot: 
DNS resolution with google:

![image](https://user-images.githubusercontent.com/64555412/172468090-9403d3d6-c04d-4111-8437-700e21ded264.png)

DNS resolution with [AdGuard DNS — ad-blocking DNS server](http://dns.adguard.com/) :
![image](https://user-images.githubusercontent.com/64555412/172468177-4a22400c-c508-4123-87d0-24ea1e4a43ac.png)

</summary>

</details>

### Your environment

The use of your DNS is generating problems with clients that they use a specific banking app in cellphone.

|   Description  |     Value    |
| -------------- | ------------ |
| DNS server in use:| 94.140.15.15#53
| How did you setup DNS configuration:| System
| Device model:| ALL models
| Operating system and version:| Android any version

**Comment by Alex-302** [comment]
A blocking rule is loaded from EasyPrivacy filter. We will exclude it from DNS filter.
