### ISSUE TITLE
unpkg.com - false positive

### ISSUE THREAD

**Issue by leo15dev** [AdguardTeam/AdGuardSDNSFilter#964]
Hello,

unpkg.com CDN is blocked now via `||unpkg.com^` rule. Please remove it from the list.

Thank you.
Best regards.

**Comment by spahl** [comment]
+1 I have the same problem. This is a package CDN not for ads.

**Comment by Icemic** [comment]
seems a upstream problem, see https://github.com/easylist/easylistchina/issues/201
