### ISSUE TITLE
Add French (FR) block list to DNS AdGuard

### ISSUE THREAD

**Issue by computman007** [AdguardTeam/AdGuardSDNSFilter#970]
Hello

DNS guard include many local blocklist

French one is missing

I propose : 

https://easylist-downloads.adblockplus.org/liste_fr.txt

If I understand well, the request concern updating  : https://github.com/AdguardTeam/AdGuardSDNSFilter/blob/master/configuration.json

**Comment by Alex-302** [comment]
There are many dangerous rules with domains, which we cannot block by DNS.
