### ISSUE TITLE
ib.snssdk.com - false positive

### ISSUE THREAD

**Issue by CHxCOOH** [AdguardTeam/AdGuardSDNSFilter#983]
`ib.snssdk.com` provides a famous news/videos feed in Toutiao / Douyin (Tiktok in China), which has more than 100 million users. 

In comments, there is a notifacation "Be careful". Although, it is better to be allowed. 

Device: x86 router running Openwrt.

**Comment by Alex-302** [comment]
Need more details:
https://kb.adguard.com/en/technical-support/reporting-tool
