### ISSUE TITLE
Pandora Plus

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#987]
@techrayz commented on [Wed Jun 29 2022](https://github.com/AdguardTeam/AdGuardDNS/issues/289)

Pandora Plus streaming music paid subscribers are given the option of searching for and listening to any song they want as long as they watch a video advertisement. It appears AdGuard public DNS is blocking the ability to watch the advertisement, which doesn't allow me to listen to the song I searched for. The Pandora app just sits there without movement when I try to play a song by searching for the title.

This makes the Pandora app useless for Pandora Plus subscribers. Could the public filter be modified to allow ads in the Pandora Android/iOS app for Pandora Plus subscribers?

**Comment by Alex-302** [comment]
@techrayz Hi. Please follow the instructions:
1. switch to non-filtered DNS and enable DNS filter;
2. Close Pandora;
3. Clear activity log in AdGuard;
4. Turn on=>off Airplane Mode to clear DNS cache;
5. Reproduce an issue;
6. Go to activity log, swipe it down to refresh and make screenshots.

**Comment by techrayz** [comment]
I'm using Adguard public DNS and was hoping this could be changed on the global filter.
________________________________

**Comment by Alex-302** [comment]
Bot sure. I don't know what is blocked.
