### ISSUE TITLE
the CU app wont open due to the dns records missing

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardSDNSFilter#989]
@JadeMin commented on [Sat Jul 02 2022](https://github.com/AdguardTeam/AdGuardDNS/issues/292)

https://play.google.com/store/apps/details?id=com.bgfcu.membership
when i open this app, it says "network connection error" and wont open
can you add the dns records of this app? i think its due to the dns records missing
its not the device or misblocking issue. ive already checked that

thank you <3

\- Aguard DNS Beta

**Comment by Alex-302** [comment]
@JadeMin Hi. This app is not working on my device. 
Is AdGuard DNS used in AdGaurd for Android app or in another way? Which DNS server?

**Comment by JadeMin** [comment]
i tried the private dns method and Nebulo app (DNS changer for DoH)
