### ISSUE TITLE
Trackers to add

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdGuardSDNSFilter#990]
Reported by: USER ID 615298

I use AdGuard DNS and I noticed that the following domains, which I think are trackers, are not being blocked by it. Please test it and if they are trackers, please block it in AdGuard DNS. 

```
analytics.ff.avast.com
nuleme-dnsotls-ds.metric.gstatic.com
zjabch-dnsotls-ds.metric.gstatic.com
data.sec.intl.miui.com
b46a1bf4-dnsotls-ds.metric.gstatic.com
9afeb7aa-dnsotls-ds.metric.gstatic.com
itnqzc-dnsotls-ds.metric.gstatic.com
ztphtt-dnsotls-ds.metric.gstatic.com
pjmzmz-dnsotls-ds.metric.gstatic.com
ev96kc-dnsotls-ds.metric.gstatic.com
rw5hla-dnsotls-ds.metric.gstatic.com
mmdo00-dnsotls-ds.metric.gstatic.com
cdn.awsusor1.fds.api.mi-img.com
resolver.msg.global.xiaomi.net
80q9kr-dnsotls-ds.metric.gstatic.com
5ekafd-dnsotls-ds.metric.gstatic.com
2b9cc2c9-dnsotls-ds.metric.gstatic.com
cdn.awsusor1.fds.api.mi-img.com
royalcollegeoflaw.org
rr4---sn-oxunxg8pjvn-bpbzl.gvt1.com
rr2---sn-oxunxg8pjvn-bpbzl.gvt1.com
rr3---sn-oxunxg8pjvn-bpbzl.gvt1.com
rr1---sn-oxunxg8pjvn-bpbzl.gvt1.com
static.whatsapp.net
a4608137-dnsotls-ds.metric.gstatic.com
clmkcv-dnsotls-ds.metric.gstatic.com
w9nz6z-dnsotls-ds.metric.gstatic.com
axb2n1-dnsotls-ds.metric.gstatic.com
18cc4f83-dnsotls-ds.metric.gstatic.com
rr1---sn-oxunxg8pjvn-bpbzl.gvt1.com
rr2---sn-oxunxg8pjvn-bpbzl.gvt1.com
cdn.awsusor1.fds.api.mi-img.com
rr4---sn-oxunxg8pjvn-bpbzl.gvt1.com
rr3---sn-oxunxg8pjvn-bpbzl.gvt1.com
thedise.me
path3.xtracloud.net
evg.dnofd.com
vuonst-dnsotls-ds.metric.gstatic.com
k45exk-dnsotls-ds.metric.gstatic.com
wntebc-dnsotls-ds.metric.gstatic.com
n3r6ui-dnsotls-ds.metric.gstatic.com
bf3c3e29-dnsotls-ds.metric.gstatic.com
vuonst-dnsotls-ds.metric.gstatic.com
k45exk-dnsotls-ds.metric.gstatic.com
8145fc2d-dnsotls-ds.metric.gstatic.com
wntebc-dnsotls-ds.metric.gstatic.com
n3r6ui-dnsotls-ds.metric.gstatic.com
bf3c3e29-dnsotls-ds.metric.gstatic.com
onesignal.com
firebase-settings.crashlytics.com
sjvxec-dnsotls-ds.metric.gstatic.com
```

Thank you.

**Comment by ihurin** [comment]
#617687

device-metrics-us-2.amazon.com
mqtt-mini.facebook.com
graph.facebook.com
analytics.google.com
dl.google.com
1a1c5454-dnsotls-ds.metric.gstatic.com
5aijiw-dnsotls-ds.metric.gstatic.com
hzn4xq-dnsotls-ds.metric.gstatic.com
kfjyir-dnsotls-ds.metric.gstatic.com
f1oy5e-dnsotls-ds.metric.gstatic.com
e7aq1q-dnsotls-ds.metric.gstatic.com
ixk9cc-dnsotls-ds.metric.gstatic.com
7ecj87-dnsotls-ds.metric.gstatic.com
xnfmj4-dnsotls-ds.metric.gstatic.com
paop5b-dnsotls-ds.metric.gstatic.com
ftu5ar-dnsotls-ds.metric.gstatic.com
rfyrdd-dnsotls-ds.metric.gstatic.com
8uwrh0-dnsotls-ds.metric.gstatic.com
9c8d2f7c-dnsotls-ds.metric.gstatic.com
hlcac4-dnsotls-ds.metric.gstatic.com
9d9rps-dnsotls-ds.metric.gstatic.com
c181f1ac-dnsotls-ds.metric.gstatic.com
mjezcj-dnsotls-ds.metric.gstatic.com
jkm3k6-dnsotls-ds.metric.gstatic.com
u6qyq0-dnsotls-ds.metric.gstatic.com
n8newr-dnsotls-ds.metric.gstatic.com
cf5d3b0f-dnsotls-ds.metric.gstatic.com
e533db2e-dnsotls-ds.metric.gstatic.com
dezodh-dnsotls-ds.metric.gstatic.com
wuxnvc-dnsotls-ds.metric.gstatic.com
ukv1rv-dnsotls-ds.metric.gstatic.com
monwhp-dnsotls-ds.metric.gstatic.com
kbepbi-dnsotls-ds.metric.gstatic.com
odu27y-dnsotls-ds.metric.gstatic.com
adashbc.ut.taobao.com
static.whatsapp.net
h.online-metrix.net
sdk.iad-01.braze.com
sdk.iad-05.braze.com
log-collector.shopee.com.br
dttijy4dc6foz.cloudfront.net
d2idu5mmj5r5g3.cloudfront.net
3t5fmdir75gmnl3elswfs4zj4eq27crvpipbgs6z837e82faa1c700c0sac.d.aa.online-metrix.net
d2idu5mmj5r5g3.cloudfront.net

**Comment by Alex-302** [comment]
It looks like sabotage:)
```
graph.facebook.com
dl.google.com
static.whatsapp.net
```

**Comment by Chilace** [comment]
> It looks like sabotage:)

Especially this entry:
`*-*-ds.metric.gstatic.com`

**Comment by Alex-302** [comment]
Useless lists:(

**Comment by ihurin** [comment]
netperform-is.vodafone.com.tr
gcpsmapi.vodafone.com
tags.tiqcdn.com
psstatic.cdn.bcebos.com
sf1-cdn-tos.huoshanstatic.com
yastatic.net
stats.24support.cc
hitbas.com
graph.facebook.com
firebaseinstallations.googleapis.com

**Comment by ihurin** [comment]
+
netperform-is.vodafone.com.tr
gcpsmapi.vodafone.com
tags.tiqcdn.com
psstatic.cdn.bcebos.com
sf1-cdn-tos.huoshanstatic.com
yastatic.net
stats.24support.cc
hitbas.com
graph.facebook.com
firebaseinstallations.googleapis.com

**Comment by Alex-302** [comment]
Same comment as above)
