### ISSUE TITLE
copilot-telemetry.githubusercontent.com

### ISSUE THREAD

**Issue by chirag127** [AdguardTeam/AdGuardSDNSFilter#991]
### Steps to reproduce

1. download github copilot
2. start using
3. See bug that copilot-telemetry.githubusercontent.com is in the logs

### Expected behavior
Not Blocked

### Actual behavior
Blocked

**Comment by Alex-302** [comment]
We do not block it.
![image](https://user-images.githubusercontent.com/8361299/178380572-1cb1cb57-8069-40af-b28c-7115e42aafd2.png)
