### ISSUE TITLE
Ad/trackers domains to review

### ISSUE THREAD

**Issue by VladisLoveZh** [AdguardTeam/AdGuardSDNSFilter#997]
User (618151) requested to review the ad and tracking domains as they are still accessible with AdGuard DNS.
List below:

- ads.facebook.com
- ads-api.twitter.com
- advertising.twitter.com
- ads.pinterest.com
- ads-dev.pinterest.com
- widgets.pinterest.com
- ads.reddit.com
- d.reddit.com
- ads.tiktok.com
- ads.yap.yahoo.com
- business.samsungusa.com
- ~browser.sentry-cdn.com~
- ~app.getsentry.com~
- ~notify.bugsnag.com~
- ~sessions.bugsnag.com~
- ~api.bugsnag.com~
- adservice.google.com
- ~app.bugsnag.com~
- adtago.s3.amazonaws.com
- analyticsengine.s3.amazonaws.com
- advice-ads.s3.amazonaws.com
- affiliationjs.s3.amazonaws.com
- advertising-api-eu.amazon.com
- amazonaax.com
- amazonclix.com

**Comment by Alex-302** [comment]
sentry and bugsnag are used for bug tracking. Maybe in future we will create a new filter for this kind of services.
Edited your message => ~text~.

**Comment by VladisLoveZh** [comment]
The user requires reviewing this domain name due to trackers and possible malware. 
fp-it.fengkongcloud.com

Malware scan report: 
[static.fengkongcloud.com - MalwareURL.pdf](https://github.com/AdguardTeam/AdGuardSDNSFilter/files/9149536/static.fengkongcloud.com.-.MalwareURL.pdf)

**Comment by Alex-302** [comment]
https://github.com/AdguardTeam/AdguardFilters/commit/c12afdf56c033b3a20081621790ec76b249e5c98
